### ISSUE TITLE
Social Networks log in

### ISSUE THREAD

**Issue by epartipilo** [nuxt-community/auth-module#10]
Hello @pi0 
I'm developing a Nuxt.js that has a Backend with user/pass, Goolge or Facebook authentication.
- Do you recomend to use [vue-authenticate](https://github.com/dgrubelic/vue-authenticate) for the social network login?
- Are you planning to implement something similar so I can use only this library?
- Do you suggest to use this same library as it is to get the job done?

Thanks!

**Comment by herbertscruz** [comment]
Hello @epartipilo 

I had the same problem. The auth-module does not resolve log in to social networks. You can use any external package for this, but you have to use the auth-module store together.

I liked [vue-authenticate](https://github.com/dgrubelic/vue-authenticate), I'll study it.
I'm working with [vue-auth](https://github.com/websanova/vue-auth), but vue-authenticate looks softer.

**Comment by epartipilo** [comment]
Thanks @herbertscruz !

I've had no time to try the vue-authenticate, hope it works with Nuxt.js
Right now my dilema is if I use the auth-module and develop the Social Network login over that o use the two libraries

Cheers!

**Comment by herbertscruz** [comment]
Hello @epartipilo ,

I believe that vue-authenticate will not do the same job as auth-module, since auth-module guarantees the access_token the existence of the access_token on the client and server.

auth-module does something close to [this](https://nuxtjs.org/examples/auth-routes#using-express-and-sessions).

**Comment by epartipilo** [comment]
Thanks @herbertscruz 

I'll give them a try.

**Comment by renztoygwapo** [comment]
do you have any recommendation for the social auth using nuxt/vue-authenticate and database as an api only ?
