### ISSUE TITLE
receive 'undefined' on `await this.$auth.logout()`

### ISSUE THREAD

**Issue by raccoonroman** [nuxt-community/auth-module#1001]
**@nuxtjs/auth-next (v5.0.0-1610642462.1bcdc1e)**
I'm getting right response when login: `const response = await this.$auth.loginWith('local', { data });`
But when trying to logout: `const response = await this.$auth.logout();` receive undefined on `response` :(
While on 'network' tab i receive the actual response:
![Screenshot from 2021-01-15 14-39-08](https://user-images.githubusercontent.com/34542700/104728415-8b816000-573f-11eb-8c9d-2359f9dddf5d.png)

**Comment by bmulholland** [comment]
It's always faster to just dig into the code to figure out why. You'll see from that that we [don't return the response from logout](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/local.ts#L227). This is currently working as intended, and I'm not really familiar with any use cases where logout returns new data. If you've got a use case that you think would be broadly applicable, please create a new issue for your feature request.
