### ISSUE TITLE
Axios-Retry Configuration Compilation Error

### ISSUE THREAD

**Issue by Axieum** [nuxt-community/auth-module#1008]
### Version
module: `@nuxtjs/auth-next@5.0.0-1610115973.9fdaa66`
nuxt: `nuxt@2.14.12`

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

Please reference commit to see all relevant configuration - https://github.com/Axieum/telescope-for-spotify/commit/1944ece1649598d50fb90a3a20f1375d120bcaa4

## Reproduction
> :warning: without a minimal reproduction we won't be able to look into your issue

#### What is expected?

For requests to be retried without error.

#### What is actually happening?

The import of `axiosRetry` is being compiled to `axios_retry_1.default`, which is not defined.

![image](https://user-images.githubusercontent.com/7577851/104832026-ba333e00-58d9-11eb-94eb-9b16717fcf88.png)
![image](https://user-images.githubusercontent.com/7577851/104832050-e222a180-58d9-11eb-8929-9bd066e0f90a.png)

#### Steps to reproduce

Add a custom retry configuration, like below:

```ts
import { AxiosError } from 'axios';
import axiosRetry, { IAxiosRetryConfig } from 'axios-retry';

// Axios module configuration (https://go.nuxtjs.dev/config-axios)
auth: {
  // https://axios.nuxtjs.org/options#retry
  retry: {
    // Attempts to retry N times
    retries: 3,
    // Extends the retry condition
    retryCondition(error: AxiosError): boolean {
      return !error.response
        || axiosRetry.isNetworkOrIdempotentRequestError(error)
        || error.response.status === 429; // 429 Too Many Requests
    },
    // Extends the retry delay based on the Retry-After header
    retryDelay(retryCount: number, error: AxiosError): number {
      const retryAfter: number = error.response?.headers['retry-after'];
      if (retryAfter) return retryAfter < 30 ? retryAfter : -1;
      return axiosRetry.exponentialDelay(retryCount);
    },
  } as IAxiosRetryConfig,
};
```

_In my case, I import this from `config/auth.ts` and then add it as_:

```ts
import axios from './config/auth.ts';
// ...
auth,
// ...
```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Performance analysis?

Not applicable.

**Comment by JoaoPedroAS51** [comment]
Hi @Axieum! I think you confused the [axios module](https://axios.nuxtjs.org) with the auth module.

See [retry option of axios module](https://axios.nuxtjs.org/options#retry)

**Comment by Axieum** [comment]
Oh, I'm terribly sorry! So many modules I've been bouncing around different repos, thanks, I'll move it over there. 😔
