### ISSUE TITLE
/api/auth/login not found

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-community/auth-module#1009]
Nuxt: 2.14.0
Axios: 5.12.5
Nuxt/Auth: 4.9.1

I'm about to create a login form and I get the error "/api/auth/login not found" when I submit the form.

Here is my code:

nuxt.config.js
```
auth: {
    strategies: {
        local: {
            token: {
                property: 'token',
                // required: true,
                // type: 'Bearer'
            },
            user: {
                property: 'user',
                // autoFetch: true
            },
            endpoints: {
                login: { url: 'api/auth/login', method: 'post', propertyName: 'token' },
                logout: { url: 'api/auth/logout', method: 'post' },
                user: { url: 'api/auth/user', method: 'get' }
            }
        }
    }
}
```

login.vue

```
data() {
    return {
        username: 'phillip',
        password: '123',
    }
},
methods: {
    async login() {
        const { username, password } = this
        try {
            let response = await this.$auth.loginWith('local', {
                data: {
                    username,
                    password,
                }
            })
            console.log(response)
        } catch (err) {
            console.log(err)
        }
    }
},
```

Did I miss something?

And is it possible to only view the documentation of v4? I didn't find a filter or anything like that

**Comment by bmulholland** [comment]
4.9 docs: https://github.com/nuxt-community/auth-module/tree/master/docs

"/api/auth/login not found" is a 404 when trying to connect to your backend server, so look into the request and your backend server setup. That's not an issue with the auth module, but please let us know if you find something that's within this code base.

**Comment by JoaoPedroAS51** [comment]
@phillipmohr Probably you need to [configure proxy of axios module](https://axios.nuxtjs.org/options#proxy)

**Comment by phillipmohr** [comment]
@JoaoPedroAS51 Do you have an example how to do that correctly?

I've already been trying for hours to make it work. I don't know what I am missing. I posted a question on stackoverflow with my full nuxt.config.js, maybe someone can help

https://stackoverflow.com/questions/65798921/nuxt-authentication-with-nuxt-auth-api-sessions-not-found

**Comment by JoaoPedroAS51** [comment]
Hi @phillipmohr! Can you try this config for axios and auth:

```js
/*
** Axios module configuration
** See https://axios.nuxtjs.org/options
*/
axios: {
  proxy: true
},

proxy: {
  '/api': 'http://localhost:3000'
}

/*
** Auth module configuration (v4)
** See https://github.com/nuxt-community/auth-module/tree/master/docs
**
** Note: this configuration is for auth v4 and will not work properly with auth v5.
*/
auth: {
  strategies: {
    local: {
      endpoints: {
        // `propertyName` is the property of the token in the login response. 
        // Here it's set to `token`, so your response should be `{ token: '...' }`.
        // You can change this to match your response.
        login: { url: '/api/auth/login', method: 'post', propertyName: 'token' }, 
        logout: { url: '/api/auth/logout', method: 'post' },

        // The user endpoint can also have `propertyName`. It works the same way as token property.
        // So if the user is directly in response data, like this `{ username: 'foo', email: 'bar' }`, 
        // you should set `propertyName: false`. Otherwise, specify the name of the property. 
        user: { url: '/api/auth/user', method: 'get' }
      },
      // If you are using JWT token, this should be set to `Bearer`
      tokenType: 'Bearer'
    }
  }
}
```

You can also take a look at [demo code](https://github.com/nuxt-community/auth-module/blob/dev/demo)

But If this config doesn't work, then I believe the problem is related to your backend, not auth and axios config. Make sure that the all endpoints exist in your backend.

**Comment by phillipmohr** [comment]
@JoaoPedroAS51 Thank you, that worked!!

**Comment by JoaoPedroAS51** [comment]
@phillipmohr I'm happy to know it worked! :smiley:
