### ISSUE TITLE
Can't change request headers for Facebook strategy

### ISSUE THREAD

**Issue by alucardu** [nuxt-community/auth-module#1017]
I have this Facebook strategy:

```
facebook: {
  endpoints: {
    login: {
      headers: { Accept: 'application/vnd.api+json', 'Content-Type': 'application/vnd.api+json' }
    }
  },
  access_token_endpoint: 'http://****.**/**/social',
  access_type: 'offline',
  client_id: '******',
  grant_type: 'authorization_code',
  redirect_uri: socialLoginUrl + '/account/aanmelden',
  response_type: 'code',
  token_key: 'jwt',
  userinfo_endpoint: 'http://****.**/**user/profile'
},
```

Request headers:

```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: nl,en-US;q=0.9,en;q=0.8,es;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 511
Content-Type: application/x-www-form-urlencoded
Host: ****
Origin: http://localhost:3000
Pragma: no-cache
Referer: http://localhost:3000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
````

When I do this request the back-end returns a 406 because the headers are incorrect:

**Comment by bmulholland** [comment]
Looks like you're missing info from the end of the report.

Since I don't use Facebook login, it's hard to debug. Could you throw in a breakpoint and trace execution to find out how the request headers are sent? If you can tell us the root cause, it will be far more likely that we'll fix it.

**Comment by alucardu** [comment]
The headers have to correspond to the headers in our back-end. I've resolved the issue by intercepting the post request in Axios:

    export default function ({ $axios }) {
      $axios.setHeader('Accept', 'application/vnd.api+json', [
        'post'
      ])
      $axios.setHeader('Content-Type', 'application/vnd.api+json', [
        'post'
      ])
    }
