### ISSUE TITLE
Log out after refresh with token persisting in cookie

### ISSUE THREAD

**Issue by uncikmarek** [nuxt-community/auth-module#1018]
### Version
module: 5.0.0-1602966760.822bc05
nuxt: 2.14.6

### Nuxt configuration
 - [x] universal
 - [ ] spa

## Info
After every refresh I get logout and redirect to /login, when I tried to just change url to /dashboard I got redirected to /login

## Reproduction
- Nuxt running in dev or prod
- Adonis 5 api running
- Login to system with correct credentials, automatically redirect to /dashboard
- Dashboard works fine and even other nuxt views
- Cookies contain api token and vuex loggedIn is set to true
- Refresh page with F5
- Redirected to /login although auth token is still in cookies but vuex loggedIn sets to false

## Checklist
* [X]  I have tested with the latest Nuxt version and the issue still occurs
* [X  I have tested with the latest module version and the issue still occurs
* [ ]  I have searched the issue tracker and this issue hasn't been reported yet

Also tried lowering version of axios as writen here: #876

**Comment by bmulholland** [comment]
Is this a dupe of https://github.com/nuxt-community/auth-module/issues/478 or https://github.com/nuxt-community/auth-module/issues/258 ?

**Comment by uncikmarek** [comment]
In #478 fix was to manually redirect back to app from /login with condition this.$auth.loggedIn, but I get false so no work for me

other fix was to use await this.$auth.setToken("local", "Bearer " + access_token) but this seems to do absolutely nothing, my vuex ist not updating with this

**Comment by JoaoPedroAS51** [comment]
Hi @uncikmarek! Can you show me your `nuxt.config.js`?

**Comment by uncikmarek** [comment]
Sure:

`import colors from 'vuetify/es5/util/colors'

export default {
    server: {
        port: process.env.APP_PORT || 3000,
        host: process.env.APP_URL || 'localhost',
    },
    publicRuntimeConfig: {
        apiUrl: process.env.API_URL || 'https://localhost:3333/api/v1/',
    },

    // Disable server-side rendering (https://go.nuxtjs.dev/ssr-mode)
    ssr: false,

    // Global page headers (https://go.nuxtjs.dev/config-head)
    head: {
        titleTemplate: '%s - konektr-admin-2',
        title: 'konektr-admin-2',
        meta: [
            { charset: 'utf-8' },
            { name: 'viewport', content: 'width=device-width, initial-scale=1' },
            { hid: 'description', name: 'description', content: '' },
        ],
        link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
    },

    // Global CSS (https://go.nuxtjs.dev/config-css)
    css: [],

    // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
    plugins: [],

    // Auto import components (https://go.nuxtjs.dev/config-components)
    components: true,

    // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
    buildModules: [
        // https://go.nuxtjs.dev/typescript
        '@nuxt/typescript-build',
        // https://go.nuxtjs.dev/stylelint
        '@nuxtjs/stylelint-module',
        // https://go.nuxtjs.dev/vuetify
        '@nuxtjs/vuetify',
    ],

    // Modules (https://go.nuxtjs.dev/config-modules)
    modules: [
        // https://go.nuxtjs.dev/axios
        '@nuxtjs/axios',
        '@nuxtjs/auth-next',
        'nuxt-i18n',
    ],

    // Axios module configuration (https://go.nuxtjs.dev/config-axios)
    axios: {
        baseURL: process.env.API_URL || 'https://localhost:3333/api/v1',
    },

    // Nuxt Auth (https://auth.nuxtjs.org)
    auth: {
        redirect: {
            login: '/login',
            logout: '/login',
            callback: '/login',
            home: '/dashboard',
        },
        strategies: {
            local: {
                token: {
                    property: 'token',
                    required: true,
                    type: 'Bearer',
                },
                user: {
                    property: 'admin',
                    autoFetch: true,
                },
                endpoints: {
                    login: { url: 'auth/login', method: 'post' },
                    logout: { url: 'auth/logout', method: 'post' },
                    user: { url: 'profile', method: 'get' },
                },
            },
        },
    },

    // Vuetify module configuration (https://go.nuxtjs.dev/config-vuetify)
    vuetify: {
        customVariables: ['~/assets/variables.scss'],
        theme: {
            dark: false,
            themes: {
                dark: {
                    primary: colors.blue.darken2,
                    accent: colors.grey.darken3,
                    secondary: colors.amber.darken3,
                    info: colors.teal.lighten1,
                    warning: colors.amber.base,
                    error: colors.deepOrange.accent4,
                    success: colors.green.accent3,
                },
            },
        },
    },

    i18n: {
        locales: [
            {
                code: 'en',
                iso: 'en-US',
                file: 'en.js',
            },
        ],
        lazy: true,
        langDir: 'locales/',
        defaultLocale: 'en',
    },

    // Build Configuration (https://go.nuxtjs.dev/config-build)
    build: {},

    router: {
        middleware: ['auth'],
        extendRoutes(routes, resolve) {
            routes.push({
                name: 'dashboard',
                path: '/',
                component: resolve(__dirname, 'pages/dashboard.vue'),
            })
        },
    },
}
`

**Comment by JoaoPedroAS51** [comment]
Thanks! Ok, I think you will need to debug the `LocalScheme`, so we can find the root casue. I think it's related to `fetchUser` or `check` methods of `LocalScheme`. Can you try to find where it fails exactly?
I think the file is `node_modules/@nuxtjs/auth-next/dist/runtime.js`.

Also, can you show me your login and user responses?

**Comment by uncikmarek** [comment]
I am setting user manually I think the autoFetch did not worked

`
const response = await this.$auth.loginWith('local', { data: this.login })
this.$auth.setUser(response.data.admin)
`

**Comment by JoaoPedroAS51** [comment]
Ok, then I'm pretty sure that your issue is caused by user endpoint. What is the user response? (`/profile`)

**Comment by uncikmarek** [comment]
response from /profile looks like this:

`{
    "id": 3,
    "status": null,
    "name": null,
    "email": "admin@konektr.com",
    "last_login": null,
    "created_at": "2021-01-21T17:13:58.837+00:00",
    "updated_at": "2021-01-21T17:13:58.837+00:00"
}`

**Comment by JoaoPedroAS51** [comment]
Ok, that's the issue. As you response in not wrapped, you need to set `user.property` to `false` in auth config (it's currently set to `admin`)

**Comment by JoaoPedroAS51** [comment]
@uncikmarek Just merged #989, which will throw an error when the property of `user.property` was not found in user response :)

**Comment by uncikmarek** [comment]
Wow nice :) I thought that user.property was for specify where in /login response is user, because in /login it is in admin :D 
I changed it to false and now it finally works, thank you so so much :)

**Comment by JoaoPedroAS51** [comment]
I'm happy to know it worked! :)
