### ISSUE TITLE
Axios interceptor not working when extending Nuxt Auth plugin

### ISSUE THREAD

**Issue by alucardu** [nuxt-community/auth-module#1021]
I have a Axios plugin like so:

    export default function ({ $axios, $auth }) {
      $axios.interceptors.request.use((req) => {
        req.data = {
          data: {
            // some data
          }
        }
        console.log('auth: ', $auth)

        return req
      })

      $axios.defaults.headers['Content-Type'] = 'application/vnd.api+json'
      $axios.defaults.headers.Accept = 'application/vnd.api+json'
    }

In my nuxt.config I have:

    plugins: [
      { mode: 'client', src: '~/plugins/axios' }
    ],

When I run my request I get a `auth undefined`.

So I try to extend the [Nuxt Auth plugin][1]:

auth.js:

    export default function ({ $auth }) {
      if ($auth.loggedIn) {
        console.log('loggin in')
      } else {
        console.log('not loggin in')
      }
    }

nuxt.config.js:

    plugins: [
      // { mode: 'client', src: '~/plugins/axios' }
    ],

    auth: {
      plugins: [{ src: '~/plugins/axios', ssr: true }, '~/plugins/auth.js'],
      // strategies etc..
    }

So I comment the Axios plugin, and I add it to the auth section as shown on the Nuxt Auth docs. When I run the request it doesn't log the `console.log('auth: ', $auth)` skipping the whole ` $axios.interceptors.request.use((req) => {` 

  [1]: https://auth.nuxtjs.org/recipes/extend/

**Comment by naufalfarras** [comment]
hi how do you solved this, seems have same issue here
