### ISSUE TITLE
Wrong attributes on Nuxt Auth documentation for Google strategy

### ISSUE THREAD

**Issue by Segrelove** [nuxt-community/auth-module#1027]
The documentation states that you need to passe a `clientId`, which is wrong since you need to pass a `client_id`

That is quite misleading :-) 

`auth: {
  strategies: {
    google: {
      clientId: '...' #<- This has to be client_id
    },
  }
}`

**Comment by bmulholland** [comment]
I notice that you bypassed our issue template, which contains information needed to respond. In particular, what auth module version are you using?

**Comment by Segrelove** [comment]
Yeah, sorry about that ! Since it was just for a minor fix on the official documentation : https://auth.nuxtjs.org/providers/google , I took the liberty to bypass your issue template. 

My version for nuxt auth is 4.9.1

**Comment by bmulholland** [comment]
That's why; the docs you're pointing to are for v5, which [we recommend using](https://auth.nuxtjs.org/status#nuxtjsauth-next-v5).

**Comment by bmulholland** [comment]
v4.9 docs are here: https://github.com/nuxt-community/auth-module/tree/master/docs
