### ISSUE TITLE
Redirect Doesnt Work Correctly

### ISSUE THREAD

**Issue by mahiraltinkaya** [nuxt-community/auth-module#1032]
Hello friends;

I ran into a problem with Nuxt auth on the redirect process.

I shared my auth-guard and configurations below.

My expectation is that the page I use auth-guard middleware will be directed to the login page if I am not logged in, and then go to the page I want to enter after login. But after login it is always redirected to the homepage. Can you help me?

loggedIn == false  auth-guard redirected me this page 
http://localhost:3000/uye-girisi?redirect=%2FSiparislerim

after login redirect me and redirect main page "/"
http://localhost:3000/?redirect=%2FSiparislerim

Auth-guard MW
```
export default async function({ $auth, redirect, store, route }) {
  if (!$auth.loggedIn) {
    redirect(`/uye-girisi?redirect=${route.path}`);
  }
}
```
Nuxt.config

```
 auth: {
    rewriteRedirects: true,
    fullPathRedirect: true,
    redirect: {
      login: "/uye-girisi",
      logout: "/"
    },
    strategies: {
      local: {
        token: {
          property: "token",
          type: "Bearer"
        },
        user: {
          property: "user"
        },
        endpoints: {
          login: { url: "/login", method: "post" },
          logout: { url: "/logout", method: "post" },
          user: { url: "/user", method: "get" }
        }
      }
    }
  },
```
-->

**Comment by teethgrinder** [comment]
I think you need to add call
```
redirect: {
      login: '/login',
      logout: '/login',
      callback: '/login',
      home: '/',
    },
```

**Comment by men232** [comment]
I just noted one weird thing, `$auth.loggedIn` always `false` after  `loginWith` calling. Try to initialize vuex with default auth state, like this:
```
// store/state.js

export default () => ({
  auth: {
    loggedIn: false,
  },
});

```

**Comment by bmulholland** [comment]
https://github.com/nuxt-community/auth-module/issues/1010
