### ISSUE TITLE
isRelativeURL fails when urls have dot caracters

### ISSUE THREAD

**Issue by lightglitch** [nuxt-community/auth-module#1038]
### Version
module: 5.0.0-1611574754.9020f2a
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

## Reproduction
I have urls that have '.' (dots) in the url, the dots normally are not url encoded and because isRelativeURL fails to considered them the redirect is not made to the previous page but to "home". 

### What is actually happening?
It's redirecting to home instead of previous page.

**Comment by bmulholland** [comment]
Fixed in #1039
