### ISSUE TITLE
New Nuxt install problems

### ISSUE THREAD

**Issue by shealan** [nuxt-community/auth-module#104]
I created a new project with the latest version of Nuxt. All working nicely. I added the auth module and after adding the module definitions to the config file I get a 404.

```
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth',
  ],
```

Is there an issue with the latest version of Nuxt?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c76">#c76</a>)</em></sub></div>

**Comment by derevandal** [comment]
@shealan Could you post the terminal output?

**Comment by shealan** [comment]
No console errors but page gives me the following error

```
Cannot GET /
```

Commenting out the auth module in the config fixes the issue and I see the index.vue page as expected.

**Comment by Fubinator** [comment]
I just stumbled upon this problem as well when updating nuxt itself (from 1.0.0 to 1.4.0). Scrolling up in my terminal it threw an error when I wouldn't have an `index.js` file in my `store/` folder:

` Error: [Auth] Enable vuex store by creating store/index.js`

I'm not entirely sure if this is the same problem, but at least you could try if this works. @shealan

**Comment by shealan** [comment]
@Fubinator that was exactly it, thank you. I'll submit a pull request on the docs.

**Comment by begueradj** [comment]
Whenever you use **@nuxtjs/auth** module, you have to activate the store. This means you have to to create a folder called **store** and put inside it at least an empty file called **index.js** .
Billal Begueradj

**Comment by love8587** [comment]
Do I need to create store folder and index.js? Has this rule changed now?

**Comment by najihoussam** [comment]
@begueradj  it's worked for me, Thank you.

**Comment by lestercastillo** [comment]
just create index.js inside store folter, Work perfectly!!!
