### ISSUE TITLE
درحالت سمت سرور که مرورگر رو رفرش می کنم .   به صفحه خروج ریدایرکت میشه 

### ISSUE THREAD

**Issue by javadrohani** [nuxt-community/auth-module#1049]
سلام آقای پارسا خسته نباشید .
من از 
https://auth.nuxtjs.org/providers/laravel-passport 
 در پروژه ناکس خودم استفاده کردم . و همه چیز اوکیه  ولی مثلا من در پیچ پروفایل از پروژه از 
  middleware: 'auth',
 استفاده کردم وقتی که لاگین می شه و به اون پیچ پوش میشه اطلاعات یوزر رو میاره و مشکی نداره ولی وقتی تو همون پیچ صفحه رو رفرش می کنم  .  از صفحه خارج میشه . 
نکته : بعد از این که  صفخه کامل بشه توی کاربر لاگین شده و مشکلی نیست ولی خوب قبلش ریداریکت شده . 
ممنون میشم کمک کنید

**Comment by bmulholland** [comment]
Sorry, English only
