### ISSUE TITLE
Where can I find the files for the current login strategies, if there are any?

### ISSUE THREAD

**Issue by dredshep** [nuxt-community/auth-module#1055]
I was watching [this guide](https://www.youtube.com/watch?v=S7Tunk-lXE0) from February last year, and I'm guessing that you guys changed stuff? He goes to auth-module/lib/schemes, but no such directory exists in the current version. In fact, I can't find any strategy now.

Does this mean that I currently have to code the strategy from scratch? Is there a template that emulates the previous strategy so that I can make one easier? I have been struggling for a couple of days to make things work but it's not very clear with the current documentation and available scheme/strategy files.

One of the doubts I have is, once I retrieve a token from my API, how do I tell Nuxt to apply it to the user's session? How do I log the user out on the /logout API entry point?

![image](https://user-images.githubusercontent.com/78047001/107283882-5e208d00-6a33-11eb-81fa-dbe219e1b332.png)

![image](https://user-images.githubusercontent.com/78047001/107283958-74c6e400-6a33-11eb-82fc-a3e07d217551.png)

The documentation is, at least for me, very unclear on how to actually log in. What goes in the options there? `/*...args..*/` Do I put a user there? A token? Where are these functions defined, and if they're not, how do I define them?

**Comment by emwiechnik** [comment]
You might have already figured out given the age of the question, but for others here is the answer. 
The methods login(...) and logout(...) use the currently set login strategy. How do you set the current strategy? You do it by calling the method setStrategy(name). For a typical scenario the methods loginWith(name, ...) and logout(...) should be enough. As mentioned in the screenshot you attached, loginWith is the recommended approach.

> I can't find any strategy now.

The strategies are listed in the Schemes section, e.g. : https://auth.nuxtjs.org/schemes/local
If you want to find all of them in the code then they're in: '~auth/runtime' : CookieScheme, LocalScheme, RefreshScheme, Oauth2Scheme, Auth0Scheme, LaravelJWTScheme .

**Comment by dredshep** [comment]
I actually didn't solve any of these problems lol. It was so hard that after a few days of asking around and not getting answers, I switched to React. 😂
