### ISSUE TITLE
Refreshing the page brokes auth state

### ISSUE THREAD

**Issue by sinnrrr** [nuxt-community/auth-module#1059]
### Version
module: 5.0.0-1612791489.a5d8c28
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
```
auth: {
    strategies: {
      redirect: false,
      local: {
        scheme: 'refresh',
        token: {
          property: 'data.accessToken',
          maxAge: 1800,
        },
        refreshToken: {
          property: 'data.refreshToken',
          data: 'refreshToken',
          maxAge: 60 * 60 * 24 * 30
        },
        user: {
          property: 'data',
        },
        endpoints: {
          login: { url: 'auth/login', method: 'post' },
          refresh: { url: 'auth/refresh', method: 'post' },
          user: { url: 'auth/user', method: 'get' },
          logout: { url: 'auth/logout', method: 'post' },
        },
      },
    },
  },
```

## Reproduction
https://github.com/sinnrrr/loonify

#### What is expected?
Normal work after reload

#### What is actually happening?
After refresh it's just logging out and throws following error in console:
```TypeError: Cannot read property 'toLowerCase' of undefined```

After this, the whole SPA is broken. The nuxt links are just reloading page and not working properly and overall all navigation becomes broken

#### Steps to reproduce
```
cd packages/frontend
yarn
yarn dev
```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [ ]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by derHodrig** [comment]
Same here

https://github.com/nuxt-community/auth-module/issues/1052

**Comment by nhanco** [comment]
we dont have solution for this ?

**Comment by sinnrrr** [comment]
> we dont have solution for this ?

no, we don't
searched through the whole lot of issues

**Comment by nhanco** [comment]
Sometime that work sometime not.
