### ISSUE TITLE
Cannot authenticate to live server

### ISSUE THREAD

**Issue by AEK-BKF** [nuxt-community/auth-module#1065]
I'm using Laravel 8, sanctum provider, and auth-next module.
As you can see in attached, I'm able to login, but the /api/user is not called, so I cannot access to home page.
Any help ?

Thanks.

![error](https://user-images.githubusercontent.com/16412739/108228454-ebf52a00-714f-11eb-92a2-502f16329943.png)

**Comment by bmulholland** [comment]
We generally cannot help with debugging because doing so depends on a full integration setup. Sorry.
