### ISSUE TITLE
refreshToken not being set

### ISSUE THREAD

**Issue by olliepotter** [nuxt-community/auth-module#1074]
Hi, I'm struggling to configure the `refresh` scheme for a local strategy... It doesn't seem to set a refresh token in either local storage or cookies like it does with the `access_token`. 

I'm using `auth-next` and Nuxt "^2.14.12".

My config is the same as the default provided here: https://auth.nuxtjs.org/schemes/refresh.

My backend gives back a response like this:
```
{
    "access_token": ...
    "refresh_token": ...
}
```

The access token works fine but the refresh token is not being stored, see below (localstorage).
![image](https://user-images.githubusercontent.com/20932396/109004465-b21caa00-76a0-11eb-953d-116b6e8318d5.png)

Refresh token isn't set in cookies either.

Thanks in advance.

**Comment by olliepotter** [comment]
I posted this question on discord and it was suggested that I try specifying the type for the refreshToken like this:
```
refreshToken: {
    property: 'refreshToken',
    data: 'refreshToken',
    maxAge: 60 * 60 * 24 * 30,
    type: 'Refresh'
}
```
I tried this and this had no effect either.

**Comment by olliepotter** [comment]
Closing this issue as it was a stupid spelling mistake in my config...

**Comment by ivan-rivera** [comment]
Would you mind sharing what was the problem? I'm facing the same issue
