### ISSUE TITLE
Question: Do not redirect to home page after callback

### ISSUE THREAD

**Issue by book000** [nuxt-community/auth-module#1079]
Thank you for creating a great module.  
I found a strange behavior when using `@nuxtjs/auth-next`.

Here is the repository of the tested project: https://github.com/book000/auth-module_test

I'm trying to create a site with a login function with a GitHub account using SPA (SSR off) and static targets.
But I'm having trouble logging in.

When I try to login, it works fine until the callback, but then the redirect to home doesn't work.
Looking at the developer tools, it looks like access to `/_auth/oauth/github/authorize` is failing. Indeed, the file does not exist under the dist directory.
This issue only occurs on static sites in the dist directory generated by `yarn generate`, not on the development server with `yarn dev`.

Is there a way to solve this problem?
Or maybe this module doesn't support SPA just because I haven't found it?

Please let me know if there is any missing information I should provide.
Sorry for the poor English. I look forward to your reply.

**Comment by kenxdrgn** [comment]
I am facing the same problem too. Did you solve it?

**Comment by book000** [comment]
I haven't solved it, but I solved it temporarily with SSR.

**Comment by bmulholland** [comment]
https://github.com/nuxt-community/auth-module/issues/1010
