### ISSUE TITLE
Docs: Page order is messed up

### ISSUE THREAD

**Issue by NickBolles** [nuxt-community/auth-module#1092]
Clicking next on status goes to middleware, but clicking next on [setup](https://dev.auth.nuxtjs.org/guide/setup) goes to status. This is presumably because they both share the position of 2 and setup sorts before status.

https://github.com/nuxt-community/auth-module/blame/dev/docs/content/en/guide/setup.md#L4

https://github.com/nuxt-community/auth-module/blame/dev/docs/content/en/status.md#L4

**Comment by bmulholland** [comment]
Seems to be working now: https://auth.nuxtjs.org/guide/setup
