### ISSUE TITLE
Set token expiration day programmatically

### ISSUE THREAD

**Issue by invisor** [nuxt-community/auth-module#1094]
I receiving an expiration date from the server. Is it possible to set expitation date or maxAge programmatically?

As I can see **expires** or **maxAge** parameters not accepting functions or something like that

**Comment by rodrigoriome** [comment]
@invisor I'm having this same issue right now. Did you find any workarounds for this? Thanks!

**Comment by invisor** [comment]
> @invisor I'm having this same issue right now. Did you find any workarounds for this? Thanks!

@rodrigoriome Nope. I just hardcoded token lifetime in the nuxt config. Still waiting for a solution

**Comment by bmulholland** [comment]
See https://github.com/nuxt-community/auth-module/discussions/1582
