### ISSUE TITLE
hasScope checks Key only not value  

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt-community/auth-module#1098]
When i try to use the scopeKey function in my middleware  it always returns true if the key is there, no matter what the value, is.
am i missing something..

user object contains 
`{
_id: "someID",
role: "someRole"
}`
setting scope key in nuxt.config.js

`auth:{scopeKey: 'role'}`

then in auth middleware
`$auth.hasScope('admin')`
`$auth.hasScope('User')`
`$auth.hasScope('it does not matter what i type here, it always returns true')`
logging these to console  always returns true, 
so it seems to check if key 'role' is there and it returns true, while the expected behavior would be to check if key role contains value admin,User etc

i'm i missing something here..?

**Comment by cpt-n3mo** [comment]
Hello and Good day! JoaoPedroAS51
thx for clearing that up for me, this totally solved the problem!

**Comment by JoaoPedroAS51** [comment]
I'm happy to know it's working now! :)
