### ISSUE TITLE
Redirect authorized user out

### ISSUE THREAD

**Issue by sky-code** [nuxt-community/auth-module#110]
In previous version (3.x) it is possible to redirect authorized user out from page, but how to do this with new version (4.x) ?

**Comment by nikkanetiya** [comment]
I think there is not straight forward middleware option in 4.x, just create the new middleware in `middleware/guest.js`

```
export default function ({ store, redirect }) {
  // If the user is authenticated (not guest)
  if (store.state.loggedIn) {
    return redirect('/')
  }
}
```

make it redirect to whatever you want, or even you can modify it to allow pass argument from page. and use it from page like `middleware: 'guest'`
