### ISSUE TITLE
$auth is undefined when outputting inside a vue file

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt-community/auth-module#1112]
### Version
module: 4.9.1
nuxt: 2.14.12

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
```javascript
auth: {
  redirect: {
    login: '/account/login',
    logout: '/account/login',
    callback: '/account/login',
    home: '/account/domains'
  },
  strategies: {
    local: {
      login: { url: 'auth/login', method: 'post', propertyName: 'token' },
      logout: { url: 'account/logout', method: 'post' },
      user: { url: 'auth/user', method: 'get', propertyName: 'user' }
    }
  }
},
```
-->

#### What is expected?

When outputting `this.$auth.user` inside of `*.vue` files after a user has logged in I shouldn't be getting an undefined error

#### What is actually happening?

I'm getting:

> Cannot read property '$auth' of undefined

When using ``this.$auth.user`` inside a vue file

#### Steps to reproduce

1. Add `this.$auth.user` to any vue file

## Additional information

![auth-error](https://user-images.githubusercontent.com/25177538/113507917-2b7fa600-9545-11eb-8180-053471a36f88.PNG)

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by bmulholland** [comment]
I'm accessing it no problem. You're probably accessing it within a template, where you shouldn't use `this`.
