### ISSUE TITLE
Only in Production and SSR: Opening site from a new tab logs out the user if their access token is expired (does NOT attempt to refresh)

### ISSUE THREAD

**Issue by MohammadKhalaji** [nuxt-community/auth-module#1121]

**Comment by rosnaib11** [comment]
Same issue only happens in production universal, did you find solution @MohammadKhalaji ?

**Comment by MohammadKhalaji** [comment]
> Same issue only happens in production universal, did you find solution @MohammadKhalaji ? I doubt cookies not properly set, in my case only happens when I tried social auth. In my cookies it still `auth.strategy`: local instead of google.

Disabling refresh token rotation and blacklisting did the trick for me. But I only look at it as a temporary workaround and I'm still waiting for a fix.

**Comment by bmulholland** [comment]
What auth module version does this happen on? Can you please provide a repro?

**Comment by bmulholland** [comment]
Oh, it's SSR. See https://github.com/nuxt-community/auth-module/issues/1197
