### ISSUE TITLE
Break my page style after user logout

### ISSUE THREAD

**Issue by ghonchesefidi** [nuxt-community/auth-module#1146]
#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - universal

### Auth configuration
 `auth: {
    localStorage: false,
    cookie: {
      prefix: 'auth.',
      options: {
        path: '/',
        maxAge: 7776000
      }
    },
    strategies: {
      local: {
        endpoints: {
          login: {url: '/server/api/auth/login', method: 'post', propertyName: 'token'},
          logout: {url: '/server/api/auth/logout', method: 'post'},
          user: {url: '/server/api/auth/user', method: 'post', propertyName: 'user'}
        },
        tokenRequired: true,
        tokenType: 'Bearer'
      }
    },
    redirect: {
      logout: '/admin/login',
    }
  },`
Hi
In my dashboard page after I logout user (this.$auth.logout()) my login page style breaks. I will attach some screenshots.  
Before logout user:  
![image](https://user-images.githubusercontent.com/30124243/115974531-a94a3680-a572-11eb-960c-5e500204a982.png)  
After user logout:  
![image](https://user-images.githubusercontent.com/30124243/115974547-c4b54180-a572-11eb-9111-175ffae33894.png)

**Comment by ghonchesefidi** [comment]
Any help or idia?

**Comment by AllanOricil** [comment]
I had this problem once. For me it happened because the css from the previous page was not removed because an exception was happening right after changing the page. Open the inspector and check if you spot and exception and if the css classes from the previous page are present.

**Comment by ghonchesefidi** [comment]
@AllanOricil Thanks for your comment. I checked CSS files. Login and dashboard styles are completely unique and sepereted.

**Comment by ghonchesefidi** [comment]
I was able to fix this problem by using window.location.href = '/admin/login' on admin logout button but I don't know what is the problem and now how its working !

**Comment by AllanOricil** [comment]
Nice you resolved the problem. But it is weird that this is happening.

**Comment by stmoerman** [comment]
> I was able to fix this problem by using window.location.href = '/admin/login' on admin logout button but I don't know what is the problem and now how its working !

Are you using CSS files to style your pages/components by any chance?

**Comment by ghonchesefidi** [comment]
@stmoerman yes I'm using both in components styles and loading Bulma as my main CSS Framework .

**Comment by bmulholland** [comment]
No one else has reported this, so closing it out for now.
