### ISSUE TITLE
Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by Boris-Karamanolev** [nuxt-community/auth-module#1156]
Please help!

I have been trying to make an Auth in Nuxt using my own express backend API. When i do a normal axios post everything is good. Whenever I add endpoints to my nuxt config it displays this error each time Im making a post request with either axios or auth(through axios again). The connection is proxied due to CORS.

Error:
![image](https://user-images.githubusercontent.com/57097132/116880948-54ba5180-ac2b-11eb-9c5e-c1c287c06449.png)

My nuxt config:
![image](https://user-images.githubusercontent.com/57097132/116881036-70255c80-ac2b-11eb-8295-ebbc928e55de.png)

My Code: 
![image](https://user-images.githubusercontent.com/57097132/116881216-a82c9f80-ac2b-11eb-8350-352c236f9702.png)

**Comment by 4orbalaka** [comment]
idk

**Comment by arjan-kwikqy** [comment]
@Boris-Karamanolev were you able to solve this issue? Have the same problem now..

**Comment by Boris-Karamanolev** [comment]
Actually yes, will post a solution tomorrow.

**Comment by arjan-kwikqy** [comment]
> Actually yes, will post a solution tomorrow.

Looking forward to it! Thank you in advance!

**Comment by Boris-Karamanolev** [comment]
This is what I changed the Nuxt config to:
![image](https://user-images.githubusercontent.com/57097132/124723756-0586ea80-df14-11eb-97a1-7840b2bd4cb1.png)
And this is my call method:
![image](https://user-images.githubusercontent.com/57097132/124723923-2e0ee480-df14-11eb-8ccb-dd15809e92ab.png)
