### ISSUE TITLE
Why is the POST request sent to localhost:3000/_auth/laravelPassport/token when I authenticate with Laravel / Passport Provider?

### ISSUE THREAD

**Issue by is-pooya** [nuxt-community/auth-module#1159]
Why is the POST request sent to **localhost:3000/_auth/laravelPassport/token** insted of **localhost:800**0 when I authenticate with Laravel / Passport Provider?

   `
    auth: {
  
      strategies: {
  
        laravelPassport: {
  
          provider: 'laravel/passport',
  
          url: 'http://localhost:8000/',
  
          clientId: '1',
  
          client_secret: 'dYxeNMPZAMzicKGjByb1hnTciqLScP7KUr7CyKgf',
  
          grantType: 'password',
  
          endpoints: {
                userInfo: '/api/user'
           }
      }
   }`

`Request URL: http://127.0.0.1:3000/_auth/laravelPassport/token`
`Request Method: POST`
`Status Code: 404 Not Found`
`Remote Address: 127.0.0.1:3000`
`Referrer Policy: strict-origin-when-cross-origin`

**Comment by JoaoPedroAS51** [comment]
Closing here due to inactivity. Feel free to reopen if the issue persists.
