### ISSUE TITLE
invalid_request Missing code_challenge

### ISSUE THREAD

**Issue by Yaxdraz** [nuxt-community/auth-module#1162]
My auth settings are like this:
![image](https://user-images.githubusercontent.com/51075535/117563105-58772980-b0ac-11eb-97b6-24501f2d4f69.png)

When i try to login it gives this error:
![image](https://user-images.githubusercontent.com/51075535/117563119-6e84ea00-b0ac-11eb-9000-c11108fe1a3b.png)

What should I do?

**Comment by fabricenl** [comment]
Same issue
