### ISSUE TITLE
The token is created only for 15 minutes

### ISSUE THREAD

**Issue by Aquinary** [nuxt-community/auth-module#1163]
### Version
module: 
nuxt: 

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
```
  auth: {
    redirect: {
      login: '/signin',
      home: '/',
      logout: '/',
    },
    strategies: {
      local: {
        token: {
          property: 'access_token',
          maxAge: 60 * 60 * 24 * 30,
          type: 'Bearer'
        },
        endpoints: {
          login: { url: 'http://localhost:8000/users/signin', method: 'post' },
          logout: false,
          user: { url: 'http://localhost:8000/users/token', method: 'get', propertyName: '' },
        }
      }
    },
  },
```

#### What is expected?
The token will be valid for 30 days
#### What is actually happening?
The token runs for 15 minutes ALWAYS at any set values
## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by Aquinary** [comment]
I managed to fix the problem in a very dirty way. I got into the source code of the module and changed these lines in runtime.mjs:
```
  _updateExpiration(token) {
    let tokenExpiration;
    const _tokenIssuedAtMillis = Date.now();
    const _tokenTTLMillis = Number(this.scheme.options.token.maxAge) * 1e3;
    const _tokenExpiresAtMillis = _tokenTTLMillis ? _tokenIssuedAtMillis + _tokenTTLMillis : 0;
    try {
      //tokenExpiration = jwtDecode(token + "").exp * 1e3 || _tokenExpiresAtMillis;
      tokenExpiration = _tokenExpiresAtMillis;
    } catch (error) {
      tokenExpiration = _tokenExpiresAtMillis;
      if (!(error && error.name === "InvalidTokenError")) {
        throw error;
      }
    }
    return this._setExpiration(tokenExpiration || false);
  }
```
But I don't think it's the right decision.

**Comment by JoaoPedroAS51** [comment]
Closing here due to inactivity. Feel free to reopen if the issue persists.
