### ISSUE TITLE
Laravel Sanctum login provider is just MESSED UP.

### ISSUE THREAD

**Issue by UsmanJavedAttari** [nuxt-community/auth-module#1164]
### Version
"@nuxtjs/auth-next": "^5.0.0-1620155494.96c1b50",
"@nuxtjs/axios": "^5.13.1",
"nuxt": "^2.15.3"

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration
```
  auth: {
    strategies: {
      laravelSanctum: {
        url: `${process.env.API_BASE_URL}/${process.env.API_PREFIX}`,
        endpoints: {
          csrf: {
            url: '/csrf-cookie'
          },
          login: {
            url: '/auth/login'
          },
          logout: {
            url: '/auth/logout'
          },
          user: {
            url: '/auth/user'
          }
        },
        //user: {
          //property: false,
        //}
      }
    },
    cookie: {
      options: {
        expires: 1
      }
    },
    localStorage: false,
    // resetOnError: true,
    redirect: {
      logout: '/sign-in',
      login: '/sign-in',
      home: '/',
      callback: '/'
    }
  },
```

## Reproduction
Just install this module and test any laravel sanctum based API, using the above configuration.

#### What is expected?
The module must load the User after login, or if not atleast set is Logged In to true.
#### What is actually happening?
I don't know what's happening, but the user is not saving into the cookie. and whenever I refresh it just goes to login page.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

IDK the module is broken or what is going on, I am using the simple config that should work seamlessly, but no the cookie doesn't even work. The store is activated, tried all the config from most of the issues, but doesn't work AT ALL. I tried everything which I could, but the user request is not sent. Everyone got it working, but this module doesn't work on my machine. Please help me out, already late due to this not 1 day almost 1 week. The docs are really outdated. Instead of finding the required things in docs, I am finding them in the issues. From the issues I got to know that the config which I AM USING FROM THE DOCS are outdated.

**Comment by UsmanJavedAttari** [comment]
Hey thank for the reply.
And I am also sure we can fix it together :)

Here's what you asked for:
`await new AuthApi().checkAuth()` it just request the user and will return user like:
```
{
Firstname: ....
Lastname:...,
etc:...
}
```

But `await new AuthApi().checkAuth()`, is just to call the user manually, I just removed it, and you can forget it.

So to the endpoints:
the request was sent to csrf-cookie, login, just two requests.
just to let you know that the login, cookies were httpOnly and was having same-site:none,secure.
but I also tried setting httpOnly=false.

And after debugging, I got here. Here you can see `const cookies =`, that cookies, doesn't have the cookie sent from backend.
![image](https://user-images.githubusercontent.com/38417879/117732080-1204f600-b1a4-11eb-90eb-6a424ede59e1.png)

**Comment by UsmanJavedAttari** [comment]
No, the csrf url is changed from backend, that's why I changed it, and in the screenshot above you can see, it is making a request without any issue, and after that there is login request which is also made perfectly, but still user is not logging in.

And to the `cookie.name`, I tried without that and it didn't work, so I assumed that may be it need to put the cookie name which is coming from backend. But it is also not working without that.

 I tried bare level config as well, but it's not going to work.

And this is the cookie situation after login request:

![image](https://user-images.githubusercontent.com/38417879/117791729-773a0500-b1ff-11eb-99fc-888cea19d64c.png)

**Comment by UsmanJavedAttari** [comment]
Also tried this, with and without `cookie.name`:

![image](https://user-images.githubusercontent.com/38417879/117796169-ab172980-b203-11eb-89bb-82c871ea9db9.png)

**Comment by vwasteels** [comment]
Hello @UsmanJavedAttari !
Thanks for the exta documentation on this, I followed the official doc then your thread here, but I still have issues : Laravel send the `XSRF-TOKEN` corectly with the first `/api/sanctum/csrf-cookie` call, but the token is not sent in the next calls, for example when I try a Login , and I receive an error fom Laravel `CSRF token mismatch` , did you succeed to make this work corectly in your app ? I must admit I dont understant how the token should be persistent when the cookie is set with an other domain than `localhost` ... 
Thank you

**Comment by UsmanJavedAttari** [comment]
@vwasteels Hey! I am not working on that project, so can't help :(

**Comment by azzumaraydid7** [comment]
i need help. user not fetch after login
![Screenshot 2022-04-16 172259](https://user-images.githubusercontent.com/50803504/163669616-df618b9c-2440-48ab-b6d0-a861d6a8b5e0.png)
p

**Comment by hoopyfrood** [comment]
> Hello @UsmanJavedAttari !
> 
> Thanks for the exta documentation on this, I followed the official doc then your thread here, but I still have issues : Laravel send the `XSRF-TOKEN` corectly with the first `/api/sanctum/csrf-cookie` call, but the token is not sent in the next calls, for example when I try a Login , I receive an error fom Laravel `CSRF token mismatch` , did you succeed to make this work corectly in your app ? I must admit I dont understant how the token should be persistent when the cookie is set with an other domain than `localhost` ... 
> 
> Thank you

Hi, experienced the same recently working on a SaaS solution, having the `SESSION_DOMAIN` set is optional and needn't be done.
