### ISSUE TITLE
Error: No Token with tokenRequired: false with nuxt-auth module (xpost)

### ISSUE THREAD

**Issue by ishitatsuyuki** [nuxt-community/auth-module#117]
https://github.com/nuxt/docs/issues/546

### Version

4.0.0

### Reproduction link

Kxze/nuxt-auth-bug

### Steps to reproduce

    yarn or npm install
    yarn build or npm run build
    yarn start or npm start
    Go to http://localhost:3000

### What is expected ?

The library logs you in after you press the log in button

### What is actually happening?

The library does not log you in even after a successful login request, as it doesn't receive a token from the API, even though tokenRequired is set to false in nuxt.config.js.

It also prints Error: No Token in the console.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c84">#c84</a>)</em></sub></div>

**Comment by pi0** [comment]
Should be fixed with #118.

**Comment by pi0** [comment]
Fixed in 4.0.1. (Please reopen if still occurs)
