### ISSUE TITLE
is v5 stable to use?

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt-community/auth-module#1171]
I'm currently using `@nuxt/auth` 4.9.1 in my web application, however, it seems that v5 contains some features that I need. I wondered whether v5, more specifically: `5.0.0-1620773067.c356fed` on `@nuxt/auth-next` is stable enough to use in my web application as an upgrade from v4?

Thoughts?

**Comment by silvesterwali** [comment]
I just install it and got some warning like below
![image](https://user-images.githubusercontent.com/40487188/119231563-1510c680-bb54-11eb-87d1-4b2b4d6645ef.png)

and I don't know what exactly this. but I got it when I initial  @nuxtjs/auth-next in my nuxt.config.js

**Comment by sts-ryan-holton** [comment]
@silvesterwali I didn't get that error, did you uninstall `@nuxtjs/auth` first? Because you don't need that

**Comment by JoaoPedroAS51** [comment]
Hi @sts-ryan-holton! Although v5 is not 100% stable, it's recommended to use it as it introduces several features and fixes. Please take a look at #893 and [status](https://auth.nuxtjs.org/status/)

**Comment by JoaoPedroAS51** [comment]
Hi @silvesterwali! I'm not sure about the cause of your issue. Can you show me all your nuxt config?

Might be caused by having both versions of auth installed, as noted by @sts-ryan-holton

**Comment by silvesterwali** [comment]
> @silvesterwali I didn't get that error, did you uninstall `@nuxtjs/auth` first? Because you don't need that

I have uninstalled and install it again at the moment.  every time start nuxt development I got this message so I install version 4.9^ and it work ...without any message showing

**Comment by silvesterwali** [comment]
> Hi @silvesterwali! I'm not sure about the cause of your issue. Can you show me all your nuxt config?
> 
> Might be caused by having both versions of auth installed, as noted by @sts-ryan-holton

here are my nuxt .config.js

the difference is just 

without warning message
```js 
  modules: [     '@nuxtjs/axios',   '@nuxtjs/auth',  ],
```
with warning message
```js 
  modules: [     '@nuxtjs/axios',   '@nuxtjs/auth-next',  ],
```

and my nuxt.config.js

![image](https://user-images.githubusercontent.com/40487188/119466946-ab710200-bd77-11eb-818c-8e893571763e.png)
![image](https://user-images.githubusercontent.com/40487188/119467011-bcba0e80-bd77-11eb-8659-f14c1ba18d23.png)
![image](https://user-images.githubusercontent.com/40487188/119467142-d78c8300-bd77-11eb-99bb-489627247367.png)
