### ISSUE TITLE
Version 5.0.0-1622018627.48534b6 broke login

### ISSUE THREAD

**Issue by toniengelhardt** [nuxt-community/auth-module#1185]
### Version
module: 5.0.0-1622226002.a93068f
nuxt: 2.15.6

### Nuxt configuration
 - [ ] universal
 - [x] spa

### Nuxt configuration
```
auth: {
    plugins: [
      '~/plugins/auth.js',
    ],
    cookie: {
      secure: true,
      expires: 7,
      options: {
        sameSite: 'lax',
      },
    },
    redirect: {
      login: '/login',
      logout: '/login',
      callback: '/login',
      home: '/write',
    },
    resetOnError: true,
    strategies: {
      local: {
        scheme: 'refresh',
        token: {
          property: 'access',
          type: 'JWT',
          maxAge: 60 * 30, // 30 minutes.
        },
        refreshToken: {
          // Data property is important, this is not a JWT token!
          property: 'refresh',
          data: 'refresh',
          maxAge: 60 * 60 * 24 * 90, // 90 days.
        },
        user: {
          property: false,
        },
        endpoints: {
          login: {
            url: '/auth/token/',
            method: 'post',
          },
          refresh: {
            url: '/auth/token/refresh/',
            method: 'post',
          },
          user: false,
          logout: false,
        },
      },
      facebook: {
        clientId: process.env.FACEBOOK_CLIENT_ID,
        responseType: 'code',
        endpoints: {
          token: process.env.BACKEND_URL + '/auth/social/facebook/',
          userInfo: process.env.BACKEND_URL + '/api/user/',
        },
        token: {
          type: 'JWT',
        },
      },
      google: {
        clientId: process.env.GOOGLE_CLIENT_ID,
        responseType: 'code',
        codeChallengeMethod: '',
        endpoints: {
          token: process.env.BACKEND_URL + '/auth/social/google/',
          userInfo: process.env.BACKEND_URL + '/api/user/',
        },
        token: {
          type: 'JWT',
        },
      },
    },
  },

// auth.js

export default function({ app, route, $auth, $axios }) {

  // If the user logged in via Facebook or Google swap the token
  // and change the auth strategy to 'local'.
  if ($auth.loggedIn && ['facebook', 'google'].includes($auth.strategy.name)) {
    $axios
        .post('auth/token/swap/')
        .then(res => {
          $auth.strategies.local.token.set(res.data.access)
          $auth.strategies.local.refreshToken.set(res.data.refresh)
          $auth.$storage.setUniversal('strategy', 'local')
          $auth.mounted()
        })
        .catch(error => { console.error('Token swap', error) })
  }

  // Since the social auth strategies do not have the capability to
  // catch errors in situ it is done here.
  if ($auth.error) {

    // Destroy all tokens.
    $auth.logout()

    if (typeof alert !== 'undefined') {
      alert(
        `An unknown error occurred (code: ${$auth.error.response?.status || 'N/A'}).\n\n` +
        'Please try again to sign in and contact our support if the problem persists.'
      )
    }
    // Remove query params to avoid errors when reloading the page and
    // attempting another login action.
    app.router.replace({ path: route.path })
  }
}
```

#### Steps to reproduce

Call login function:

```
async login() {
      await this.$auth.loginWith('local', {
        data: {
          username: this.username,
          password: this.password,
        },
      })
}
```

#### What is expected?

After login user should be redirected to /write (works in 5.0.0-1622018627.48534b6). 

#### What is actually happening?

Login doesn't do anything, worked fine with previous version.

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

In the most recent commit baseUrl was removed, maybe it is actually needed?

**Comment by mschoeffmann** [comment]
i can confirm this after the upgrade from 5.0.0-1622018627.48534b6 to 5.0.0-1622226002.a93068f

it looks like it ignores the custom axios base url for configured endpoints:
```
  publicRuntimeConfig: {
    axios: {
      browserBaseURL: 'https://my-api.example.com/v1',
    },
  },
  auth: {
    redirect: {
      login: '/login',
      logout: '/login',
      home: '/',
      callback: false,
    },
    fullPathRedirect: true,
    localStorage: false,
    cookie: {
      prefix: 'auth.',
      options: {
        path: '/',
        maxAge: 2592000,
      },
    },
    strategies: {
      local: {
        scheme: 'refresh',
        token: {
          property: 'tokens.access.token',
        },
        refreshToken: {
          property: 'tokens.refresh.token',
          data: 'refreshToken',
        },
        user: {
          property: 'user',
        },
        endpoints: {
          login: { url: '/test-auth/login', method: 'post' },
          logout: { url: '/test-auth/logout', method: 'post' },
          refresh: { url: '/test-auth/refresh-tokens', method: 'post' },
          user: { url: '/test-auth/self', method: 'get' },
        },
      },
    },
  },
```
... uses `/test-auth/login` instead of `https://my-api.example.com/v1/test-auth/login`

**Comment by toniengelhardt** [comment]
Thanks!

**Comment by JoaoPedroAS51** [comment]
@toniengelhardt @mschoeffmann Fixed! :wink: 

`@nuxtjs/auth-next@5.0.0-1622309801.87126e3`

**Comment by asterd** [comment]
@JoaoPedroAS51 I think this fix broke something else. If I have a nuxt app with router.baseUrl configured to /myapp (for example) and the auth strategies token endpoint is an absolute URL (eg https://server/oauth2/token) the module calls: http://myserver/myapp/http://server/oauth2/token!! And obviously broke all the thinks. Without router.baseUrl customization it works. I thinks the code you changed managed exactly this behaviour. I hope it will be fixed asap! Thanks a lot!

**Comment by RonAlmog** [comment]
Hey @toniengelhardt , can you please explain these comments:
```
// If the user logged in via Facebook or Google swap the token
// and change the auth strategy to 'local'.
```
and maybe share the code for this backend method:
```.post('auth/token/swap/')```
i mean, user that was authenticated thru fb, has no password, how will you create a jwt token for her?
thanks!

**Comment by toniengelhardt** [comment]
> Hey @toniengelhardt , can you please explain these comments:
> 
> ```
> // If the user logged in via Facebook or Google swap the token
> // and change the auth strategy to 'local'.
> ```
> 
> and maybe share the code for this backend method:
> `.post('auth/token/swap/')`
> i mean, user that was authenticated thru fb, has no password, how will you create a jwt token for her?
> thanks!

Hey @RonAlmog, this is a little hack to make refreshing tokens work with social authentication. I authenticate the user with the token from the provider, then I switch the strategy to local behind the scenes and retrieve a new local + refresh token from the backend, which is then used until the refresh token expires. Once expired the user authenticates again via social and the process repeats. 

I'm using `Django` and `rest_framework_simplejwt` in the backend, which doesn't require a password to generate the token if the user is authenticated. 

The swap endpoint looks like this: 

```
class SwapTokenView(APIView):
    """Generate an auth/refresh token pair for an authenticated user"""
    def post(self, request: Request, **kwargs) -> Response:
        if not request.user.is_authenticated:
            raise ValidationError('Authentication required.')
        refresh = RefreshToken.for_user(request.user)
        return Response({
            'access': str(refresh.access_token),
            'refresh': str(refresh),
        })
```

This is probably not ideal, but it works well and I couldn't find another solution...

**Comment by RonAlmog** [comment]
ok thanks!
