### ISSUE TITLE
Not redirecting after login when going directly on the route

### ISSUE THREAD

**Issue by darrenchiu** [nuxt-community/auth-module#1188]
I have been trying to confirm if Nuxt Auth have this feature implemented but don't seem to find a conclusion in other threads, e.g. #134 .

Would anyone be able to confirm is this is a feature implemented or not?

Thanks.

**Comment by KunalAggarwal** [comment]
Refer to https://github.com/nuxt-community/auth-module/issues/205#issuecomment-850906221 in case login logout redirection doesn't work for someone. I managed to get it working as mentioned in that comment. Might be helpful for someone.

**Comment by darrenchiu** [comment]
Works like a charm. Thanks @KunalAggarwal
