### ISSUE TITLE
Option to use oauth IdToken instead of AccessToken

### ISSUE THREAD

**Issue by sschadwick** [nuxt-community/auth-module#119]
### What problem does this feature solve?

Currently, the auth-module uses the returned AccessToken and attaches it to each request (via the axios module). https://github.com/nuxt-community/auth-module/blob/master/lib/schemes/oauth2.js#L92

My current environment (AWS Cognito,  Api Gateway Authorizer => Lambda) checks for and evaluates the IdToken. When I attempt to use the AccessToken, my api endpoints return a 401 Unauthorized.

### What does the proposed changes look like?

Add a config option to utilize the returned IdToken instead of AccessToken. Default setting should still use AccessToken.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c85">#c85</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey. Would you please share your current auth config?

**Comment by sschadwick** [comment]
Thanks for the quick reply, here's my config:
```
auth: {
  strategies: {
    oauth: {
      _scheme:                'oauth2',
      authorization_endpoint: 'https://<congitoInstance>.auth.us-west-2.amazoncognito.com/oauth2/authorize',
      userinfo_endpoint:      '',
      scope:                  [],
      response_type:          'token',
      token_type:             '',
      redirect_uri:           '<siteDomain>',
      client_id:              '<cognitoClientId>'
    }
  }
},
```

**Comment by pi0** [comment]
Thanks, @sschadwick for info. That'll help moving forward.
