### ISSUE TITLE
Google login redirects to /login with query string option

### ISSUE THREAD

**Issue by amansharmadev** [nuxt-community/auth-module#1193]
Is this a bug in version "@nuxtjs/auth-next": "5.0.0-1622309801.87126e3"  ?

Github and Facebook working right.

**Comment by amansharmadev** [comment]
I got the fix so closing this issue

`responseType: 'token id_token', `

earlier responseType was 'code'

**Comment by aekirgil** [comment]
Hi,

May you share the facebook solution to flow and nuxt configuration, please?

I figure out integration until the callback phase of the flow but I don't know how to get user data and how to finished the login flow.

Thanks

**Comment by RonAlmog** [comment]
stuck on the same thing. any progress? found any solution?

**Comment by amansharmadev** [comment]
Facebook does not required anything special it works out of the box in my case.
Please share code or more details

**Comment by RonAlmog** [comment]
thanks, @amansharmadev . do you have a page in your website that is the redirect url from facebook? what is that page look like?
in your facebook settings, there is site url (i guess the url to return info to our website?) what did you write there?
![Screenshot 2021-08-08 110213](https://user-images.githubusercontent.com/5527427/128636582-a7988580-d9f6-4390-a34f-e2f246b69dad.png)

**Comment by amansharmadev** [comment]
You don't need to add the website info
Just create App 
add name, email and App domain (in my case it is 'localhost')
