### ISSUE TITLE
nonce property doesn't get along with empty code_challenge_method with google strategy

### ISSUE THREAD

**Issue by dajpes** [nuxt-community/auth-module#1199]
### Version
nuxt: 2.15.3
module:  5.0.0-1622918202.e815752

https://github.com/nuxt-community/auth-module/commit/92eabbd55580302487d483bf51df6df46aad120b#diff-1298e7a5a53becd4c571426459b3b54ebe1b790280a0ecf0f946cf8ff5ad88bd

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

```js
auth: {
    redirect: {
      login: '/',
      home: false,
    },
    strategies: {
      google: {
        clientId:
          'mySecret.apps.googleusercontent.com',
        scope: ['profile', 'email'],
        redirectUri: 'http://localhost:3000/login',
        codeChallengeMethod: '',
        token: {
          maxAge: 3600,
        },
      },
    },
  }
  
```

## Reproduction
> :warning: without a minimal reproduction we won't be able to look into your issue

1 Step: Create a new nuxt app Repo
2- Install and configure nuxt auth with its config (see above) and  a default vuex store
3- implement a google auth button with $auth.loginWith("google")
4-**BEFORE** getting the google error page, copy the url created by nuxt (open dev tools, and on the networks tabs the url should be there)
In my case, this is the url I get:
```
https://accounts.google.com/o/oauth2/auth?protocol=oauth2&response_type=token&access_type&client_id=YOLO.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Flocalhost%3A3005%2Flogin&scope=openid%20profile%20email%20profile%20email&state=GMaz12xzTu&code_challenge_method=&nonce=SXyX7LgsDa
```
5- Now with the url that you copy (that it's also similar to the above), copy paste the url again in a new tab, but first get rid of this part "&code_challenge_method=&nonce=SXyX7LgsDa". Your url should be like this now:
```
https://accounts.google.com/o/oauth2/auth?protocol=oauth2&response_type=token&access_type&client_id=YOLO.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Flocalhost%3A3005%2Flogin&scope=openid%20profile%20email%20profile%20email&state=GMaz12xzTu
```
6- Now the login works

#### What is expected?
google auth  should work with the default parameters
#### What is actually happening?
Google auth doesn't work
## Additional information
 I think the problem is because of the nonce parameter, I'd bet the bug was introduced [here ](https://github.com/nuxt-community/auth-module/commit/92eabbd55580302487d483bf51df6df46aad120b#diff-1298e7a5a53becd4c571426459b3b54ebe1b790280a0ecf0f946cf8ff5ad88bd). 
 
Maybe if there's a way to disable both code_challenge_method and nonce parameters in oAuth.

The only workaround I found was setting inside the google strategy this parameter:

```  responseType: 'token id_token' ```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by adammacias** [comment]
Confirm. I have the same bug here. 

- @nuxtjs/auth-next: 5.0.0-1624817847.21691f1
- nuxt: 2.15.7

**Comment by adibemohamed** [comment]
the same issue, solved the same way
