### ISSUE TITLE
Manual FetchUser callback

### ISSUE THREAD

**Issue by sschadwick** [nuxt-community/auth-module#120]
### What problem does this feature solve?

AWS Cognito does not currently offer a userinfo_endpoint. https://forums.aws.amazon.com/thread.jspa?messageID=819386&tstart=0

### What does the proposed changes look like?

It would be very helpful to have the option to override the FetchUser function, as the userinfo data in this case is (client-side) derivable from the IdToken.

Essentially, the proposed changes would be similar to the fetchUser option in https://github.com/samtgarson/nuxt-oauth.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c86">#c86</a>)</em></sub></div>

**Comment by p3t3r67x0** [comment]
Looks like userInfo endpoint has been added... https://docs.aws.amazon.com/cognito/latest/developerguide/userinfo-endpoint.html
