### ISSUE TITLE
Auth-next not working properly with Google

### ISSUE THREAD

**Issue by ForceBlood** [nuxt-community/auth-module#1202]
### Version
module: 5.0.0-1622918202.e815752
nuxt: 2.15.3

### Nuxt configuration
 - [x] universal
 - [ ] spa

### Nuxt configuration
```
  auth: {
    strategies: {
      google: {
        clientId: 'XXXXXXXXXXXXXXXX.apps.googleusercontent.com',
        codeChallengeMethod: '',
        scope: ['profile', 'email', 'openid'],
        responseType: 'token id_token',
        redirectUri: 'http://localhost:3000/login',
        endpoints: {
          authorization: 'https://accounts.google.com/o/oauth2/v2/auth',
          userInfo: 'https://www.googleapis.com/oauth2/v3/userinfo',
        }
      }
    }
  }
```

## Reproduction
https://codesandbox.io/s/sd7ff

#### What is expected?
The user should be logged in

#### What is actually happening?
The user is redirected to the site but loggedIn is set to false and user is null

#### Steps to reproduce

1. Get a Client ID for google
2. Set up google auth with your client ID
3. Observe user not getting loggedIn even though the token is accessible from this.$auth.strategy.token.get('google')

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

![image](https://user-images.githubusercontent.com/33997884/121808427-22a40280-cc61-11eb-8569-f4457ec49f28.png)

**Comment by ForceBlood** [comment]
^^ Seems like it was an issue with the Vue.js dev tools showing the state wrong.

**Comment by diakonovm** [comment]
Version: `@nuxtjs/auth-next": "5.0.0-1624817847.21691f1`

I am having the same issue.

I am making a call to a server which grants permission to the application with Google, but upon redirect the user is not logged in. I do not understand if I need to pass back a `jwt` token from the server or the response as detailed in the [google exchange code](https://developers.google.com/identity/protocols/oauth2/openid-connect#exchangecode). In any case, neither is working.

```
google: {
        endpoints: {
          authorization: 'https://accounts.google.com/o/oauth2/auth',
          token: `${process.env.BASE_URL}/oauth/google`,
          logout: `http://localhost:8080/login`,
          userInfo: `${process.env.BASE_URL}/me`,
        },
        grantType: 'authorization_code',
        responseType: 'code',
        redirectUri: `http://localhost:8080/me/chat`,
        scope: ['openid', 'profile', 'email'],
        clientId: '***',
        state: 'UNIQUE_AND_NON_GUESSABLE',
        codeChallengeMethod: ''
      }
```
