### ISSUE TITLE
Refresh scheme doesn't seem to be working.

### ISSUE THREAD

**Issue by BlackoutGG** [nuxt-community/auth-module#1213]
I've got an express back end that responds with the access token and refresh token upon login. However the refresh timer does seem to be firing off when the access_token expires (for test purposes I set the expiry on the token to 3 minutes).

### Version
module: 4.9.1
nuxt: 2.15.x

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 
 - [ x] spa

```
  auth: {
    redirect: {
      login: '/',
      home: '/',
    },
    strategies: {
      local: {
        scheme: 'refresh',
        token: {
          property: 'token',
          maxAge: 180,
          global: true,
        },
        refreshToken: {
          property: 'refresh_token',
          data: 'refresh_token',
          maxAge: 3600,
        },
        user: {
          property: 'user',
        },
        endpoints: {
          login: {
            url: '/auth/login',
            method: 'post',
            // propertyName: 'token',
          },
          refresh: { url: '/auth/refresh', method: 'post' },
          logout: { url: '/auth/logout', method: 'post' },
          user: { url: '/auth/user', method: 'get' },
        },
      },
    },
```

**Helpful Links:** 
- https://codesandbox.io/
- https://github.com/nuxt-community/auth-module
-->

#### What is expected?
The token should refresh using /api/auth/refresh once the access_token expires.

#### What is actually happening?
Refresh interval does not seem to be firing off, and in local the refresh token does not seem to be set (even the refresh_token was sent in the login response)
```
"auth._refresh_token.local": "false"
```

**Comment by devzom** [comment]
Have You resolved the issue, or what's happened?

**Comment by devzom** [comment]
@BlackoutGG have You resolved the issue?

**Comment by halilyuce** [comment]
Same issue here, did you find a solution?

**Comment by Destaq** [comment]
Having some trouble here too, were you able to figure out a solution?

**Comment by devzom** [comment]
I've handled the laravelJWT refresh scheme but with lot of workarounds, also had a auth.plugin which was handling setInterval and checking token.expiry 30sec before it had to expiry.

But I've found the built-in timer of $nuxt.auth wasn't refreshing token, but before any request was made and refresh_token was valid then $auth is calling refreshTokens() and applying the new access_token.
