### ISSUE TITLE
I don't know how to set the propertyName when the loginAPI returns the token as the second level of information.

### ISSUE THREAD

**Issue by kodai305** [nuxt-community/auth-module#1218]
If the loginAPI returns the token in the following format, it will work.

```
{"token": "XXXX"}
```

The settings are as follows.

```
  auth: {
    redirect: {
      login: '/login', 
      logout: '/login',
      callback: undefined, 
      home: '/home' 
    },
    strategies: {
      local: {
        endpoints: {
          login: { url: 'https://XXX/login', method: 'post', propertyName: 'token' },
          user: false, 
          logout: false 
        }
      }
    }
  },
```

However, the loginAPI I want to use returns the token in the following format.

```
{
    "Result": {
        "Status": "Done",
        "token": "XXX",
    },
    "Status": "Done"
}
```

In such a case, what should I set for the propertyName?

**Comment by JoaoPedroAS51** [comment]
Hi @kodai305! You should use dot notation `Result.token` :)

Note that `propertyName` is for auth v4 only. If you are using v5, see [token option](https://auth.nuxtjs.org/schemes/local#token).

**Comment by kodai305** [comment]
Thank you @JoaoPedroAS51 . I use v5 and, setting property to `Result.token`, successful login process.
But, I have it set up as follows, but after logging in, it transitions to '/'. Is there something wrong with my settings?

```
redirect: {
  home: '/home'
}
```

**Comment by kodai305** [comment]
I'm sorry, I tried again and it went to '/home'.
So let me call it solved.
