### ISSUE TITLE
When accessing /login while already logged in, I want to go to the page set in home instead of the login screen.

### ISSUE THREAD

**Issue by kodai305** [nuxt-community/auth-module#1219]
I have the following setup.

```
auth: {
    redirect: {
      login: '/login',
      logout: '/login',
      callback: undefined,
      home: '/home'
    },
    strategies: {
      local: {
        token: {
          property: 'Result.token',
          global: true,
          required: true,
          type: 'Bearer'
        },
        endpoints: {
          login: { url: 'https://XXX/v1/login', method: 'post' },
          user: false, 
          logout: false 
        }
      }
    }
  },
```

After successful login, when I access /login, the login screen of /login is displayed.
Is there any way to make it go to the path set for home if I am already logged in?

**Comment by JoaoPedroAS51** [comment]
Hi @kodai305! You should define your user endpoint. It's needed in order to retrieve the user as we don't store it.

See [fetch user](https://auth.nuxtjs.org/schemes/local#fetch-user) for more information.

**Comment by kodai305** [comment]
Thank you for your information.
