### ISSUE TITLE
options.token.name not used anymore

### ISSUE THREAD

**Issue by Sheby** [nuxt-community/auth-module#122]
### Version

[4.0.1](https://github.com/nuxt-community/auth-module/releases/tag/4.0.1)

### Steps to reproduce

Set token.name to false.

Login using any strategy.

Token is still set in localStorage under key 'auth._token.local' or whatever other strategy is used.

### What is expected ?

Token should not appear in localStorage.

### What is actually happening?

Token is still set in local storage.

### Additional comments?

I've just upgraded from 4.0.0-rc.3 to 4.0.1.
In older version version I've set token.name to false since I'm using same auth in multiple nuxt projects.
Lets say my cookie domain is '.example.com' and i have nuxt projects on 'admin.example.com' (d1) and 'store.example.com' (d2).
If a user logs in on d1 cookies and local storage are set, and then if he goes to d2 he will be logged in automatically, which is desired.
But if he then logs out either on d1 (or d2) and navigates to d2 (or d1) he will be logged in again since local storage was not cleared,
at the same time new cookie will be set which is valid for both domains, and voila user is logged in on both domains again like he never logged out.

It looks to me all values are saved both in local storage and cookies, maybe you could provide an option to disable local storage completely?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c87">#c87</a>)</em></sub></div>

**Comment by benmccallum** [comment]
It looks like you can no longer customize the name, but you can still disable certain universal storage techniques:
* [setCookie](https://github.com/nuxt-community/auth-module/blob/08299eaba9c5b8be73f469ec1de2c1cb1009f95f/lib/core/storage.js#L168) checks for falsey `options.cookie`, so instead of setting `cookie.name` to false, you should set `cookie` to false
* [setLocalStorage](https://github.com/nuxt-community/auth-module/blob/08299eaba9c5b8be73f469ec1de2c1cb1009f95f/lib/core/storage.js#L135) is similar, so in your case you should set `localStorage` to false.

Does that help?

**Comment by benmccallum** [comment]
Looks like the docs are out of date, I'll update them when I get a sec

**Comment by Sheby** [comment]
It works, thanks. I somehow missed that while I was going trough source.

There is one bigger undocumented issue, if you can put that in the docs too please.
If token.prefix starts with "_" then setting token on the server side won't work.
I used $auth.setToken(...) inside axios interceptor and if the interceptor is triggered on server side request it does nothing.
Fixed this by changing prefix to "token" from "_token".

**Comment by benmccallum** [comment]
Hey @Sheby, let me know how the documentation looks when changed in the above PR #135. 😃

**Comment by Sheby** [comment]
@benmccallum seems good.
On different issue #133 , could you just add that if token.prefix starts with "_" local store won't work on server side.

**Comment by benmccallum** [comment]
Sure thing, let's discuss that over there. The PR can treat both.
