### ISSUE TITLE
Custom scheme axios headers, etc

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/auth-module#1226]
Is there a way to set custom headers with `this.$auth.loginWith('customScheme')` ? For example, i need to set a header:

```
Content-type: application/x-www-form-urlencoded
```

When getting a token from a backend, seems like there's no way to do that.

**Comment by JoaoPedroAS51** [comment]
Hi @webcoderkz! Yes, you can achieve this by passing a second argument, which is the axios request config:
```js
this.$auth.loginWith('customScheme', {
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded'
  }
})
```

Let me know if it worked! :)

**Comment by webcoderkz** [comment]
@JoaoPedroAS51, thanks! Is it documented? Couldn't find this kind of information. So, there's no need to create own scheme, just for the headers i guess.

**Comment by JoaoPedroAS51** [comment]
Yes, it's documented in [api/auth#loginWith](https://auth.nuxtjs.org/api/auth#loginwithstrategyname-args), but in the example it set params and data instead of headers.

> Do you have any custom scheme working examples?

Sorry, we don't have an example in the demo, but [the example in docs](https://auth.nuxtjs.org/guide/scheme#creating-your-own-scheme) should work.

**Comment by webcoderkz** [comment]
I saw this example, but where can i check all the methods when defining my own scheme?

**Comment by JoaoPedroAS51** [comment]
Which scheme are you extending?

**Comment by webcoderkz** [comment]
none, just creating it from the scratch. Do you recommend to extend like local or refresh schemes?

**Comment by JoaoPedroAS51** [comment]
I don't know what custom features you want to add, but extending one of them will save you some time.
Of course, unless you need something really specific which couldn't be implemented by extending one of them.

**Comment by webcoderkz** [comment]
Well, thanks, docs could be a bit improved anyway :)

**Comment by JoaoPedroAS51** [comment]
But if you want to create from scratch, take a look at [local scheme source code](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/local.ts) first. It will lead you to the right direction :)

**Comment by webcoderkz** [comment]
What's the purpose of `endpoints` btw? Can't get it. I can call endpoint by any name, it doesn't matter? How it's being called? Let's say:

```
    strategies: {
      local: {
        endpoints: {
          login: {
            url:
              'http://example.com',
            method: 'post',
            propertyName: 'access_token',
          },
          logout: { url: '/logout', method: 'get' },
          user: { url: '/userinfo', method: 'get', propertyName: false },
        },
      },
```

Does endpoint name matters?

**Comment by JoaoPedroAS51** [comment]
They are used by the scheme: [login endpoint](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/local.ts#L175), [user endpoint](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/local.ts#L175) and [logout endpoint](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/local.ts#L239)

**Comment by webcoderkz** [comment]
@JoaoPedroAS51 how can i extend refresh scheme?

Local is located on this path: `import { LocalScheme } from '~auth/runtime'`

But how do i import RefreshScheme?

**Comment by JoaoPedroAS51** [comment]
@webcoderkz Try `import { RefreshScheme } from '~auth/runtime'`
