### ISSUE TITLE
dispatch this.$auth.fetchUser() in middleware

### ISSUE THREAD

**Issue by IsidroMar95** [nuxt-community/auth-module#1228]
How can i dispatch `this.$auth.fetchUser()` i mean is that even posible?

**Comment by IsidroMar95** [comment]
i figured out how to do it:

```js
export default function ({ $auth }) {
  $auth.fetchUser()
}
```

**Comment by zakihuang** [comment]
I have a question like this.
After login with github, i  want to get the user infomation at the callback.vue page, but i can't find a method to do...
