### ISSUE TITLE
401 response on get user after login

### ISSUE THREAD

**Issue by omid-reza** [nuxt-community/auth-module#1233]
### Version
module: 5.0.0-1624817847.21691f1
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] spa

### Nuxt configuration
```javascript
  auth:{
    strategies: {
      'laravelSanctum': {
        provider: 'laravel/sanctum',
        url: 'http://localhost:8000',
        endpoints:{
          login:{
            url:'/login',
          },
          logout:{
            url:'/api/logout'
          },
        }
      },
    },
    redirect:{
      login: '/auth/login',
      logout:'/',
      home:'/'
    },
    cookie: {
      options: {
        sameSite: 'lax'
      },
    },
  },
  axios: {
  },
```

#### What is expected?
I expect to get user and login correct.
#### What is actually happening?
I get 401(`unauthenticated` message) error from laravel after login on get user data
## Additional information
- **There is my** [question](https://stackoverflow.com/questions/68266276/get-401unauthenticated-error-after-login-on-laravel-sanctum-with-nuxtjs) **on stackoverflow with more information about this problem**

## Checklist
* [ ]  I have tested with the latest Nuxt version and the issue still occurs
* [ ]  I have tested with the latest module version and the issue still occurs
* [ ]  I have searched the issue tracker and this issue hasn't been reported yet

### What is expected?
I expect to get user and login correct.

### What is actually happening?
I get 401(`unauthenticated` message) error from laravel after login on get user data

**Comment by bmulholland** [comment]
There isn't any action the auth module can take here. 401 responses are on the laravel side. If you find an issue within the nuxt/auth codebase, please open an issue for that.
