### ISSUE TITLE
How to override refresh method's axios config?

### ISSUE THREAD

**Issue by webcoderkz** [nuxt-community/auth-module#1242]
nuxt.config.js:

```
  strategies: {
    local: {
      scheme: 'refresh',
      token: {
        property: 'access_token',
        maxAge: 1800,
      },
      refreshToken: {
        property: 'refresh_token',
        data: 'refresh_token',
        maxAge: 18000,
        tokenRequired: true,
      },
      user: {
        property: false,
      },
      endpoints: {
        login: {
          url:
            keycloakURL +
            '/auth/realms/spring-data-rest/protocol/openid-connect/token',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
          },
          method: 'post',
          propertyName: 'access_token',
        },
        refresh: {
          url:
            keycloakURL +
            '/auth/realms/spring-data-rest/protocol/openid-connect/token',
          headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
          },
          method: 'post',
        },
        logout: { url: '/logout', method: 'get' },
        user: {
          url:
            keycloakURL +
            '/auth/realms/spring-data-rest/protocol/openid-connect/userinfo',
          method: 'get',
          propertyName: false,
        },
      },
    },
  },
```

How can i send data as a string, when firing `refresh` method? When i'm using login, i can alter the data:

```
this.$auth.loginWith('local', {
  data: `grant_type=password&client_id=client&username=${this.formData.username}&password=${this.formData.password}`,
})
```

Is there a way to make the same thing with refresh method? I cannot find in the sources, where i can override it.

**Comment by webcoderkz** [comment]
I've tried to use a custom refresh scheme:

```
import { RefreshScheme } from '~auth/runtime'

export default class KeycloakScheme extends RefreshScheme {
  refreshTokens() {
    // Refresh endpoint is disabled
    if (!this.options.endpoints.refresh) {
      return Promise.resolve()
    }

    // Token and refresh token are required but not available
    if (!this.check().valid) {
      return Promise.resolve()
    }

    // Get refresh token status
    const refreshTokenStatus = this.refreshToken.status()

    // Refresh token is expired. There is no way to refresh. Force reset.
    if (refreshTokenStatus.expired()) {
      this.$auth.reset()

      // throw new ExpiredAuthSessionError()
    }

    // Delete current token from the request header before refreshing, if `tokenRequired` is disabled
    if (!this.options.refreshToken.tokenRequired) {
      this.requestHandler.clearHeader()
    }

    const endpoint = {
      data: {
        client_id: undefined,
        grant_type: undefined,
      },
    }

    // Add refresh token to payload if required
    if (this.options.refreshToken.required && this.options.refreshToken.data) {
      endpoint.data[this.options.refreshToken.data] = this.refreshToken.get()
    }

    // Add client id to payload if defined
    if (this.options.clientId) {
      endpoint.data.client_id = this.options.clientId
    }

    // Add grant type to payload if defined
    if (this.options.grantType) {
      endpoint.data.grant_type = 'refresh_token'
    }

    // cleanObj(endpoint.data)

    // Make refresh request
    return this.$auth
      .request(endpoint, this.options.endpoints.refresh)
      .then(response => {
        // Update tokens
        this.updateTokens(response, { isRefreshing: true })
        console.log('refresh fired')
        return response
      })
      .catch(error => {
        this.$auth.callOnError(error, { method: 'refreshToken' })
        return Promise.reject(error)
      })
  }
}
```

and put `console.log('refresh fired')`, but no success, calling it `this.$auth.refreshTokens()`

**Comment by webcoderkz** [comment]
@JoaoPedroAS51 i need your help :)

**Comment by JoaoPedroAS51** [comment]
Hi @webcoderkz! :)
First let's try adding a `console.log` in  `refreshTokens` method before `Refresh endpoint is disabled`, just to check if it's being called.

**Comment by JoaoPedroAS51** [comment]
Just to be sure, have you changed the `scheme` in auth config to the path of your custom scheme?

**Comment by JoaoPedroAS51** [comment]
Now what you want to change is the `const endpoint`, like the example below
```js
const endpoint = {
  data: `grant_type=password&client_id=client&username=${this.formData.username}&password=${this.formData.password}`
}
```

**Comment by webcoderkz** [comment]
How do i pass `formData.username` in a refresh method? Also do i need to declare constructor when overriding a scheme?

**Comment by JoaoPedroAS51** [comment]
What kind of data you need to pass to `refresh` enpoint?

**Comment by JoaoPedroAS51** [comment]
> Can you point me, where to insert it exactly, please?

The first line of `refreshTokens` method. Above the comment `Refresh endpoint is disabled`.

**Comment by webcoderkz** [comment]
> What kind of data you need to pass to refresh enpoint?

`grant_type=refresh_token&client_id=client&refresh_token=TOKEN_STRING`

I need to send it as string above.

**Comment by JoaoPedroAS51** [comment]
@webcoderkz You can add me on discord Joao Pedro AS51#1284

**Comment by webcoderkz** [comment]
@JoaoPedroAS51 sent a friend request

**Comment by JoaoPedroAS51** [comment]
Try this:
```js
const endpoint = {
  data: `grant_type=refresh_token&client_id=${this.options.clientId}&refresh_token=${this.refreshToken.get()}`
}
```

Then remove the other code below: `Add refresh token to payload if required`, ` Add client id to payload if defined` and `Add grant type to payload if defined`

**Comment by webcoderkz** [comment]
With the help of @JoaoPedroAS51 here's the final solution:

```js
import { RefreshScheme, ExpiredAuthSessionError } from '~auth/runtime'

export default class KeycloakScheme extends RefreshScheme {
  async login(endpoint, { reset = true } = {}) {
    if (!this.options.endpoints.login) {
      return
    }

    // Ditch any leftover local tokens before attempting to log in
    if (reset) {
      this.$auth.reset({ resetInterceptor: false })
    }

    const _endpoint = {
      data: `username=${endpoint.data.username}&password=${endpoint.data.password}`,
    }

    // Add client id to payload if defined
    if (this.options.clientId) {
      _endpoint.data += `&client_id=${this.options.clientId}`
    }

    // Add grant type to payload if defined
    if (this.options.grantType) {
      _endpoint.data += `&grant_type=${this.options.grantType}`
    }

    // Add scope to payload if defined
    if (this.options.scope) {
      _endpoint.data += `&scope=${this.options.scope}`
    }

    // Make login request
    const response = await this.$auth.request(
      _endpoint,
      this.options.endpoints.login
    )

    // Update tokens
    this.updateTokens(response)

    // Initialize request interceptor if not initialized
    if (!this.requestHandler.interceptor) {
      this.initializeRequestInterceptor()
    }

    // Fetch user if `autoFetch` is enabled
    if (this.options.user.autoFetch) {
      await this.fetchUser()
    }

    return response
  }

  refreshTokens() {
    // Refresh endpoint is disabled
    if (!this.options.endpoints.refresh) {
      return Promise.resolve()
    }

    // Token and refresh token are required but not available
    if (!this.check().valid) {
      return Promise.resolve()
    }

    // Get refresh token status
    const refreshTokenStatus = this.refreshToken.status()

    // Refresh token is expired. There is no way to refresh. Force reset.
    if (refreshTokenStatus.expired()) {
      this.$auth.reset()

      throw new ExpiredAuthSessionError()
    }

    // Delete current token from the request header before refreshing, if `tokenRequired` is disabled
    if (!this.options.refreshToken.tokenRequired) {
      this.requestHandler.clearHeader()
    }

    const endpoint = {
      data: `grant_type=refresh_token&client_id=${
        this.options.clientId
      }&refresh_token=${this.refreshToken.get()}`,
    }

    // // Add refresh token to payload if required
    // if (this.options.refreshToken.required && this.options.refreshToken.data) {
    //   endpoint.data[this.options.refreshToken.data] = this.refreshToken.get()
    // }

    // // Add client id to payload if defined
    // if (this.options.clientId) {
    //   endpoint.data.client_id = this.options.clientId
    // }

    // // Add grant type to payload if defined
    // if (this.options.grantType) {
    //   endpoint.data.grant_type = 'refresh_token'
    // }

    // cleanObj(endpoint.data)

    // Make refresh request
    return this.$auth
      .request(endpoint, this.options.endpoints.refresh)
      .then(response => {
        // Update tokens
        this.updateTokens(response, { isRefreshing: true })
        return response
      })
      .catch(error => {
        this.$auth.callOnError(error, { method: 'refreshToken' })
        return Promise.reject(error)
      })
  }
}
```

**Comment by productfrontenddeveloper** [comment]
> With the help of @JoaoPedroAS51 here's the final solution:
> 
> ```js
> import { RefreshScheme, ExpiredAuthSessionError } from '~auth/runtime'
> 
> export default class KeycloakScheme extends RefreshScheme {
>   async login(endpoint, { reset = true } = {}) {
>     if (!this.options.endpoints.login) {
>       return
>     }
> 
>     // Ditch any leftover local tokens before attempting to log in
>     if (reset) {
>       this.$auth.reset({ resetInterceptor: false })
>     }
> 
>     const _endpoint = {
>       data: `username=${endpoint.data.username}&password=${endpoint.data.password}`,
>     }
> 
>     // Add client id to payload if defined
>     if (this.options.clientId) {
>       _endpoint.data += `&client_id=${this.options.clientId}`
>     }
> 
>     // Add grant type to payload if defined
>     if (this.options.grantType) {
>       _endpoint.data += `&grant_type=${this.options.grantType}`
>     }
> 
>     // Add scope to payload if defined
>     if (this.options.scope) {
>       _endpoint.data += `&scope=${this.options.scope}`
>     }
> 
>     // Make login request
>     const response = await this.$auth.request(
>       _endpoint,
>       this.options.endpoints.login
>     )
> 
>     // Update tokens
>     this.updateTokens(response)
> 
>     // Initialize request interceptor if not initialized
>     if (!this.requestHandler.interceptor) {
>       this.initializeRequestInterceptor()
>     }
> 
>     // Fetch user if `autoFetch` is enabled
>     if (this.options.user.autoFetch) {
>       await this.fetchUser()
>     }
> 
>     return response
>   }
> 
>   refreshTokens() {
>     // Refresh endpoint is disabled
>     if (!this.options.endpoints.refresh) {
>       return Promise.resolve()
>     }
> 
>     // Token and refresh token are required but not available
>     if (!this.check().valid) {
>       return Promise.resolve()
>     }
> 
>     // Get refresh token status
>     const refreshTokenStatus = this.refreshToken.status()
> 
>     // Refresh token is expired. There is no way to refresh. Force reset.
>     if (refreshTokenStatus.expired()) {
>       this.$auth.reset()
> 
>       throw new ExpiredAuthSessionError()
>     }
> 
>     // Delete current token from the request header before refreshing, if `tokenRequired` is disabled
>     if (!this.options.refreshToken.tokenRequired) {
>       this.requestHandler.clearHeader()
>     }
> 
>     const endpoint = {
>       data: `grant_type=refresh_token&client_id=${
>         this.options.clientId
>       }&refresh_token=${this.refreshToken.get()}`,
>     }
> 
>     // // Add refresh token to payload if required
>     // if (this.options.refreshToken.required && this.options.refreshToken.data) {
>     //   endpoint.data[this.options.refreshToken.data] = this.refreshToken.get()
>     // }
> 
>     // // Add client id to payload if defined
>     // if (this.options.clientId) {
>     //   endpoint.data.client_id = this.options.clientId
>     // }
> 
>     // // Add grant type to payload if defined
>     // if (this.options.grantType) {
>     //   endpoint.data.grant_type = 'refresh_token'
>     // }
> 
>     // cleanObj(endpoint.data)
> 
>     // Make refresh request
>     return this.$auth
>       .request(endpoint, this.options.endpoints.refresh)
>       .then(response => {
>         // Update tokens
>         this.updateTokens(response, { isRefreshing: true })
>         return response
>       })
>       .catch(error => {
>         this.$auth.callOnError(error, { method: 'refreshToken' })
>         return Promise.reject(error)
>       })
>   }
> }
> ```

your setting ?
```
declare module '~auth/runtime' {
  // Here you declare what you're trying to import from `~auth/runtime`
  export { RefreshScheme, RefreshController } from '@nuxtjs/auth-next/dist'
}
``` thats true ?
