### ISSUE TITLE
Module not sending cookie in the fetchUser() request?

### ISSUE THREAD

**Issue by Giuliopime** [nuxt-community/auth-module#1259]
### Version
module: 5.13.6
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/api/configuration-mode):
 - [x] universal
 - [ ] spa

### Nuxt configuration
```
  axios: {},

  router: {
    middleware: ['auth']
  },

  auth: {
    strategies: {
      cookie: {
        scheme: '~/schemes/customScheme',
        cookie: {
          name: 'session_id',
        },
        token: {
          required: false,
          type: false
        },
        user: {
          property: false,
          autoFetch: true
        },
        endpoints: {
          login: {
            url: `${process.env.API_BASE_URL}/login`,
            method: 'post'
          },
          logout: {
            url: `${process.env.API_BASE_URL}/logout`,
            method: 'post'
          },
          user: {
            url: `${process.env.API_BASE_URL}/user`,
            method: 'get'
          }
        }
      },
    }
  }
```

### ~/schemes/customScheme.js
```
export default class CustomScheme extends LocalScheme {
  // Override `fetchUser` method of `local` scheme
  async fetchUser (endpoint) {
    // Try to fetch user and then set
    return this.$auth.requestWith(
      this.name,
      endpoint,
      this.options.endpoints.user
    ).then((response) => {
      this.$auth.setUser(response.data)

      return response
    }).catch((error) => {
      this.$auth.callOnError(error, { method: 'fetchUser' })
    })
  }
}
```

I use Ktor for my backend and when I login via the /login route I receive the following response so the cookie gets set correctly in the client browser.
![Screenshot 2021-08-12 at 17 55 39](https://user-images.githubusercontent.com/60524738/129228655-ec9f7e0b-b2da-4aac-a849-a74638e6edf1.png)  

The issue is that when I then try to fetch the user via the /user route the cookie doesn't get sent in the request and so I get a 401 back as the server doesn't get any session cookie so it threats me as unauthorized.   
![Screenshot 2021-08-12 at 18 03 06](https://user-images.githubusercontent.com/60524738/129229812-86017ac3-bb0a-448d-a0eb-b125fd2cbb29.png)

*Also I'm using the customScheme.js scheme because the normal fetchUser() method of the default local scheme just fails silently.*

## Questions
- **How can I send the cookie in the /user request?**
- **How can I fix the fact that fetchUser() just fails silently?**

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by Giuliopime** [comment]
For all those who have the same issue, just create a plugin for axios and put
```j
export default function ({ $axios }, inject) {
  $axios.defaults.withCredentials = true
}
```

This allows the cookie to be sent and it's missing in the auth module

**Comment by bmulholland** [comment]
Another workaround is to [set axios to use credentials in nuxt.config.js](https://github.com/nuxt-community/auth-module/issues/979#issuecomment-776218576):

```
axios: {
  credentials: true
}
```
