### ISSUE TITLE
Cannot logout with Okta because it needs the id_token

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [nuxt-community/auth-module#1272]
### Is your feature request related to a problem? Please describe.

I set up the oauth2 scheme to work with Okta. I need the access tokens for the Bearer authorization header. Yet, I need the id token to logout from the authorization server. The logout URI is `https://account.okta.com/oauth2/default/v1/logout?id_token_hint={{id_token_encoded}}`. Yet, this module only gets token (i.e., access_token) and refresh_token.

### Describe the solution you'd like to see

This module should be able to return the access, id and refresh tokens when using the token helpers.

### Describe alternatives you've considered

When I request the id_token response in the token settings, I cannot complete the login flow because I need the access_token.

**Comment by miguel-a-calles-mba** [comment]
Related PR: https://github.com/nuxt-community/auth-module/pull/868

**Comment by bmulholland** [comment]
#868 was merged, and I recently pushed https://github.com/nuxt-community/auth-module/commit/972fa1fcb00150d4b3ef4b0eb422aaf3b8a1b40a

Please let me know if this issue is still present after those changes
