### ISSUE TITLE
Redirection for authenticated users does not work in a static app

### ISSUE THREAD

**Issue by ivan-rivera** [nuxt-community/auth-module#1280]
### Version
module: 5.0.0-1616003482.75c20e6
nuxt: 2.15.3

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt configuration

You can find my config file with the entire repo [here](https://github.com/ivan-rivera/sleep_rescue_client/blob/master/nuxt.config.js#L109).
```
  auth: {
    localStorage: true,
    watchLoggedIn: true,
    redirect: {
      login: '/',
      logout: '/',
      home: '/dashboard',
    },
    strategies: {
      cookie: {
        cookie: {
          name: 'XSRF-TOKEN',
        },
        endpoints: {
          csrf: {
            url: '',
          },
        },
      },
      local: {
        scheme: 'refresh',
        token: {
          property: 'data.access_token',
          maxAge: 60 * 60 * 24 * 90,
          type: '',
        },
        user: {
          property: false,
        },
        refreshToken: {
          property: 'data.renewal_token',
          maxAge: 60 * 60 * 24 * 90,
          type: '',
        },
        endpoints: {
          login: { url: '/v1/session', method: 'post' },
          logout: { url: '/v1/session', method: 'delete' },
          refresh: { url: '/v1/session/renew', method: 'post' },
          user: { url: '/v1/user', method: 'get', propertyName: false },
        },
      },
    },
  },
```

## Reproduction

To reproduce this problem, please visit my website where the problem occurs: www.sleeprescue.org and log in with a test account, email: wegetav744@macauvpn.com, password: password123 then you should be redirected to the "/dashboard" route. If you manually edit the URL and remove the "/dashboard", you will be taken to the sign-up page again except you will not be able to log in (the button won't work), the only way to recover is to manually edit the URL to include the "/dashboard" route again. Note that this problem does not occur locally when I run `yarn dev` but it does occur when I run `nuxt generate` and then `nuxt start`. 

#### What is expected?

If I visit the index URL ("/") as a logged-in user, I should be redirected to the pre-defined page, but it is not happening.

#### What is actually happening?

If I visit the index URL ("/") as a logged-in user, I see the sign up page and I'm unable to log in or out until I manually navigate to "/dashboard" again (or another page for signed-in users).

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by devzom** [comment]
@ivan-rivera have You fixed it?

**Comment by ivan-rivera** [comment]
@devzom yes and I'm not sure if this problem was really caused by the auth module. I have a static app with an SPA fallback, here is the relevant config snippet:

```
export default {
   ...
  target: 'static',
  generate: {
    fallback: '404.html',
    exclude: [ // these pages are hidden behind the authentication wall anyway so they can't be indexed
      '/page1',
      '/page2',
      ...
    ],
  },
  ...
```

I added "/" to the exclusions and it seems to work now. I just suspected that this issue may have something to do with the SPA vs pre-rendered content switching and it looks like I wasn't wrong, but I still have no idea what's really going on here.

**Comment by devzom** [comment]
Okey, great that You've fixed it. But actually I'm thinking 💭 that You could use routeMiddleware to check $auth.state and allow to access /login page only for nonAuthenticated user, should work :)
 https://nuxtjs.org/docs/2.x/components-glossary/pages-middleware

**Comment by ivan-rivera** [comment]
@devzom yeah, but I thought that's what the `auth: {redirect: {...}}` configs together with `auth: true/false` flags are supposed to handle

**Comment by devzom** [comment]
@ivan-rivera redirect.endpoints works just on $auth logic when ex. User log in then it's redirected to /dashboard but I doesn't cover route guard for this specific /dashboard route
