### ISSUE TITLE
Discord oauth2 Missing "code_challenge"

### ISSUE THREAD

**Issue by kikawet** [nuxt-community/auth-module#1285]
### Version
module: 5.0.0-1624817847.21691f1
nuxt: ^2.15.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

## Reproduction
I'm using firefox just in case it matters
I created a codesandbox project
https://codesandbox.io/s/jolly-chebyshev-jdfur?file=/.env
1. add your cliendId and clientSecret from discord 
2. set your discord redirect to https://jdfur.sse.codesandbox.io/login

#### What is expected?
- this.$auth.loggedIn should set this.$auth.loggedIn to true
#### What is actually happening?
- Discord provider doesn't send the "code_challenge"
#### Steps to reproduce
1. create discord app using link - https://auth.nuxtjs.org/providers/discord
2. get to the oauth2 section
  2.1 set redirect to https://jdfur.sse.codesandbox.io/login
  
![imagen](https://user-images.githubusercontent.com/28111220/131700550-6e7afdc5-c26f-4960-9d9b-4639ed4a0ab4.png)

3. copy clientId and clientSecret into the sandbox project - https://codesandbox.io/s/jolly-chebyshev-jdfur?file=/.env
4. click "discord" it should trigger `this.$auth.loginWith('discord')` 
5. click allow in the discord page
6. you should be in a page with the following url `https://jdfur.sse.codesandbox.io/login?error=invalid_request&error_description=Missing "code_challenge"`

## Checklist
* [ ]  I have tested with the latest Nuxt version and the issue still occurs
* [ ]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### What is expected?
- this.$auth.loggedIn should set this.$auth.loggedIn to true

### What is actually happening?
the auth module doesn't send the "code_challenge"

**Comment by Stiiks** [comment]
I've got the same issue, that's why i create a pull request adding S256 as code challenge to default options in order to work. Meanwhile, you can add yourself the needed options in your nuxt.config.json. This is mine, as an example : 

```javascript
auth: {
    strategies: {
      discord: {
        clientId: process.env.CLIENT_ID,
        clientSecret: process.env.CLIENT_SECRET,
        scope: ['identity', 'guilds'],
        grantType: 'authorization_code',
        codeChallengeMethod: 'S256'
      }
    }
  }
```

**Comment by Intevel** [comment]
Hey @Stiiks can you reference your PR here?
