### ISSUE TITLE
Laravel Passport not being auto redirected to homepage

### ISSUE THREAD

**Issue by stephenjason89** [nuxt-community/auth-module#1295]
Does anyone encounter that everytime the browser is closed. if the user opens the browser and navigates to your site,  even if they have a valid token, they will be redirected to the login page and won't be redirected to the homepage.

I can clearly see an xhr call to my user endpoint which returns an authenticated user.

However, if you don't close the browser and just open a new tab, the user is directly redirected to homepage or any url that he is visiting. This is the correct behavior. It should be the same even if it is a newly opened browser.
       
       
       
       
        "@nuxtjs/auth-next": "^5.0.0-1621716493.b9b36c6",
        nuxt - universal

### Nuxt configuration

```
 auth: {
        plugins: [{ src: '~/plugins/axios', ssr: true }, '~/plugins/auth'],
        redirect: {
            login: '/login',
            logout: '/login',
            callback: '/callback',
            home: '/',
        },
        cookie: {
            secure: process.env.WS_HOSTNAME === 'foodat.ph',
        },
        localStorage: {
            prefix: 'auth.',
        },
        strategies: {
            laravelPassportPasswordGrant: {
                provider: 'laravel/passport',
                url: '/central',
                endpoints: {
                    user: {
                        url: '/api/user',
                    },
                },
                token: {
                    maxAge: 60 * 60 * 2,
                },
                refreshToken: {
                    maxAge: 60 * 60 * 24 * 30,
                },
                clientId: process.env.PASSPORT_CLIENT_ID,
                clientSecret: process.env.PASSPORT_CLIENT_SECRET,
                grantType: 'password',
            },
      },
  }
```

**Comment by bmulholland** [comment]
You didn't use the bug template so I don't have all the info I need. If you're using SSR, see https://github.com/nuxt-community/auth-module/issues/1197
