### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by epartipilo** [nuxt-community/auth-module#13]
Hi @pi0 

I have an hybrid site which uses a cookie and also a PHP session, the module do its job when working from Nuxt but some pages are still in PHP and the user can log out from them.

The thing is that when they log out from the PHP site the session and the cookie are destroyed but when I go back to the Nuxt site I can see that from the SSR it comes *loggedIn* false but client side renders *loggedIn* true so Vue throws this warning.

What could be a good approach? Using the **fetch** method?

Thanks

**Comment by epartipilo** [comment]
Ok I see know that the PHP site destroys PHP session and Cookie but not the LocalStorage

**Comment by pi0** [comment]
Hi @epartipilo. Sorry for late answering. For an exactly same reason, we can disable token store using `token.disabled = false` in 3.x versions. Does this works for you? if not we may add another option to just disable localStorage part ...

**Comment by epartipilo** [comment]
Thanks for the quick reply @pi0 

Seems that in my case I need to disable only the LocalStorage because the intention is to Log In and Log Out users either from the Nuxt site or the PHP site and both systems share the same Cookie name. 

So `token.disabled = false` does not set the cookie and the PHP site does not know the user is already logged.

Do you want me to make a PR of this or is a quick fix for you?

Thanks a lot!

**Comment by pi0** [comment]
@epartipilo Sure. PRs always welcome :)

**Comment by epartipilo** [comment]
Hi @pi0 

How can I contribute? I already has the fix working but pushing a new brach says I don't have the correct access rights

Thanks!

**Comment by pi0** [comment]
PR marged. Do you want to directly contribute to this repository?

**Comment by epartipilo** [comment]
@pi0 Well I did Fork the repo because I'm planning to integrate Google and Facebook login within this system, If it's interesting to you that's a yes.

Cheers!

**Comment by pi0** [comment]
Invitation [sent](https://github.com/nuxt-community/auth-module/invitations). This is awesome about your plan in Oauth integrations. Feel free making feature branches directly here :)

PS: Closing this issue as should be fixed now.
