### ISSUE TITLE
Cannot customize the Token name？

### ISSUE THREAD

**Issue by linda8167** [nuxt-community/auth-module#130]
### Version

[v4.1.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.1.0)

### Reproduction link

[https://nuxt-auth.herokuapp.com/](https://nuxt-auth.herokuapp.com/)

### Steps to reproduce

4.0.0. Rc3 upgraded to 4.1.0

### What is expected ?

auth._token=Bearer%20..................................

### What is actually happening?

auth.strategy=local; auth._token.local=Bearer%20..................................

### Additional comments?

How do I define the full name of a Cookie?

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c97">#c97</a>)</em></sub></div>

**Comment by benmccallum** [comment]
Have you used the configurable options?
* [token.name](https://auth.nuxtjs.org/options.html#token)
* [cookie.name](https://auth.nuxtjs.org/options.html#cookie)

**Comment by linda8167** [comment]
I used version 4.1.0, I didn't find in the defaults.js

**Comment by benmccallum** [comment]
No worries, with those options configured did it work for you? Feel free to close the issue if it did!

**Comment by Sheby** [comment]
That option is not use anymore, I looked it up in source code.
My related issue  #122

**Comment by PJLindsay** [comment]
You can read how to configure/customize here: https://auth.nuxtjs.org/getting-started/options#token

I think this issue can be closed?

**Comment by rafalolszewski94** [comment]
This seems to now work still in 2020. Experiencing this with latest version.
