### ISSUE TITLE
How to set Nuxt Auth without login

### ISSUE THREAD

**Issue by ikamez** [nuxt-community/auth-module#1300]
I have 2 website (A and B) that sync together.
In website A after login I had button to link with website B and  send token that I got from login to website B.

The question is How can I use this token without login again with website B ?

Thanks.

**Comment by devzom** [comment]
If You already are sending the auth token from success login into SiteB and it's valid token to access authentication on SiteB You should:
- have prepared endpoint on siteB, ex: siteB.com/auth/redirect?:token which handle token send as query parameter
- handle the token on server if use SSR so on created() or mounted() if client render and validate it, (if it's ex. JWT or not)
- use the retrieved token to call for userData endpoint ex.  api.siteB.com/me
- use the method to setUser data by  `this.$auth.setUserToken(token, refreshToken)` which will call the `/me` endpoint, get userData and set it to the $auth.store
https://auth.nuxtjs.org/api/auth#setusertokentoken-refreshtoken
