### ISSUE TITLE
How to use setUser? (Yeah, I have read the Docs, many times)

### ISSUE THREAD

**Issue by qifei** [nuxt-community/auth-module#1311]
Just start Nuxt project this month.

I want to save user data after login, I don't want use autoFetch, cause I need to do some calculation of the data.
so my config
```
user: {
	property: false,
	autoFetch: false,
},
endpoints: {
	login: { url: '/api/auth/login', method: 'post', propertyName: 'data.user' },
	user: false,
	logout: { url: '/api/auth/logout', method: 'post' },
}
```
but the $auth.user is empty, after I refresh the page.

Could you help me with this, thanks a lot.

**Comment by sMesle** [comment]
Hello, you need to use loginWith methods with your current strategy and the data you want to pass, then you can call your api endpoint to retrieve the user information, do calculation, and then set the user. Here is my code snippets for this, hope it helps :)

```js        
this.$auth
    .loginWith('local', {
      data: {
        username: this.username,
        password: this.password,
      },
    })
    .then(() => {
      this.$axios.get('PATH_TO_USER_INFORMATION').then((res) => {
        this.$auth.setUser(res.data);
      })
    })
```

**Comment by qifei** [comment]
@sMesle Thank you for your help

my LOGIN API will return the user info, so I don't need to get USER API right after the login process,
`
let res = await this.$auth.loginWith('local', { data: loginData })
if (res.status===0) {
let myData = {
id: res.user._id,
name: res.user._strName
}
this.$auth.setUser(myData)
}
`
just after the login, I can print out the this.$auth.user, but when I refresh the page, it will be an empty object {}

**Comment by nunos7** [comment]
The info is not persisted... you can create a index.js in store folder, with code below:
Read [this](https://auth.nuxtjs.org/api/storage) for store info in cookie before.
`export const actions = {
  async nuxtServerInit({
    commit
  }, {
    req
  }) {
    let auth = null
    if (req.headers.cookie) {
      // cookie found
      // console.log('cookie found...')
      try {
        // check data user login with cookie
        const data = this.$auth.$storage.getCookie('user', true);

        auth = data // set the data auth
      } catch (err) {
        // No valid cookie found
        // console.log('No valid cookie found')
        auth = null
      }
    }

    // set the user for AuthNuxt
    // Source: https://auth.nuxtjs.org/api/auth
    this.$auth.setUser(auth);
  },
}
`
