### ISSUE TITLE
openIDConnect scheme is missing (not resolved)

### ISSUE THREAD

**Issue by heinsenberg82** [nuxt-community/auth-module#1316]
### Version
module: 5.0.0-1624817847.21691f1
nuxt: 2.15.8

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [ X] spa

### Nuxt configuration
auth: {
    strategies: {
      oidc: {
        scheme: 'openIDConnect',
        clientId: 'web-client',
        endpoints: {
          configuration: 'https://##endpoint##/.well-known/openid-configuration',
        },
        redirectUri: "/signin-oidc",
        logoutRedirectUri: "/signout-callback-oidc",
        idToken: {
          property: 'id_token',
          maxAge: 60 * 60 * 24 * 30,
          prefix: '_id_token.',
          expirationPrefix: '_id_token_expiration.'
        },
        responseType: 'code',
        grantType: 'authorization_code',
        scope: ['openid', 'profile', 'offline_access'],
        codeChallengeMethod: 'S256',
      }
    }
  },

## Reproduction
When I try to build, it fails: "FATAL  Cannot resolve "openIDConnect" from "C:\code\nuxt-app\openIDConnect""

#### What is expected?
Successfull build.
#### What is actually happening?
Build fails.
#### Steps to reproduce
Build a nuxt app with the above configuration.
## Checklist
* [ x ]  I have tested with the latest Nuxt version and the issue still occurs
* [ x ]  I have tested with the latest module version and the issue still occurs
* [ x ]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by AllanOricil** [comment]
I had this today as well!

**Comment by AllanOricil** [comment]
![image](https://user-images.githubusercontent.com/55927613/135548829-d55dcfb3-ac5e-4069-829e-0bd8a16a2eba.png)

**Comment by assemmarwan** [comment]
I am facing the same issue. 

Seems like the version on npm is out of sync with the documentation, since OpenIDConnect was added 2 weeks ago while the version on npm is 3 months old. I'm gonna try to build it and reference it locally for now 😄

**Comment by AllanOricil** [comment]
> I am facing the same issue.
> 
> Seems like the version on npm is out of sync with the documentation, since OpenIDConnect was added 2 weeks ago while the version on npm is 3 months old. I'm gonna try to build it and reference it locally for now 😄

We're you able to build it? On windows 10 It did not work :/

**Comment by assemmarwan** [comment]
Finally got it to work. The documentation needs to be updated, I think.

According to the documentation this is the structure of the auth config in Nuxt-config:
```json
  // OpenID Auth
  auth: {
    strategies: {
      oidc: {   // <---------------
        scheme: "openIDConnect",
        clientId: process.env.OPENID_CLIENTID,
        endpoints: { configuration: process.env.OPENID_CONFIG_URL },
      },
    },
  },
```

But what worked with me is:
```json
  // OpenID Auth
  auth: {
    strategies: {
      openIDConnect: { // <----------------
        scheme: "openIDConnect",
        clientId: process.env.OPENID_CLIENTID,
        endpoints: { configuration: process.env.OPENID_CONFIG_URL },
      },
    },
  },
```

All I did is replace `oidc` with `openIDConnect`

**Comment by Anstroy** [comment]
@AllanOricil thanks for replying. Do you mean doing something like

`yarn add git:/github.com/nuxt-community/auth-module.git#next` ??

**Comment by AllanOricil** [comment]
@Anstroy no, you will have to checkout the branch, build it locally and then use npm or yarns to reference your build.

**Comment by Anstroy** [comment]
@AllanOricil 

1) I cloned the repo and then generated the 'dist' folder
2) then saved that folder within my project
3) added this line to my 'package.json`:
    ```
    "dependencies": {
       "@nuxt/auth-next": "./modules/auth-module/dist/",
       ...
    }
    ```
4) Modified my `nuxt.config.js` to:
    ```
    modules: [
      '@nuxtjs/axios',
      '@nuxt/my-auth'
    ],
   ```

But still doesnt work

**Comment by brccosta** [comment]
Dear @assemmarwan and all, I tried to build the dist and I did the same steps as suggested. However, I got the same error as @Anstroy . Would you guys know how can we use OpenID Connect with Nuxt?

**Comment by maximilianmikus** [comment]
I created a fork with prebuilt dist files committed: https://github.com/maximilianmikus/auth-module

you can try it out with `npm i maximilianmikus/auth-module#dev` (just import `auth` instead of `auth-next`)

**Comment by muhmuhhum** [comment]
any updates on this ?

**Comment by bmulholland** [comment]
The npm version is now up to date and should have the oidc schema included. Please try again with that.

**Comment by mtirzitis** [comment]
@bmulholland build now works!
But scope param append to default list instead of replacing it.

What I get is:
scope=openid profile offline_access openid profile email

from:
`scope: ['openid', 'profile', 'email'],`

**Comment by bmulholland** [comment]
Glad to hear the build works - I'll close out this specific issue.

I don't have bandwidth to work on the scope bug, but a PR (or at least a separate issue) would be most welcomed.

**Comment by kilakewe** [comment]
> @bmulholland build now works! But scope param append to default list instead of replacing it.
> 
> What I get is: scope=openid profile offline_access openid profile email
> 
> from: `scope: ['openid', 'profile', 'email'],`

I'm seeing this issue too. It breaks this scheme for me as "offline_access" is not a valid scope in my OIDC provider. I'm happy to make look at the code to propose changes, but does anyone know where this likely to be handled? I couldn't find it in the scheme so I'm assuming it must be somewhere else or in the core files.

**Comment by kilakewe** [comment]
> @bmulholland build now works! But scope param append to default list instead of replacing it.
> 
> What I get is: scope=openid profile offline_access openid profile email
> 
> from: `scope: ['openid', 'profile', 'email'],`

I'm seeing this issue too. It breaks this scheme for me as o

**Comment by bmulholland** [comment]
https://github.com/nuxt-community/auth-module/pull/868/files#diff-a3d7a042966af512cfada2e9fea2385c534a626a7d2df167cb95c116fc0a3480R49

**Comment by devmanzur** [comment]
> > @bmulholland build now works! But scope param append to default list instead of replacing it.
> > What I get is: scope=openid profile offline_access openid profile email
> > from: `scope: ['openid', 'profile', 'email'],`
> 
> I'm seeing this issue too. It breaks this scheme for me as "offline_access" is not a valid scope in my OIDC provider. I'm happy to make look at the code to propose changes, but does anyone know where this likely to be handled? I couldn't find it in the scheme so I'm assuming it must be somewhere else or in the core files.

Same issue
