### ISSUE TITLE
iOS + service worker + restarting chrome bug

### ISSUE THREAD

**Issue by zatorck** [nuxt-community/auth-module#1321]
### Version
module: 5.0.0-1613647907.37b1156
nuxt: ^2.14.12

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

```
  auth: {
    cookie: {
      options: {
        maxAge: 60 * 60 * 24 * 365 // secure: true
      }
    },
    strategies: {
      'laravelSanctum': {
        provider: 'laravel/sanctum',
        url: process.env.BACKEND_URL,
        maxAge: 86400,
        endpoints: {
          user: { url: '/api/user', method: 'get' }
        }
      },
    },
  },
```

## Reproduction
This issue only happens in iOS. I didn't managed to reproduce on Android / Web.

I have a project using laravel sanctum. You can visit it on https://jaty.pl

On login page I have `auth: 'guest',` option. I think this is because of bug, but  after showing me this page i can still see user in console `console.log(this.$auth.user)` so I think this is some problem with middleware?

#### Steps to reproduce

1. Create project with  service worker (workbox / or native doesn't matter) - simplest `sw.js` file necessary below.

```
self.addEventListener('fetch', function (event) {
    event.respondWith(fetch(event.request))
})
```

2.  My project uses `laravelSanctum` strategy 
3. Login on iOS device on Chrome
4. Go to secure area of your application 
5. Hard close browser or restart phone
6. Go back to browser 

#### What is expected?
See secure page again if token didn't expire

#### What is actually happening?
You are redirected to login page and in console you see error: 

```
hierarchyRequestError: the operation would yield an incorrect node tree
```

## Checklist
* [*]  I have tested with the latest Nuxt version and the issue still occurs
* [*]  I have tested with the latest module version and the issue still occurs
* [*]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by bmulholland** [comment]
I have no way to repro this myself, so you'll need to investigate it further on your own. If you figure out why it's happening, a PR would be welcomed. Closing this for now since it's not actionable for me.
