### ISSUE TITLE
Support sessionStorage in auth.Strategies options

### ISSUE THREAD

**Issue by mtskf** [nuxt-community/auth-module#1322]
### Is your feature request related to a problem? Please describe.
Local storage was never meant to be used as secure storage; the token data in the localStorage can be easily extracted even after closing the app and reused. Thus, sessionStorage is preferable.

### Describe the solution you'd like to see
It would be great if there's an "session" option in the auth.strategies options, which uses window.sessionStorage to store the JWT instead of window.localStorage.

Thanks so much for providing the awesome module, I really love it! 👍
I'd appreciate if you could support the feature! It would be really life saving. 😊

**Comment by Intevel** [comment]
Hey @mtskf, I added this in #1441
