### ISSUE TITLE
When I click on the cookie scheme link, I get Page Not Found.

### ISSUE THREAD

**Issue by muhammederdinc** [nuxt-community/auth-module#1325]
When I click on the cookie scheme link, I get Page Not Found.

https://github.com/nuxt-community/auth-module/blob/72052ef1a7c4156ba0ff6e7ee02f1e14fff97c3d/docs/content/en/schemes/local.md?plain=1#L12

**Comment by bmulholland** [comment]
Doc links work on the actual site, not in markdown: https://auth.nuxtjs.org/guide/scheme

**Comment by muhammederdinc** [comment]
![image](https://user-images.githubusercontent.com/33763365/150371703-63e0cf71-8431-4af2-8d92-6c0cf3f54ed9.png)
I got the error on the actual site. Now when I test again, sometimes I get an error, sometimes it works. I'm not sure if the problem could be with my device or browser.

**Comment by bmulholland** [comment]
Oh, in that case it's probably a known bug with the doc site: sometimes ending slashes are added, sometimes not, and that can break relative paths.

The nuxt team is working on better doc infrastructure that will fix this, and hopefully that's coming soon.
