### ISSUE TITLE
Documentation should be more clear about scope

### ISSUE THREAD

**Issue by fago** [nuxt-community/auth-module#1334]
### Version
nuxt-auth v4 and v5

#### What is expected?
When getting started, one needs to understand what nuxt-auth provides and what not. When getting started with our team, it was not clear to folks of what nuxt-auth is able to do exaclty in terms of session handling.

#### What is actually happening?
The introduction is quite short "Zero-boilerplate authentication support for Nuxt.js!" - but it's not clear what the capabilities in terms of session handling are.

### What is expected?
Provide a good introduction that clarifies the scope of available solutions.

After digging into more details this clarifies that it is expected to be solved by the backend:
https://auth.nuxtjs.org/schemes/local#fetch-user

**Comment by fago** [comment]
I've tried to come up with a docs improvement based on what we figured out meanwhile.

**Comment by fago** [comment]
Note: There are varies issues around sessions and adding support for it, so I think this is not so clear in general.

e.g. see #304 and #1322

**Comment by maximilianmikus** [comment]
:+1:
