### ISSUE TITLE
Make it possible to grab auth config from external resource

### ISSUE THREAD

**Issue by LeoQuote** [nuxt-community/auth-module#1341]
### Is your feature request related to a problem? Please describe.

In some circumstances, the auth config is configured in backend rather than nuxt.config.js. It would be good if there's an option to grab config fron backend api.
### Describe the solution you'd like to see

set a remote url in nuxt.config.js, once loaded, nuxt will try to request the remote url and load config , then we can use loginWith method to initilize login process .
### Describe alternatives you've considered

maybe a custom schema is also an alternative, I will try to add a custom config first.

**Comment by bmulholland** [comment]
This would be a huge feature and we don't have time to add or support it. You might be able to turn you nuxt config into an async function and write something that does it yourself, though.
