### ISSUE TITLE
It seems that this option(token: { global: false }) is not valid

### ISSUE THREAD

**Issue by DemoMacro** [nuxt-community/auth-module#1345]
### Question
When I set auth: {token: { global: false }} up, it still automatically includes the authentication token in all axios requests, which is causing problems with cors, may someone please help me?

### Version
module: 5.0.0-1624817847.21691f1
nuxt: 2.15.7

### Nuxt configuration
```js
  auth: {
    // Options
    token: {
      global: false,
    },
    strategies: {
      local: false,
      github: {
        ...
      },
    },
  },
```

**Comment by cchacholiades** [comment]
I am having this issue too on 5.0.0-1643103966.eefc505

**Comment by nevillenzf** [comment]
Still the same in 5.0.0-1595976864.509d9d6

**Comment by MOHAMMADHMEAD** [comment]
any update ??

**Comment by MOHAMMADHMEAD** [comment]
@DemoMacro  @cchacholiades  @nevillenzf  try to add token config inside strategies 

 strategies: {
      auth0: {
        token: {
          global: false
        },
.....
}

**Comment by enmust** [comment]
begs to question what else doesn't work as it's supposed to
