### ISSUE TITLE
error is-retry-allowed@2.2.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"

### ISSUE THREAD

**Issue by Bjunk** [nuxt-community/auth-module#1347]
### Version
module: 5.0.0-1637333559.35dbd53
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ X] universal
 - [ ] spa

## Reproduction
> :warning: without a minimal reproduction we won't be able to look into your issue

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by bmulholland** [comment]
Please fill in the rest of the template - this bug is not actionable without more information.

**Comment by bmulholland** [comment]
Closing as inactive
