### ISSUE TITLE
Sanctum Providers : does not persist CSRF Token through requests

### ISSUE THREAD

**Issue by vwasteels** [nuxt-community/auth-module#1355]
### Version
module: 5.0.0
nuxt: 2.15.8

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [x] spa

### Nuxt configuration

```
  axios: {
    proxy: true,
    credentials: true,
    debug: process.env.DEBUG,
  },

  // NOTE: proxy is used to prevent CORS issues during development
  proxy: {
    '/api': {
      target: process.env.API_DOMAIN,
      pathRewrite: { '^/api': '/' }
    }
  },

  auth: {
    strategies: {
      laravelSanctum: {
        provider: 'laravel/sanctum',
        url: '/api',
      }
    },
  },
```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

#### What is expected?

`POST` on `/login` should reach API corectly

#### What is actually happening?

It return a 419 with Exception : `CSRF token mismatch`.

#### Steps to reproduce

I followed this issue for more documentation : https://github.com/nuxt-community/auth-module/issues/1164#issuecomment-839199946

First call to `/csfr-cookie` woks well and returns 2 cookies on domain `.indivisible.test`
![Screenshot -  2021-12-07 à 15 53 03](https://user-images.githubusercontent.com/1151398/145053210-857d960e-93c1-4edb-be56-0b40ed90f30a.jpg)

2nd call to the login endpoint, tiggered this way : 
```js
    this.$auth.loginWith('laravelSanctum', {
        data: {
          email: 'someone@email.com',
          password: 'somepassword'
        }
      })
```
returns a 419 with Exception : `CSRF token mismatch`.
![Screenshot -  2021-12-07 à 15 53 28](https://user-images.githubusercontent.com/1151398/145053843-484e656a-4894-475e-8688-20d3506679ce.jpg)

with no Cookie present in the Resquest Headers, which seems normal since the previous  SET-COOKIE was calling a different domain than `localhost`, but then, how is it suppose to work ?

On the Laravel side : 
- `'supports_credentials' => true,` in `config/cors.php`
- `'stateful' => [ 
        '*'.env('SESSION_DOMAIN'), 
        'localhost:3000'
    ],` in `config/sanctum.php`

Thanks a lot for your help, I'm very stucked on this !!

**Comment by vwasteels** [comment]
any thought on this ? I am still stuck :(
Thank you anyway

**Comment by T-Zahil** [comment]
Any news ? :/

**Comment by vwasteels** [comment]
yes I made it work by adding a ngynx proxy to serve nuxt on the same top-level domain than the API

this reading helped me understanding :
https://dev.to/nicolus/laravel-sanctum-explained-spa-authentication-45g1

here is my ngynx config for this : 
```
server {
    server_name mynuxtsite.mytoploveldomain.com;
    listen 127.0.0.1:80;
    location / {
            proxy_pass      http://localhost:3000;
            proxy_set_header    Host             $host;
            proxy_set_header    X-Real-IP        $remote_addr;
            proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header    X-Client-Verify  SUCCESS;
            proxy_set_header    X-Client-DN      $ssl_client_s_dn;
            proxy_set_header    X-SSL-Subject    $ssl_client_s_dn;
            proxy_set_header    X-SSL-Issuer     $ssl_client_i_dn;
            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
            chunked_transfer_encoding on;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_redirect off;
            proxy_buffering off;
    }
}
```

**Comment by T-Zahil** [comment]
Thanks a lot @vwasteels !

**Comment by bmulholland** [comment]
Looks like this was resolved by fixing the laravel hosting setup, so closing it out.

**Comment by jerickcm** [comment]
Im facing the same issue in my local development can anyone help me with this
