### ISSUE TITLE
Is there a way to use logout as redirect?

### ISSUE THREAD

**Issue by ejpg** [nuxt-community/auth-module#1362]
Hi!

I have a webapp that half of the pages are made with symfony and we are putting some new pages in vue2.
The problem is that now to do logout we need to redirect to `/logout` that it goes to a page in symfony and does it, is NOT an endpoint.
Is there a way to do this with this module?

Thanks !!

**Comment by TimVanHerwijnen** [comment]
I think you can just redirect using a anchor or redirect in Nuxt.
After this you can call `$auth.reset()` this will clear the user. `$auth.reset()` is also called when using `$auth.logout()`.
Does your project use Nuxt? Since this is a Nuxt module.

**Comment by ejpg** [comment]
Yes it uses nuxt ! I solved it creating a custom scheme and replacing the logout function with the redirect
