### ISSUE TITLE
Using Azure B2C with Open ID Connect

### ISSUE THREAD

**Issue by tschni** [nuxt-community/auth-module#1364]
## Description

I saw that OpenIDConnect integration was released a short time ago. #868 (@vanhoofmaarten)
Since I am a big fan of OpenIDConnect, I wanted to use this for our login process with Azure B2C. Unfortunately, the whole thing is not working as I had hoped 😢.

--------

### Problem 1: Authorization endpoint is not called correctly with already existing query parameters

The structure of the Azure B2C URLs in the OpenID Configuration is as follows: `https://{tendant-name}.b2clogin.com/{tendant-name}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={policy_name}`.

As you can see, the query parameter `p` is already set at the end by default.

However, this is not taken into account when automatically generating the URL, a `?` is inserted for the query parameters instead of a `&`:

![image](https://user-images.githubusercontent.com/58136516/146564576-5e9c7785-8c2b-4628-b09f-d39a031aa6cb.png)

For further testing I changed the `?` manually in the address bar to `&`.

--------

### Problem 2: Scopes are not overwritten, only appended

In my config I only specified the scope `openid`: https://github.com/tschni/nuxt-auth-azureb2c-openid/blob/321ad424c4c7d7c2e4a64b5c6e53140fb489a0c9/nuxt.config.js#L55

I set it this because in the Azure B2C OpenID configuration `scopes_supported` has only `openid`:

![image](https://user-images.githubusercontent.com/58136516/146562816-6e040c24-c46b-4cd3-9f1b-cd1bab26b25e.png)

However, when I look at the called URL, the scope was not overwritten but just appended to the default setting:

![image](https://user-images.githubusercontent.com/58136516/146563633-89282843-5f6a-45e7-892e-a322a2e74f75.png)

This always causes a warning message in the console:

![image](https://user-images.githubusercontent.com/58136516/146563188-6d85a3ce-b317-4fc0-8d32-25278a2e9509.png)

--------

### Problem 3 (the hardest): Authorization Endpoint is called indefinitely (token is not recognized / stored?)

After manually modifying the upper issues in the address bar, I finally arrived at the normal login screen of Azure B2C.

There I was able to log in correctly and was then also redirected to the callback URL. However, the problem is that I was redirected from the callback URL (i.e. the login page) back to Azure where I can log in an infinite number of times without nuxt-auth noticing it correctly:

![image](https://user-images.githubusercontent.com/58136516/146566438-b33ccfcb-6486-4a30-b365-12a8a4313034.png)

--------

Has anyone ever connected Azure B2C and can tell me how? Thanks.

## Version
module: `5.0.0-1637745161.ea53f98`
nuxt: `2.15.8`

## Nuxt configuration

Full config file: https://github.com/tschni/nuxt-auth-azureb2c-openid/blob/master/nuxt.config.js

#### [mode](https://nuxtjs.org/api/configuration-mode):
 - [x] universal

#### [auth](https://auth.nuxtjs.org/schemes/openIDConnect):
```js
auth: {
  strategies: {
    azure_b2c: {
      scheme: 'openIDConnect',
      clientId: process.env.AZURE_CLIENT_ID,
      endpoints: {
        configuration: process.env.AZURE_CONFIG_URL
      },
      scope: ['openid']
    }
  }
}
```

**example environment variables:**

- AZURE_CLIENT_ID: `6ae5d303-e61c-4701-a8a1-b88d8f33918a`
- AZURE_CONFIG_URL: `https://{tendant-name}.b2clogin.com/{tendant-name}.onmicrosoft.com/v2.0/.well-known/openid-configuration?p={policy_name}`

## Reproduction
https://github.com/tschni/nuxt-auth-azureb2c-openid

#### Steps to reproduce

1. Clone the [repo](https://github.com/tschni/nuxt-auth-azureb2c-openid)
2. Rename the `.env.example` file to `.env` and fill the environment variables
3. Install dependencies (`yarn install`)
4. Open the app (http://localhost:3000) and and log in within the Azure B2C policy

**Comment by tschni** [comment]
**After a weekend as well as dozens of attempts later, I was able to solve problem 1 and 3:**

-------------

#### Problem 1

In addition to the URL structure used above, Azure B2C also offers the alternative structure `https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<policy-name>/oauth2/v2.0/authorize`. There are no query parameters set for this one, which is why there are no problems 😍 

The appropriate OpenID documentation with this structure can be loaded via the following URL: `https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<policy-name>/v2.0/.well-known/openid-configuration`

-------------

#### Problem 3

In the code of nuxt-auth the further process is aborted if the token is not present in the response:
https://github.com/nuxt-community/auth-module/blob/ea53f987d340747e0adf78d250bdc7ab0f460456/src/schemes/openIDConnect.ts#L284-L286

In the documentation of the OpenIDConnect scheme you can read that the token is taken from the `access_token` field by default: https://auth.nuxtjs.org/schemes/openIDConnect#token

However, Azure B2C does not return an Access Token, only the ID & Refresh Token. Therefore I have added the following to the config:
```js
token: {
  property: 'id_token'
}
```

It is important to note that in Azure B2C AD the redirect URL is entered as "Single-page application" and not as "Web"!

-------------

**So only problem 2 remains, for this I'll look at the code again at the next opportunity and try to adjust the faulty part.**

**Comment by vanhoofmaarten** [comment]
Hi @tschni,

Lovely to see you've managed to solve the first and third issue.

For the second issue, I think we need to update the following part: https://github.com/nuxt-community/auth-module/blob/dev/src/inc/configuration-document.ts#L135-L140

Defu concats arrays by default. I think it would be sensible that in this case arrays should be overwritten. This is possible by updating the `Array Function Merger. See: https://www.npmjs.com/package/defu#user-content-array-function-merger

**Comment by tschni** [comment]
Hi @vanhoofmaarten,

I'll try to take a look at this over the weekend.

As mentioned above, I got the process to work using the "Authorization Code Flow with PKCE". But now I have the question how secure this process actually is...

The tokens, including the long-lived refresh token, are stored in a session cookie and cookies can be read during XSS attacks, which I of course try to exclude.

**Comment by tschni** [comment]
So far I haven't gotten to the pull request unfortunately, but I happened to find a workaround for the scopes in other issues.
In the config, I now specify them as a string, instead of an array, and thus no longer get an error message.

However, my question regarding the security aspect remains unanswered.
