### ISSUE TITLE
Hot to access $auth in composition api

### ISSUE THREAD

**Issue by denys119** [nuxt-community/auth-module#1367]
How can I get access to $auth in composition api since I cant use this.$auth in functions.
I am using nuxt ^2.13.3 with compositio api @nuxtjs/composition-api ^0.31.0

Instead of using: 
methods: {
    async logOut() {
      await this.$auth.logout()
    }
  }

I want to access $auth in a method from setup() like: 
setup () {
const logout = async () {
 await ......
}
return {logout}
}

**Comment by marek1990kaminski** [comment]
Try this
```
import {useStore} from '@nuxtjs/composition-api';

const {$axios, $auth} = useContext();

```

**Comment by nengine** [comment]
Not useStore, should be useContext

```
import {useContext} from '@nuxtjs/composition-api';

const {$axios, $auth} = useContext();
```

**Comment by marek1990kaminski** [comment]
> Not useStore, should be useContext
> 
> ```
> import {useContext} from '@nuxtjs/composition-api';
> 
> const {$axios, $auth} = useContext();
> ```

hey, you are right, I called right fun, but imported wrong one.
