### ISSUE TITLE
User data is not updated when the page is refreshed

### ISSUE THREAD

**Issue by the-prime-thanatos** [nuxt-community/auth-module#1399]
### Version
module: 5.0.0-1624817847.21691f1
nuxt: 2.15.7

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

## Reproduction
> :warning: without a minimal reproduction we won't be able to look into your issue

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
After authorization and refreshing the page on any of the screens, a request for obtaining user data goes away: 
![Снимок экрана 2021-12-28 172315](https://user-images.githubusercontent.com/16982771/147561719-3cf5821d-25a2-4867-a8db-aeb8e47f970e.png) 
But the data doesn't change:
![image](https://user-images.githubusercontent.com/16982771/147561795-8aadc2e4-bed0-4dad-a2fd-874d34477819.png)
and there are no data refresh events in vue-dev-tools - vuex: 
![image](https://user-images.githubusercontent.com/16982771/147561868-b378e391-dfd1-4458-856e-045db8f5515a.png)

**Comment by Tragio** [comment]
@TheRagnar show us your Nuxt configuration 🙂

**Comment by the-prime-thanatos** [comment]
> @TheRagnar show us your Nuxt configuration 🙂
```
export default {
  // Target: https://go.nuxtjs.dev/config-target
  target: 'static',

  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'smeta',
    htmlAttrs: {
      lang: 'ru'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '~/assets/scss/normalize.8.0.1.scss',
    '~/assets/scss/global.scss'
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    '~/plugins/vue-window-size',
    '~/plugins/vuex-persist',
    '~/plugins/vClickOutside',
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    // '@nuxtjs/eslint-module',
    '@nuxtjs/composition-api/module',
    '@nuxtjs/svg',
    '@nuxtjs/vuetify'
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    '@nuxtjs/axios',
    '@nuxtjs/auth-next'
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    baseURL: 'http://test.cmeta.kz/',
    debug: true,
    proxyHeaders: false,
    credentials: false
  },
  router: {
    middleware: ['auth']
  },
  auth: {
    redirect: {
      login: '/',
      home: '/estimates',
      logout: '/',
    },
    strategies: {
      local: {
        token: {
          property: 'access',
          global: true
        },
        user: {
          property: false,
        },
        endpoints: {
          login: { url: '/api/auth/jwt/create', method: 'post' },
          refresh: { url: '/api/auth/jwt/refresh', method: 'post' },
          logout: { url: '/api/auth/logout', method: 'post' },
          user: { url: '/api/auth/users/me/', method: 'get', propertyName: false,}
        },
      }
    }
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},
  generate: {
    // choose to suit your project
    interval: 2000
  },
  svg: {
    vueSvgLoader: {
      // vue-svg-loader options
    },
    svgSpriteLoader: {
      // svg-sprite-loader options
    }
  },
  loading: {
    continuous: true,
    color: '#2F80ED'
  }
}

```

**Comment by Tragio** [comment]
@TheRagnar make sure all endpoints are working properly.

```
user: { url: '/api/auth/users/me/', method: 'get', propertyName: false,}
```
You can remove `propertyName: false,` since that it's from the old version.

Also, check if the Type is really Bearer and the other default values are correct according to https://auth.nuxtjs.org/schemes/local#token

I also noticed that in the User endpoint you have an extra slash. `/api/auth/users/me/`<- most probably it shouldn't be there, so change it to `/api/auth/users/me` . If Auth can't fetch the user it will not save the state.

**Comment by TheRagnar** [comment]
None of the above helps. Here is a video with a demonstration of the problem. P.S. I can not upload a demo to the sandbox due to the fact that the server is running on http, and the sandbox does not send requests
https://video.drift.com/v/abMsgX2Tjx8/

**Comment by TheRagnar** [comment]
> @TheRagnar make sure all endpoints are working properly.
> 
> ```
> user: { url: '/api/auth/users/me/', method: 'get', propertyName: false,}
> ```
> 
> You can remove `propertyName: false,` since that it's from the old version.
> 
> Also, check if the Type is really Bearer and the other default values are correct according to https://auth.nuxtjs.org/schemes/local#token
> 
> I also noticed that in the User endpoint you have an extra slash. `/api/auth/users/me/`<- most probably it shouldn't be there, so change it to `/api/auth/users/me` . If Auth can't fetch the user it will not save the state.

None of the above helps. Here is a video with a demonstration of the problem. P.S. I can not upload a demo to the sandbox due to the fact that the server is running on http, and the sandbox does not send requests
https://video.drift.com/v/abMsgX2Tjx8/

**Comment by the-prime-thanatos** [comment]
The problem turned out to be in VuexPersistence. It was forced after receiving a request from the server - it replaced data with data from local storage

**Comment by steklopod** [comment]
Ренджер - ты что-то не то делаешь. Все норм рефрешиться. Может я не до конца понял в чем твоя проблема правда. Может попробуй удали
```js
user: {
          property: false,
        }
```

**Comment by Intevel** [comment]
Maybe it helps to activate autofetch

**Comment by bmulholland** [comment]
Resolved per https://github.com/nuxt-community/auth-module/issues/1399#issuecomment-1005270035
