### ISSUE TITLE
Nuxt Auth Discord not matching the Discord API 

### ISSUE THREAD

**Issue by emyfops** [nuxt-community/auth-module#1403]
### Version
Any versions

### Nuxt configuration

    strategies: {
      discord: {
        clientId: '916493936971907084',
        clientSecret: 'censored'
      },
    },
    redirect: {
      login: '/',
      callback: '/token',
      home: '/',
      logout: '/'
    },
  

////////////////////////////////////////////////////////////////////////////////////////////////
WEBPAGE CODE : https://pastebin.com/5ERUnant

#### What is expected?

It should send a request with: client_id, redirect_uri, response_type and scope

#### What is actually happening?

It's sending a request with: client_id, redirect_uri, response_type and scope, state, ***code_challenge_method and code_challenge***

code_challenge_method and code_challenge are not in the API doc, causes it to fail the auth and getting: 
`error_description: 'Missing "code_verifier"'`
Discord API doesn't accept any of those (code_challenge_method and code_challenge)

#### Steps to reproduce
Click on the text (Code provided)

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

Remove the code_challenge_method and code_challenge query, and it works perfectly

**Comment by Intevel** [comment]
Hello, you forgot the `responseType` property in the `configuration`. You have to set the `responseType` to token to get a token. The way you want to do it, according to the **Discord Authorization Flow**, you would get a code to request a token.
**That's no bug, close this issue if you have no other questions**

https://discord.com/developers/docs/topics/oauth2#implicit-grant

**Comment by emyfops** [comment]
Indeed you were right

> Hello, you forgot the `responseType` property in the `configuration`. You have to set the `responseType` to token to get a token. The way you want to do it, according to the **Discord Authorization Flow**, you would get a code to request a token. **That's no bug, close this issue if you have no other questions**
> 
> https://discord.com/developers/docs/topics/oauth2#implicit-grant
