### ISSUE TITLE
bug with sanctum user endpoints

### ISSUE THREAD

**Issue by vwasteels** [nuxt-community/auth-module#1414]
doing it quick with a screenshot , user endpoint shoudl not start with /api :

in https://github.com/nuxt-community/auth-module/blob/dev/src/providers/laravel-sanctum.ts 

![Screenshot -  2022-01-06 à 16 57 23](https://user-images.githubusercontent.com/1151398/148411570-1d78c929-9c8e-46e2-b5b7-1bf4b7974bdb.jpg)

**Comment by bmulholland** [comment]
> user endpoint shoudl not start with /api

Can you please back up that claim?

**Comment by vwasteels** [comment]
yes sure,

if you leave it that way, it will call :
`api.domain.com/login` for login
`api.domain.com/api/user` for user instead of `api.domain.com/user`

in order to make it work you can :
1. change your URL endpoint to `/api/user` in your laravel api routes
2. OR : specify the right endpoint in nuxt/auth config

------

Specific to my case : I use a proxy on axios to redirect `localhost:3000/api/*` to `api.domain.com/*`
This is my config (I chosed option 2 from above):

```js
  axios: {
    proxy: true,
    credentials: true,
  },
  proxy: {
    "/api": {
      target: process.env.API_DOMAIN,
      pathRewrite: { "^/api/": "" }
    }
  },
  auth: {
    localStorage: false,
    strategies: {
      laravelSanctum: {
        provider: 'laravel/sanctum',
        url: '/api',
        endpoints: {
          user: {
            url: '/api/user'
          }
        }
      }
    }
  }
```

**Comment by bmulholland** [comment]
What is the source of truth for what the user endpoint should be? Is there laravel/sanctum documentation that says the `/api/user` default is incorrect?

**Comment by vwasteels** [comment]
sanctum does not provide those URLs, you have to define them your self like so : 

```php
Route::post('/login', [ApiAuthController::class, 'login']);
Route::post('/logout', [ApiAuthController::class, 'logout']);

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user', function (Request $request) {
        return $request->user();
    });
});
```

You are right, this is not incorrect , its just not logic to prefix only one route in the API endpoints , its not consistent

**Comment by vwasteels** [comment]
Note : after struggling a few days, I highly recommend reading this article to understand what sanctum does before starting to implement it :
https://dev.to/nicolus/laravel-sanctum-explained-spa-authentication-45g1

**Comment by bmulholland** [comment]
The defaults could perhaps be better here, but you should be able to easily overwrite them, if you wish. And others are already using the defaults, so a small breaking change like this isn't worth the small benefit.
