### ISSUE TITLE
Page access control

### ISSUE THREAD

**Issue by sky-code** [nuxt-community/auth-module#143]
How to give access to a page for authenticated users and for not authenticated at the same time?
I set
`
router: {
        middleware: ['auth']
    }
` auth for all routes, but for some page I set `auth: false` which disable auth, when user go to this page, auth module don't load user and page looks like you are not authenticated.
auth module can be enabled and restrict access, or fully disabled, but for many cases we need third  option, enable auth module, but not restrict access, it is possible to receive such behavior with auth-module `4.1.0` ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c107">#c107</a>)</em></sub></div>

**Comment by toadkicker** [comment]
It sounds like a mixing of concerns to me. I'm approaching it with a very strong divide of auth/noauth and it keeps things easy to understand. I suppose you could use something like `v-if="$store.state.auth.loggedIn"` to switch views based on that, but I often find myself creating a new component when I need to do that.

**Comment by JoaoPedroAS51** [comment]
Closing here, as this is an old issue and has been inactive.
