### ISSUE TITLE
Sending logout request with payload

### ISSUE THREAD

**Issue by kadlinobit** [nuxt-community/auth-module#1434]
Hi, 
I need to send refresh token in logout request to successfully logout. Is it possible to add a request body to $auth.logout() POST request? 

The body should be: 
```js
{
	"refresh_token": "gmPd...8wuB"
}
```

**Comment by dyehuty** [comment]
Hi, I used this for that purpose:

```
this.$auth.logout({
  data:{ 
    refresh_token: "gmPd...8wuB"
  }
})
```

**Comment by kadlinobit** [comment]
> Hi, I used this for that purpose:
> 
> ```
> this.$auth.logout({
>   data:{ 
>     refresh_token: "gmPd...8wuB"
>   }
> })
> ```

Hi @dyehuty ,
I swear I have tried the same thing before and $auth module was sending empty payload. **But now it works** - I must have had old code cached in the browser or something like that. 

Anyway thanks a lot!
