### ISSUE TITLE
[Docu] $storage lead to nowhere

### ISSUE THREAD

**Issue by rowild** [nuxt-community/auth-module#1443]
This is related to Nuxt DOCUMENTATION, not code!

### Version
module: 
nuxt: 

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [x] spa

## Reproduction
https://auth.nuxtjs.org/api/auth/#loggedin

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
https://auth.nuxtjs.org/api/auth/#loggedin

The documentation links $storage to a page that does not exist.

PS: Would it be possible to provide a documentation-related github section here? There is bugs, feature request etc; documentation as a separate option would be helpful for all, I assume?

**Comment by Intevel** [comment]
Fixed in #1444

**Comment by rowild** [comment]
Thank you, @Intevel !
