### ISSUE TITLE
Built-in auto token refresh

### ISSUE THREAD

**Issue by robsontenorio** [nuxt-community/auth-module#148]
### What problem does this feature solve?

Automatically refresh the "token" if it expires, because some Oauth providers has a short token TTL.

### What does the proposed changes look like?

Once https://github.com/nuxt-community/auth-module/pull/145 has been accepted, I will propose a PR to auto refresh the "token" if it has been expired. 

@pi0 @breakingrobot  where place it?  Maybe `lib/core/auth.js`? 

```js
mounted () {
    // handle token expiration        
    if (this.strategy.options.auto_refresh_token === true) {
      this.watchTokenExpiration()
    }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c109">#c109</a>)</em></sub></div>

**Comment by jonasgrosch** [comment]
@robsontenorio Really looking forward to this. Any idea when you'll have time for the PR?

**Comment by robsontenorio** [comment]
Just waiting another PR be merged.

**Comment by sobolevn** [comment]
@robsontenorio any progress on the issue? I am trying to solve the same problem.

**Comment by robsontenorio** [comment]
There was some tries in the past, but mantainers does not reviewed it. The code base from PRs is deprecated now.

**Comment by niklasravnsborg** [comment]
What is the current approach of most people to solve this? I also need this functionality.

**Comment by kvanska** [comment]
we're using this workaround for now. https://github.com/nuxt-community/auth-module/pull/208#issuecomment-408293603. 

would like to know if this project is moving forward anymore? there is some pull requests merged but for some reason there's no releases since a while.

**Comment by lokanathchandrareddy** [comment]
Any update on this this issue ?

**Comment by truesteps** [comment]
Any news?

**Comment by hugazo** [comment]
Nothing?

**Comment by geoffreylzf** [comment]
Any update for the refresh token support?

**Comment by GillesWHC** [comment]
Anything?

**Comment by JoaoPedroAS51** [comment]
Hey there! We are working on refresh support! For now you can use the new [branch (feat/refresh)](https://github.com/nuxt-community/auth-module/tree/feat/refresh)

Docs and more details can be found at #361

**Comment by pl-ekleft** [comment]
> Hey there! We are working on refresh support! For now you can use the new [branch (feat/refresh)](https://github.com/nuxt-community/auth-module/tree/feat/refresh)
> 
> Docs and more details can be found at #361

Is this functionality available in the master branch?

**Comment by bmulholland** [comment]
No, sorry, this is only available in the auth-next branch. If you need this feature, you should upgrade. See the [status page](https://auth.nuxtjs.org/status/) for more details. Closing this issue since it's available now :)
