### ISSUE TITLE
Test auth module with Nuxt 3

### ISSUE THREAD

**Issue by bmulholland** [nuxt-community/auth-module#1520]
make a new project with nuxt 3 and set up nuxt auth. https://v3.nuxtjs.org/

Then report back on if it works

**Comment by Intevel** [comment]
The Axios module is not yet compatible with Nuxt3, the first thing that happens when you start it is an axios error. They cant compiling it.

**Comment by bmulholland** [comment]
Thanks for looking into it!

**Comment by Lycoon** [comment]
Any update on it?

**Comment by Intevel** [comment]
No I don't think so, and as long as the Axios module is not compatible, the Auth module will not be compatible either.

**Comment by Denoder** [comment]
@Intevel  i put a pull request for the axios module for nuxt 3, so waiting for that.

**Comment by ironytr** [comment]
> @Intevel i put a pull request for the axios module for nuxt 3, so waiting for that.

Hello, is auth module working with ur pr? thank you for axios module yet auth module not working. Would you mind  put a temporarily jwt auth project with your nuxt-module while waiting this project to work  with nuxt3?  T_T

**Comment by Denoder** [comment]
> > @Intevel i put a pull request for the axios module for nuxt 3, so waiting for that.
> 
> Hello, is auth module working with ur pr? thank you for axios module yet auth module not working. Would you mind put a temporarily jwt auth project with your nuxt-module while waiting this project to work with nuxt3? T_T

Unfortunately the auth module does not work with the PR as there's changes needed to be made to the auth module itself. Axios works with the pr but would need to do extra work with the auth module.

**Comment by Intevel** [comment]
Yes of course. But still, the Axios module has to work before we can work on the Auth Module for Nuxt 3. I will take a look at your PR. @Teranode

**Comment by kazigk** [comment]
Axios module works for me with `{proxyHeaders: false}`. It's just a little buggy.

**Comment by Denoder** [comment]
@kazigk What seems to be the issues you are having?

**Comment by tad0xe** [comment]
currently have a nuxt-auth project which only works on my local machine, but when deployed on live server it doesn't work

**Comment by Denoder** [comment]
I made a module directory for nuxt-community plugins I utilize for nuxt 3. You can use these until the current modules are updated: https://github.com/Teranode/nuxt-module-alternatives

**Comment by nyxb** [comment]
> I made a module directory for nuxt-community plugins I utilize for nuxt 3. You can use these until the current modules are

I am confused?!

nuxt-module-alternatives
Alternative modules to use while waiting for Nuxt 3 Compatibility

Current Modules

Nuxt Axios Module: [Nuxt Community Repository](https://github.com/nuxt-community/axios-module)
Nuxt Proxy Module: [Nuxt Community Repository](https://github.com/nuxt-community/proxy-module)
Nuxt Auth Module: [Nuxt Community Repository](https://github.com/nuxt-community/auth-module)
Nuxt Google Fonts Module: [Nuxt Community Repository](https://github.com/nuxt-community/google-fonts-module)
VueJS/Nuxt Pinia: [VueJS/Nuxt Pinia Repository](https://github.com/vuejs/pinia)
Nuxt Element Plus: ?
Nuxt Vuex: ?

The Nuxt Auth Module: [Nuxt Community Repository](https://github.com/nuxt-community/auth-module) links exactly to this repository, which does not work with Nuxt3

**Comment by Denoder** [comment]
@VidarDev 

the links are references to the repositories of the modules im currently modifying. The @nuxtjs folder contains the auth module, look at the readme.

**Comment by nyxb** [comment]
@Teranode  

nvm my bad >.< now i check it ^^ good job and thanks for that

**Comment by droplister** [comment]
Was trying to use auth module with a fresh Nuxt 3 install:

```
[vite] Internal server error: Failed to resolve import "./middleware" from ".nuxt\auth.js". Does the file exist?
Plugin: vite:import-analysis
```

Vite does not love this line:
https://github.com/nuxt-community/auth-module/blob/c9880dc28fa13ba036f078d37ff76e1267c65d21/templates/plugin.js#L1

**Comment by pa3datka** [comment]
nuxt 3 uses $fetch, why not make autn on fetch???

**Comment by marwenbk** [comment]
any update?

**Comment by bmulholland** [comment]
Nuxt 3 support is coming as part of a broader re-write, and you can track that status at https://v3.nuxtjs.org/community/roadmap/#-core-modules

**Comment by serialine** [comment]
not only nuxt3 but also nuxt bridge
nuxtjs/axios, nuxtjs/proxy, nuxtjs/auth dependencies

**Comment by OblivionSY** [comment]
Is there an estimated timeframe? It just says "planned". In the meantime, what is the suggestion to use either instead or as a workaround?

**Comment by Arturexe** [comment]
Is this it?

https://www.npmjs.com/package/@nuxtjs-alt/auth

**Comment by bmulholland** [comment]
Closing this issue, as the current module will not work with Nuxt 3. You can track the timeline for Nuxt 3 support at https://nuxt.com/docs/community/roadmap/#-core-modules. That's the latest information I have.

**Comment by KoenCa** [comment]
This also seems a good alternative for Nuxt 3: https://sidebase.io/nuxt-auth/getting-started . It is based on a popular auth library for Next.js.
