### ISSUE TITLE
No login redirect on refresh.

### ISSUE THREAD

**Issue by SnooHD** [nuxt-community/auth-module#155]
### What problem does this feature solve?

When a user logs in, the user is redirected to `home`.
When the page is refreshed, the user will be logged in again, and because of that, redirected to `home` again.
I think that this is bad UX.

### What does the proposed changes look like?

I want to disable redirect in case there was a `refresh`.
Maybe this can be enabled / disabled by adding an option to nuxt.config?
```
auth: {
   refreshRedirect: false
}
```

Changing this in the watchState of the `init` function in `/lib/core/auth.js` should work:
```
// Watch for loggedIn changes only in client side
if (process.browser) {
  this.$storage.watchState('loggedIn', loggedIn => {
    if (!routeOption(this.ctx.route, 'auth', false)) {
      //disable redirect after login on refresh / first load.
      if(!this.options.refreshRedirect){
        if(loggedIn && !this.ctx.from){
           return
        }
      }

      this.redirect(loggedIn ? 'home' : 'logout')
    }
  })
}
```

Not sure if this is the best way of implementing it, but it works for me.

*Edit:*
*Changed the implementation because my previous method didn't redirect on first load even when NOT logged in.*

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c113">#c113</a>)</em></sub></div>

**Comment by SnooHD** [comment]
I added a pull requests, so this can be closed.

**Comment by toadkicker** [comment]
#158 was reverted, this should be reopened, or link to current issue
