### ISSUE TITLE
Middleware ignoring setting in nuxt.config.js

### ISSUE THREAD

**Issue by jamestowers** [nuxt-community/auth-module#16]
`auth.middleware.js` is not using the value supplied in `nuxt.config.js`: 

```
middleware.auth = function authMiddleware ({ store, redirect }) {
  // If user not logged in, redirect to /login
  if (!store.getters['auth/loggedIn']) {
    return redirect('/login')
  }
}
```

`/login` should be the value of `auth.redirect.notLoggedIn` fdromthe 

The same applies for the `no-auth` middleware

**Comment by jamestowers** [comment]
Sorry, ignore that, I was using an outdated version, this works fine with v3.0.1 👍

**Comment by pi0** [comment]
Hi. Happy hearing it was fixed and thanks for your issue reports.
