### ISSUE TITLE
Auth missing after refresh - Firebase

### ISSUE THREAD

**Issue by Robin-kwan** [nuxt-community/auth-module#1672]
My nuxt app couldn't find auth when I manually refresh the page after login or on protected routes and it redirects me back to login page. However, the cookies are still there, and checking in created it also found the cookies.
This issue doesn't happen in localhost. Only happens when I deployed it on Firebase. I will try to deploy somewhere else to find out if the issue still occurs.
Has anyone had this issue before?

Auth version 4.9.1
Nuxt - universal mode

**Comment by Intevel** [comment]
Currently I am not aware of such a problem, it would be nice if you could deploy it again somewhere else and test it. 💚

**Comment by Robin-kwan** [comment]
Haven't had a chance to deploy on Firebase again but since then I can kinda tell it was a deployment script.
