### ISSUE TITLE
Using Auth module in a nuxt-bridge app

### ISSUE THREAD

**Issue by Oldwo1f** [nuxt-community/auth-module#1681]
``Hello there.

I wonder if it is possible to use NuxtAuth module within a nuxt-bridge app (with composition-api and script setup).

If yes, Can someone explain me how can we access   ' $auth ' since we dont have access to ' this '

In this exemple, this is not defined
`let response = await this.$auth.loginWith('local', { data: datatogo })`

Best regards

**Comment by bmulholland** [comment]
https://github.com/nuxt-community/auth-module/issues/1519
