### ISSUE TITLE
After token expiration the authorization header on axios still presents

### ISSUE THREAD

**Issue by javialon26** [nuxt-community/auth-module#172]
### Version

[v4.3.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.3.0)

### Reproduction link

[https://github.com/nuxt-community/auth-module](https://github.com/nuxt-community/auth-module)

### Steps to reproduce

I use local strategy with a token. After the token expires if i reload the page, the user is logged out because i have resetOnError=True, but in all request made with axios the authorization header with the expired token is still present and all request return 401.

### What is expected ?

After token expiration the auth header in axios must be removed.

### What is actually happening?

The auth header is still present and all request fail.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c130">#c130</a>)</em></sub></div>

**Comment by robsontenorio** [comment]
I think it should be handled on LOCAL Scheme implementation. The LOCAL Scheme should implement a built-in refresh token policy. Of course, the backend should handle the "refresh token" policy.

For OAUTH2 Scheme a solution was proposed. Waiting approval.
https://github.com/nuxt-community/auth-module/pull/188

**Comment by metawise** [comment]
I wonder what happened to this issue?

**Comment by manniL** [comment]
@robsontenorio We did not forget any of you.

**Comment by pi0** [comment]
Fix released with [v4.9.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.9.0).
