### ISSUE TITLE
always redirect to logout option

### ISSUE THREAD

**Issue by javialon26** [nuxt-community/auth-module#173]
### Version

[v4.3.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.3.0)

### Reproduction link

[https://github.com/nuxt-community/auth-module](https://github.com/nuxt-community/auth-module)

### Steps to reproduce

the user is always redirected to logout option. The documentation says "if after logout current route is protected" but the user is always redirected to logout url.

### What is expected ?

Redirect user only if the current route is protected, not in all pages.

### What is actually happening?

The user is always redirected

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c131">#c131</a>)</em></sub></div>

**Comment by PCDotFan** [comment]
Same here 😓

**Comment by leonov-kirill** [comment]
+1

**Comment by daniplaninc** [comment]
+1

**Comment by muhammad-abubakkar** [comment]
Please fix this bug.
