### ISSUE TITLE
Why fetchUser is not working correctly

### ISSUE THREAD

**Issue by 93lucasp** [nuxt-community/auth-module#1755]
I run a PUT on the user, and after from the response I run `setUser()` 

it is updating my store(vuex) but when i refresh it fetch the old data. It works only if i logout and login again. This is the code, any help?

```
const user = (await this.$axios.put(/user, this.userScoped)).data;
await this.$auth.setUser(user);
```

**Comment by shiroze** [comment]
Can I know what is the solution here to setting user data ? @93lucasp
