### ISSUE TITLE
http://auth.nuxtjs.org/ is not working

### ISSUE THREAD

**Issue by jericopulvera** [nuxt-community/auth-module#177]
### Version

[v0.4.0](https://github.com/nuxt-community/auth-module/releases/tag/v0.4.0)

### Reproduction link

[http://auth.nuxtjs.org/](http://auth.nuxtjs.org/)

### Steps to reproduce

Visit http://auth.nuxtjs.org

### What is expected ?

Docs showing

### What is actually happening?

Docs not showing

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c135">#c135</a>)</em></sub></div>

**Comment by pasBone** [comment]
both http://auth.nuxtjs.org/  and  http://auth.nuxtjs.org can't visit.   The number of times you redirects you too much

**Comment by suryaadtmaja** [comment]
i can't access too, i ask vue official in twitter, got no reply yet.

**Comment by jericopulvera** [comment]
You can view the docs here at the mean time

https://github.com/nuxt-community/auth-module/tree/dev/docs
