### ISSUE TITLE
use token to login instead of username and password

### ISSUE THREAD

**Issue by duckimann** [nuxt-community/auth-module#1784]
I currently have this setup

```
export default {
  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // 'bootstrap-vue/nuxt',
    "@nuxtjs/i18n",
    "@nuxtjs/axios",
    "@nuxtjs/proxy",
    "@nuxtjs/auth-next",
  ],

  router: {
    middleware: ['auth']
  },

  auth: {
    strategies: {
      facebook: {
        clientId: '...',
        endpoints: {
          token: "/api/facebook/"
        }
      },
      google: {
        clientId: process.env.GOOGLE_AUTH_CLIENT_ID,
        codeChallengeMethod: "",
        responseType: 'code',
        endpoints: {
          token: '/api/google/',
          userInfo: '/api/user/'
        }
      },
    }
  },

  axios: {
    proxy: true,
  },
  proxy: {
    "/api/": {
      target: process.env.BASE_API_URL || 'http://localhost/',
      pathRewrite: { '^/api/': '/' },
    },
  },
}
```

and now i want to send the token from facebook/google to my backend, validate the token then returns my backend's token, and set it as primary. Basically like `local` strategy but use token from those 2 services instead of email/password combination.

How should i do it?

_Note: I've done with my backend, it does accept token from those 2 services._

**Comment by trandaison** [comment]
Setup a callback URL for your facebook app.
Facebook will redirect to your callback URL with a token, then make an api call with that token to your server with axios, after that use `setTokens`, `setUser`, `setStrategy` methods to login.

The library already supported this!

**Comment by duckimann** [comment]
I know that already. The thing i wanted is `i just need to put a url in then the lib handle the rest (fetch, set token, etc)`. But thanks.
