### ISSUE TITLE
Local Scheme What is the token return format?

### ISSUE THREAD

**Issue by bigzs** [nuxt-community/auth-module#179]
What format should the server return?

nuxt.config:
`axios: {
    baseURL:'http://127.0.0.1:8091/index.php/index'
  },

  auth: {
    strategies: {
      local: {
        endpoints: {
          login: { url: '/index/login', method: 'post', propertyName: 'token' },
          logout: { url: '/index/logout', method: 'post' },
          user: { url: '/index/user', method: 'get', propertyName: 'user' }
        },
        // tokenRequired: true,
        // tokenType: 'bearer',
      }
    }
  },`

php:
` public function login()
    {
	    header("Access-Control-Allow-Origin: *");
	    $temp['test'] = 11111;
        $token['token'] = $temp;
        return $token;
    }`

pesponse:{"token":{"test":11111}}

**Comment by jimpsson** [comment]
It all depends on your configuration, according to what you currently provided:
**POST /index/login**
```
{
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
}
```

**GET /index/user**
```
{
    user: {
        id: 1234,
        username: 'john_doe'
        ...props
     }
}
```
