### ISSUE TITLE
user data null when loggedIn getter is true

### ISSUE THREAD

**Issue by epartipilo** [nuxt-community/auth-module#19]
@pi0 
I have a header which shows user data when user is loggedIn but as the time the loggedIn value change and the component renders the user data is not already fetched so it gives and user undefined attribute so to show user data I have to check if user is defined or not.

As the user endpoint is required, what if the loggedIn is consider if token (in case of enabled) and user data are defined?

**Comment by pi0** [comment]
Hi. Seems a nice idea if we check both using && :)

**Comment by pi0** [comment]
I've made a quick commit. Does it looks good?

**Comment by pi0** [comment]
Shipped in 3.1.1
