### ISSUE TITLE
$auth.user.username is blank

### ISSUE THREAD

**Issue by Mr-Black-Dahlia** [nuxt-community/auth-module#194]
Anytime I call $auth.user.username it shows up blank.

my strategy:
```
local: {
      endpoints: {
        login: { url: '/auth/local', method: 'post', propertyName: 'jwt' },
        logout: null,
        register: { url: '/auth/local/register', method: 'post'},
        user: { url: '/user/me', method: 'get', propertyName: '_id', }
      }
```

--------------
my api return:

```
{
    "_id": "5b02e9839b32b5476c1edc54",
    "username": "test",
    "email": "test@test.com",
    "__v": 0,
    "role": {
        "_id": "5aff1a55216e7d293cdfe4a9",
        "name": "Authenticated",
        "description": "Default role given to authenticated user.",
        "type": "authenticated",
        "__v": 0
    },
    "id": "5b02e9839b32b5476c1edc54"
}
```

In the inspector I see this:
`auth:Object
loggedIn:true
strategy:"local"
user:"5b02e9839b32b5476c1edc54"`

But nothing else attached to the user. Can't figure it out and I've been staring at the docs/examples for 2 days now.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c144">#c144</a>)</em></sub></div>

**Comment by indiecore-fm** [comment]
If you use undefined or null as the property type for the user endpoint it works.

**Comment by mosinve** [comment]
All is working correclty
As said in docs: 
> propertyName
>propertyName can be used to specify which field of the response JSON to be used for value. It can be `undefined` to directly use API response or being more complicated like auth.user.

So in your case it's a `_id` field and so you have it value in `user` state. And then you change `propertyName` to `null|undefined|''` it takes whole api response data, so as said in docs. 

There's not an issue IMHO.

**Comment by CraftingGamerTom** [comment]
Can this be closed?
