### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jamestowers** [nuxt-community/auth-module#2]
Are there any usage instructions anywhere for this yet?

**Comment by pi0** [comment]
Hi @jamestowers & Thanks for your interest.I'm still working on this module to make all store actions customizable enough. Will add docs then soon. Meanwhile you can checkout `templates` directory to get idea how it works.

**Comment by pi0** [comment]
Hi @jamestowers & Thanks for your interest.I'm still working on this module to make all store actions customizable enough. Will add docs then soon. Meanwhile you can checkout `templates` directory to get an idea how it works.

**Comment by pi0** [comment]
Thanks to @herbertscruz  this issue cloud be closed now :)
