### ISSUE TITLE
User is not fetched on login, because user is not set?

### ISSUE THREAD

**Issue by totaltrash** [nuxt-community/auth-module#20]
Hi, I think 3.1.1 introduces a bug - after a successful login, the user is not fetched, because loggedIn returns false, because the user is null - bit of a catch 22, unless I'm missing something?

https://github.com/nuxt-community/auth-module/blob/e4bfd4e4ec825158f39fc0e09b8d1085f95bf169/lib/templates/auth.store.js#L121

**Comment by pi0** [comment]
Thanks for report. Should be fixed in 3.2.0 :)
