### ISSUE TITLE
Layout does not work in SPA mode

### ISSUE THREAD

**Issue by rktyt** [nuxt-community/auth-module#207]
### Version

[v4.5.1](https://github.com/auth-module/releases/tag/v4.5.1)

### Reproduction link

[https://example.com/none](https://example.com/none)

### Steps to reproduce

```
mode: 'spa',
router: {
    middleware: ['auth']
},
```

layouts/auth.vue
```
<template>
  <div>
    <header>Header</header>
    <main><nuxt/></main>
    <footer>Footer</footer>
  </div>
</template>
```

pages/login.vue
```
<template>
  <div>
    Login Form
  </div>
</template>
<script>
export default {
  layout: 'auth'
}
</script>
```

-------------

After generated, shown only "Login Form" when direct access to `/login/`.

### What is expected ?

Make the layout available.

### What is actually happening?

The layout can not be fully used in SPA mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c160">#c160</a>)</em></sub></div>

**Comment by Kntt** [comment]
i have the same problem.
if i set
```
options: {
  auth: xxx
}
```
the layout does not work

**Comment by manniL** [comment]
Please add a reproduction repository or a CodeSandbox. (https://template.nuxtjs.org/)
