### ISSUE TITLE
can't set custom function for user

### ISSUE THREAD

**Issue by rahul9874563210** [nuxt-community/auth-module#216]
Sorry if it is irrelevant .
I checked on docs there is no info about calling custom function for login and user setting . As you can check into nuxt.config.js file

```javascript
strategies: {
      local: {
        endpoints: {
          login: {url: '/WsUsers/login', method: 'post', propertyName: 'token.id', tokenName: 'authorization' },
          logout: false,
          user: {url: '/Workshops', method: 'get', propertyName: 'data'},
        },
        tokenRequired: true,
        tokenType: ''
      },
    },
```

here i want to call custom function which gets detail form server which i want an set it into auth.
Kinldy help.

**Comment by bart** [comment]
Is it possible to set a function here?
