### ISSUE TITLE
Authorization header is leaked by API calls made from anonymous subsequent client requests

### ISSUE THREAD

**Issue by farin** [nuxt-community/auth-module#231]
### Version

[v4.5.1](https://github.com/auth-module/releases/tag/v4.5.1)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

Let's have a route which provides data for both logged and not logged user where logged resource is enhanced with some additional private data.

Something like route `foo.vue`
```
async asyncData({ app }) {
   return await app.$axios.$get('/api/foo')
}
```  
Underling API server returns data based on logged/not logged user.

Now
- Run Nuxt server with server side rendering
- Open /foo in not logged browser - you get correctly public version of page
- Log in
- Open /foo again with logged user - you get correctly private version of page
- Open /foo in new independent not logged browser session (eg private mode / different browser)  - you get incorrectly private version of page

### What is expected ?

Anytime you request page as not logged then API call should not have set Authorization token

### What is actually happening?

Although state is properly hydrated as not logged without user, axios request made by server has Authorization header which contains token of previous user.

Token is leaked by global default of axios. This can be verified with
```
import axios from 'axios`
console.log(axios.defaults.headers)
```

app.$axios seems to be ok

### Additional comments?

Workaround for this issue, put middleware before auth which clear token on server side

```
middleware: ['token-security-fix', 'auth']
```

and then middleware
```
import axios from 'axios'

export default function ({ app }) {
  if (process.server) {
    delete axios.defaults.headers.common['Authorization']    
  }
}
```

Similar behavior probably happen also for configuration where redirect are enabled and some routes are marked public using by `auth: false`
Didn't tested it but i expect that header will be also preserved in axios defaults and any axios request from such routes can leak token of different users.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c189">#c189</a>)</em></sub></div>

**Comment by jimpsson** [comment]
I think that you should use the Nuxt $axios module exclusively for your own backend API or other sources that you fully can trust, simply because of separation concerns like you describe above.

If you use axios directly from the required npm module, then you get a different instance that you make requests from.

I made a simple test in my environment, nuxt app served on port 3000 and another express app on 3333. I looked at requests in my browser and it did not leak any authorization headers.
`axios('http://localhost:3333/test').then(console.log)`

Sorry if I have misunderstand you, just trying to give my thoughts.

**Comment by farin** [comment]
Ah mea cupla. 
Checked it precisely again and .... rather not telling details :-). Very lame, accidentally set default myself in some unexpceted placed.

Sorry for false report.
