### ISSUE TITLE
$auth not defined in plugin & resetOnError option is ignored...

### ISSUE THREAD

**Issue by ConsoleTVs** [nuxt-community/auth-module#245]
### Version

[v4.5.1](https://github.com/auth-module/releases/tag/v4.5.1)

### Reproduction link

[http://prntscr.com/kxf2s5](http://prntscr.com/kxf2s5)

### Steps to reproduce

Follow the steps in the small detailed guide...

### What is expected ?

- To have the $auth inside the plugin to use .onError
- To log out the user if the request fails (resetOnError is true)

### What is actually happening?

- $auth is undefined
- The user is not logged out, so I must find alternatives like using $auth in the plugin but I'm unable to...

Example failed request because bad token: http://prntscr.com/kxf48b
Result in the local storage: http://prntscr.com/kxf4i6

### Additional comments?

nuxt.config.js:

```
    auth: {
        // See https://auth.nuxtjs.org/getting-starterd/options
        redirect: {
            login: '/',
            logout: '/',
            user: '/dashboard'
        },
        strategies: {
            local: {
                endpoints: {
                    login: { url: '/login', method: 'post', propertyName: 'token' },
                    logout: { url: '/logout', method: 'post' },
                    user: { url: '/user', method: 'get', propertyName: 'user' }
                },
            }
        },
        resetOnError: true
    },
```

Also, just as a side note, the login redirect is not working either... Login works tho.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c203">#c203</a>)</em></sub></div>

**Comment by shawnlauzon** [comment]
I'm hitting the same problem: my token to the server is expired, and so I want to logout and force getting a new token. Unfortunately `resetOnError` is not resetting the token, and my plugin (which is defined in the `auth/plugins` property as defined [here](https://auth.nuxtjs.org/getting-started/options#plugins) rather than at the top level sees `this.$auth` is undefined.

**Comment by shawnlauzon** [comment]
> Also, just as a side note, the login redirect is not working either... Login works tho.

See #134 for a workaround.

**Comment by ConsoleTVs** [comment]
You want my advice? Get away from this library. Make your own with a few lines of code. This just sucks and nobody wants to correct it, neither will I.

**Comment by killlerr** [comment]
Any fixes?

**Comment by ConsoleTVs** [comment]
go to next.js. That's my fix.

**Comment by nicbavetta** [comment]
I am also running into this issue. Any update?

**Comment by themondays** [comment]
Move your plugs' declaration into `auth`, instead of 
```
module.exports = {
    plugins: [
        <some plugins without auth>
    ],
    ...
    auth: {
        redirect: {
        ...
        },
        strategies: {
        ...
        },
        ...
        plugins: [
             '~/plugins/your-plugin-with-auth.js'
        ]
    },

```

**Comment by nicbavetta** [comment]
@themondays  - Thank you. That does indeed work - missed this in the documentation.

**Comment by gkkirilov** [comment]
I think this can be closed as resolved @pi0

**Comment by simplenotezy** [comment]
Should definitely be more clear in the documentation

**Comment by simplenotezy** [comment]
The problem with this method is that inject does not work inside a auth-plugin; so you'll need to include your plugin both places.

**Comment by emielmolenaar** [comment]
@themondays Thanks! Been wasting a couple of hours on this one... :(

**Comment by amirakbulut** [comment]
> Move your plugs' declaration into `auth`
> 
> ```
> module.exports = {
>     plugins: [
>         <some plugins without auth>
>     ],
>     ...
>     auth: {
>         redirect: {
>         ...
>         },
>         strategies: {
>         ...
>         },
>         ...
>         plugins: [
>              '~/plugins/your-plugin-with-auth.js'
>         ]
>     },
> ```

How does this solve making `resetOnError: true` work?

**Comment by bmulholland** [comment]
Closing as stale for now. Please re-open a new issue if this is still present on nuxt-auth
