### ISSUE TITLE
facebook login demo not working

### ISSUE THREAD

**Issue by napestershine** [nuxt-community/auth-module#254]
### Version

[v4.5.1](https://github.com/auth-module/releases/tag/v4.5.1)

### Reproduction link

[https://nuxt-auth.herokuapp.com/](https://nuxt-auth.herokuapp.com/)

### Steps to reproduce

Visit URL https://nuxt-auth.herokuapp.com/
click on Login
click Login with Facebook
see the error `App not set up: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.`

### What is expected ?

it should get user log in and show user area

### What is actually happening?

It's throwing error page

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c213">#c213</a>)</em></sub></div>

**Comment by filipwronski** [comment]
It's not nuxt error. it's wrong facebook config.

STEP 1:

In Settings -> Basic -> Contact Email. (Give your/any email)

STEP 2: in 'App Review' Tab : change

Do you want to make this app and all its live features available to the general public? Yes

**Comment by napestershine** [comment]
I did both of the steps but still I am getting same error.

**Comment by jaasaria** [comment]
hi, how do you handle auth.login after the social media success response?

**Comment by napestershine** [comment]
I need to check in code
