### ISSUE TITLE
Passing $nuxt.$auth.$state.loggedIn = true to console bi-pass security

### ISSUE THREAD

**Issue by pavel-jurasek-hypofriend-de** [nuxt-community/auth-module#256]
### Version

[v4.5.1](https://github.com/auth-module/releases/tag/v4.5.1)

### Reproduction link

[https://github.com/nuxt-community/auth-module/tree/dev/examples](https://github.com/nuxt-community/auth-module/tree/dev/examples)

### Steps to reproduce

open any develper bar and type in console:  $nuxt.$auth.$state.loggedIn = true

### What is expected ?

This should not be possible.

### What is actually happening?

It should not be possible to bypass authentication.

### Additional comments?

No

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c214">#c214</a>)</em></sub></div>

**Comment by toadkicker** [comment]
FWIW I did get `Error: [vuex] Do not mutate vuex store state outside mutation handlers.`

**Comment by Vincebe** [comment]
![image](https://user-images.githubusercontent.com/4950885/49873739-e89ddf80-fe1c-11e8-8d63-9e8b855e1af1.png)

Confirmed. I get an error but the value stays true. Then i'm able to view a protected page by clicking a router button.

This is a major security breach.

"@nuxtjs/auth": "^4.5.3"
"nuxt": "^2.3.4"

**Comment by manniL** [comment]
Guys, everyone can "bypass" your authentication and see your secure pages. You have to validate the API calls of your server so they don't get the important information.

**Comment by Vincebe** [comment]
Of course api calls are validated against the token, but it shouldn't be that simple to bypass the middleware...

**Comment by manniL** [comment]
@Vincebe It doesn't matter if you do it that way or set breakpoints and change variables 🤷‍♂️ Maybe you need a minute more or so but will that change the outcome? (Of course not)
