### ISSUE TITLE
Waiting for user fetch?

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/auth-module#26]
Problem is following.
If u use this module with any route protection ( like a buildin middleware auth/no-auth) if you reload page on the protected page it will redirect you to the unprotected path because fetching user info not yet finished.
How to protect path so they work properly on reload, e.g. it should wait for auth-module to complete it fetch user request before deciding anything. But i dont see a way for this using auth-module. I dont even see a way to tell if fetching already failed and user not auth or its not yet finished fetching..
Am i missing something?

**Comment by pi0** [comment]
Hey @aldarund. If possible, please provide a basic reproduction code for your conditions and reopen this. I would be happy helping more :)

**Comment by aquarius-kreative** [comment]
Напиши мне, помогу чем смогу
