### ISSUE TITLE
Add configurable refresh token on local scheme

### ISSUE THREAD

**Issue by codetheorist** [nuxt-community/auth-module#261]
### What problem does this feature solve?

Allows the user to store a refresh token using local scheme, using a configurable key name that should be used.

### What does the proposed changes look like?

In lib/schemes/local, add the following default settings:

```javascript
const DEFAULTS = {
  tokenRequired: true,
  tokenType: 'Bearer',
  globalToken: true,
  refreshToken: false,
  refreshTokenKey: 'refresh_token',
  accessTokenKey: 'access_token',
  tokenName: 'Authorization'
}
```

Utilise the new settings in the login function, as follows:

```javascript
async login (endpoint) {
  if (!this.options.endpoints.login) {
    return
  }

  const accessTokenKey = this.options.accessTokenKey 
    ? this.options.accessTokenKey 
    : 'access_token'

  const refreshTokenKey = this.options.refreshTokenKey
    ? this.options.refreshTokenKey
    : 'refresh_token'

  // Ditch any leftover local tokens before attempting to log in
  await this._logoutLocally()

  const result = await this.$auth.request(
    endpoint,
    this.options.endpoints.login
  )

  if (this.options.tokenRequired) {
    const token = this.options.tokenType
      ? this.options.tokenType + ' ' + result[accessTokenKey]
      : result[accessTokenKey]

    this.$auth.setToken(this.name, token)
    this._setToken(token)

    if(this.options.refreshToken) {
      const refreshToken = this.options.tokenType
        ? this.options.tokenType + ' ' + result[refreshTokenKey]
        : result[refreshTokenKey]

      this.$auth.setRefreshToken(this.name, refreshToken)
    }
  }

  return this.fetchUser()
}
```

This would almost certainly be a breaking change, as it would require the response received to be a JSON object rather than a String.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c221">#c221</a>)</em></sub></div>

**Comment by yurriiy** [comment]
Is there any way to save refresh token into store? (local scheme)

**Comment by vyacheslav-startsev** [comment]
> Is there any way to save refresh token into store? (local scheme)

You can used custom strategy for it: https://stackoverflow.com/a/54731143/10965934

**Comment by geoffreylzf** [comment]
> > Is there any way to save refresh token into store? (local scheme)
> 
> You can use custom strategy for it: https://stackoverflow.com/a/54731143/10965934

Can you some any example?

**Comment by scoutrul** [comment]
Hello? I need this feature!
