### ISSUE TITLE
No redirect to /secure after login

### ISSUE THREAD

**Issue by xMikasax** [nuxt-community/auth-module#272]
### Version

[v4.5.2](https://github.com/auth-module/releases/tag/v4.5.2)

### Reproduction link

[https://github.com/nuxt-community/auth-module/tree/dev/examples](https://github.com/nuxt-community/auth-module/tree/dev/examples)

### Steps to reproduce

1) Open login page
2) Try to open secure page
3) Login
![Снимок экрана 2018-11-26 в 22.25.03.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/ca3a8ba0-f1b1-11e8-b304-ad599efdefc2.png)

### What is expected ?

Redirect to secure

### What is actually happening?

Stay on login page 
![Снимок экрана 2018-11-26 в 22.25.07.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/d1281310-f1b1-11e8-b304-ad599efdefc2.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c239">#c239</a>)</em></sub></div>

**Comment by pstephan1187** [comment]
I am also having this issue.

**Comment by protectedfor** [comment]
When this issue will be fixed? Or how can I make it work?

Thanks.

**Comment by garethredfern** [comment]
I am having the same issue.

**Comment by gianniskarmas** [comment]
All this strange behaviour comes from Browser->SSL Validation.
Have a look on my answer on [this](https://github.com/nuxt-community/auth-module/issues/258#issuecomment-436789381) issue:
