### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by NickBolles** [nuxt-community/auth-module#274]
### What problem does this feature solve?

Typescript types for $auth on the vue instance

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c219">#c219</a>)</em></sub></div>

**Comment by warheartvik** [comment]
I run into the same issue. For testing sake, I use some like this.

        //@ts-ignore
        if (this.$auth.loggedIn) {
            this.$router.push('/');
        }

but I don't recomend to use it all over the app, the code will look like crap.

**Comment by NickBolles** [comment]
WIP Types

```ts
/**
 * Augment the typings of Vue.js
 */

import Vue, { ComponentOptions } from "vue";
import { CookieAttributes } from "js-cookie";

// todo: context?
interface StorageCookieOptions extends CookieAttributes {
  cookie: {
    prefix: string;
    options?: StorageCookieOptions;
  };
}
interface Storage {
  setUniversal(key: string, value: any, isJson?: boolean): string;
  getUniversal(key: string, isJson?: boolean): any;
  syncUniversal(key: string, defaultValue: any, isJson?: boolean): any;
  // Local State
  setState(key: string, val: any): string;
  getState(key: string): string;
  watchState(key: string, handler: (newValue: any) => void);
  // Cookies
  setCookie(key: string, val: any, options?: StorageCookieOptions);
  getCookie(key: string, isJson?: boolean): any;
  // Local Storage
  setLocalStorage(key: string, val: any, isJson?: boolean);
  getLocalStorage(key: string, isJson?: boolean): any;
}

interface Auth {
  ctx: any;
  $state: any; // todo: type this
  $storage: Storage;
  user: any;
  loggedIn: boolean;
  loginWith(strategyName: string, ...args): Promise<never>;
  login(...args): Promise<never>;
  logout(): Promise<never>;
  fetchUser(): Promise<never>;
  fetchUserOnce(): Promise<never>;
  hasScope(scopeName: string): boolean;
  setToken(strategyName: string, token?: string): string;
  syncToken(strategyName: string): string;
  onError(handler: (error: Error, name: string, endpoint: any) => void);
  setUser(user?: any);
  reset(): Promise<never>;
  redirect(name: string);
}

declare module "vue/types/options" {
  interface ComponentOptions<V extends Vue> {
    auth?: boolean;
  }
}

declare module "vue/types/vue" {
  interface Vue {
    $auth: Auth;
  }
}

```

**Comment by NickBolles** [comment]
Please post suggestions for improvements if you have any, I'll put a PR together at some point, I think there are a few issues with these typings that need to be fixed before that though.

**Comment by SolarLiner** [comment]
Using `Promise<never>` implies that the Promise is never resolved. I think you wanted to write `Promise<void>`, which translates to a promises which resolves without a value.

**Comment by ryanwinchester** [comment]
@NickBolles I'm a typescript noob. Where do I put that code?

**Comment by danielroe** [comment]
@ryanwinchester Add it to a file called `index.d.ts` in your root directory.

Alternatively, you could also set up a types directory with a number of type declaration files, in which case I would add this content as another file in that directory, making sure it was listed in `tsconfig.json` under `compilerOptions.typeRoots`.

**Comment by clementmas** [comment]
What's the status on this?

Can it be supported by default?
Ideally we just have to add `@nuxtjs/auth` to the `types` array of `tsconfig.json` like most other modules.

**Comment by jonnyparris** [comment]
FYI - made a PR to definitely typed using @NickBolles's approach here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38132

**Comment by laflo** [comment]
> FYI - made a PR to definitely typed using @NickBolles's approach: [DefinitelyTyped/DefinitelyTyped#38132](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38132)

I think the Promises should be of type `Promise<void>` instead of type `Promise<never>` as mentioned above. Correct me if I'm wrong.

**Comment by NickBolles** [comment]
@jonnyparris Looks like that PR is merged now. Should we close this?

**Comment by jonnyparris** [comment]
@NickBolles sure
@laflo feel free to make a PR there too, sorry I missed it first time around

**Comment by steklopod** [comment]
Guys, please explain how to include this type.
Can we now  add `@nuxtjs/auth` to the types array of `tsconfig.json` like most other modules.?

**Comment by jonnyparris** [comment]
Almost; you need to add `@types/nuxtjs__auth` to the `tsconfig.json > compilerOptions > types` array.

Make sure you've also added `@types/nuxtjs__auth` as a devDependency in your project.

**Comment by NickBolles** [comment]
I submitted a PR to make this more automatic. See #486

**Comment by Greenfig** [comment]
To resolve `this.$auth` in vuex typescript modules, I had to add the following
> types/vue-shim.d.ts

```
import { Auth } from '@nuxtjs/auth'

declare module 'vuex/types/index' {
    interface Store<S> {
        $auth: Auth,
    }
}
```

**Comment by Micka33** [comment]
I still have this issue in my NuxtJS project...
```
 ERROR  ERROR in @/layouts/app.vue(109,12):
109:12 Property '$auth' does not exist on type 'CombinedVueInstance<Vue, AppData, {....}, {....}, Readonly<unknown>>'.
    107 |     },
    108 |     logout() {
  > 109 |       this.$auth.logout()
        |            ^
    110 |         .then(() => {
    111 |           let logoutUrl = new URL(`https://${this.$auth.strategies.auth0.options.domain}/v2/logout`);
    112 |           let { origin } = new URL(document.URL);

```

Not sure what to do to fix it...

**Comment by Greenfig** [comment]
@Micka33 did you add "@types/nuxtjs__auth" to your types array in the tsconfig.json?

**Comment by Micka33** [comment]
Just did it, and my editor displays the following:
<img width="455" alt="Screenshot 2020-07-06 at 11 57 41" src="https://user-images.githubusercontent.com/3918958/86581151-004d3380-bf80-11ea-8e7f-cfd967f0e65c.png">

Should install something more than `@nuxtjs/auth` ?

**Comment by udyux** [comment]
I'm running into an issue with the generic argument for the `Auth` type on components in our Nuxt app. We have this in our Vue augmentation:

```typescript
declare module 'vue/types/vue' {
  interface Vue {
    // ...
    $auth: Auth<SettingsDto>;
  }
}
```

In components however, typescript is picking up our augmentation as well as the types module augmentation which doesn't provide a generic type for `Auth` causing it to fallback to `any`. In VSCode I can see both being picked up but it seems to prioritize the module's definition. The result is the `$auth.user` property is always `Partial<any>`.

Any ideas on how I could fix this?
