### ISSUE TITLE
How to redirect to a custom router?

### ISSUE THREAD

**Issue by hojas** [nuxt-community/auth-module#277]
### What problem does this feature solve?

In nuxt.config.js I set this:

```
auth: {
    redirect: {
      login: '/login/',
      callback: '/login/',
      home: '/',
    },
}
```

Always redirect to home page after login, in some page that is not required auth. But in this case, I want to redirect to a custom page such as current page. And there is no login page in my app, only a login form in a modal. I am using bootstrap.

### What does the proposed changes look like?

Hope that I can redirect to a custom page not the auth module specified in nuxt.config.js. Or that will be great if I can set the redirect dynamic.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c246">#c246</a>)</em></sub></div>

**Comment by xtrasmal** [comment]
1. If you redirect to the same page where you came from, then you can do a check.
  example pseudo:    if user is logged in, then $router.push('where/ever')

2. You can create a page called: after-login.vue. This will be the page where you redirect to, always.

3. Store the current page or the redirect in the store. It does not matter where you are. After a successful login, you redirect to  $router.push(this.$store.state.lazybrain.storedRoute)) or whatever place you invented. 

And there probably are some more interesting approaches thinkable. Therefore..I think it is not needed to ask for a feature request.

**Comment by hojas** [comment]
@xtrasmal Thanks so much.
