### ISSUE TITLE
Social Strategy Callback on Static HTML 

### ISSUE THREAD

**Issue by pvenableh** [nuxt-community/auth-module#280]
I have Local, Google, and Facebook strategies setup correctly. They work as intended when running nuxt start, or nuxt dev. But, when I do a nuxt generate to produce a static site, only the local strategy works. The social strategies open the appropriate pages on Facebook and Google, but stall at the callback page and nothing is saved in local storage or in any cookie…loggedIn is still false.

I am using auth-module 4.5.2. Any idea as to why local is working and the social strategies wouldn't on static HTML pages?

**Comment by HughesWang** [comment]
Hi everyone, I got the same problem.

Is this question resolved ?

**Comment by pvenableh** [comment]
Hey Hughes.  I was able to resolve this by changing the mode in nuxt.config.js to SPA from UNIVERSAL.  Since, in this case, I was generating a static site, the SPA didn't adjust anything expect the social strategies in the Nuxt Auth module started working.

**Comment by HughesWang** [comment]
Thank you for your reply.

Now I set it to SPA, but it is not good for SEO.

So in the future, I still hope to be able to set it to universal.

I will continue to follow it, I hope the official can support as soon as possible.

**Comment by pvenableh** [comment]
If you are running 'npm run generate' it will all be static HTML and fine for SEO.
