### ISSUE TITLE
how can i get the Bearer token ?

### ISSUE THREAD

**Issue by levivi** [nuxt-community/auth-module#285]

**Comment by levivi** [comment]
this.$auth.getToken('local')

thanks

**Comment by saniales** [comment]
I add another contribute, you actually get the token by using the function @levivi used, but with the strategy name, not "local" only

example, if your strategy is "auth0" you have to use `this.$auth.getToken('auth0')`

**Comment by amirakbulut** [comment]
> I add another contribute, you actually get the token by using the function @levivi used, but with the strategy name, not "local" only
> 
> example, if your strategy is "auth0" you have to use
> 
> ```ts
> this.$auth.getToken('auth0');
> ```

When I run this, it returns something like `Bearer BlCnrFIUG3K4LNottrIkFftUoKbxIvZ-`, isn't a Bearer token meant to be much longer? I have no idea what to do with this token, can you enlighten me?

**Comment by saniales** [comment]
Just pass it in authorization header when you call your api
