### ISSUE TITLE
Problem with updateToken action

### ISSUE THREAD

**Issue by cesaramirez** [nuxt-community/auth-module#29]
When store tries to update the token this error appears
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/12446271/34440396-7dfde97c-ec7a-11e7-977b-e9df684ca4d7.png">

It started to happen after the last update.

**Comment by pi0** [comment]
Hi. This problem should be fixed now. Would you please test against auth@3.4.0 ?

**Comment by cesaramirez** [comment]
Update the package and another problem arose
<img width="1307" alt="screen shot 2017-12-29 at 10 18 26" src="https://user-images.githubusercontent.com/12446271/34441479-a3f0a988-ec81-11e7-8ad5-6ee02dfa3a74.png">

**Comment by cesaramirez** [comment]
Fixed with version 3.4.1, Thanks
