### ISSUE TITLE
Auth middleware not working the way it should

### ISSUE THREAD

**Issue by Awais-cb** [nuxt-community/auth-module#290]
Whenever i try to login this auth module won't redirect me to home `/`.However on logout it keeps redirects me to logout which is ok but when i refresh the home page it keeps allowing me to visit it even if i am not logged in which seems like a pretty serious bug.I am using auth middleware to protect it but still no luck! 
Here is my auth object
```
auth: {
    strategies: {
      local: {
        endpoints: {
          login: { url: 'users/signin', method: 'post', propertyName: 'user.token' },
          user: { url: 'users/me', method: 'get', propertyName: 'data' },
          logout: false
        }
      }
    },
    redirect: {
      // login: '/',
      logout: '/login',
      home: '/',
      callback: '/'
    },
    watchLoggedIn: true,
    rewriteRedirects: true
  }
```
Any help regarding this issue would be really appreciated

**Comment by russellsean** [comment]
Hey, don't know if you found a solution but you need to add the following to your nuxt.config.js file
```javascript
  router: {
    middleware: [
      'auth',
    ]
  },
```
