### ISSUE TITLE
Prevent redirect

### ISSUE THREAD

**Issue by DiegoGallegos4** [nuxt-community/auth-module#295]
I don't want to have the expected behavior which is redirecting after login, in my case Im using facebook. How can I make the process completely async?

**Comment by kaboume** [comment]
Hi,
in your nuxt.config.js add an option home to false 

auth: {
    redirect: {
      callback: "/callback",
      home: false 
    },

Bye

**Comment by tomkochi** [comment]
@kaboume
I tried this but no luck. Any idea?

auth: {
    strategies: {
      facebook: {
        client_id: 'CLIENT_ID',
        userinfo_endpoint: false,
        scope: ['public_profile', 'email'],
        redirect_uri:'https://my-domain.com/callbak'
      },
      google: {
        client_id: 'CLIENT_ID,
        user:false,
        redirect_uri:'https://my-domain.com/callbak'
      },
      redirect: {
        callback: "/callback",
        home: false
      },
    },
  },
