### ISSUE TITLE
Social Sign In using twitter and linkedin

### ISSUE THREAD

**Issue by amjadkhan896** [nuxt-community/auth-module#309]
Hi all,
I am using the auth module for social login. Is there any way to log in using Linkedin and Twitter. I searched a lot but could not find anything. I searched for the official docs also. Is there a way to log in using Twitter and LinkedIn.

Thanks a lot

**Comment by amjadkhan896** [comment]
anybody here

**Comment by joshtom** [comment]
Hello @amjadkhan896  Were you able to get a solution to this? If so, please share

**Comment by suleymangezsat** [comment]
Here is my solution for Twitter OAuth : https://codesandbox.io/s/eloquent-field-3ihhzh
Note: since requests to Twitter go through my backend, my backend has its own jwt mechanism (local scheme).
