### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by sebmor** [nuxt-community/auth-module#312]
I get an error with the latest @nuxt/auth, this error only happens in development, not in production.

The cookies module, which is a dependency of @nuxt/auth crashes for some reason. When I remove the nuxt/auth package, everything runs fine.

![screenshot 2019-03-07 at 15 55 41](https://user-images.githubusercontent.com/405407/53965466-96a1e880-40f1-11e9-8870-f90ed0e6f695.png)

**Comment by DevBrent** [comment]
There is a default "local" validation scheme that calls /api/auth/user on every request (even 404s) which if Nuxt's $axios config is not setup with a baseURL that is not on port 3000, you're going to end up calling the Nuxt server in an infinite loop and trying to validate etc.

**Comment by chris-aeviator** [comment]
Why has this issue been solved? Nuxt running out of memory here is the issue, not setting local auth scheme to fasle - nuxt fails miserably here and this should be addressed rather by burying and not documenting a workaround in an github issue
