### ISSUE TITLE
Body-parser deprecated

### ISSUE THREAD

**Issue by assoft** [nuxt-community/auth-module#313]
Why do I get this warning?

node: v11.11.0
---------------
package.json:
   ```
 "@nuxtjs/auth": "^4.5.3",
    "@nuxtjs/axios": "^5.3.6",
    "cross-env": "^5.2.0",
    "nuxt": "^2.4.0",
    "vuetify": "^1.5.0",
    "vuetify-loader": "^1.2.0"
```

![My Secreen](https://i.paste.pics/3cdfdbcf20f8997a989c701400082ce3.png)

**Comment by vhf** [comment]
@assoft You're not doing anything wrong, this issue was fixed here: https://github.com/nuxt-community/auth-module/pull/199 but it hasn't been release yet.
