### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot assign to read only property 'message' of object ''

### ISSUE THREAD

**Issue by kriss145** [nuxt-community/auth-module#317]
I'm building a project on Nuxt. I added Auth module and I have an error on the server.
After logged - user data and loggedIn - works, when I refresh a page I see this error and I dont' se user data etc.

> Uncaught (in promise) TypeError: Cannot assign to read only property 'message' of object ''

When I'm a dev server - all works, I got user data, token etc.

Thanks :)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c296">#c296</a>)</em></sub></div>

**Comment by bart** [comment]
I have the exact same error!

**Comment by bart** [comment]
I have the same error. Any idea what the reason is? It seems like it has to do with checking the store `$auth.loggedIn`

**Comment by bart** [comment]
All right, I figured it out. You must just delete local storage and cache data for your domain. It should work afterwards!

**Comment by kieranhall** [comment]
I also have this issue and have resolved with clearing my local storage and cookies.  However, this issue can return when deploying a new static build of my app.  Is there a recommended method for forcing the client to delete this data in such a scenario?

**Comment by bart** [comment]
I would say that's impossible to kind of force it. But what you can try is resetting it on a login page for example.

**Comment by bmulholland** [comment]
Closing out this issue as stale. If someone else encounters this problem, please post a new issue with more details on the error message and, ideally, repro steps.
