### ISSUE TITLE
Redirect not generated when protected page accessed directly

### ISSUE THREAD

**Issue by ColtonProvias** [nuxt-community/auth-module#332]
### Version

[v4.5.3](https://github.com/auth-module/releases/tag/v4.5.3)

### Reproduction link

[https://github.com/ColtonProvias/auth-issue](https://github.com/ColtonProvias/auth-issue)

### Steps to reproduce

1. Clone the linked repo locally.
2. Run `yarn install`
3. Run `yarn run dev`
4. Go to `http://localhost:3000` and try clicking both links on the front page.
5. Or try going to `http://localhost:3000/protected` directly.

### What is expected ?

Accessing `/protected` should automatically redirect to `/login`, and the page should say that you were redirected from `/protected`. This should work either directly or through both links.

### What is actually happening?

When accessing the page directly or via the non nuxt-link link, no redirect is provided to the login page. They should also generate the same result as accessing it via nuxt-link.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c312">#c312</a>)</em></sub></div>

**Comment by MathiasCiarlo** [comment]
Been having issues with this for so long, I just submitted a [pull request](#333) that fixes it! :)

**Comment by MathiasCiarlo** [comment]
This is a duplicate of #326

**Comment by pi0** [comment]
Should be fixed in [v4.6.0](https://github.com/nuxt-community/auth-module/releases/tag/v4.6.0).
