### ISSUE TITLE
Хрень

### ISSUE THREAD

**Issue by igorpopryadukhin** [nuxt-community/auth-module#344]
Потратил массу времени, оказалось пустышкой.

**Comment by brolnickij** [comment]
@igorpopryadukhin и чем же эта библиотека Вас не устроила? В ней есть все, что нужно. 
Прежде чем делать какие-либо выводы, разберитесь с документацией и описанием к этой библиотеке, так как она делает абсолютно все, что нужно для решения задач любого уровня.
Ваше заявление - непрофессионально.

**Comment by DmitriyColors** [comment]
> @igorpopryadukhin и чем же эта библиотека Вас не устроила? В ней есть все, что нужно.
> Прежде чем делать какие-либо выводы, разберитесь с документацией и описанием к этой библиотеке, так как она делает абсолютно все, что нужно для решения задач любого уровня.
> Ваше заявление - непрофессионально.

Добрый день! Вижу вы тоже русско язычный. 
Уже пару часов убил на чтение открытых вопросов и так не нашел ответа. 
Возможно вы имеет больше в работе с данной библиотекой, так что задам вопрос вам. 

Данный модуль/библиотека/компонент (в общем как хотите), по умолчанию выставляет в headers запроса, что-то типа "Content-Type": "****", "Authorization" : "***"., в связи с чем мне вечно возвращается 401 ошибка и сообщение на моем бэке "error: NotAuthenticated: No auth token". 
В общем пока не нашел ответа как отключить заголовок. Если поможете, заранее спасибо!
