### ISSUE TITLE
nuxt auth always redirecting to login 

### ISSUE THREAD

**Issue by nitinsinghnaruka** [nuxt-community/auth-module#347]
auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/login',
            method: 'post',
            propertyName: false
          },
          logout: {
            url: '/logout',
            method: 'post'
          },
          user: {
            url: '/user',
            method: 'get',
            propertyName: false
          }
        },
        // tokenRequired: true,
        // tokenType: 'Bearer', // Case sensitive when dealing with Laravel backend.
      }
    },
    redirect: {
      login: '/login',
      logout: '/',
      callback: '/login',
      home: '/dashboard'
    }
  },

  router: {
    middleware: ['auth']
  },

dashboard page
export default {
  name: 'dashboard',
  layout: 'dashboard',
}

**Comment by noelboss** [comment]
Same here…

**Comment by ewen-lbh** [comment]
yep same

**Comment by paulvonber** [comment]
Same

**Comment by blackfyre** [comment]
Same

**Comment by diguliu** [comment]
Same

**Comment by StefKors** [comment]
for me my template was this:
`<button @click="login()">Login with Google</button>`
adding `.prevent` solved it
`<button @click.prevent="login()">Login with Google</button>`

**Comment by EthrisDev** [comment]
For people using Laravel Passport and basic `/user` route in `api.php`, you need to specify propertyName in strategy like this, also remember to have correct route prefix.

```
strategies: {
      local: {
        endpoints: {
          login: {
            url: 'api/login',
            method: 'post',
            propertyName: 'access_token'
          },
          user: { url: 'api/user', method: 'get', propertyName: false } //here
        },
        tokenType: 'Bearer',
        tokenRequired: true
      }
    },
    redirect: {
      login: '/login',
      logout: '/login',
      home: '/dashboard',
      user: '/dashboard'
    }
```

**Comment by tsega** [comment]
I think my issue was related to not specifying all the properties of the `redirect` key.
