### ISSUE TITLE
v4.6.0 breaks the expires time given as number

### ISSUE THREAD

**Issue by enVolt** [nuxt-community/auth-module#364]
### Version

[v4.6.0](https://github.com/auth-module/releases/tag/v4.6.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

Provide expires time as number (in days) as documented here - https://auth.nuxtjs.org/api/options.html#cookie

### What is expected ?

Cookie should be set with expiry of current time + n number of days expiry

### What is actually happening?

Throwing error

### Additional comments?

Before v4.6.0 js-cookie library was being used to provide functions related to cookie, now `cookie` library is used, which doesn't support all the options.

To be precise, this is the culprit -
https://github.com/nuxt-community/auth-module/pull/360/files#r289317793

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c341">#c341</a>)</em></sub></div>

**Comment by enVolt** [comment]
cc - @mayankshaan

**Comment by enVolt** [comment]
cc @mayank-shaan

**Comment by pi0** [comment]
Fixed in 4.6.1:

https://github.com/nuxt-community/auth-module/releases/tag/v4.6.1
