### ISSUE TITLE
Invalid character in header content ["Set-Cookie"]

### ISSUE THREAD

**Issue by reivaxm** [nuxt-community/auth-module#368]
Hi team !
I thinks that the file have an issue (typo)
You call the function instead of the value returned

https://github.com/nuxt-community/auth-module/blob/4d3feff1cd859dd6894db0bd224ae0a98f3d4cc5/lib/core/storage.js#L230

**Comment by reivaxm** [comment]
juste replace serializeCookie by serializedCookie works for me

**Comment by pi0** [comment]
Ah sh 😯 Will fix in few minutes

**Comment by reivaxm** [comment]
No Problem, Cool Thanks a lot
