### ISSUE TITLE
Add Auth0 Tenant Configuration Documentation

### ISSUE THREAD

**Issue by crawfordleeds** [nuxt-community/auth-module#374]
### What problem does this feature solve?

The nuxt-auth demo Auth0 tenant seems to have some configuration modifications that requires a prompt each time a known user logs in. With the default configuration, a user will struggle to change accounts as after logging in there seems to be a silent login process where auth0 automatically redirects to the callback route rather than confirming the account for which the user wishes to log in with.

I've been really struggling to find a solution. I'd be more than happy to add this to the docs as a pull request, I was just hoping someone could help me understand what changes were made to the tenant.

### What does the proposed changes look like?

I'll make a PR documenting the config process of a new Auth0 tenant.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c349">#c349</a>)</em></sub></div>

**Comment by bcnzer** [comment]
@crawfordleeds Appears you and I were fighting with the same issue yesterday, with Auth0. 

Turns out the silent/automatic logging in is due to a setting called "Enable Seamless SSO". In old Auth0 tenants (i.e. from last year) that was optional. Now it's on by default. [More detail here](https://github.com/nuxt-community/auth-module/issues/375)

**Comment by crawfordleeds** [comment]
@bcnzer thanks so much for the feedback! It's wild that Auth0 seems to have removed the "enable seamless SSO" option without any documentation to that change - or at least I can't find any. I have a few thoughts that might be useful to the community. I'll follow up tomorrow on issue #375 for better context on the discussion. Thanks again!
