### ISSUE TITLE
onRedirect not triggering for oAuth login

### ISSUE THREAD

**Issue by pju-** [nuxt-community/auth-module#382]
### Version

[v4.7.0](https://github.com/auth-module/releases/tag/v4.7.0)

### Reproduction link

[htttps://unvail.able](htttps://unvail.able)

### Steps to reproduce

I need localized redirects on login, so I have the following config:

In nuxt.config
```
		redirect: {
			…
			home: '/login-landing'
		}, 
```

in a plugin:

```
app.$auth.onRedirect((to, from) => {
		if (to === '/login-landing') {
			// return localized path
		}

		return to;
	});
```

This works great for normal logins, but is not triggered for an oAuth-Login via google.

Sorry I can not provide an example repo, but this needs a Google-oAuth setup to try it out.

### What is expected ?

onRedirect should be triggered

### What is actually happening?

onRedirect is not triggered

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c358">#c358</a>)</em></sub></div>

**Comment by ljanecek** [comment]
Same problem here

**Comment by warlyware** [comment]
I can also confirm that this is an issue when using the Google provider.

**Comment by mrdj07** [comment]
When $auth triggers _handleCallback, it is triggered before the plugins defined in auth inside the nuxt.config are instanciated. 

Therefore, when the login callback redirect is triggered, there is nothing populated inside _redirectListeners.

**Comment by qwexvf** [comment]
any updates on this?....

**Comment by bmulholland** [comment]
We don't have bandwidth to support 4v and are focused on v5/auth-next. Please try that out and file a new issue if you have a problem with it.
