### ISSUE TITLE
Page Component with auth set to guest doesn't open.

### ISSUE THREAD

**Issue by nancoder** [nuxt-community/auth-module#383]
### Version

[v4.7.0](https://github.com/auth-module/releases/tag/v4.7.0)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-m1so6](https://codesandbox.io/s/codesandbox-nuxt-m1so6)

### Steps to reproduce

1. Install and add the Auth module
2. Set the router middleware to auth
3. In a page component, set the auth property to guest
4. Click on "auth:guest" link

### What is expected ?

To open the link if the user is not logged in and redirect to home if is logged in.

### What is actually happening?

The link doesn't open.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c360">#c360</a>)</em></sub></div>

**Comment by studnitz** [comment]
This should be fixed with [4.8.1](https://github.com/nuxt-community/auth-module/releases/tag/v4.8.1).
