### ISSUE TITLE
Google not working with oauth2 server side callback

### ISSUE THREAD

**Issue by Zsavajji** [nuxt-community/auth-module#393]
### Version

[v4.8.0](https://github.com/auth-module/releases/tag/v4.8.0)

### Reproduction link

[https://this-page-intentionally-left-blank.org/](https://this-page-intentionally-left-blank.org/)

### Steps to reproduce

Upgrade to 4.8.0, try to login with Google oauth2.
In the callback url fetch method you'll have no auth data.

### What is expected ?

To have the `access_token` available into `$auth.getToken('google')`

### What is actually happening?

It's undefined

### Additional comments?

What i can see, is that in the new server side callback url, the data gets extracted from the route without parsing the query:
`const parsedQuery = Object.assign({}, this.$auth.ctx.route.query, this.$auth.ctx.route.hash)`

This assignment returns an empty object in my case.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c363">#c363</a>)</em></sub></div>

**Comment by mmachatschek** [comment]
Hey @Zsavajji,

@pi0 
I ran into the same issue. You were on the right track. I opened a PR #394 which should fix the problem.

Cheers

**Comment by pi0** [comment]
Landed in [4.8.1](https://github.com/nuxt-community/auth-module/releases/tag/v4.8.1)
