### ISSUE TITLE
Implicit redirect_uri issue. Not inferred from redirects.callback as stated by documentation.

### ISSUE THREAD

**Issue by dappiu** [nuxt-community/auth-module#396]
### Version

[v4.8.1](https://github.com/auth-module/releases/tag/v4.8.1)

### Reproduction link

[https://auth.nuxtjs.org/schemes/oauth2.html#redirect-uri](https://auth.nuxtjs.org/schemes/oauth2.html#redirect-uri)

### Steps to reproduce

I upgraded to v4.8.1 from v4.7.0 and I could see the SSR support for OAuth based flow working straight away, using `nuxt dev`.
But, then, in production build I noticed something strange. 

Premise: I'm using a server-side based flow, so I have custom `access_token_endpoint` and `userinfo_endpoint`, the `response_type` is set to `'code'` and for Goole I also have `access_type` set to `'offline'`.
I used to leave `redirect_uri` unspecified as this got correctly inferred from version 4.7.0.

This is the relevant excerpt from the config:
```
auth: {
  cookie: { 
    secure: process.env.NODE_ENV === 'production'
  },
  redirect: {
    login: '/accedi',
    logout: '/',
    callback: '/login-callback',
    home: '/'
  },
  strategies: {
    local: { ... },
    facebook: {
      client_id: '<< REDACTED >>',
      response_type: 'code',
      authorization_endpoint: 'https://facebook.com/v3.2/dialog/oauth',
      access_token_endpoint: 'https://api.my-redacted-domain.tld/api/v1/auth/facebook',
      userinfo_endpoint: 'https://api.my-redacted-domain.tld/api/v1/users/me',
      refresh_token_key: false,
      scope: ['public_profile', 'email']
    },
    google: {
      client_id: '<< REDACTED >>',
      response_type: 'code',
      access_type: 'offline',
      authorization_endpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
      access_token_endpoint: 'https://api.my-redacted-domain.tld/api/v1/auth/google',
      userinfo_endpoint: 'https://api.my-redacted-domain.tld/api/v1/users/me',
      refresh_token_key: false,
      scope: ['openid', 'profile', 'email'],
    }
  }
}
```

In production build I noticed that my API for `access_token_endpoint` got called two times: a first time without the `redirect_uri=` query parameter, a second time with the `redirect_uri` specified (are there perhaps differences in how the `redirect_uri` is inferred from client side or server side?)

Setting an explicit `redirect_uri` in both strategies configurations helped in restoring the correct behaviour, and now the access_token_endpoint gets called only one time with `redirect_uri` correctly appended as before.

I think we have to fix documentation and examples for login and login callback pages, as the documentation for the `redirect_uri` makes you think that redirect.login and redirect.callback should be the same page, but then the linked example shows a configuration with a separate login and callback pages. The login page has a method `isCallback` that is not used anywhere and maybe was used before when the example had a single page for login and callback pages.

### What is expected ?

`redirect_uri` inferred from `redirects.callback`

### What is actually happening?

`redirect_uri` is not present on the URL query, at least for Facebook and Google OAuth flows with no explicit `redirect_uri` configured on 4.8.1. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c364">#c364</a>)</em></sub></div>

**Comment by bmulholland** [comment]
This is likely resolved in auth-next
