### ISSUE TITLE
the login page stuck on loading.

### ISSUE THREAD

**Issue by SniffAByte** [nuxt-community/auth-module#399]
Hello Guys! I hope you can help!
this is this first time for me to use this module and I got stuck. 
I installed it and axios through  
npm install @nuxtjs/auth @nuxtjs/axios --save
and inside nuxt.config.js once I add nuxtjs/auth to modules and save and go to login page it takes a long time to load and it doesn't load. i don't know where the problem is. i even tried to reinstall npm and all packages, reinstall all my project & I even used another linux dist and the problem still exists! 

how can I fix it!
this is my nuxt.config.js modules code:
```
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth'
  ],
```
I didn't add anything else! the project is new and I didn't do anything else! 
but when  i delete '@nuxtjs/auth' from modules it works fine.

**Comment by keyvans2** [comment]
I had this problem too. go to this path:

" nodemodules/@nuxtjs/axios/module "

you should delete " module " in " axios " folder and it works like a charm

**Comment by SniffAByte** [comment]
> I had this problem too. go to this path:
> 
> " nodemodules/@nuxtjs/axios/module "
> 
> you should delete " module " in " axios " folder and it works like a charm

I thought I shouldn't make any updates inside node_modules, should I?

**Comment by temofart** [comment]
@SniffAByte I got the same, did you find way to fix this ?

**Comment by felipe-muner** [comment]
I have the same issue...

How can we fix it?
