### ISSUE TITLE
Allow to set header types

### ISSUE THREAD

**Issue by SHxKM** [nuxt-community/auth-module#401]
### What problem does this feature solve?

This module seems to be in maintenance only mode but I'll try.

Upon a successful `loginWith`, `auth` wants to hit the `user` endpoint in order to obtain the user. In my case, the endpoint is:

`/api/accounts/auth/user/`

and it returns:

```
{
    "pk": 12,
    "username": "admins",
    "email": "xm@gmail.com",
}
```

**but**, it requires a GET method with the following **headers**:

Key: `Authorization`
Value: `Token XXXXXXXXXXXXXXXXXXXX`

No matter what I tried, I couldn't get this to work with this module. I simply couldn't find a way to set the headers like this in a get request, and therefore I'm temporarily resorting to mapping my endpoints and managing my state manually.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c371">#c371</a>)</em></sub></div>

**Comment by bmulholland** [comment]
I have this exact setup running in production with auth-next: my server returns a JWT, and the JWT is included as a bearer token. Unless I'm missing something, the scenario you describe does work?
