### ISSUE TITLE
I can't get the result (response) by loginWith method

### ISSUE THREAD

**Issue by duxinxiao** [nuxt-community/auth-module#411]
### What problem does this feature solve?

![企业微信截图_a43ae1ff-6824-40bc-b543-a6001417fe9d.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/47fd09c0-a87b-11e9-843c-4511e466d3ac.png)
local schemes ignore the result except token, but sometimes we may need the hole response. For my situation, server will tell me some information about this login action, but I cant get it

### What does the proposed changes look like?

return the whole response

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c375">#c375</a>)</em></sub></div>

**Comment by woutercouvaras** [comment]
This would be great to have :)  In the meantime, I'm still trying to figure out if there isn't a way around this to get the full response.

**Comment by woutercouvaras** [comment]
When you say you copied local's code, do you mean the local strategy from the auth module?

**Comment by emielmolenaar** [comment]
```
this.$auth.onError(function(error) {
  // error.response is your full server response, do something nice with it :)
})
```

**Comment by leviwheatcroft** [comment]
It's [this](https://github.com/nuxt-community/auth-module/blob/dev/lib/core/auth.js#L313) `then` callback, it should return the original promise like:

```
      .then(() => {
        this.$storage.setState('busy', false)
        return promise
      })
```

I'd submit a PR, but I can't get the tests to pass (even before making any changes).
