### ISSUE TITLE
app.$auth.loggedIn return false everytime

### ISSUE THREAD

**Issue by imsidz** [nuxt-community/auth-module#412]
i am using latest nuxt 2.8.1 with latest auth module 4.8.1
i am trying to make a middleware 

`export default function({ store, app, redirect }) {
    console.log(app.$auth.loggedIn) //return always false
    console.log(app.$auth.user) // return always null
    if (app.$auth.loggedIn) {
        return redirect('/dashboard');
    }
}`

when i see vue 
result is this
[http://prntscr.com/ohaba6](url)

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c378">#c378</a>)</em></sub></div>

**Comment by kwatog** [comment]
I had this issue and solved by cloning the LocalScheme. The issue is when calling the fetchUser, it uses requestWith which somehow is failing. So I changed it to just request instead.

```
    // Try to fetch user and then set
    const user = await this.$auth.request(
      this.options.endpoints.user.url,
      '/user/data/'
    )
    this.$auth.setUser(user)
```
