### ISSUE TITLE
Improper check of hasRefreshTokenChanged

### ISSUE THREAD

**Issue by mstacy** [nuxt-community/auth-module#418]
https://github.com/nuxt-community/auth-module/blob/226203fe33f6ee68b89fd66bfd76bc1ebb87aa20/lib/schemes/refresh.js#L94

Believe this line should be:
`this.hasRefreshTokenChanged = refreshToken !== this._getRefreshToken()`

Current check returns false when with different tokens:
`this.hasRefreshTokenChanged = refreshToken === this._getRefreshToken()`

From the check below using `this.hasRefreshTokenChanged`:
`if (!this._getRefreshTokenExpiration() || this.hasRefreshTokenChanged) {`
It would appear the current check is giving the wrong response and the functionality doesn't match with the variable name. Current naming implies we are looking for the tokens to be different from one another

**Comment by JoaoPedroAS51** [comment]
Hi! Thank you for report this! I'll give a look as soon as I can.

**Comment by JoaoPedroAS51** [comment]
Hi @mstacy ! I just pushed an update fixing this issue. Thank you for your help! :)
