### ISSUE TITLE
Computed loggedIn property : Mismatching childNodes vs. VNodes 

### ISSUE THREAD

**Issue by leo91000** [nuxt-community/auth-module#420]
### Version

[v4.8.1](https://github.com/auth-module/releases/tag/v4.8.1)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-mcvnw?fontsize=14](https://codesandbox.io/s/codesandbox-nuxt-mcvnw?fontsize=14)

### Steps to reproduce

1) Install nuxt
2) Setup axios and auth (I use axios 5.5.4)
3) Install vuetify (optional)
4) Setup vuetify (optional)
5) In the layout of your application add a computed property with the following function : 
            isLogged() {
                return this.$auth.loggedIn;
            }
6) Add the following html tag : <v-btn v-if="isLogged">Login</v-btn>

### What is expected ?

The code should not return any error.

### What is actually happening?

I get the following error : 
"[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render."

### Additional comments?

Note : If I remove the v-if directive, the error disapear

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c389">#c389</a>)</em></sub></div>

**Comment by manniL** [comment]
This is normal, as the generated HTML should be stateless. I'm working on a writeup for it :relaxed:

**Comment by leo91000** [comment]
Thanks ! Not sure if it is the right way to go but I uses nuxtServerInit with $auth.$storage.getCookie() to fill the store with isLoggedIn

**Comment by MLDMoritz** [comment]
This happens without auth-module too - It might be a problem with nuxt itself.

Would love to hear more from this issue.
