### ISSUE TITLE
Redirection from guest page to redirect.home

### ISSUE THREAD

**Issue by Geminii** [nuxt-community/auth-module#423]
Hi, 

**Configuration**
```javascript
auth: {
    // Options
    strategies: {
      local: {
        endpoints: {
          login: { url: process.env.BASE_URL + '/auth', method: 'post', propertyName: 'token' },
          logout: false,
          user: { url: process.env.BASE_URL + '/users/auth', method: 'get', propertyName: false }
        }
      }
    },
    redirect: {
      login: '/signin,
      logout: '/signin',
      home: '/home'
    },
    resetOnError: true,
    rewriteRedirects: true,
    fullPathRedirect: true
  },
  router: {
    middleware: ['auth']
  },
```

**Steps to reproduce**
- I authenticate my user on the application (url : `/signin`)
- User is redirect to `/home`
- I kill/close my browser
- Reopen the default page, user is connected but not redirect (url: `/`).

**What is expected ?**
- On the default page (guest middleware), i want to be redirect to `/home` page instead of current default page `/`.

**What is actually happening?**
- When i reopen the browser, call on the endpoint.user is `DONE successfully`
- User is authenticated on the header, but the middleware doesn't redirect to `/home`.

**Comments**
I try to debug the problem of redirection but i think it's a problem about watch on `loggedIn`.

Maybe i missing something in the configuration ? or this case isn't implemented at the moment ? 

Thanks a lot for your answers.
Best regards.

**Comment by noobling** [comment]
There is no feature like that right now nor to me does it sound like something the auth module should handle. The redirection to home after login is something the module does do.

**Comment by Geminii** [comment]
@noobling I don't understand why the middleware `guest` should'nt does this verification. 
Because on the header, the user is already connected. And when you refresh the page for the second time, this time we have been redirect. 
Maybe an improvment to add on the watch about `loggedIn` ?

**Comment by noobling** [comment]
Ah you might be experiencing a bug do you have `auth: false` in your home page? If you do remove that then when you refresh the page there should be no redirection

**Comment by Geminii** [comment]
Nope no one. 
Currently, i want to be redirect on all not connected page to `home` page. 
When i kill the browser, and try to access at one of some connected page. I'm loggin but not not redirect to home page the first time. When i refresh the current page, the second time i'm redirect. 

I suppose at the moment the browser steps for the first time : 
- page is loaded (auth: guest on each not connected page)
- get the user's data
- header updated with the user's data
- no watch about user's data => so no redirection 

I suppose when the page is loaded, the middleware `guest` says : no user's data so i don't need to redirect.

**Comment by farhadf246** [comment]
hi
i have the same problem.
when i reopen browser auth redirect to login page and when i refresh the page user will be redirect to home page
