### ISSUE TITLE
Get access token and refresh token after login endpoint 

### ISSUE THREAD

**Issue by Ned452** [nuxt-community/auth-module#446]
Hi, 
Firstly, thank you for detailed documentary of auth module!
But I can't find the solution of my problem
I want to get 'access token' and 'refresh token' after i login endpoints 
Something like this:
`auth: {
  strategies: {
    local: {
      endpoints: {
        login: { url: '/api/auth/login', method: 'post', propertyName: 'token.access', refrshToken:'token.refresh'},
        user: { url: '/api/auth/user', method: 'get' },
        logout: { url: '/api/auth/logout', method: 'post' }
      },
      refreshToken: true
    }
  }
},`
and result in:
![Снимок](https://user-images.githubusercontent.com/38585815/64361856-1283db80-d016-11e9-8029-4627f2340dac.PNG)

>

**Comment by JoaoPedroAS51** [comment]
Hi @Ned452 ! We are working on refresh support for local strategy. It's not finished yet, but at the meantime you can use the new [branch (feat/refresh)](https://github.com/nuxt-community/auth-module/tree/feat/refresh).

Docs and more details can be found at #361

**Comment by Ned452** [comment]
@JoaoPedroAS51, Thank you!

**Comment by cardaddy** [comment]
@JoaoPedroAS51 Would the refresh support for local strategy be the same for oauth2 with grant_type authorization_code?

**Comment by cardaddy** [comment]
@JoaoPedroAS51 Would the refresh support for local strategy be the same for oauth2 with grant_type authorization_code?

**Comment by JoaoPedroAS51** [comment]
Hi @cardaddy ! I don't think it works on OAuth2 out of the box, because it doesn't match OAuth2 requirements. But we want to improve the system to support OAuth2. I let you know as soon as we support it.
