### ISSUE TITLE
Add cookie samesite option default value for security

### ISSUE THREAD

**Issue by hareku** [nuxt-community/auth-module#465]
### What problem does this feature solve?

It is difficult to use CSFR tokens on SPA sites like Nuxt.js, and many sites do not use CSRF tokens.

Therefore, add a default value for the cookie samesite option to prevent CSRF.

The default value is `lax`. Chrome tries to make `lax` the default value for security.
https://www.chromestatus.com/feature/5088147346030592

### What does the proposed changes look like?

Set the default value of the cookie samesite option to `lax`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c427">#c427</a>)</em></sub></div>

**Comment by hareku** [comment]
This is the case when the domain of the Nuxt.js site and the API domain are the same.

**Comment by hareku** [comment]
https://github.com/nuxt-community/auth-module/pull/466#issuecomment-569431362

**Comment by dappiu** [comment]
I think we should take action now. Please see this: https://github.com/nuxt-community/auth-module/pull/466#issuecomment-631987959
