### ISSUE TITLE
[Question] Release plan 

### ISSUE THREAD

**Issue by oanhnn** [nuxt-community/auth-module#47]
I need a new release for my production.
Can you show your release plan?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c35">#c35</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Sorry for this long time. We had many changes until getting stable. 4.0.0 is released and i hope we can stay with semver releases now. [release notes](https://github.com/nuxt-community/auth-module/releases)
