### ISSUE TITLE
 two endpoints

### ISSUE THREAD

**Issue by prabodhana** [nuxt-community/auth-module#499]
I want to add two endpoints for nuxtjs project one for admin and other one for client..

like below...

     auth: {
    strategies: {
      local: {
        one:{
          
          endpoints: {
            login: { url: '/admin/login', method: 'post', propertyName: 'meta.token' },
            logout: { url: '/logout', method: 'post' },
            user: { url: '/admin/admin', method: 'get', propertyName: 'data' },
          },
         
        },
        two:{
          endpoints: {
          
            login: { url: '/client/login', method: 'post', propertyName: 'meta.token' },
            logout: { url: '/logout', method: 'post' },
            user: { url: '/client/client', method: 'get', propertyName: 'data' }
          },
        }
        
      },
     
    }
    },

how can i do that?

thank you...
 

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c455">#c455</a>)</em></sub></div>

**Comment by hbsoftco** [comment]
I have same issue.
