### ISSUE TITLE
OIDC scheme 

### ISSUE THREAD

**Issue by madmonkey** [nuxt-community/auth-module#503]
### What problem does this feature solve?

Simplicity of configuration -> point to a discovery endpoint and have the requisite information from the authority server configure the required flow with sensible overridable defaults. 

https://github.com/IdentityModel/oidc-client-js
https://github.com/perarnborg/vuex-oidc

I'd be happy to contribute - but I would need a bit of guidance on how best to approach.

### What does the proposed changes look like?

Setting-up a auth strategy would look like the following (it could be an enhancement to the oAuth scheme):

oidc: {
   issuer: 'https://[endpoint]', *or* wellknownendpoint: 'https://[endpoint]/.well-known/openid-configuration'
   client_id: '606654455983411e',
   client_secret: '3dc309db955098a56b4fbc12677803468bfd477'
}

Issuing a GET to issuer/.well-known/openid-configuration already provides a response similar to the following, which provides endpoints for authorization token, user, end_session,etc., in addition to supported scopes, grant types, etc. :

{
   "issuer":"https://[endpoint]",
   "jwks_uri":"https://[endpoint]/.well-known/openid-configuration/jwks",
   "authorization_endpoint":"https://[endpoint]/connect/authorize",
   "token_endpoint":"https://[endpoint]/connect/token",
   "userinfo_endpoint":"https://[endpoint]/connect/userinfo",
   "end_session_endpoint":"https://[endpoint]/connect/endsession",
   "check_session_iframe":"https://[endpoint]/connect/checksession",
   "revocation_endpoint":"https://[endpoint]/connect/revocation",
   "introspection_endpoint":"https://[endpoint]/connect/introspect",
   "device_authorization_endpoint":"https://[endpoint]/connect/deviceauthorization",
   "frontchannel_logout_supported":true,
   "frontchannel_logout_session_supported":true,
   "backchannel_logout_supported":true,
   "backchannel_logout_session_supported":true,
   "scopes_supported":[
      "openid",
      "profile",
      "email",
      "offline_access"
   ],
   "claims_supported":[
      "name",
      "user_name",
      "user_type",
      "role",
      "email",
      "phone_number"
   ],
   "grant_types_supported":[
      "authorization_code",
      "client_credentials",
      "refresh_token",
      "implicit",
      "password",
      "urn:ietf:params:oauth:grant-type:device_code"
   ],
   "response_types_supported":[
      "code",
      "token",
      "id_token",
      "id_token token",
      "code id_token",
      "code token",
      "code id_token token"
   ],
   "response_modes_supported":[
      "form_post",
      "query",
      "fragment"
   ],
   "token_endpoint_auth_methods_supported":[
      "client_secret_basic",
      "client_secret_post"
   ],
   "subject_types_supported":[
      "public"
   ],
   "id_token_signing_alg_values_supported":[
      "RS256"
   ],
   "code_challenge_methods_supported":[
      "plain",
      "S256"
   ]
}

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c460">#c460</a>)</em></sub></div>

**Comment by IGassmann** [comment]
This will be a welcomed addition to v5.

**Comment by bmulholland** [comment]
https://github.com/nuxt-community/auth-module/pull/868 was merged, and I think that means this feature request so I'm closing it out. Please create a new issue if I've missed anything :)
