### ISSUE TITLE
urgent : use with keycloak ! Help me please !

### ISSUE THREAD

**Issue by titoff002** [nuxt-community/auth-module#512]
Hello,

I'm use this auth-module with keyloak.

My strategie on nuxt.config.js :

`      keycloak: {
        _scheme: 'oauth2',
		client_id: 'client-bo',
		userinfo_endpoint: 'SERVER/protocol/openid-connect/userinfo',
        authorization_endpoint: 'SERVER/protocol/openid-connect/auth',
        //userinfo_endpoint: false,
        access_type: 'offline',
        access_token_endpoint: 'SERVER/protocol/openid-connect/token',
        //response_type: 'code',
		response_type: 'token id_token',
        token_type: 'Bearer',
        token_key: 'access_token',
		  scope: ['openid', 'profile', 'email'],
		  redirect_uri: 'http://127.0.0.1:3000/'		
      },`

The conection is ok.

when I click on the "connect" button: I am redirected to my keycloak environment. Once authenticated on keycloak: I am redirected to my nuxtjs application.

However, the problem is that my store are empty. Do you have an idea about this problem?

![image](https://user-images.githubusercontent.com/24948237/71882252-645b8000-3134-11ea-8099-52aed3b13a02.png)

loggedIn : is always false
user : is always 'null'

can you tell me why it doesn't work?

Thanks to you.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c466">#c466</a>)</em></sub></div>

**Comment by joka253** [comment]
Hi @titoff002,
have you, by any chance, been able to solve the problem? I'm stuck with the same issue right now and can't really get my head around it.

Best regards

**Comment by alxndr13** [comment]
i also have this issue. Did you solve it?
