### ISSUE TITLE
How to take token from header instead of body during login

### ISSUE THREAD

**Issue by flyingboy007** [nuxt-community/auth-module#517]
Using nuxt-auth for authentication. The endpoints are configured like this. 

      auth: {
        strategies: {
          local: {
            endpoints: {
              login: {url: '/sellers/login', method: 'post', propertyName: 'How to ref header here'},
              logout: {url: '/api/auth/logout', method: 'post'},
              user: false
            },
          //  tokenRequired: true,
            tokenType: ''
          }
        }
      }

But server is sending token in `response` header instead of body. So `nuxt-auth` is not working. How can I fix this?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c473">#c473</a>)</em></sub></div>

**Comment by sergiocastrovale** [comment]
I'm having this exact same issue. Did you find a solution @flyingboy007 ?

**Comment by vesper8** [comment]
sigh.. I have exact same issue.. server returns authorizing token as header.. and nowhere in docs does it say how to handle this. Did you find a solution @sergiocastrovale @flyingboy007 ?

**Comment by flyingboy007** [comment]
No. I updated the server to return it in body. Not that happy with this
solution. But until I find a way  I will keep it like this.
