### ISSUE TITLE
Using $auth in plugins

### ISSUE THREAD

**Issue by alex-eri** [nuxt-community/auth-module#524]
### What problem does this feature solve?

I want to extend axios with plugin

export default function ({ $axios, $auth, redirect }) {
  $axios.onError((error) => {
    const code = parseInt(error.response && error.response.status)
    console.log('error' + code)
    console.log(error)
    if (code === 401) {
      console.log($auth)
      redirect('/auth/login')
      return true
    }
  })
}

but $auth is undefined.

### What does the proposed changes look like?

inject auth $auth to plugins

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c482">#c482</a>)</em></sub></div>

**Comment by feam-codes** [comment]
There is a sneaky example in the docs: https://auth.nuxtjs.org/recipes/extend.html :)
If you attach your axios plugin into auth.plugins config you have access to $auth.

**Comment by alex-eri** [comment]
@feam-codes nuxt plugins, not auth plugins

**Comment by feam-codes** [comment]
@alex-eri If you append your nuxt plugin to auth.plugins instead of plugins, it gets loaded like a normal nuxt plugin but with access to $auth.

**Comment by alex-eri** [comment]
i appended at both - it not working. with auth.plugins seems it works.
