### ISSUE TITLE
Login POST request converted to GET request

### ISSUE THREAD

**Issue by nivv** [nuxt-community/auth-module#537]
### Version

[v4.8.5](https://github.com/auth-module/releases/tag/v4.8.5)

### Reproduction link

[https://google.se](https://google.se)

### Steps to reproduce

Somehow the defined POST is converted to a GET request.

```
   auth: {
        redirect: {
            login: '/login',
            logout: '/',
            callback: '/login',
            home: '/profile'
        },
        strategies: {
            local: false,
            password_grant: {
                _scheme: 'local',
                endpoints: {
                    loginn: {
                        url: '/oauth/token',
                        method: 'post',
                        propertyName: 'access_token'
                    },
                    logout: false,
                    user: {
                        url: '/api/admin/user',
                        method: 'get',
                        propertyName: 'data'
                    }
                }
            }
        }
    },
```

![Skärmklipp 2020-02-21 10.20.03.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/654ddb50-548b-11ea-b377-297ef0b732e8.png)

If I change the request method to PATCH/PUT it sends the request as PATCH/PUT

### What is expected ?

A POST request is made

### What is actually happening?

A GET request is made

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c501">#c501</a>)</em></sub></div>

**Comment by nivv** [comment]
Another detail I left out is that the request is made to a remote server.

**Comment by nivv** [comment]
This seems to be a local issue, maybe because my client isnt on https on my machine?

**Comment by nivv** [comment]
This can be closed, it was a third party extension in Chrome (Privacy possum)

**Comment by Strahinja** [comment]
Also it seems you have a typo in `loginn:` vs `login:`.

**Comment by Maxiride** [comment]
> 
> 
> This can be closed, it was a third party extension in Chrome (Privacy possum)

You can close the issue yourself without waiting for moderators to chime in ;)
