### ISSUE TITLE
Auth Module completely breaking Nuxt?

### ISSUE THREAD

**Issue by 1nchHigh** [nuxt-community/auth-module#545]
### Version

[v4.8.5](https://github.com/auth-module/releases/tag/v4.8.5)

### Reproduction link

[https://github.com/1nchHigh/Nuxt-Auth-Issue](https://github.com/1nchHigh/Nuxt-Auth-Issue)

### Steps to reproduce

1 - Create App using Nuxt CLI

2 - Add Axios & Auth Module:
yarn add @nuxtjs/auth @nuxtjs/axios

3 - Add the two modules to 'Modules' section in Nuxt Config

4 - Add auth Object in Nuxt Config

5 - Add Router Object with middleware 'AUTH' in Nuxt Config

6 - Create index.js in Store folder

7 - Create a login.vue page

8 - Launch App

### What is expected ?

The app launches and due to the 'auth' middleware in the router object the app loads the 'login page'

### What is actually happening?

Localhost attempts to load for a long time. 

I see no build errors for Client / Server

It attempts to load for a while and then I receive:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

In the console.

I literally configured this in another app yesterday and it worked fine. No matter what I try now, I can't get this to work when I add the Auth Module. 

I may be doing something stupid, but I just can't figure out what I've done differently today!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c506">#c506</a>)</em></sub></div>

**Comment by 1nchHigh** [comment]
The reproduction repo contains a crash report? Maybe that could help?

**Comment by 1nchHigh** [comment]
Restarting my PC Fixed it, I have literally 0 idea what happened.... sorry!

**Comment by 1nchHigh** [comment]
Yeah no it didnt fix it. It works first time after PC Reboot and then doesn't work again.
I can't reboot my PC every time I make a change to the app.

Any suggestions?

**Comment by 1nchHigh** [comment]
{
  "header": {
    "reportVersion": 1,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20200303.134425.3980.0.001.json",
    "dumpEventTime": "2020-03-03T13:44:25Z",
    "dumpEventTimeStamp": "1583243065484",
    "processId": 3980,
    "cwd": "C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website",
    "commandLine": [
      "C:\\Program Files\\nodejs\\node.exe",
      "C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website\\node_modules\\.bin\\\\..\\nuxt\\bin\\nuxt.js"
    ],
    "nodejsVersion": "v12.16.1",
    "wordSize": 64,
    "arch": "x64",
    "platform": "win32",
    "componentVersions": {
      "node": "12.16.1",
      "v8": "7.8.279.23-node.31",
      "uv": "1.34.0",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.40.0",
      "napi": "5",
      "llhttp": "2.0.4",
      "http_parser": "2.9.3",
      "openssl": "1.1.1d",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019c",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "lts": "Erbium",
      "headersUrl": "https://nodejs.org/download/release/v12.16.1/node-v12.16.1-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.16.1/node-v12.16.1.tar.gz",
      "libUrl": "https://nodejs.org/download/release/v12.16.1/win-x64/node.lib"
    },
    "osName": "Windows_NT",
    "osRelease": "10.0.18362",
    "osVersion": "Windows 10 Pro",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz",
        "speed": 3000,
        "user": 111375,
        "nice": 0,
        "sys": 55156,
        "idle": 294625,
        "irq": 4796
      },
      {
        "model": "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz",
        "speed": 3000,
        "user": 162171,
        "nice": 0,
        "sys": 54593,
        "idle": 244109,
        "irq": 343
      },
      {
        "model": "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz",
        "speed": 3000,
        "user": 130328,
        "nice": 0,
        "sys": 46859,
        "idle": 283687,
        "irq": 500
      },
      {
        "model": "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz",
        "speed": 3000,
        "user": 135656,
        "nice": 0,
        "sys": 48812,
        "idle": 276406,
        "irq": 453
      },
      {
        "model": "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz",
        "speed": 3000,
        "user": 137984,
        "nice": 0,
        "sys": 49703,
        "idle": 273187,
        "irq": 343
      },
      {
        "model": "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz",
        "speed": 3000,
        "user": 142234,
        "nice": 0,
        "sys": 48812,
        "idle": 269828,
        "irq": 265
      }
    ],
    "networkInterfaces": [
      {
        "name": "Ethernet",
        "internal": false,
        "mac": "6c:2b:59:d7:2f:3b",
        "address": "fe80::7491:26ce:7573:f056",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 10
      },
      {
        "name": "Ethernet",
        "internal": false,
        "mac": "6c:2b:59:d7:2f:3b",
        "address": "10.100.170.137",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "Loopback Pseudo-Interface 1",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "::1",
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "Loopback Pseudo-Interface 1",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      }
    ],
    "host": "KSAMIT003"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x00007ff62d2e19f9",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+10873"
    },
    {
      "pc": "0x00007ff62d2e5e1c",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+28316"
    },
    {
      "pc": "0x00007ff62d2e4dd8",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+24152"
    },
    {
      "pc": "0x00007ff62d3e34cb",
      "symbol": "v8::base::CPU::has_sse+38363"
    },
    {
      "pc": "0x00007ff62dbf9f4e",
      "symbol": "v8::Isolate::ReportExternalAllocationLimitReached+94"
    },
    {
      "pc": "0x00007ff62dbe2021",
      "symbol": "v8::SharedArrayBuffer::Externalize+833"
    },
    {
      "pc": "0x00007ff62daae57c",
      "symbol": "v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436"
    },
    {
      "pc": "0x00007ff62dab97d0",
      "symbol": "v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312"
    },
    {
      "pc": "0x00007ff62dab62f4",
      "symbol": "v8::internal::Heap::PageFlagsAreConsistent+3204"
    },
    {
      "pc": "0x00007ff62daabb13",
      "symbol": "v8::internal::Heap::CollectGarbage+1283"
    },
    {
      "pc": "0x00007ff62dabae1c",
      "symbol": "v8::internal::Heap::RemoveNearHeapLimitCallback+2460"
    },
    {
      "pc": "0x00007ff62d7cdc0f",
      "symbol": "v8::internal::DeserializerAllocator::DecodeReservation+623"
    },
    {
      "pc": "0x00007ff62d7c9772",
      "symbol": "v8::internal::PartialDeserializer::DeserializeEmbedderFields+1474"
    },
    {
      "pc": "0x00007ff62d7c9cce",
      "symbol": "v8::internal::PartialDeserializer::DeserializeEmbedderFields+2846"
    },
    {
      "pc": "0x00007ff62d7ce6d9",
      "symbol": "v8::internal::ScriptData::ScriptData+2665"
    },
    {
      "pc": "0x00007ff62db55565",
      "symbol": "v8::internal::Compiler::GetWrappedFunction+661"
    },
    {
      "pc": "0x00007ff62dbdc73b",
      "symbol": "v8::ScriptCompiler::CompileFunctionInContext+2011"
    },
    {
      "pc": "0x00007ff62dbdbf54",
      "symbol": "v8::ScriptCompiler::CompileFunctionInContext+84"
    },
    {
      "pc": "0x00007ff62d3a2fbb",
      "symbol": "v8::internal::MemoryChunkLayout::ObjectStartOffsetInDataPage+68539"
    },
    {
      "pc": "0x00007ff62d3a1655",
      "symbol": "v8::internal::MemoryChunkLayout::ObjectStartOffsetInDataPage+62037"
    },
    {
      "pc": "0x00007ff62d45d321",
      "symbol": "node::InitializeContext+817"
    },
    {
      "pc": "0x00007ff62d45d699",
      "symbol": "node::NewContext+89"
    },
    {
      "pc": "0x00007ff62d3eb681",
      "symbol": "v8::base::CPU::has_sse+71569"
    },
    {
      "pc": "0x00007ff62d3ecabb",
      "symbol": "v8::base::CPU::has_sse+76747"
    },
    {
      "pc": "0x00007ff62dfca9ac",
      "symbol": "v8::internal::SetupIsolateDelegate::SetupHeap+45852"
    },
    {
      "pc": "0x000001a39bb995ac",
      "symbol": ""
    }
  ],
  "javascriptHeap": {
    "totalMemory": 2154987520,
    "totalCommittedMemory": 2154987520,
    "usedMemory": 2046174952,
    "availableMemory": 48436624,
    "memoryLimit": 2197815296,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 262144,
        "committedMemory": 262144,
        "capacity": 32808,
        "used": 32808,
        "available": 0
      },
      "new_space": {
        "memorySize": 4194304,
        "committedMemory": 4194304,
        "capacity": 2094912,
        "used": 532616,
        "available": 1562296
      },
      "old_space": {
        "memorySize": 1798979584,
        "committedMemory": 1798979584,
        "capacity": 1698009232,
        "used": 1696057592,
        "available": 1951640
      },
      "code_space": {
        "memorySize": 2789376,
        "committedMemory": 2789376,
        "capacity": 2465984,
        "used": 2465984,
        "available": 0
      },
      "map_space": {
        "memorySize": 299634688,
        "committedMemory": 299634688,
        "capacity": 298217680,
        "used": 298217680,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 48218112,
        "committedMemory": 48218112,
        "capacity": 48052656,
        "used": 48052656,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 909312,
        "committedMemory": 909312,
        "capacity": 815616,
        "used": 815616,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 2094912,
        "used": 0,
        "available": 2094912
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 195.515,
    "kernelCpuSeconds": 9.812,
    "cpuConsumptionPercent": 108.067,
    "maxRss": 2517798912,
    "pageFaults": {
      "IORequired": 1311785,
      "IONotRequired": 0
    },
    "fsActivity": {
      "reads": 13639,
      "writes": 66
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "%ConEmuDir%": "C:\\Program Files\\Cmder\\vendor\\conemu-maximus5",
    "=C:": "C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website",
    "aliases": "C:\\cmder\\config\\user_aliases.cmd",
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "ANSICON": "238x1000 (238x61)",
    "ANSICON_DEF": "7",
    "APPDATA": "C:\\Users\\KSAMIT003\\AppData\\Roaming",
    "architecture": "64",
    "architecture_bits": "64",
    "ccall": "call C:\\cmder\\vendor\\bin\\cexec.cmd",
    "cexec": "C:\\cmder\\vendor\\bin\\cexec.cmd",
    "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
    "ChocolateyLastPathUpdate": "132265107041914597",
    "CMDER_ALIASES": "1",
    "CMDER_CLINK": "1",
    "CMDER_CONFIGURED": "1",
    "CMDER_INIT_END": "13:37:27.33",
    "CMDER_INIT_START": "13:37:23.51",
    "CMDER_ROOT": "C:\\cmder",
    "CMDER_SHELL": "cmd",
    "CMDER_USER_FLAGS": " ",
    "CommonProgramFiles": "C:\\Program Files\\Common Files",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "COMPUTERNAME": "KSAMIT003",
    "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
    "ConEmuANSI": "ON",
    "ConEmuAnsiLog": "",
    "ConEmuArgs": "/Icon \"C:\\cmder\\icons\\cmder.ico\" /Title Cmder /dir \"C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website\"",
    "ConEmuArgs2": "",
    "ConEmuBackHWND": "0x00010426",
    "ConEmuBaseDir": "C:\\cmder\\vendor\\conemu-maximus5\\ConEmu",
    "ConEmuBaseDirShort": "C:\\cmder\\vendor\\conemu-maximus5\\ConEmu",
    "ConEmuBuild": "180626",
    "ConEmuCfgDir": "C:\\cmder\\vendor\\conemu-maximus5",
    "ConEmuConfig": "",
    "ConEmuDir": "C:\\cmder\\vendor\\conemu-maximus5",
    "ConEmuDrawHWND": "0x00010428",
    "ConEmuDrive": "C:",
    "ConEmuHooks": "Enabled",
    "ConEmuHWND": "0x000803D4",
    "ConEmuPalette": "Nord",
    "ConEmuPID": "10760",
    "ConEmuServerPID": "11152",
    "ConEmuTask": "{cmd::Cmder}",
    "ConEmuWorkDir": "C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website",
    "ConEmuWorkDrive": "C:",
    "debug_output": "0",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "fast_init": "0",
    "feFlagName": " ",
    "GIT_INSTALL_ROOT": "C:\\Program Files\\Git",
    "HOME": "C:\\Users\\KSAMIT003",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\KSAMIT003",
    "INIT_CWD": "C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website",
    "LANG": "en_US.UTF-8",
    "lib_base": "call \"C:\\cmder\\vendor\\lib\\lib_base.cmd\"",
    "lib_console": "call \"C:\\cmder\\vendor\\lib\\lib_console.cmd\"",
    "lib_git": "call \"C:\\cmder\\vendor\\lib\\lib_git.cmd\"",
    "lib_path": "call \"C:\\cmder\\vendor\\lib\\lib_path.cmd\"",
    "lib_profile": "call \"C:\\cmder\\vendor\\lib\\lib_profile.cmd\"",
    "LOCALAPPDATA": "C:\\Users\\KSAMIT003\\AppData\\Local",
    "LOGONSERVER": "\\\\KSAMIT003",
    "max_depth": "1",
    "nix_tools": "1",
    "NODE": "C:\\Program Files\\nodejs\\node.exe",
    "NODE_ENV": "development",
    "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"dev\"],\"original\":[\"dev\"]}",
    "npm_config_bin_links": "true",
    "npm_config_ignore_optional": "",
    "npm_config_ignore_scripts": "",
    "npm_config_init_license": "MIT",
    "npm_config_init_version": "1.0.0",
    "npm_config_registry": "https://registry.yarnpkg.com",
    "npm_config_save_prefix": "^",
    "npm_config_strict_ssl": "true",
    "npm_config_user_agent": "yarn/1.22.0 npm/? node/v12.16.1 win32 x64",
    "npm_config_version_commit_hooks": "true",
    "npm_config_version_git_message": "v%s",
    "npm_config_version_git_sign": "",
    "npm_config_version_git_tag": "true",
    "npm_config_version_tag_prefix": "v",
    "npm_execpath": "C:\\Program Files (x86)\\Yarn\\bin\\yarn.js",
    "npm_lifecycle_event": "dev",
    "npm_lifecycle_script": "nuxt",
    "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
    "npm_package_author_name": "Alex Wilkes",
    "npm_package_dependencies_nuxt": "^2.0.0",
    "npm_package_dependencies_nuxt_buefy": "^0.3.2",
    "npm_package_dependencies__nuxtjs_auth": "^4.8.5",
    "npm_package_dependencies__nuxtjs_axios": "^5.9.5",
    "npm_package_dependencies__nuxtjs_dotenv": "^1.4.0",
    "npm_package_dependencies__nuxtjs_pwa": "^3.0.0-0",
    "npm_package_description": "KSAM IMIS Base Website - Using REST",
    "npm_package_devDependencies_babel_eslint": "^10.0.1",
    "npm_package_devDependencies_babel_jest": "^24.1.0",
    "npm_package_devDependencies_eslint": "^6.1.0",
    "npm_package_devDependencies_eslint_config_prettier": "^6.10.0",
    "npm_package_devDependencies_eslint_plugin_nuxt": ">=0.4.2",
    "npm_package_devDependencies_eslint_plugin_prettier": "^3.1.2",
    "npm_package_devDependencies_husky": "^4.0.0",
    "npm_package_devDependencies_jest": "^24.1.0",
    "npm_package_devDependencies_lint_staged": "^10.0.0",
    "npm_package_devDependencies_prettier": "^1.19.1",
    "npm_package_devDependencies_stylelint": "^10.1.0",
    "npm_package_devDependencies_vue_jest": "^4.0.0-0",
    "npm_package_devDependencies__nuxtjs_eslint_config": "^2.0.0",
    "npm_package_devDependencies__nuxtjs_eslint_module": "^1.0.0",
    "npm_package_devDependencies__nuxtjs_stylelint_module": "^3.1.0",
    "npm_package_devDependencies__vue_test_utils": "^1.0.0-beta.27",
    "npm_package_husky_hooks_pre_commit": "lint-staged",
    "npm_package_lint_staged____css_vue_": "stylelint",
    "npm_package_lint_staged____js_vue_": "yarn lint",
    "npm_package_name": "imis-base-website",
    "npm_package_private": "true",
    "npm_package_readmeFilename": "README.md",
    "npm_package_scripts_build": "nuxt build",
    "npm_package_scripts_dev": "nuxt",
    "npm_package_scripts_generate": "nuxt generate",
    "npm_package_scripts_lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "npm_package_scripts_start": "nuxt start",
    "npm_package_scripts_test": "jest",
    "npm_package_version": "1.0.0",
    "NUMBER_OF_PROCESSORS": "6",
    "OneDrive": "C:\\Users\\KSAMIT003\\OneDrive",
    "OneDriveConsumer": "C:\\Users\\KSAMIT003\\OneDrive",
    "OS": "Windows_NT",
    "Path": "C:\\Users\\KSAMIT003\\AppData\\Local\\Temp\\yarn--1583242874682-0.6238481876926851;C:\\Users\\KSAMIT003\\Desktop\\Nuxt Projects\\imis-base-website\\node_modules\\.bin;C:\\Users\\KSAMIT003\\AppData\\Local\\Yarn\\Data\\link\\node_modules\\.bin;C:\\Program Files\\libexec\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin;C:\\cmder\\bin;C:\\cmder\\vendor\\bin;C:\\cmder\\vendor\\conemu-maximus5\\ConEmu\\Scripts;C:\\cmder\\vendor\\conemu-maximus5;C:\\cmder\\vendor\\conemu-maximus5\\ConEmu;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Git\\cmd;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files (x86)\\Cmder;C:\\Program Files (x86)\\Watchman\\bin\\;C:\\Program Files (x86)\\Yarn\\bin\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\nodejs\\;C:\\Users\\KSAMIT003\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\;C:\\Users\\KSAMIT003\\AppData\\Local\\Programs\\Python\\Python37-32\\;C:\\Users\\KSAMIT003\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\KSAMIT003\\.dotnet\\tools;C:\\Users\\KSAMIT003\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\KSAMIT003\\AppData\\Local\\Programs\\Fiddler;C:\\Users\\KSAMIT003\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files (x86)\\Cmder;C:\\Program Files (x86)\\Watchman\\bin\\;C:\\Users\\KSAMIT003\\AppData\\Local\\Yarn\\bin;C:\\Users\\KSAMIT003\\AppData\\Roaming\\npm;C:\\Users\\KSAMIT003\\AppData\\Local\\GitHubDesktop\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\cmder",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC",
    "PLINK_PROTOCOL": "ssh",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel",
    "PROCESSOR_LEVEL": "6",
    "PROCESSOR_REVISION": "9e0a",
    "ProgramData": "C:\\ProgramData",
    "ProgramFiles": "C:\\Program Files",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "ProgramW6432": "C:\\Program Files",
    "PROMPT": "C\bL\bI\bN\bK\b \b$P$G",
    "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\Tools\\PowerShell\\Modules\\",
    "PUBLIC": "C:\\Users\\Public",
    "SESSIONNAME": "Console",
    "SVN_SSH": "C:\\\\Program Files\\\\Git\\\\bin\\\\ssh.exe",
    "SystemDrive": "C:",
    "SystemRoot": "C:\\WINDOWS",
    "TEMP": "C:\\Users\\KSAMIT003\\AppData\\Local\\Temp",
    "TERM": "cygwin",
    "time_init": "0",
    "TMP": "C:\\Users\\KSAMIT003\\AppData\\Local\\Temp",
    "USERDOMAIN": "KSAMIT003",
    "USERDOMAIN_ROAMINGPROFILE": "KSAMIT003",
    "USERNAME": "KSAMIT003",
    "USERPROFILE": "C:\\Users\\KSAMIT003",
    "user_aliases": "C:\\cmder\\config\\user_aliases.cmd",
    "verbose_output": "0",
    "VS110COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\",
    "VS120COMNTOOLS": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\",
    "VUE_ENV": "server",
    "windir": "C:\\WINDOWS",
    "YARN_WRAP_OUTPUT": "false",
    "_AXIOS_BASE_URL_": "http://localhost:3000/"
  },
  "sharedObjects": [
    "C:\\Program Files\\nodejs\\node.exe",
    "C:\\WINDOWS\\SYSTEM32\\ntdll.dll",
    "C:\\WINDOWS\\System32\\KERNEL32.DLL",
    "C:\\WINDOWS\\System32\\KERNELBASE.dll",
    "C:\\WINDOWS\\System32\\WS2_32.dll",
    "C:\\WINDOWS\\System32\\RPCRT4.dll",
    "C:\\WINDOWS\\System32\\PSAPI.DLL",
    "C:\\WINDOWS\\System32\\ADVAPI32.dll",
    "C:\\WINDOWS\\System32\\msvcrt.dll",
    "C:\\WINDOWS\\System32\\sechost.dll",
    "C:\\WINDOWS\\System32\\USER32.dll",
    "C:\\WINDOWS\\System32\\win32u.dll",
    "C:\\WINDOWS\\SYSTEM32\\USERENV.dll",
    "C:\\WINDOWS\\System32\\GDI32.dll",
    "C:\\WINDOWS\\System32\\ucrtbase.dll",
    "C:\\WINDOWS\\System32\\gdi32full.dll",
    "C:\\WINDOWS\\System32\\msvcp_win.dll",
    "C:\\WINDOWS\\SYSTEM32\\IPHLPAPI.DLL",
    "C:\\WINDOWS\\System32\\profapi.dll",
    "C:\\WINDOWS\\System32\\CRYPT32.dll",
    "C:\\WINDOWS\\System32\\MSASN1.dll",
    "C:\\WINDOWS\\System32\\bcrypt.dll",
    "C:\\WINDOWS\\SYSTEM32\\dbghelp.dll",
    "C:\\WINDOWS\\SYSTEM32\\WINMM.dll",
    "C:\\WINDOWS\\SYSTEM32\\WINMMBASE.dll",
    "C:\\WINDOWS\\System32\\cfgmgr32.dll",
    "C:\\WINDOWS\\System32\\bcryptPrimitives.dll",
    "C:\\WINDOWS\\System32\\IMM32.DLL",
    "C:\\cmder\\vendor\\conemu-maximus5\\ConEmu\\ConEmuHk64.dll",
    "C:\\WINDOWS\\System32\\powrprof.dll",
    "C:\\WINDOWS\\System32\\UMPDC.dll",
    "C:\\WINDOWS\\SYSTEM32\\CRYPTBASE.DLL",
    "C:\\WINDOWS\\system32\\uxtheme.dll",
    "C:\\WINDOWS\\System32\\combase.dll",
    "C:\\WINDOWS\\system32\\mswsock.dll",
    "C:\\WINDOWS\\System32\\kernel.appcore.dll",
    "C:\\WINDOWS\\System32\\NSI.dll",
    "C:\\WINDOWS\\SYSTEM32\\dhcpcsvc6.DLL",
    "C:\\WINDOWS\\SYSTEM32\\dhcpcsvc.DLL",
    "C:\\WINDOWS\\SYSTEM32\\DNSAPI.dll",
    "C:\\Program Files\\Bonjour\\mdnsNSP.dll",
    "C:\\Windows\\System32\\rasadhlp.dll",
    "C:\\WINDOWS\\System32\\fwpuclnt.dll",
    "C:\\WINDOWS\\system32\\napinsp.dll",
    "C:\\WINDOWS\\system32\\pnrpnsp.dll",
    "C:\\WINDOWS\\System32\\winrnr.dll",
    "C:\\WINDOWS\\system32\\NLAapi.dll",
    "C:\\WINDOWS\\system32\\wshbth.dll"
  ]
}

**Comment by pi0** [comment]
Hi @1nchHigh. The issue is visible by `AXIOS_BASE_URL`. You need to configure axios baseURL option from `nuxt.config.js` so auth module makes requests to correct endpoint.
