### ISSUE TITLE
401 error when using cookies and not token

### ISSUE THREAD

**Issue by radudiaconu0** [nuxt-community/auth-module#550]
WHen i use laravel airlock with nuxt js and auth module on every page i navigate i get 401 error without being authenticated. i put correct middleware on every route. why is that happen? when i login all things works properly.(i use spa mode but i am curious how can i make things works on unversal mode)
this is my nuxt configuration:

`axios: {
    baseURL: 'http://app.cheer.test/',
    withCredentials: true
  },
  auth: {
    redirect: {
      login: '/login',
      logout: '/',
      callback: '/login',
      home: '/home'
    },
    strategies: {
      local: {
        endpoints: {
          login: {
            url: 'login',
            method: 'post',
            withCredentials: true,
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type': 'application/json'
            }
          },
          logout: {
            url: 'logout',
            method: 'post',
            withCredentials: true,
          },
          user: {
            url: '/api/user',
            method: 'get',
            propertyName: 'user',
            withCredentials: true,
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type': 'application/json'
            }
          },
          home: '/home'
        },
        tokenRequired: false,
        tokenType: false
      }
    }
  },`

**Comment by AndrewSavetchuk** [comment]
Same here! 
Nuxt auth for some reason tries to fetch user when I'm browsing the website as a guest 🤔

Here's my config:
<img width="235" alt="Screen Shot 2020-03-13 at 3 05 12 AM" src="https://user-images.githubusercontent.com/14139435/76580130-862c0700-64d7-11ea-9e9d-3da8af94c2db.png">

**Comment by tiran133** [comment]
Have a look at this might help you with the solution
https://serversideup.net/using-laravel-airlock-with-nuxtjs/

**Comment by dloused** [comment]
same here...


> Nuxt auth for some reason tries to fetch user when I'm browsing the website as a guest 🤔
>

**Comment by brcpar** [comment]
I'm having the same issue as well.  There has to be a better way to see if user is logged in on cookie flow that doesn't involve getting a 401 from the user endpoint.  And with the user endpoint set to false, you're always logged in.  Seems like getting the logged in status in general for the cookie flow is a little off.

**Comment by ryzexsp** [comment]
same here ...

any solution ?

**Comment by pawel-marciniak** [comment]
Same issue here... Can this be even fixed?

**Comment by planetchili** [comment]
Yeah, it seems pretty broken. Glad it's not just me. Disabling the feature altogether and grabbing that data manually seems like a viable workaround at least.

**Comment by JoaoPedroAS51** [comment]
Closing here, as [laravel sanctum provider](https://auth.nuxtjs.org/providers/laravel-sanctum) is now available in auth v5.

**Comment by GanchoDanailov** [comment]
any update on this?

**Comment by JoaoPedroAS51** [comment]
@GanchoDanailov @planetchili @pawel-marciniak @ryzexsp @brcpar @dloused @tiran133 @AndrewSavetchuk 

Hey guys! This issue was already fixed :)

You should use [cookie scheme](https://auth.nuxtjs.org/schemes/cookie), which depends on cookie instead of token. And if you are using laravel sanctum, then I recommend the [laravel sanctum provider](https://auth.nuxtjs.org/providers/laravel-sanctum).

Both are available in auth v5. We now recommend using v5 instead of v4. See [status](https://auth.nuxtjs.org/status) and #893

**Comment by topcoder1208** [comment]
I am running the similar project on my local pc (windows 10).
When I was running this project on my pc, I faced the cors error of wildcard * , and 401 unauthorized error.
How can I solve it?
