### ISSUE TITLE
Disable dataGrantType and dataClientId is refresh token request

### ISSUE THREAD

**Issue by kilakewe** [nuxt-community/auth-module#551]
### What problem does this feature solve?

Some Auth endpoints don't allow extra data to be contained in the request (a.k.a hasura-backend-plus).

### What does the proposed changes look like?

 When setting these values as undefined or even empty in the module configuration section, the module should omit them from the request.  

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c510">#c510</a>)</em></sub></div>

**Comment by kilakewe** [comment]
I was able to achieve the result I wanted by removing dataClientId and dataGrantType from the defaults in lib/schemes/refresh.js, but would like to see it as a configurable option.

**Comment by JoaoPedroAS51** [comment]
@kilakewe Thank you for reporting it! I'll fix this!

**Comment by JoaoPedroAS51** [comment]
@kilakewe Fixed in commits https://github.com/nuxt-community/auth-module/pull/361/commits/f735c3607af1b9c652e505c36e6771392fac50ca and https://github.com/nuxt-community/auth-module/pull/361/commits/fea5fe9f6eb1310366839deb5119b86020e2ff39
