### ISSUE TITLE
 await this.$auth.loginWith('local', ... code not working

### ISSUE THREAD

**Issue by yunchiri** [nuxt-community/auth-module#554]
### Version

[v4.9.0](https://github.com/auth-module/releases/tag/v4.9.0)

### Reproduction link

[https://cmty.app/nuxt/issues/new?type=bug-report&repo=auth-module](https://cmty.app/nuxt/issues/new?type=bug-report&repo=auth-module)

### Steps to reproduce

try {
        let res = await this.$auth.loginWith('local', { data: this.login });
...

catch (error) {
}

before I used feat/refreshtoken => worked
after upgrade 4.9.0

this.$auth.loginWith   not working

i've debugging   auth.js

L:122
  loginWith (name, ...args) {
    return this.setStrategy(name).then(() => this.login(...args))
  }

name parameter always : ""  ( i expect 'local')

### What is expected ?

L:122
  loginWith (name, ...args) {
    return this.setStrategy(name).then(() => this.login(...args))
  }

name parameter always : ""  ( i expect 'local')

### What is actually happening?

L:122
  loginWith (name, ...args) {
    return this.setStrategy(name).then(() => this.login(...args))
  }

name parameter : ''

so return  undefined

### Additional comments?

nuxt.config.js

  auth: {
    cookie: false,
    strategies: {
      local: {
        _scheme: "refresh",
        endpoints: {
          login: { url: "/auth/login", method: "post" },
          refresh: { url: "/auth/refresh", method: "post" },
          logout: false,
          user: false
        },
        token: {
          property: "access_token",
          maxAge: 30
        },
        refreshToken: {
          property: "refresh_token",
          data: "refreshToken",
          maxAge: 90
        },
        clientId: {
          property: "clientId"
        },
        autoRefresh: false
      }
    }
  },

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c512">#c512</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @yunchiri! Refresh support wasn't released in v4.9.0. Please, use dev branch.
