### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by RokasDie** [nuxt-community/auth-module#567]
Hello,

I am fairly new to Nuxt JS and its module Auth. I want to be sure if my application is secure. Currently this is how it works:

my nuxt.congif.js file:
```
 auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: 'api/auth/login',
            method: 'post',
            propertyName: 'user'
          },
          logout: { url: '/api/auth/logout', method: 'post' },
          user: { url: 'api/auth/user', method: 'get' }
        },
        tokenRequired: false,
        tokenType: false,
        autoFetchUser: false
      }
    },
    redirect: { home: '/' }
  },

  /*
   ** Axios module configuration
   ** See https://axios.nuxtjs.org/options
   */
  axios: {
    proxy: true
  },
  proxy: { '/api/': 'http://localhost:4000/' },
```

So the user logins in nuxt application and then I send username and password to the back-end. My back-end is Express JS + Passport JS. I have local Passport strategy which checks if user exists in the database. If the user exists I serialise it and it's id is included in the session. I then send the user id back to nuxt 

Here my knowledge gets weak and I would like some guidance. The responded user id is then held in $auth instance. However, how safe is this instance? Can somebody access it besides my nuxt server? 

Please feel free to tell if some more information would be required.

Regards,
Rokas

**Comment by jeremy21212121** [comment]
Great question! Unfortunately github issues is probably not the place to ask. Its just for issues with the code, not issues you are having using the code. Gitter or IRC would be a better place.

That said, I think you are good. I don't think `client.id` is secret, they [expose it to the user in an example app](https://github.com/passport/express-4.x-local-example/blob/master/views/profile.ejs)  in the repo.

You have the right mindset though! Question everything! You are right to be wary of `$auth`. Check out `$auth.ctx`. That is the context object that is usually only available server-side. When you also use the dotenv module, it adds your whole `.env` file (often full of secrets) to the context object. So using both modules causes the contents of the `.env` file to leak to the client! I think that is bad, but I'm still investigating. (I need check if it still leaks with a prod build, I suspect it does. I also need to do a thorough search of closed issues to make sure it is novel)

I'll be opening a separate issue if my hunch is accurate.

Hack The Planet!
