### ISSUE TITLE
User not saved in the store

### ISSUE THREAD

**Issue by Torone** [nuxt-community/auth-module#568]
### Version

[v4.9.0](https://github.com/auth-module/releases/tag/v4.9.0)

### Reproduction link

[https://google.com](https://google.com)

### Steps to reproduce

I was excited to try the new core feature for response data on `loginWith` method and so I added it to handle messages, etc...
My initial auth configuration  for local users was:

```
      local: {
          [...]
          user: { url: '/me', method: 'GET', propertyName: false }
        },
        [...]
      },
```

I find out that for get response data from `loginWith` I must write something in the `propertyName` and so I added `'user'`. It works.
Unfortunately the user is not saved anymore in the store. I can see the call to my API to fetch the user but the Vue store is empty.
I tried to force it by using `fetchUser` but it doesn't work too.

Any clue?

### What is expected ?

To set the user in the store after login.

### What is actually happening?

The user is not set in the store.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c522">#c522</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @Torone! We just updated the docs! You can use `setUser` right after a successfully login.

Like this:
```js
this.$auth.loginWith('local', { ... }).then(response => {
    this.$auth.setUser(response.data.user)  
})
```

https://auth.nuxtjs.org/api/auth.html#setuser-user

**Comment by Torone** [comment]
Thanks, I missed the `setUser` I was trying to `fetchUser` only. Cheers

**Comment by itgelo** [comment]
> Hi @Torone! We just updated the docs! You can use `setUser` right after a successfully login.
> 
> Like this:
> 
> ```js
> this.$auth.loginWith('local', { ... }).then(response => {
>     this.$auth.setUser(response.data.user)  
> })
> ```
> 
> https://auth.nuxtjs.org/api/auth.html#setuser-user

when reload page userdata disappears, what's the solution?

**Comment by JoaoPedroAS51** [comment]
Hi @itgelo! Can you show me your auth config?

**Comment by itgelo** [comment]
nuxt.config.js
```
...
auth: {
    redirect: {
      home: '/',
      login: '/login',
      logout: '/login',
    },
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/login',
            method: 'post',
            propertyName: 'data.token',
          },
          user: false,
          logout: false,
        },
        tokenRequired: true,
        tokenName: 'Authorization',
        tokenType: 'Bearer',
      },
    },
  },
...
```
Login
```
this.$auth
    .loginWith('local', { data })
    .then(async (res) => {
        const {
            data: { data: user },
        } = res;

        await this.$auth.setUser(user);
    })
    .catch((e) => {
        this.$message.error(
            e.response ? e.response.message : e.message,
        );
    });
```

**Comment by JoaoPedroAS51** [comment]
@itgelo Looking at your config I can see you disabled `user` endpoint by setting it to `false`. To fetch user after reload a page you must define `user` endpoint. And as you are setting the user after a successfully login, add `autoFetchUser: false` to your config.
https://auth.nuxtjs.org/schemes/local.html#autofetchuser

Sorry, I accidentally added `await` to `setUser` example. 😅 You don't need to await `setUser`.

**Comment by JM-Beltran** [comment]
i have a question, what parameter does the endpoint user send in the url to know what to receive in the backend? 
I have been looking for information here in the questions but nothing appears, I would appreciate your help
