### ISSUE TITLE
how to access auth method in vuex getters

### ISSUE THREAD

**Issue by webafra** [nuxt-community/auth-module#570]
hi .

i created user.js file in store directory and write this code on the getters method :

```
export const getters = {
  authenticated(state) {
    // return is loggedIn or not;
    this.$store.state.auth.loggedIn
  },
};

```

How can I do this?
thanks .

**Comment by Trixpua** [comment]
You can access through the rootState, like this:

` authenticated(state, commit, rootState) {
    // return is loggedIn or not;
    rootState.auth.loggedIn
  },`
