### ISSUE TITLE
Auth multiple logins

### ISSUE THREAD

**Issue by imranr970** [nuxt-community/auth-module#571]
Hi I want multiAuth like simple login and loginAsContributor so how will I suppose to do that?
Please someone tell me will be really thankful.

**Comment by imranr970** [comment]
Can't you please answer me or suggest me any article or any helping guide?

**Comment by pi0** [comment]
For sure I would be happy to help @imranr970 :) Initially just moved the issue to a more proper place so others can see and help too. [nuxt discord](https://discordapp.com/invite/ps2h6QT) is also a friendly place for asking for help.

Would you please explain more about your question? Like what is your current stack for backend? And what authentication provider/flow you prefer to use?

**Comment by imranr970** [comment]
I am using Laravel for backend and using jwt api I want I have multiple login options
login for user and login for admin. separate @nuxtjs/auth endpoints for each user.

**Comment by pi0** [comment]
Indeed it is supported by [schemes](https://auth.nuxtjs.org/guide/scheme.html).

In nuxt.config.js you have to define them like this:

```js
  auth: {
    strategies: {
      user: {
        _scheme: 'local',
        endpoints: {
          login: { url: '/api/auth/user/login', method: 'post', propertyName: 'token' },
          logout: { url: '/api/auth/user/logout', method: 'post' },
          user: { url: '/api/auth/user/user', method: 'get', propertyName: 'user' }
        },
      },
      admin: {
        _scheme: 'local',
        login: { url: '/api/auth/admin/login', method: 'post', propertyName: 'token' },
        logout: { url: '/api/auth/admin/logout', method: 'post' },
        user: { url: '/api/auth/admin/user', method: 'get', propertyName: 'user' }
      },

    }
  }
```

And then you can use `this.$auth.loginWith('user', ...)` or `this.$auth.loginWith('admin', ...)`

**Comment by imranr970** [comment]
I am really thankful to you one last question kindly reply this one too please.
How do I redirect each scheme to its specific route on login.
I mean admin login on adminDashboard.vue
userlogin on userLogin.vue

**Comment by StanleyMasinde** [comment]
Hi, @imranr970 This is how I do it.
![image](https://user-images.githubusercontent.com/35426405/85323729-36df7480-b4d1-11ea-8d97-53f09ed273de.png)
I call the redirect method after a successful login

**Comment by CodyBontecou** [comment]
@pi0 Could you please update this answer to work with Nuxt Auth v5.0?

**Comment by maulayyacyber** [comment]
Hi @pi0, can you give sample about redirects for two strategy ? 

thanks very much

**Comment by ashikXpress** [comment]
R

**Comment by DominiqueGarmier** [comment]
> @pi0 Could you please update this answer to work with Nuxt Auth v5.0?

I doubt you are still looking for this, but for anyone else coming across this like myself. [Here](https://auth.nuxtjs.org/guide/scheme/) they talk about it in the docs.

**Comment by TutorFx** [comment]
> Indeed it is supported by [scheme/strategy](https://auth.nuxtjs.org/guide/scheme.html).
> 
> In nuxt.config.js you have to define them like this:
> 
> ```js
>   auth: {
>     strategies: {
>       user: {
>         _scheme: 'local',
>         endpoints: {
>           login: { url: '/api/auth/user/login', method: 'post', propertyName: 'token' },
>           logout: { url: '/api/auth/user/logout', method: 'post' },
>           user: { url: '/api/auth/user/user', method: 'get', propertyName: 'user' }
>         },
>       },
>       admin: {
>         _scheme: 'local',
>         login: { url: '/api/auth/admin/login', method: 'post', propertyName: 'token' },
>         logout: { url: '/api/auth/admin/logout', method: 'post' },
>         user: { url: '/api/auth/admin/user', method: 'get', propertyName: 'user' }
>       },
> 
>     }
>   }
> ```
> 
> And then you can use `this.$auth.loginWith('user', ...)` or `this.$auth.loginWith('admin', ...)`

now there is a new way to do this:
`auth: {
  strategies: {
    local1: { scheme: 'local', /* ... */ },
    local2: { scheme: 'local', /* ... */ },
    custom: { scheme: '~/schemes/customStrategy', /* ... */ },
  }
}`

**Comment by sherlockmac** [comment]
> Indeed it is supported by [scheme/strategy](https://auth.nuxtjs.org/guide/scheme.html).
> 
> In nuxt.config.js you have to define them like this:
> 
> ```js
>   auth: {
>     strategies: {
>       user: {
>         _scheme: 'local',
>         endpoints: {
>           login: { url: '/api/auth/user/login', method: 'post', propertyName: 'token' },
>           logout: { url: '/api/auth/user/logout', method: 'post' },
>           user: { url: '/api/auth/user/user', method: 'get', propertyName: 'user' }
>         },
>       },
>       admin: {
>         _scheme: 'local',
>         login: { url: '/api/auth/admin/login', method: 'post', propertyName: 'token' },
>         logout: { url: '/api/auth/admin/logout', method: 'post' },
>         user: { url: '/api/auth/admin/user', method: 'get', propertyName: 'user' }
>       },
> 
>     }
>   }
> ```
> 
> And then you can use `this.$auth.loginWith('user', ...)` or `this.$auth.loginWith('admin', ...)`

In the documentation the scheme part is different.

I had issues with `scheme: 'local'` from documentation and when changed to `_scheme: 'local'` the issue was gone.
