### ISSUE TITLE
Can not make Auth module works with refresh token - the module losts strategy

### ISSUE THREAD

**Issue by axel-verse** [nuxt-community/auth-module#572]
### Version

[v4.9.0](https://github.com/auth-module/releases/tag/v4.9.0)

### Reproduction link

[https://github.com/axel-verse/nuxt-auth-bug](https://github.com/axel-verse/nuxt-auth-bug)

### Steps to reproduce

1) Setup Auth module as it described in https://github.com/nuxt-community/auth-module/pull/361
2) Try to use $auth.loginWith at any page

### What is expected ?

Successfull login

### What is actually happening?

TypeError: Cannot read property 'mounted' of undefined
    at Auth.mounted (auth.js?facc:112)
    at Auth.setStrategy (auth.js?facc:108)
    at Auth.loginWith (auth.js?facc:123)
    at VueComponent.doLogin (index.vue?6ced:21)
    at click (index.vue?d50a:53)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)

### Additional comments?

Any help is appreciated

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c523">#c523</a>)</em></sub></div>

**Comment by martijnd** [comment]
Had the same problem, I think the npm version goes off the master branch, while the dev branch has the refresh support added... I fixed it by changing ```"@nuxtjs/auth": "^4.9.0",``` to ```"@nuxtjs/auth": "nuxt-community/auth-module#dev",``` in package.json... at least until the dev is synced with master.

**Comment by axel-verse** [comment]
@martijnd, thanks you for you help, your solution works for me. 

So for now all that left is wait for sync

**Comment by axel-verse** [comment]
The issue was solved at GitHub

**Comment by chris-aeviator** [comment]
> @nuxtjs/auth": "nuxt-community/auth-module#dev",

when changing my package.json to this, delete `@nuxtjs-auth` from `node_modules` and run `yarn install` no nuxt auth module is installed, running nuxt fails with a module not found for nuxt auth

**Comment by JoaoPedroAS51** [comment]
Hi @chris-aeviator! That answer is outdated.
We published the `dev` branch as `@nuxtjs/auth-next`. Just run `yarn add @nuxtjs/auth-next` :)

**Comment by chris-aeviator** [comment]
Ok – I was unsure if both were the same thing thanks for clarification
