### ISSUE TITLE
Security issue with vuex store integration

### ISSUE THREAD

**Issue by 1isten** [nuxt-community/auth-module#583]
### Version

[v4.9.0](https://github.com/auth-module/releases/tag/v4.9.0)

### Reproduction link

[#](#)

### Steps to reproduce

Open the browser console, enter:

`$nuxt.$store.state.auth.user = { some fake value };` (optional)

`$nuxt.$store.state.auth.loggedIn = true;`

### What is expected ?

The value of `$store.state.auth.user`, `$store.state.auth.loggedIn`, etc.. should not be mutated by console.

### What is actually happening?

The login state is changed to `true`! And I can now access any "secret" page.

### Additional comments?

I'm not sure its a bug of the auth module or nuxt itself. As nuxt exposes `$nuxt` instance to the console, its very danger that user can access vuex values and mutate it directly through the console.

If its a bug of nuxt, please let me know if it is necessary to open a new issue on the nuxt repo.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c531">#c531</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi, @1isten thanks for creating the issue.

Indeed any possible implementation of the auth module or nuxt project, if someone has access to the console can mutate state also cookies and LS. It is the nature of client-side javascript. You can do whatever you want. Also even not exposing `$nuxt`, one can easily get a ref to vue instance by DOM and access nuxt, router, and store! (same method as Vue Devtools works)

I think best would be not bundling important stuff in client bundle and fetching such data from API.

**Comment by 1isten** [comment]
Hi @pi0 , thanks for your reply. Actually I've tried to to mutate those values through `$nuxt.$store.$auth.loggedIn` and `$nuxt.$auth.loggedIn`, both won't work. Maybe the `$auth` is proxied or defined via `Object.defineProperties`? I really think the `$store.state.auth` should be protected the same way. Or it would be nice to put some information on the docs to remind developers that:

Instead of using 

```html
<div v-if="$store.state.auth.loggedIn">
    <!-- some contents that should only visible by logged in users -->
<div>
```

maybe

```html
<div v-if="$auth.loggedIn">
    <!-- some contents that should only visible by logged in users -->
<div>
```

would be safer?

**Comment by 1isten** [comment]
My main concern is when the `$store.state.auth.loggedIn` is set to `true` via console, the auth middleware becomes useless - all the routes with `middleware: auth` will become accessible. 

As for the Vue Devtools, it is not available in `production` mode so the end user can't alter vuex state.

**Comment by MrJmpl3** [comment]
> 
> 
> My main concern is when the `$store.state.auth.loggedIn` is set to `true` via console, the auth middleware becomes useless - all the routes with `middleware: auth` will become accessible. Is the middleware redirection mechanism based on `$store.state.auth.loggedIn`? If so, will it be better to change it to base on `$auth.loggedIn`?
> 
> As for the Vue Devtools, it is not available in `production` mode so the end user can't alter vuex state.

A good practice in the backend check the auth with the error code 403.
The error 403 inform to the frontend: "Forbidden, need auth!"

**Comment by 1isten** [comment]
@MrJmpl3 Sure, but in case of just by typing `$nuxt.$store.state.auth.loggedIn = true` in console won't trigger any further request for the backend to check. If a page is previously protected by an auth middleware, it will be exposed immediately.  For example: 

if I have:

1). a `/login` page with `middleware: 'auth'` + `auth: 'guest'`
2). a `/dashboard` page with `middleware: 'auth'`

and if the `auth.redirect` config is like:

```js
// nuxt.config.js

export default {
  auth: {
    redirect: {
      login: '/login', // if unauthenticated, redirect /dashboard to /login
      home: '/dashboard',  // if authenticated, redirect /login to /dashboard
    },
  },
};
```

then suppose an unauthenticated user is on`/login`, by simply type `$nuxt.$store.state.auth.loggedIn = true` in console will redirect the user to `/dashboard` immediately without any request.

I know important stuff should only be fetched via sending request to the backend, but just exposing the pages (UI details) which are not supposed to be seen by a guest makes me feel uncomfortable..

**Comment by MrJmpl3** [comment]
Oh! I understand, your suggest when change the page and that page has auth middleware, the module check 'loggedIn' was changed to true so execute fetchUser ..

**Comment by MrJmpl3** [comment]
@pi0 can be a good idea to future versions?

**Comment by pi0** [comment]
Indeed, using `$auth.loggedIn` instead of `$auth.state` and not using the store is the preferred approach. Vuex integration will be deprecated in v5 and only possible with a plugin.

But it doesn't change the fact SSR applications after hydration, are SPAs. Anything that you can do to make browser (not API) thinking user is authenticated via context if someone has access to the console or can inject javascript, can do too. In other words, when you load the page, all `.js` chunks can be downloaded which contain code to render any secret page. Worst case one can download and patch them to bypass. One can still use `$auth.setUser`

> As for the Vue Devtools, it is not available in production mode so I think the end-user can't alter vuex state.

It is disabled by intention but the method can be always used: ([actual implementation](https://github.com/vuejs/vue-devtools/blob/dev/packages/shell-chrome/src/detector.js#L31))

```js
document.querySelector('#__layout').__vue__.$root
```

> Can it be a good idea to future versions?

@MrJmpl3 Of course :) If we can do any attempt to make it harder but not affecting DX and Performance. Any ideas welcome.

**Comment by 1isten** [comment]
Thanks @pi0 , that's good to know.
