### ISSUE TITLE
Extending auth module for usage of company proxy server

### ISSUE THREAD

**Issue by mpgalaxy** [nuxt-community/auth-module#584]
### What problem does this feature solve?

Currently the auth module can't make use of a company proxy server, resulting in timeout with external identity provider(e.g. keycloak).

### What does the proposed changes look like?

I would like to extend the auth module with a custom proxy config for axios, thus being able to access external identity providers via the company proxy.
I already started with the base structure. Maybe you can give me a hint how to continue...:
```javascript
export default function({ $auth }) {
  if (!$auth.loggedIn) {
    return
  }
  
  require('dotenv').config()

  if (process.env('COMPANY_HTTP_PROXY')) {
    const axios = require('axios')
    const HttpsProxyAgent = require('https-proxy-agent')
    const agent = new HttpsProxyAgent(process.env('COMPANY_HTTP_PROXY'))

    const customAxiosConfig = {
      url: currentAxiosUrl,    // this should be a dynamic value, depending on the url the auth module is trying to reach via axios
      httpsAgent: agent
    }
    axios.request(customAxiosConfig).then((...)) // the custom axios config for usage with the auth module should be set here

  }
}
```
How can I accomplish that ?
Please help.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c533">#c533</a>)</em></sub></div>

**Comment by mpgalaxy** [comment]
Maybe this might work ?
```javascript
export default function({ $auth, $axios }) {
  if (!$auth.loggedIn) {
    return
  }

  
  if (process.env.COMPANY_HTTP_PROXY) {
    const HttpsProxyAgent = require('https-proxy-agent')
    const agent = new HttpsProxyAgent(process.env.COMPANY_HTTP_PROXY)

    $axios.onRequest((config) => {
      config.httpsAgent = agent
    })
  }
}
```

**Comment by pi0** [comment]
Hi. Proxy is out of auth-module scope. Please see https://github.com/nuxt-community/proxy-module/issues/66#issuecomment-607730172
