### ISSUE TITLE
unsupported_grant_type with laravel.passport strategy

### ISSUE THREAD

**Issue by devondahon** [nuxt-community/auth-module#590]
### Version

[v4.9.0](https://github.com/auth-module/releases/tag/v4.9.0)

### Steps to reproduce

I'm using Laravel 7.3 with Passport.

In `nuxt.config.js`:
```
    strategies: {
      'laravel.passport': {
        url: 'http://laravel.test',
        client_id: 2,
        client_secret: 'S0gpcgfIDgbvIHCL3jIhSICAiTsTUMOR0k5mdaCi'
      },
    }
```
In `pages/index.vue`:
```
methods: {
    async login () {
      await this.$auth.loginWith('laravel.passport')
    }
  }
```

### What is expected ?

When I click on the login button executing the `login` method, I'm redirected to laravel's login page, then I fill username and password, finally I should get registered and redirected back to my Nuxt redirection page.

### What is actually happening?

But instead, I'm not redirected to Nuxt redirection page and I get the following error message in Laravel:
```
{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided","message":"The authorization grant type is not supported by the authorization server."}
```

If I add `redirect_uri: 'http://localhost:3000'` to the `laravel.passport` strategy, then Laravel returns `code` and `state` parameters, but then I'm not sure what I should do with it. If I send it back with a second method like this:
```
    async sendCode () {
      await this.$auth.loginWith('laravel.passport', {
        code: this.$route.query.code,
        state: this.$route.query.state
      })
    }
```
Laravel is sending back new `code` and `state` value.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c537">#c537</a>)</em></sub></div>

**Comment by piotrkulpinski** [comment]
@devondahon Did you manage to fix the issue? I'm having a similar issue and wondering how did you solve it.

**Comment by JoaoPedroAS51** [comment]
Hi @piotrkulpinski! Can you show me your auth config?

**Comment by devondahon** [comment]
@piotrkulpinski Yes, I finally fixed it thanks to @pi0 and @JoaoPedroAS51. You can check my config and help from @JoaoPedroAS51 in [this post](https://github.com/nuxt-community/auth-module/issues/505).
