### ISSUE TITLE
Call to refresh token endpoint requires refresh token in response

### ISSUE THREAD

**Issue by jseitel** [nuxt-community/auth-module#592]
It appears that the new refresh scheme (for the local strategy) expects/requires the refresh token to be present in the response from the refresh backend endpoint.  Very commonly (if not by convention), endpoints to refresh one's access token only include the access token, not the refresh token. For example, django-rest-framework-simplejwt works this way.

Here's the relevant snippet of code (in refresh.js, starting line 151):

```
   // Make refresh request
    return this.$auth.requestWith(
      this.name,
      endpoint,
      this.options.endpoints.refresh,
      true
    ).then(({ response, data }) => {
      // Update tokens
      this.$auth.token.set(getProp(data, this.options.token.property))
      this.$auth.refreshToken.set(getProp(data, this.options.refreshToken.property))
      // Update client id
      const clientId = getProp(data, this.options.clientId.property)
      if (this.options.clientId && clientId) {
        this._setClientId(clientId)
      }
      return response
    })
```

The problem is line 160, specifically:
`this.$auth.refreshToken.set(getProp(data, this.options.refreshToken.property))`

In my case, `data` resolves to something like this:

`{"access":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3BrIjoxLCJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiY29sZF9zdHVmZiI6IuKYgyIsImV4cCI6MTIzNTY3LCJqdGkiOiJjNzE4ZTVkNjgzZWQ0NTQyYTU0NWJkM2VmMGI0ZGQ0ZSJ9.ekxRxgb9OKmHkfy-zs1Ro_xs1eMLXiR17dIDBVxeT-w"}`

Since there's no refresh token in the response, I can't set `refreshToken.property` to anything.  If I do, it's not found, and `getProp` will unset the value (which means I'm logged out as soon as my new access token expires). If I set `refreshToken.property` to false, then it does get set, but to the wrong value (the entire response body).

Possible solutions I can think of:

* Use a custom scheme that removes line 160 (I will probably do this as a stopgap in the near-term)
* Remove the call to `this.$auth.refreshToken.set` on line 160 (like I said, I *think* the standard behavior is not to include the refresh token in the response anyway)
* Put the call to `this.$auth.refreshToken.set` behind a setting that can be flipped in options

Thoughts? I'm happy to take a crack at a PR if we want to make a change to support this.

cc/ @pi0 (P.S. thank you for all the hard work on the feature branch for this!!)

**Comment by JoaoPedroAS51** [comment]
Hi @jseitel! Yeah you're right. This should be optional. I'll open a PR to fix this issue. I'm just not sure when it will be merged since dev branch is under a big refactor.

At the meantime you can solve this issue by setting the refresh token property to the same value as token property in your auth config.

**Comment by jseitel** [comment]
Awesome, thanks @JoaoPedroAS51!

Unfortunately the workaround doesn't quite work - if I set it to be the same as the token property, I end up setting refresh token to the access token (wrong type, gets rejected by the backend).

I did a quick fork of the repo and removed line 160 for my purposes. I should be good to go until the PR makes it to dev branch.

Thank you!

**Comment by JoaoPedroAS51** [comment]
@jseitel Oh yeah now I see, sorry I misread :sweat_smile:
