### ISSUE TITLE
Send user email with token

### ISSUE THREAD

**Issue by shayani** [nuxt-community/auth-module#605]
I'm using Rails Simple Token Authentication as API and I can sucefully validate the username and password with Auth modulo, but, to get the any other information from the API, I always need to send user_token and user_email. 

I managed to set user_token with `tokenName: 'user_token',` but how do I set se always send the user_email too?

**Comment by MrJmpl3** [comment]
I don't understand this, can upload some examples of the code?

I think use axios interceptors

**Comment by shayani** [comment]
The gem Simple Token Authentication, for Rails + Devise requires 2 infos: `user_token` and `user_email` in headers.
Does Axios Interceptors can add a new header to the request?

**Comment by JoaoPedroAS51** [comment]
Hi @shayani! Yes, you can add a new header to the request using Axios Interceptors. 

Something like this:
```js
this.$axios.onRequest(config => {
  config.headers.user_email = 'your@email.com'
  return config
})
```

Alternatively you can add a new header using axios `setHeader`.
`this.$axios.setHeader('user_email', 'your@email.com')`.

**Comment by shayani** [comment]
Thank you @JoaoPedroAS51
