### ISSUE TITLE
Auth: false prevent redirect after login

### ISSUE THREAD

**Issue by jasonlyu123** [nuxt-community/auth-module#607]
https://github.com/nuxt-community/auth-module/blob/85466345311bf882ae2f603ba43ef1dc638d2cdb/lib/core/auth.js#L58

The problem is with this line. It check whether current page enable `auth middleware` to see if you have right to stay on current page when logout. But I can't figure out the point of this check when login. 

When I remove `auth: false` on page's option , or use `auth: 'guest'` the redirect works.

It make sense to think you would have to disable `auth middleware` to prevent infinite redirect on login page. But you actually don't have to do that. And when you disable it, it'll prevent the redirect. It not a straightforward behavior.  

Can any person of the core team explain why this check is necessary while login or it's a bug?  

If the check is necessary, maybe add a note to the docs about you can't disable `auth middleware` in login page. If it's a bug. How to fix it is a problem, just disable the check in login would result in different redirect page if the fallback redirect dev added after login is different.

_Originally posted by @jasonlyu123 in https://github.com/nuxt-community/auth-module/issues/437#issuecomment-582748421_

The discussion of the origin issue is kind of all over the place, so I open this issue to **focus on this specific issue**. If this is not a expected behavior, the potential fix of this could be ship with v5 as breaking changes.

**Comment by jasonlyu123** [comment]
[example repo](https://github.com/jasonlyu123/nuxt-auth-false-example)

**Comment by jasonlyu123** [comment]
I read though the middleware section of the doc again. I guess this is the expected behavior. I'll just make a PR to make it more clear.

**Comment by MrJmpl3** [comment]
I think, the `auth: false` is unneccesary in the docs.

- If you don't need auth in page, don't add the middleware
- If you need only guest, add `auth: 'guest'`

Why exists `auth: false`?

**Comment by jasonlyu123** [comment]
Agree, `auth: guest` should be preferred. `auth: false` should not exist or should only be used in edge cases. It confused me a lot.
