### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content error in refresh authenticated page

### ISSUE THREAD

**Issue by mohammadreza-soft74** [nuxt-community/auth-module#610]
hi.
i logged in successfully and get token and user but when i redirect to authenticated page and then refresh page redirect me to login page. 
`
 
     
     auth:{

      strategies:{

          local:{

              endpoints:{

                  login:{ url: '/login', method: 'post', propertyName: 'data.token' },
                  logout:{ url: '/logout', method: 'get' },
                  user:{ url: '/user', method: 'get', propertyName: false}
              },

              tokenName:'Authorization',
               tokenRequired:true,
              tokenType:'Bearer',
              //watchLoggedIn:false,
              // autoFetchUser:true
          }
      },
      

      redirect:{

          login:'/auth/login',
          home:'/',
          logout:'/auth/login'
      }
      }
`

**Comment by manniL** [comment]
[This post](https://blog.lichter.io/posts/vue-hydration-error/) should help you ☺️
