### ISSUE TITLE
not respecting header settings, sending only json on local login scheme

### ISSUE THREAD

**Issue by wedwardbeck** [nuxt-community/auth-module#616]
### Version

[v4.9.0](https://github.com/auth-module/releases/tag/v4.9.0)

### Reproduction link

[https://github.com/wedwardbeck/nuxt-auth-vs-axios-form-issue](https://github.com/wedwardbeck/nuxt-auth-vs-axios-form-issue)

### Steps to reproduce

In reference to issue 323 (https://github.com/nuxt-community/auth-module/issues/323) and following the direction in issue 41 (https://github.com/nuxt-community/auth-module/issues/41) to send login to my API as form data, not json.

Using this change, the header content type shows "application/x-www-form-urlencoded" but the Form Data shows malformed json data.  This results in a 422 error in return from the API. When changing the method to use axios, the API call works fine and shows the Form Data as expected in DevTools. I've verified via Postman and Insomnia as well, so the issue seems to be with nuxt-auth, and how it sends the data.

Using nuxt-auth, the request headers says:
Content-Type: application/x-www-form-urlencoded

The Form Data shows:
{"username":"bob@gmail.com","password":"notreallyme"}:

Using axios headers say:
Content-Type: application/x-www-form-urlencoded

The Form Data shows:
username: bob@gmail.com
password: notreallyme

### What is expected ?

Expected to have form data sent when header config is "application/x-www-form-urlencoded".  

Request should show:
Form Data
username: bob@gmail.com
password: notreallyme

### What is actually happening?

Request sends malformed json in body when header Content Type is set to "application/x-www-form-urlencoded".  Field names are quoted and an extra colon is after json object (unsure either should be expected). 

The Form Data shows:
{"username":"bob@gmail.com","password":"notreallyme"}:

Default settings w/json body show (to show difference from result above):
The Form Data shows:
{username: "bob@gmail.com",password: "notreallyme"}

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c548">#c548</a>)</em></sub></div>

**Comment by ionut-tanasa** [comment]
I just literally stumbled upon this issue.

Any workarounds in the meanwhile?

**Comment by wedwardbeck** [comment]
The current workaround is to just use the axios call and not the auth
module. I haven't worked on updating the auth store as it would be done in
the auth module, but am hoping that can be done so reverting to use auth
fully once fixed will not be a chore.

**Comment by JoaoPedroAS51** [comment]
Hi @wedwardbeck! I tested your reproduction repo. You can simple pass the `FormData` to `loginWith` as you did in axios.

```js
const form = new FormData()
form.append("username", this.username)
form.append("password", this.password)
await this.$auth.loginWith('local', {
  data: form
})
```

**Comment by wedwardbeck** [comment]
@JoaoPedroAS51 thank you! That was the fix to get working - sorry I thought I had tried that variation.   
Thanks again for the help.
