### ISSUE TITLE
Authorization Token wrongly saved as Bearer [object Object]

### ISSUE THREAD

**Issue by mjzarrin** [nuxt-community/auth-module#618]
I have created a new project very similar to [demo](https://github.com/nuxt-community/auth-module/tree/dev/examples/demo) in examples.
the API provides tokens correctly, However, instead of token value, the token type is set for Authorization.

<img width="1680" alt="Screen Shot 2020-04-17 at 09 34 18" src="https://user-images.githubusercontent.com/1506712/79534223-3e2c7100-808f-11ea-8ee5-6fa69a06ab4a.png">
<img width="1680" alt="Screen Shot 2020-04-17 at 09 34 57" src="https://user-images.githubusercontent.com/1506712/79534244-4b496000-808f-11ea-9d0a-abf07395bf57.png">

Server Error : 
` 
ERROR  Format is Authorization: Bearer [token]                                                                                                                          05:10:48

  at middleware (node_modules/express-jwt/lib/index.js:70:21)
  at node_modules/express-unless/index.js:47:5
  at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (node_modules/express/lib/router/index.js:317:13)
  at node_modules/express/lib/router/index.js:284:7
  at Function.process_params (node_modules/express/lib/router/index.js:335:12)
  at next (node_modules/express/lib/router/index.js:275:10)
  at jsonParser (node_modules/body-parser/lib/types/json.js:110:7)
  at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (node_modules/express/lib/router/index.js:317:13)
  at node_modules/express/lib/router/index.js:284:7
  at Function.process_params (node_modules/express/lib/router/index.js:335:12)
  at next (node_modules/express/lib/router/index.js:275:10)
  at cookieParser (node_modules/cookie-parser/index.js:71:5)
  at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (node_modules/express/lib/router/index.js:317:13)
`

**Comment by JoaoPedroAS51** [comment]
Hi @mjzarrin! Can you show me your auth config?

**Comment by mjzarrin** [comment]
> Hi @mjzarrin! Can you show me your auth config?

Yeah, sure, Im using  "@nuxtjs/auth": "^4.9.1" and here is the auth config part in the nuxt.config.js.

> modules: [
    '@nuxtjs/axios',
    '@nuxtjs/dotenv',
    '@nuxtjs/auth'
  ],
 axios: {
    proxy: true
  },
  proxy: {
    '/api': 'http://localhost:3000'
  },
  auth: {
    redirect: {
      callback: '/callback',
      logout: '/signed-out'
    },
    strategies: {
      local: {
        token: {
          property: 'token.accessToken'
        }
      },
      localRefresh: {
        _scheme: 'refresh',
        token: {
          property: 'token.accessToken',
          maxAge: 15
        },
        refreshToken: {
          property: 'token.refreshToken',
          data: 'refreshToken',
          maxAge: false
        },
        clientId: {
          property: 'token.clientId',
          data: 'clientId'
        },
        grantType: {
          data: 'grantType'
        },
        autoRefresh: true
      }
    }
  },
  serverMiddleware: ["~/api/auth"]

**Comment by JoaoPedroAS51** [comment]
Thanks! So, you are receiving this error because this config is from dev branch that will be used for v5.

For v4.9.1 you should follow this [demo](https://github.com/nuxt-community/auth-module/tree/master/examples/demo)
```
auth: {
    redirect: {
      callback: '/callback',
      logout: '/signed-out'
    },
    strategies: {
      local: {
        endpoints: {
          login: { propertyName: 'token.accessToken' }
        }
      }
    }
  },
```
 
**Note:** Refresh tokens aren't supported yet. If you need it for your project, then use dev branch instead of changing your config to the example above. To do so, add `"@nuxtjs/auth": "nuxt-community/auth-module#dev"` to your `package.json`.

You can see the new docs at https://dev.auth.nuxtjs.org/

**Comment by mjzarrin** [comment]
@JoaoPedroAS51 ,
That's works.
Thank you so much!
