### ISSUE TITLE
Refresh scheme not working

### ISSUE THREAD

**Issue by bramburn** [nuxt-community/auth-module#619]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://www.textbin.online/TsNoZnOROV](https://www.textbin.online/TsNoZnOROV)

### Steps to reproduce

Hello,
once you setup vuex, auth and axios. If I define the `_scheme:'refresh'` it does not generate the correct code in the `auth/plugins.js` or copies over the `auth/scheme/refresh.js`
![auth-conf.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/1652fd20-80a8-11ea-a290-a73e3cd0693f.png)
![file structure.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/1f99b6d0-80a8-11ea-a290-a73e3cd0693f.png)

this is the `plugins.js`
https://pastebin.com/WYa8WgHT

it only shows the local when it generates the `npm run dev` or `yarn dev`.

### What is expected ?

To import the `refresh.js` scheme in `auth/scheme/` folder.
Also creates a strategy `local1` but it is only showing local scheme.

### What is actually happening?

not copying the refresh.js
but I can add my own custom schemes using the source links
does not register the new `local1` if I assigned `_scheme:'refres'`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c550">#c550</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi! Refresh support wasn't released yet. It will be added on v5 , but you can use dev branch until then. Add `"@nuxtjs/auth": "nuxt-community/auth-module#dev"` to your `package.json`.

You can see the new docs at https://dev.auth.nuxtjs.org/

**Comment by bramburn** [comment]
haha! I'm such an idiot!?!!!!!
thanks just done so i'll play around with it later.
Regards,


B.Ramburn BSc LLM#
Snr. Quantity Surveyor
