### ISSUE TITLE
Registration and password recovery 

### ISSUE THREAD

**Issue by DudaevAR** [nuxt-community/auth-module#623]
### What problem does this feature solve?

Single interface for registration, login and password recovery.
Now you need to send a second request for login after registration.
But tokens can come already at registration/password recovery.

### What does the proposed changes look like?

it doesn't look complicated:
- add new endpoints
- reuse login logic
These methods will differ from login only by endpoint.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c552">#c552</a>)</em></sub></div>

**Comment by bramburn** [comment]
i think this is beyond the scope of the Auth. Auth is only for authentication, as each system or app would have their own password recovery method, email, secret key, etc...

**Comment by DudaevAR** [comment]
Is there a way to customize scheme without fork?

**Comment by bramburn** [comment]
can you explain the step by step or draw a flow diagram that shows the password recovery? most Auth backend does not provide password recovery using the same api endpoint.

**Comment by MrJmpl3** [comment]
I saw the scheme custom in the docs:

https://auth.nuxtjs.org/guide/scheme.html
