### ISSUE TITLE
Add domain option for cookie

### ISSUE THREAD

**Issue by redfish31** [nuxt-community/auth-module#64]
Hi,

It's possible to add an option "domain" for the cookie please ?
Example : 
`cookie: {
  name: 'token',
  options: {
    domain: '.example.com'
  }
}`

With this option, the cookie is valid for all subdomains (like : www.example.com, example.com and other.example.com).

Thx :)

**Comment by pi0** [comment]
Hi. It is already possible. Any option in `cookie.options` will be directly passed to [js-cookie](https://www.npmjs.com/package/js-cookie#domain). Maybe we need to clarify this fact in the docs.

**Comment by phips28** [comment]
I know this is an old thread, but in the docs (https://auth.nuxtjs.org/api/options#cookie) it says:
> domain - domain (and by extension subdomain/s) where the cookie is visible. **Default is domain and all subdomains.**

But thats not true, its not default to all subdomains `.domain.com` instead it uses full domain `www.domain.com`.
