### ISSUE TITLE
Got error when install from branch dev v5

### ISSUE THREAD

**Issue by Calion54** [nuxt-community/auth-module#642]
### Version

Dev v5

### Steps to reproduce

When I install the modules from the dev branch, I put this one in my package.json and I run npm i
```
"@nuxtjs/auth": "github:nuxt-community/auth-module#dev"
```

In my nuxt.config.js. I put : 
<img width="259" alt="Capture d’écran 2020-04-24 à 8 56 58 PM" src="https://user-images.githubusercontent.com/15995915/80247319-25632300-866e-11ea-8781-f313cc955a83.png">

### What is expected ?

![Capture d’écran 2020-04-24 à 8 48 05 PM](https://user-images.githubusercontent.com/15995915/80246555-e7b1ca80-866c-11ea-967b-76154039fd17.png)

Do you have an idea ?

**Comment by pi0** [comment]
Hi @Calion54 It is because we migrated to typescript. Will add CI/CD script to publish nightly versions

**Comment by Calion54** [comment]
Hi @pi0 thanks for you answer. Do you have a date for it to be operational?

**Comment by menthol** [comment]
install `#ab927f6557124802003f87a8c5da9af905ea94bd` instead of `#dev`

ex:
```
yarn add nuxt-community/auth-module\#ab927f6557124802003f87a8c5da9af905ea94bd
```

**Comment by Calion54** [comment]
Thanks you so much @menthol. I will use this version for now.

**Comment by JoaoPedroAS51** [comment]
Hey guys! Now dev branch can be installed using `@nuxtjs/auth-next` :)

**Comment by radudiaconu0** [comment]
i get this error now =(
Template src not found: /home/radu/Desktop/logintest/node_modules/@nuxtjs/auth-next/templates/plugin.js

**Comment by JoaoPedroAS51** [comment]
Solved. ;)

**Comment by cardaddy** [comment]
Hi guys, I'm getting the following error when trying to load from dev. 

 ✖ Nuxt Fatal Error                                                                                                   │
   │                                                                                                                        │
   │   Error: Module `@nuxtjs/auth-next` not found. Please ensure `@nuxtjs/auth-next` is in `dependencies` and installed.  

I'm using

modules: [
    '@nuxtjs/auth-next',
  ],

and 

"dependencies": {
"@nuxtjs/auth-next": "github:nuxt-community/auth-module#dev",
}

thoughts?

**Comment by JoaoPedroAS51** [comment]
Hi @cardaddy! This error is because you're setting to dev branch instead of a version. Use `npm install @nuxtjs/auth-next --save` or `yarn add @nuxtjs/auth-next` to get the latest version.

**Comment by cardaddy** [comment]
Hi @JoaoPedroAS51, I don't appear to be seeing the auth/core/ packages in the .nuxt folder, am I missing a step? I'm using modules @nuxtjs/auth-next`` along with the npm install. I see auth-next in node_modules along with the files nested within dist.

**Comment by JoaoPedroAS51** [comment]
@cardaddy In v5 we don't move core files to .nuxt anymore.

**Comment by cardaddy** [comment]
@JoaoPedroAS51 I guess that would explain why I can't find it. I'm trying to use this code, https://github.com/nuxt-community/auth-module/blob/dev/docs/schemes/oauth2.md however it doesn't appear to be in the current production version. Should I create a new issue?

**Comment by JoaoPedroAS51** [comment]
You can use it. What are you trying to use `oauth2` scheme or create a custom scheme that extends `oauth2` scheme?

**Comment by JoaoPedroAS51** [comment]
Can you show me your auth config?

**Comment by cardaddy** [comment]
oauth2. I needed the token refresh capability and when using the strategy below I was getting undefined with the endpoints in v4.9.1. After looking at the oauth module in v4.9.1 I didn't see the updated oauth2 code. I attempted using the dev version, but ran into a different issue where it's attempting to want to set the grant type as implicit. Any suggestions?

```

    strategies: {
      // local: false,
      hri: {
        scheme: 'oauth2',
        endpoints: {
          authorization: 'http://localhost:8080/portal/auth/oauth/authorize',
          token: `http://localhost:8080/portal/auth/oauth/token`,
          userInfo: 'http://localhost:8080/portal/auth/api/users/me',
          logout: 'https://example.com/logout'
        },
        token: {
          property: 'access_token',
          type: 'Bearer',
          maxAge: 1800
        },
        refreshToken: {
          property: 'refresh_token',
          maxAge: 60 * 60 * 24 * 30
        },
        responseType: 'token',
        grantType: 'authorization_code',
        accessType: 'code',
        redirectUri: process.env.BASE_URL + '/portal/login',
        clientId: 'clientId',
        scope: ['user_info'],
        state: 'test',
      }
```

**Comment by cardaddy** [comment]
@JoaoPedroAS51 I was able to resolve my issues and get things working. Any time table when v5 will make it's way into a stable release? Also is there any sort of auto logout function with the oauth2 scheme? Thanks for the help.

**Comment by JoaoPedroAS51** [comment]
Hi @cardaddy! I'm happy to know you were able to solve the issue! Can you tell me what happened? :)

We are working hard to release v5 as soon as possible. I can't tell you a date yet, but as soon as we release I let you know. We are currently working on PKCE support and Ky integration.

Oauth2 scheme don't have auto logout, but that's a good idea! I'll implement that. ;)

**Comment by cardaddy** [comment]
@JoaoPedroAS51 I had responseType set to token rather than code and our frontend developer had a bug in his security code on the landing page. Does localStorage do anything anymore? New configuration that works perfectly, see below.


```
  auth: {
    localStorage: false,
    redirect: {
      logout: '/signed-out',
      home: '/portal/'
    },
    strategies: {
      hri: {
        scheme: 'oauth2',
        endpoints: {
          authorization: '/portal/auth/oauth/authorize',
          token: `/portal/auth/oauth/token`,
          userInfo: '/portal/auth/api/users/me',
        },
        redirectUri: process.env.BASE_URL + '/portal/login',
        responseType: 'code',
        grantType: 'authorization_code',
        clientId: 'clientId',
        scope: ['user_info'],
        state: 'test'
      }
    }
  },
```
Any issues using the dev version in a prod env now? We just really need to refresh token. 

Auto logout would be really nice when the refresh token expires. That would be a great addition. 

Thanks for all your work.

**Comment by JoaoPedroAS51** [comment]
@cardaddy Thanks!

We sync storage data between localStorage and cookies. But it's optional.
Cookies are required for SSR projects as we can't access localStorage in Server Side.
localStorage is mostly used for SPA projects that don't want cookies.

I didn't test the latest versions in prod env yet. I'll make some test soon and let you know.

**Comment by cardaddy** [comment]
@JoaoPedroAS51 keep me posted on the auto logout feature as well. Thank you!

**Comment by JoaoPedroAS51** [comment]
@cardaddy Just opened the PR #657

**Comment by JoaoPedroAS51** [comment]
@cardaddy Auto logout has been merged. You can update the package :)

**Comment by cardaddy** [comment]
@JoaoPedroAS51 you are the man! Thanks so much!
