### ISSUE TITLE
Error in loading latest build

### ISSUE THREAD

**Issue by sarfarazengglb** [nuxt-community/auth-module#646]
Compiled successfully but unable to run

Failed to show Nuxt.js app after 5 reloads
Your Nuxt.js app could not be shown even though the webpack build appears to have finished.

Try to reload the page manually, if this problem persists try to restart your Nuxt.js dev server.

**Comment by menthol** [comment]
install `#ab927f6557124802003f87a8c5da9af905ea94bd` instead of `#dev`

ex:
```
yarn add nuxt-community/auth-module\#ab927f6557124802003f87a8c5da9af905ea94bd
```

**Comment by sarfarazengglb** [comment]
after adding it is working thanks
