### ISSUE TITLE
Cookie's maxAge reset every refresh

### ISSUE THREAD

**Issue by pisethx** [nuxt-community/auth-module#650]
The auth._token.local in cookie has maxAge of 24h. However, every browser's refreshes would set it to the next 24h. I expect it to persist for 24h and not for 24h since the website last reloads.

nuxt.config.js

`auth: {
    localStorage: false,
    cookie: {
      options: {
        maxAge: 60 * 60 * 24
        // secure: true
      }
    },
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/login',
            method: 'post',
            propertyName: false
          },
          logout: {
            url: '/logout',
            method: 'post'
          },
          user: false
        },
        tokenRequired: true
      }
    },
    redirect: false
  }`

**Comment by bmulholland** [comment]
Is this still an issue on `@nuxtjs/auth-next`?

**Comment by bmulholland** [comment]
Please open a new issue if it is
