### ISSUE TITLE
How install dev branch on nuxt?

### ISSUE THREAD

**Issue by radudiaconu0** [nuxt-community/auth-module#651]
How install dev branch on nuxt?

**Comment by JoaoPedroAS51** [comment]
Hi @radudiaconu0! @pi0 will add CI/CD script to publish nightly versions.

**Comment by radudiaconu0** [comment]
Thanks :)

**Comment by JoaoPedroAS51** [comment]
Hi @radudiaconu0! Now you can use `@nuxtjs/auth-next` to install dev branch :)

**Comment by radudiaconu0** [comment]
Thanks dude. I will mention you when I become millionere

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51 
i get this error;( when run npm run dev
Error: Template src not found: /home/radu/Desktop/logintest/node_modules/@nuxtjs/auth-next/templates/plugin.js   │

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51  you must put the template folder in npm.this solved the issue

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 Done. Just wait a sec to CI publish.

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51  i have a big problem. after successfully login end redirect to home (ith middleware:auth set) after refresh i cant acces home route anymore it keeps redirect me to login. what should i do?=(

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 Can you show me your config?

Ah, don't forget to use `$auth.loggedIn` instead of `$auth.check`, because we reverted this change.

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51 I have just middleware auth all routes and guest on login .

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51  is m doing something wrong?

**Comment by srxa** [comment]
![Screenshot 2020-04-29 15 35 59](https://user-images.githubusercontent.com/11848079/80602242-28279480-8a2f-11ea-9e47-9cc411af1a6f.png)

How ti fix this error?

**Comment by JoaoPedroAS51** [comment]
@srxa This means that the strategy doesn't have a scheme. Can you show me your auth config?

**Comment by JoaoPedroAS51** [comment]
I'll make it throw an error if this happens :)

**Comment by srxa** [comment]
```
auth: {
    //plugins: ['~/plugins/auth.js'],
    redirect: {
      home: '/',
      login: '/',
      callback: '/callback',
      logout: 'http://auth.tambex.com/auth/realms/tambex.com/protocol/openid-connect/logout?redirect_uri=http%3A%2F%2Fdev.tambex.com'
    },
    localStorage: false,
    resetOnError: true,
    strategies: {
      local: {
        token: {
          property: 'token',
          // required: true,
          // type: 'Bearer'
        },
        user: {
          property: 'user',
          // autoFetch: true
        },
        endpoints: {
          login: {
            url: '/api/auth/login',
            method: 'post'
          },
          logout: {
            url: '/api/auth/logout',
            method: 'post'
          },
          user: {
            url: '/api/auth/user',
            method: 'get'
          }
        }
      },
      tambex: {
        _scheme: 'oauth2',
        endpoints: {
          authorization: `http://auth.tambex.com/auth/realms/tambex.com/protocol/openid-connect/auth`,
          token: `http://auth.tambex.com/auth/realms/tambex.com/protocol/openid-connect/token`,
          userInfo: `auth.tambex.com/auth/realms/tambex.com/protocol/openid-connect/userinfo`
        },
        responseType: 'code',
        token: {
          property: 'access_token',
          type: 'Bearer',
          maxAge: 1500
        },
        scope: '*',
        grantType: 'authorization_code',
        clientId: 'tambex-site',
        state: 'UNIQUE_AND_NON_GUESSABLE'
      },
      fusion: {
        _scheme: 'oauth2',
        endpoints: {
          authorization: `http://192.168.77.60:9011/oauth2/authorize`,
          token: `http://192.168.77.60:9011/oauth2/token`,
          userInfo: `http://192.168.77.60:9011/oauth2/userinfo`
        },
        responseType: 'code',
        token: {
          property: 'access_token',
          type: 'Bearer',
          maxAge: 1500
        },
        scope: '[offline_access]',
        accesssType: 'offline',
        grantType: 'authorization_code',
        clientId: 'someID',
        clientSecret: 'someSecret',
        state: 'UNIQUE_AND_NON_GUESSABLE'
      }
    }
  },
```

**Comment by JoaoPedroAS51** [comment]
Ok, I see where is the error. Now to set schemes we use `scheme` instead of `_scheme`. Change to `scheme: 'oauth2'`

**Comment by srxa** [comment]
OK, Thanks

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 I'm testing here and I have the same issue. I'll work on a fix. :)

**Comment by radudiaconu0** [comment]
> @radudiaconu0 I'm testing here and I have the same issue. I'll work on a fix. :)

Thanks bro

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51 how it works?

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51  how the fix works?

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 Seems that Laravel Sanctum requires `referer` header in SSR request to authorize the request. The fix will set `referer` header on mount. #654

**Comment by radudiaconu0** [comment]
Still doesn't work @JoaoPedroAS51

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 It wasn't merged yet.

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51  ok thanks

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51 do you have any idea how i can use sanctum with laravel echo? i get error 419.... i use laravel echo module for nuxt

**Comment by StanleyMasinde** [comment]
> Thanks dude. I will mention you when I become millionaire

Just a mention? 🤣

**Comment by bmulholland** [comment]
Dev branch is available as `@nuxtjs/auth-next` so closing this out
