### ISSUE TITLE
keep redirecting me to login after refresh

### ISSUE THREAD

**Issue by radudiaconu0** [nuxt-community/auth-module#653]
after successfully login and redirect to /home (with middleware:auth set) after refresh i cant acces home route anymore it keeps redirect me to login.i use laravel sanctum

**Comment by JoaoPedroAS51** [comment]
Hi @radudiaconu0! Fix on #654

**Comment by radudiaconu0** [comment]
Thanks bro

**Comment by JoaoPedroAS51** [comment]
Are you able to access /home in client side? Because in my tests I'm redirected to login after refresh, but then in client side I'm logged in again.

**Comment by radudiaconu0** [comment]
I am glad I can help

**Comment by JoaoPedroAS51** [comment]
If this issue persist after we merge the PR, let me know.

**Comment by radudiaconu0** [comment]
> If this issue persist after we merge the PR, let me know.

sure

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51 i can confirm that it works;) thank you for your work

**Comment by radudiaconu0** [comment]
i can confirm it works. thanks;)

**Comment by radudiaconu0** [comment]
@JoaoPedroAS51 You have any idea how can I use @nuxtjs/laravel-echo with sanctum in this module?
