### ISSUE TITLE
access_token_endpoint ignore configured baseURL

### ISSUE THREAD

**Issue by ThisIsAreku** [nuxt-community/auth-module#655]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://github.com/ThisIsAreku/nuxt-auth-baseurl-bugreport](https://github.com/ThisIsAreku/nuxt-auth-baseurl-bugreport)

### Steps to reproduce

Configure a prefix in nuxt-axios and a proxy rule:
```
    axios: {
        debug: process.env.NODE_ENV !== 'production',
        proxy: true,
        prefix: '/api/',
    },
    proxy: {
        '/api/': { target: process.env.API_URL, pathRewrite: {'^/api/': '/'} }
    },
```

Configure facebook strategy to forward the code to the backend:
```
    auth: {
        strategies: {
            facebook: {
                client_id: process.env.FB_CLIENT_ID,
                scope: ['public_profile', 'email', 'user_birthday'],
                response_type: 'code',
                access_token_endpoint: `/auth/callback`,
                userinfo_endpoint: '/users/me',
            },
        }
    },
```

### What is expected ?

When returning from facebook with the code, the expected request to be made should take account of the configured prefix, in this example `/api/auth/callback`

### What is actually happening?

The request is made against `/auth/callback` which is not matched by nuxt-proxy

### Additional comments?

https://github.com/nuxt-community/auth-module/blob/master/lib/schemes/oauth2.js#L162 seems to be the culprit.
Also, at this point `process.server` is aways false

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c558">#c558</a>)</em></sub></div>

**Comment by bmulholland** [comment]
We don't have bandwidth to support v4 anymore; please upgrade to auth-next and create a new Issue if the problem persists.
