### ISSUE TITLE
work with sanctum and laravele echo module

### ISSUE THREAD

**Issue by radudiaconu0** [nuxt-community/auth-module#658]
i have an issue....I can't use auth module with sanctum and laravel echo module...it says $auth.getToken is not o function in console from echo module...I tried some workaround to get token from cookies but still doesn't work.....I get error 419 in laravel echo server csrf token missmatch.....so I don't know what to do...I tried to find a solution on Google and documentation but still nothing...

**Comment by radudiaconu0** [comment]
I don't know if this issue is related with this module or @nuxtjs/laravel-echo module

**Comment by JoaoPedroAS51** [comment]
Hi @radudiaconu0!

> it says `$auth.getToken` is not o function

That's because `$auth.getToken` was removed in v5. Now we get the token using `$auth.token.get()`
Laravel echo module need to add support to v5.

**Comment by radudiaconu0** [comment]
Ok thanks I will try to modify this on laravel echo module

**Comment by JoaoPedroAS51** [comment]
I can make a fork

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 You can use my fork https://github.com/JoaoPedroAS51/laravel-echo/tree/feat/auth-v5

Can you test it? I'm not sure if this solves 419 csrf token mismatch

**Comment by radudiaconu0** [comment]
Hmmm I will try @JoaoPedroAS51

**Comment by radudiaconu0** [comment]
you must introduce referer header @JoaoPedroAS51

**Comment by radudiaconu0** [comment]
yeah didn't solve the issue=(

**Comment by JoaoPedroAS51** [comment]
> you must introduce referer header

Are you sure? The plugin is client side only and referer is only need for server side.

**Comment by radudiaconu0** [comment]
if i don't specify refere header onlaravel echoi get error 401 unauthenticated.Otherwise i get "message": "CSRF token mismatch."

**Comment by JoaoPedroAS51** [comment]
@radudiaconu0 Ok. I'll work on this today. I let you know when I finish.

**Comment by radudiaconu0** [comment]
thank dude. in the end someone who want to help me. i posted this in more forums but none cared =( i will treat you with a beer if i ever meet you =)

**Comment by JoaoPedroAS51** [comment]
Thanks! :D
Yeah it sucks when we need help and no one helps...

Ah, can you take a screenshot of the request?

**Comment by JoaoPedroAS51** [comment]
You can add me on discord Joao Pedro AS51#1284

**Comment by radudiaconu0** [comment]
yeah maybe we can fix this together

**Comment by radudiaconu0** [comment]
iget token = 200 if i call $auth.token.get()

**Comment by omaratta212** [comment]
I'm having the same CSRF issue, any idea how to fix this?

![image](https://user-images.githubusercontent.com/33264041/85738274-311ba600-b700-11ea-8d0f-fa846ecf8769.png)

**Comment by JoaoPedroAS51** [comment]
Closing here, as this issue was already solved discussing in discord.

Helpful links: [laravel sanctum provider](https://auth.nuxtjs.org/providers/laravel-sanctum) and [laravel-echo module for auth v5](https://github.com/nuxt-community/laravel-echo/pull/14)
