### ISSUE TITLE
500 error when login fails with Passport password grant

### ISSUE THREAD

**Issue by aaronhuisinga** [nuxt-community/auth-module#659]
### Version
5.0-dev

### Steps to reproduce
1. Install 5.0-dev build of auth module
2. Configure Passport auth strategy using grantType of password
3. Enter invalid credentials and submit form

### What is expected ?
When logging in with invalid credentials, a 400 code should be thrown with a message from the authentication server.

### What is actually happening?
A 500 (NuxtServerError) is being returned

![Console output](https://i.imgur.com/9o5Lnrw.png)

### Additional Comments?
Using the current 5.x beta build and running into this issue. Using the Nuxt Axios module with proxy enabled and SSR. Every failed login results in a NuxtServerError being returned to the app and an exception being thrown instead of the excepted 4xx failed login response sent from the Passport instance we're trying to authenticate with.

**Comment by JoaoPedroAS51** [comment]
Hi @aaronhuisinga! Thank you for your report. I'll work on a fix for this issue :)

**Comment by JoaoPedroAS51** [comment]
Hi @aaronhuisinga! The fix for this issue has been merged :)
Please update the package to the latest version **5.0.0-1588537732.a13c02f**

**Comment by aaronhuisinga** [comment]
Thanks so much! Just tested it out and it’s working as expected.
