### ISSUE TITLE
Types for @nuxtjs/auth-next

### ISSUE THREAD

**Issue by Bernix01** [nuxt-community/auth-module#661]
### What problem does this feature solve?

Use `auth-next` with `nuxt-ts`.

### What does the proposed changes look like?

Maybe this is ci/cd related.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c561">#c561</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @Bernix01! Thank you for your report! Just released a fix in 799e5cc88e71fdb0df13c76670cee705d5525536
