### ISSUE TITLE
Previous Cookies being concatenated with serializedCookie with each request

### ISSUE THREAD

**Issue by cardaddy** [nuxt-community/auth-module#671]
**_Edit to simplify test scenario_**

We are experiencing the following error while attempting to make multiple api request. See below for reproducible scenarios. **_This only appears to happen when fetchOnServer is set to true._** 

We are using the following versions

> "@nuxtjs/auth-next": "^5.0.0-1588866376.2380814",
> "@nuxtjs/axios": "^5.10.3",

> Whitelabel Error Page
> This application has no configured error view, so you are seeing this as a fallback.
> 
> Thu May 07 11:48:29 EDT 2020
> [205a751b] There was an unexpected error (type=Internal Server Error, status=500).
> HTTP header is larger than 8192 bytes.

**index.vue**

We are hard coding three news items where each one would make a unique request to the backend api.

Scenarios 

1) When there is only 1 newsItem request, we do not experience any http header errors

2) When there are 2 newsItems requested, we do not experience the http header error on the initial load, we only encounter it when the token expires and a refresh token is issued. 

3) When all 3 newsItems are requested, we receive the http request on the initial load. 

```
<template>
  <v-container fluid>
    {{newsItem1}}
    {{newsItem2}}
    {{newsItem3}}
  </v-container>
</template>
<script>

export default {
  name: "Home",

  data() {
    return {newsItem1: null,newsItem2: null,newsItem3: null,}
  },

  fetchOnServer: true,

  async fetch() {
    this.newsItem1 = await this.$axios.$get('http://localhost:8080/api/newsItem1')
    this.newsItem2 = await this.$axios.$get('http://localhost:8080/api/newsItem2' )
    this.newsItem3 = await this.$axios.$get('http://localhost:8080/api/newsItem3')
  }

}
</script>

```

**nuxt.config.js**

```
  auth: {
    localStorage: false,
    redirect: {
      logout: '/signed-out',
      home: '/portal/'
    },
    strategies: {
      hri: {
        scheme: 'oauth2',
        endpoints: {
          authorization: '/portal/auth/oauth/authorize',
          token: `/portal/auth/oauth/token`,
          userInfo: '/portal/auth/api/users/me',
        },
        redirectUri: process.env.BASE_URL + '/portal/login',
        responseType: 'code',
        grantType: 'authorization_code',
        clientId: 'clientId',
        scope: ['user_info'],
        state: 'test'
      }
    }
  },
```

Access Token

> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY29tcGFueV9pZCJdLCJ1c2VyX25hbWUiOiJ1c2VyMDAxIiwic2NvcGUiOlsidXNlcl9pbmZvIl0sImF0aSI6IjFkNDEwMDA2LWZhYWEtNDNmMS1iNzNhLWM0MjViMjgwMjkwYiIsImxhc3RfbmFtZSI6Ikxhc3QiLCJleHAiOjE1ODg5MDg2NjEsImZpcnN0X25hbWUiOiJGaXJzdCIsImF1dGhvcml0aWVzIjpbIlJPTEVfVElNRV9TSEVFVCIsIlJPTEVfT05FU09MX1BPIiwiUk9MRV9FWFBFUklNRU5UQUwiLCJST0xFX0dSQU5UX0RBU0hCT0FSRF9BTEIiLCJST0xFX1JFUE9SVF9TRUNVUklUWSIsIlJPTEVfQ0xPVkVSX0ZJTkFOQ0UiLCJST0xFX1BVUkNIQVNFX09SREVSIiwiUk9MRV9BVVRIRU5USUNBVEVEIiwiUk9MRV9USU1FUkVDT1JEUyIsIlJPTEVfT05FU09MX1ZFTkRPUiIsIlJPTEVfQ0xPVkVSX0ZJTkFOQ0VfQU5EX1BBWVJPTEwiLCJST0xFX0dSQU5UX0RBU0hCT0FSRF9SUENJIiwiUk9MRV9TWVNURU1fQURNSU4iXSwianRpIjoiOWFjYmFjNmUtNGY0Yi00NmE3LWIzYzYtYzQ3MWY5ZDQ2NGFiIiwiZW1haWwiOiJmaXJzdC5sYXN0QGNvbXBhbnkub3JnIiwiY2xpZW50X2lkIjoiY2xpZW50SWQifQ.0kE51ZnNBH1pPSkVwepDvR12BpTtB8unaRNSK_JxEd4

Refresh Token

> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY29tcGFueV9pZCJdLCJ1c2VyX25hbWUiOiJ1c2VyMDAxIiwic2NvcGUiOlsidXNlcl9pbmZvIl0sImxhc3RfbmFtZSI6Ikxhc3QiLCJleHAiOjE1ODg4NjU3NTcsImZpcnN0X25hbWUiOiJGaXJzdCIsImF1dGhvcml0aWVzIjpbIlJPTEVfVElNRV9TSEVFVCIsIlJPTEVfT05FU09MX1BPIiwiUk9MRV9FWFBFUklNRU5UQUwiLCJST0xFX0dSQU5UX0RBU0hCT0FSRF9BTEIiLCJST0xFX1JFUE9SVF9TRUNVUklUWSIsIlJPTEVfQ0xPVkVSX0ZJTkFOQ0UiLCJST0xFX1BVUkNIQVNFX09SREVSIiwiUk9MRV9BVVRIRU5USUNBVEVEIiwiUk9MRV9USU1FUkVDT1JEUyIsIlJPTEVfT05FU09MX1ZFTkRPUiIsIlJPTEVfQ0xPVkVSX0ZJTkFOQ0VfQU5EX1BBWVJPTEwiLCJST0xFX0dSQU5UX0RBU0hCT0FSRF9SUENJIiwiUk9MRV9TWVNURU1fQURNSU4iXSwianRpIjoiMWQ0MTAwMDYtZmFhYS00M2YxLWI3M2EtYzQyNWIyODAyOTBiIiwiZW1haWwiOiJmaXJzdC5sYXN0QGNvbXBhbnkub3JnIiwiY2xpZW50X2lkIjoiY2xpZW50SWQifQ.QYSQ3DyoycBIXzbBt2iSK0fO3UJCrve0cVufCdwnWok

**Comment by cardaddy** [comment]
@JoaoPedroAS51 do you know if headers from the previous request are being appended to headers of the current request serverside causing them to exceed the header limit? I'm assuming the auth module is handling all the headers.

**Comment by cardaddy** [comment]
I have been able to locate the bug causing the expanding header. Storage.js line 187 sets the header cookie for each request, however on line 190 we are concatenating the set header cookie from the previous request with the serializedCookie and no duplicate filter. This is causing the headers to expand infinitely with each request.  A duplicate filter needs to be applied or we need to just set the cookie once. 

else if (process.server && this.ctx.res) {
            // Send Set-Cookie header from server side
            const prevCookies = this.ctx.res.getHeader('Set-Cookie');
            this.ctx.res.setHeader('Set-Cookie', [].concat(prevCookies, serializedCookie).filter(v => v));
        }

could be fixed with

**Comment by cardaddy** [comment]
@JoaoPedroAS51 could you tell us how to fork V5 so we can apply a temp fix until you guys can get around to fixing this issue permanently?

**Comment by a-mazalov** [comment]
@JoaoPedroAS51 We have exactly the same problem as @cardaddy. 
On our project, we use the nginx reverse proxy server and temporarily solve this problem by hiding cookies in the headers.

**Comment by cardaddy** [comment]
@JoaoPedroAS51 I'm not sure what the consequences will be for removing the concatenating headers, but I removed that code in my fork and it appears to have resolved our header issue. 

https://github.com/cardaddy/auth-module/blob/dev/src/core/storage.ts

**Comment by JoaoPedroAS51** [comment]
Hi @cardaddy! Can you try the following filter and see if it solves your issue?
```js
this.ctx.res.setHeader('Set-Cookie', [].concat(prevCookies, serializedCookie)
  .filter((v, i, arr) => arr.indexOf(v) === i))
```

**Comment by JoaoPedroAS51** [comment]
@cardaddy I improved the filter! :)
Now it will also prevent cookies with multiple values (it will remove the cookie with old value).
Can you try it too?
```js
const cookies = this.ctx.res.getHeader('Set-Cookie') || []
this.ctx.res.setHeader('Set-Cookie', cookies
   .filter((v, i, arr) => arr.findIndex(val => val.startsWith(v.substr(0, v.indexOf('=')))) === i))
```

**Comment by cardaddy** [comment]
@JoaoPedroAS51 works! Could you add the patch to v5? Thanks

**Comment by JoaoPedroAS51** [comment]
Hi @cardaddy! Just merged the PR :)
