### ISSUE TITLE
cookie: false, but cookies still get set!

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-community/auth-module#673]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://eqdnq.sse.codesandbox.io/](https://eqdnq.sse.codesandbox.io/)

### Steps to reproduce

1. Delete all Cookies.
2. Press Login Button.
3. Cookies are set by loginWith

full codesandbox: https://codesandbox.io/s/nuxt-auth-autofetchuser-not-working-eqdnq?file=/nuxt.config.js

### What is expected ?

No cookies are set when option cookie: false
Existing cookies are ignored for login state.

### What is actually happening?

Cookies are still being set.
Cookies are being read and used for determining login State.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c566">#c566</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @sugoidesune! I'm seeing your codesandbox. This issue is happening because `cookie: false` was set inside `strategies` object. It should be set in `auth` object. :)

**Comment by sugoidesune** [comment]
Argh what an embarrassing oversight -_-"
Thank you
