### ISSUE TITLE
Setting any cookie options breaks webpack

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-community/auth-module#675]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

https://codesandbox.io/s/nuxt-auth-setting-any-cookie-options-breaks-webpack-4golb?file=/nuxt.config.js

### Steps to reproduce

1. Set cookie setting to an object.
(2. To fix, comment the cookie option.)

### What is expected ?

Cookie options are being read and work.

### What is actually happening?

Setting cookie options breaks webpack in any configuration, because even an empty objects breaks it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c568">#c568</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @sugoidesune! This issue is related to my answer of your other issue. See https://github.com/nuxt-community/auth-module/issues/673#issuecomment-625843214
