### ISSUE TITLE
$auth.loggedIn stays false after loginWith('local').

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-community/auth-module#676]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://codesandbox.io/s/nuxt-auth-autofetchuser-not-working-eqdnq](https://codesandbox.io/s/nuxt-auth-autofetchuser-not-working-eqdnq)

### Steps to reproduce

1. Login with loginwith.

### What is expected ?

After a succesful loginWith() call, $auth.loggedIn should switch to true.

### What is actually happening?

$auth.loggedIn stays false, only refreshes on page reload.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c569">#c569</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @sugoidesune! That's because `loggedIn` state is based on user data :)

**Comment by sugoidesune** [comment]
Took me also a while to realise, These two things would be seperate in my book.
Could also use a more explicit text in the docs!
Thanks!

**Comment by JoaoPedroAS51** [comment]
@sugoidesune We discussed about `loggedIn` being separated from user data, but we choose this approach to ensure that user is logged in and data has been fetched so we can safely navigate and render templates depending on `$auth.user`.

**Comment by Timibadass** [comment]
I'm currently experiencing this issue and I have to refresh my app using `window.location` for `this.$auth.$state` to get updated with both user info and `loggedIn` as `true`

**Comment by Izzatullo** [comment]
Hi. Does it fetch user data after logged in?

**Comment by Timibadass** [comment]
Hi @Izzatullo, I have tried manually setting the user with `this.$auth.setUser(user)` when `autoFetchUser` was set to `false`, I've also tried setting it to `true` and although it fetches the user data, `this.$auth.$state` still returns default values for both `user` and `loggedIn`. The two methods don't change until I refresh my app.

**Comment by JoaoPedroAS51** [comment]
Hi @Timibadass! Sorry for the delay. Can you show me your config and your login method? :)

**Comment by Timibadass** [comment]
My config currently looks like this
`endpoints: {
          login: {
            url: "users/auth/login",
            method: "post",
            propertyName: "token"
          },
          user: {
            url: "users/accounts",
            method: "get",
            propertyName: "user"
          },
          logout: false
        },
        tokenType: "",
        autoFetchUser: false,
        tokenRequired: true
      }`

and my login method looks like this
` 
            let res = await this.$auth.loginWith("local", {
              data: { email, password }
            });
            this.$auth.setUser(res.data.user);
`

@JoaoPedroAS51 .

**Comment by JoaoPedroAS51** [comment]
@Timibadass Your config seems fine to me.

Are you using vuex-persistedstate or nuxt-vuex-localstorage? An user reported that these packages don't work with auth-module and after uninstalling them this issue was fixed.

**Comment by Timibadass** [comment]
@JoaoPedroAS51 I just removed the plugin(vuex-persist) and it works as expected, Thanks!

I think it should be added to the documentation so people would know not to use it with the auth module.

**Comment by sugoidesune** [comment]
Sorry continued conversation on github about this issue.
Turns out that `loggedIn` is actually 'user is set' and not just 'login call succesful'
