### ISSUE TITLE
How i use auth-next with typescript

### ISSUE THREAD

**Issue by radudiaconu0** [nuxt-community/auth-module#678]
How i use auth-next with typescript? I get this error: 
      Property '$auth' does not exist on type 'void'.

I put @nuxtjs/auth-next in tsconfig.json

**Comment by JoaoPedroAS51** [comment]
Just released a fix in 799e5cc

**Comment by andyconda21** [comment]
I'm having issues getting this working as well. Is there a writeup somewhere on what else needs to be done to set this up for typescript?
