### ISSUE TITLE
Can't create two local schemes with nuxt auth module

### ISSUE THREAD

**Issue by Izzatullo** [nuxt-community/auth-module#680]
https://cmty.app/nuxt/auth-module/issues/c571

**Comment by JoaoPedroAS51** [comment]
Hi @Izzatullo! Just add `_scheme: 'local'` to both strategies :)

**Comment by sugoidesune** [comment]
makesure _scheme is outside of endpoints. thats a mistake i made.
i kept local, but added convert_google local scheme.
![image](https://user-images.githubusercontent.com/20317691/81702557-bce8b400-946b-11ea-8fea-502da1ba68b6.png)

**Comment by Izzatullo** [comment]
@sugoidesune You have added only one of them and worked? @JoaoPedroAS51 what do you think about @sugoidesune way? Does it work?

**Comment by Izzatullo** [comment]
Thanks brothers. @JoaoPedroAS51  and @sugoidesune. In next project, I will give a shot and try your answers . Now I have made it with different ways but the most important thing is that is working ).

**Comment by Izzatullo** [comment]
By the way, In nuxt docs, most of the examples are forward you in 404 page of github and this really makes me irritated. Hate Nuxt Docs

**Comment by JoaoPedroAS51** [comment]
> @sugoidesune You have added only one of them and worked? @JoaoPedroAS51 what do you think about @sugoidesune way? Does it work?

@Izzatullo Yes, it works. By default, instance names are the same as scheme names. That means if the strategy name is `local`, it will try to use `local` scheme. If you want to use a custom name for the strategy (like `localOne` or `localTwo`), then you need to set the `_scheme` :)

 You can read more about schemes here:
https://auth.nuxtjs.org/guide/scheme.html

**Comment by JoaoPedroAS51** [comment]
> By the way, In nuxt docs, most of the examples are forward you in 404 page of github and this really makes me irritated. Hate Nuxt Docs :-(((

Can you tell me what examples are broken? I would be happy to fix them :)
