### ISSUE TITLE
Password grant using Axios baseURL

### ISSUE THREAD

**Issue by aaronhuisinga** [nuxt-community/auth-module#682]
### Version
5.0-dev

### Steps to reproduce
1. Install 5.0-dev build of auth module
2. Configure Passport auth strategy using grantType of password
3. Submit login form

```
module.exports = {
  mode: 'universal',

  router: {
    middleware: ['auth'],
  },

  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth-next',
  ],

  axios: {
    baseURL: 'http://testing.com/api/v1',
  },

  auth: {
    strategies: {
      laravelPassport: {
        provider: 'laravel/passport',
        url: 'http://api.testing.com',
        endpoints: {
          user: {
            url: 'http://api.testing.com/api/v1/users/auth',
          },
        },
        token: {
          maxAge: 60 * 60,
        },
        refreshToken: {
          maxAge: 60 * 60 * 24 * 7,
        },
        clientId: process.env.PASSPORT_CLIENT_ID,
        clientSecret: process.env.PASSPORT_CLIENT_SECRET,
        grantType: 'password',
      },
    },
  },
};
```

### What is expected?
Request is made to http://localhost:3000/_auth/laravelPassport/token

### What is actually happening?
Request is made to http://testing.com/api/v1/_auth/laravelPassport/token

### Additional Comments?
Using the current 5.x beta build and running into this issue. If a baseURL is configured for Axios, the login call to the server for password grants is failing. It's not ignoring the baseURL, and is sending the request to the wrong URL because of it. The request should be going to the Nuxt app, not the Axios baseURL, which can be pointing to an external service (and is, in my case).

**Comment by JoaoPedroAS51** [comment]
Hi @aaronhuisinga! Thank you for your report! I'm working on a fix right now 😃
