### ISSUE TITLE
Updated Doc with local refresh scheme

### ISSUE THREAD

**Issue by sdil** [nuxt-community/auth-module#686]
### What problem does this feature solve?

I'm having difficulty using refresh token to integrate with my Django REST Framework backend. After reading the source code (https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/refresh.ts) and pull requests, it does mention about 'refresh' scheme. However, I could not find anything about that in the official documentation.

### What does the proposed changes look like?

Updated doc with local refresh scheme.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c575">#c575</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @sdil! Refresh support wasn't releaset yet. It will be released in v5, but if you want to use it now, you can use dev version. We published a new package for dev version `@nuxtjs/auth-next`

Please, check the updated docs for dev version in https://dev.auth.nuxtjs.org/

**Comment by sdil** [comment]
Ohh. Thanks for the clarification :)
