### ISSUE TITLE
Secondary Local and Custom schemes are not loggedIn after page reload.

### ISSUE THREAD

**Issue by sugoidesune** [nuxt-community/auth-module#693]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://codesandbox.io/s/local2-ciqks](https://codesandbox.io/s/local2-ciqks)

### Steps to reproduce

reproduction link: 
1. login button 1. refresh page -> still logged in.
2. login button 2. refresh page -> not logged in anymore

technical:
1: set `cookie: false,`
2: Login with a new `strategy` using the `local scheme`. For instance
    `local2: {_scheme: 'local',...}`
3: Reload Page.

### What is expected ?

Token is read from localstorage, user is fetched, and visitor status is loggedin. Like when using strategy 'local'.

### What is actually happening?

User is not fetched and Visitor is not loggedIn.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c580">#c580</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @sugoidesune! I'm gonna make some tests to see what is happening :)
Just note that `cookie` is required for `universal` mode.

**Comment by JoaoPedroAS51** [comment]
@sugoidesune Yes, that's the problem. `cookie` is required for `universal` mode. If you change to `spa` mode then custom schemes will work with `cookie: false`.

**Comment by sugoidesune** [comment]
Good enough for now.
But would be great if this was fixed for version 5.

Thank you for ⚡ responses ❤

**Comment by JoaoPedroAS51** [comment]
Actually it can't be "fixed" because localStorage only works on client side. If you are using `universal` mode your app runs in server side too. Then we need to use cookies to sync scheme.

**Comment by sugoidesune** [comment]
@JoaoPedroAS51  But thats the thing. Login button 1 works, because it's the standard `local` scheme.
if you use a second 'local' scheme it doesn't work.
So its just that additional local schemes get ignored.

```
auth: {
  strategies: {
    local: { /* ... */ }, //  works
    local: { _scheme: 'local',/* ... */ }, // does not work.
  }
}
```

**Comment by JoaoPedroAS51** [comment]
Hi @sugoidesune! Let me explain :)

What really happens here is that `local` strategy is being set as default strategy. So as cookies are disabled and localStorage doesn't work in server side, it tries to get the strategy but fails. Then the fallback is the default strategy (local). If you set `defaultStrategy` option, you will see that `local` strategy will not work anymore.
```js
auth: {
  defaultStrategy: 'local2',
  strategies: {
    local: { /* ... */ }, //  won't work anymore
    local2: { _scheme: 'local',/* ... */ }, // will work
  }
}
```

What I'm trying to say is that cookies are required in order to sync in server side, otherwise sync will fail. Even for the default strategy that is "working", you can see a mismatch between server and client sides, because in server side you ain't logged in but in client side you are.

**Comment by sugoidesune** [comment]
If `cookie: false` server side authentication will by design never work and there is no reason to perform it.

- Server side authentication should be turned off
- Server should not fallback to `defaultStrategy`
- Should leave the authentication process to the clientside.

I haven't looked at the source yet hopefully a simple if statemet would suffice:

```
If(process.server && this.$auth.options.cookie){
 userDefaultStrategy()
return
}
```
