### ISSUE TITLE
change redirec_uri based  on current url

### ISSUE THREAD

**Issue by Weijian23** [nuxt-community/auth-module#694]
Hi,
Is there a way to set the redirect_uri dynamically? Based on the different environments, the redirect_uri should be different. 
I tried to use process.env.BASE_URL, it works when I run on my localhost, but in the production environment, its value is undefined.
In my nuxt.config file, when I run "npm run dev" I can print localhost, but when I run "npm run build", the value is undefined.
So is there a way I can check and overwrite the value of a login strategy?
Thanks a lot.

**Comment by bmulholland** [comment]
As this issue is a bit old and there hasn't been other support for such a feature, I'm closing it as stale.
