### ISSUE TITLE
Sanctum can not authenticate

### ISSUE THREAD

**Issue by PaulJasiul** [nuxt-community/auth-module#697]
I made a Laravel controller which return:
```
$token = $user
            ->createToken('my-token')
            ->plainTextToken;

return JsonResponse::create([
            'token' => $token
        ]);
```

In Nuxt app I get successful login and I see some values in cookie:
- auth._token.laravelSanctum: 200
- auth.redirect: %2F
- auth._token_expiration.laravelSanctum: false
- auth.strategy: laravelSanctum

But I am not authenticated. What is wrong with my code?

**Comment by StanleyMasinde** [comment]
You are supposed to return the token you created for the user
```php
$token = $user->createToken('token-name');

return $token->plainTextToken;
```

The response will automatically be converted to JSON
though you can still
```php
$token = $user->createToken('token-name');

return response()->json(['token' => $token->plainTextToken]);
```

**Comment by StanleyMasinde** [comment]
If you are authenticating a Single Page application, it is advisable that you use the cookie-based flow
