### ISSUE TITLE
Is it possible to not use universal login with Auth0, but directly a link with google?

### ISSUE THREAD

**Issue by ctwhome** [nuxt-community/auth-module#703]
I want to be able to use something like this:
`this.$auth.loginWith('auth0-google')`
or
`this.$auth.loginWith('auth0-github')`

Is this possible?
this is how my login modal looks:
![image](https://user-images.githubusercontent.com/4195550/83038447-40de9680-a03d-11ea-8000-bdd44adf25f4.png)

**Comment by bmulholland** [comment]
Closing as stale
