### ISSUE TITLE
Login redirect not working, $auth.user.loggedIn is false, $auth.user is null when $auth.loginWith('local', {}) returns

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [nuxt-community/auth-module#707]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://github.com/nuxt-community/auth-module/issues/58#issuecomment-635763044](https://github.com/nuxt-community/auth-module/issues/58#issuecomment-635763044)

### Steps to reproduce

Start a project with @nuxtjs/auth version 4.9.0 or 4.9.1 (got to simulate in both). Make sure the endpoints configured in `auth.strategies.local.endpoints.login` and `auth.strategies.local.endpoints.user` are a little bit slow (1s to respond or more). 

### What is expected ?

User is logged in and redirected to the root.

### What is actually happening?

Screen shows the network activity bar (fetching the JWT token and user), and then nothing more rather than clearing the login and password fields happen (user is stuck at the login screen), If user navigates afterwards to the root, the root route opens normally.

### Additional comments?

This happens since version 4.7.0. Got to use some workarounds, but a new implementation made me stumble upon this problem once again.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c586">#c586</a>)</em></sub></div>

**Comment by ponnex** [comment]
Having the same problem also, it does not rediret to `/home` and `$auth.loggedIn` is `false`

**Comment by basiteaal** [comment]
Same issue here. Any fix?

**Comment by leonelsanchesdasilva** [comment]
@basiteaal Check my solution here: https://github.com/nuxt-community/auth-module/issues/58#issuecomment-635763044

**Comment by basiteaal** [comment]
@leonelsanchesdasilva Thanks for your suggestion. We've fixed it with a very simple window.reload but I actually think this is a bug.

**Comment by dev-gaster** [comment]
I am trying to use Nuxt Auth with oauth google Strategy for logins, the code works but after am redirected to my call back url, i have failed to get the token or even set the user to loggedIn,

Any workarrounds

**Comment by bmulholland** [comment]
We don't have bandwidth to support 4.9 and are focused on auth-next. Please open a new issue if this is still happening with that new version.
