### ISSUE TITLE
Refresh scheme logs out user on first load page if token has expired. (for auth-next)

### ISSUE THREAD

**Issue by rivor** [nuxt-community/auth-module#716]
### Version

[v5.0.0](https://github.com/auth-module/releases/tag/v5.0.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

Just let token expire and refresh page without doing any axios requests before leaving page.

### What is expected ?

user to be still logged in after page refresh 

### What is actually happening?

user is getting logged out even though refresh token is still valid

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c589">#c589</a>)</em></sub></div>

**Comment by JoaoPedroAS51** [comment]
Hi @rivor! I tried to reproduce your issue, but for me it's working as expected. It seems more like a misconfiguration problem. Can you show me your config?

**Comment by rivor** [comment]
@JoaoPedroAS51 hey! Well, i already went back to original auth and use that right now but i had this configuration for it
`
	/*
	** Nuxt.js modules
	*/
	modules: [
		'@nuxtjs/axios',
		'@nuxtjs/auth-next'
	],

	auth: {
		strategies: {
			local: {
				endpoints: {
					login: { url: '/api/auth/login', method: 'post', propertyName: 'token' },
					logout: { url: '/api/auth/logout', method: 'post' },
					user: { url: '/api/auth/user', method: 'get', propertyName: 'user' }
				}
			}
			refresh: {
				token: {
					property: 'token',
					maxAge: 3600,
					// type: 'Bearer'
				},
				refreshToken: {
					property: 'refreshToken'
					maxAge: false,
				},
				user: {
					property: 'user',
					// autoFetch: true
				},
				endpoints: {
					login: { url: '/api/auth/login', method: 'post' },
					refresh: { url: '/api/auth/refresh', method: 'post' },
					user: { url: '/api/auth/user', method: 'get' },
					logout: { url: '/api/auth/logout', method: 'post' }
				},
				// autoLogout: false
			}
		},

		//plugins: [ '~/plugins/axios.js' ]
	},
`

**Comment by JoaoPedroAS51** [comment]
@rivor Your config seems fine. Just `propertyName` were deprecated in auth-next.
In your tests, what was the lifetime of the token?

**Comment by rivor** [comment]
@JoaoPedroAS51 for login token it was 1 hour but when testing i set it to 5 seconds, for refresh token it doesn't expire.

**Comment by JoaoPedroAS51** [comment]
@rivor And did you change the token `maxAge` to `5`? 
> `maxAge` will be used if for some reason we couldn't decode the token to get the expiration date.

**Comment by rivor** [comment]
@JoaoPedroAS51 yeah, i tried changing that too, same thing. Maybe it's because i use ssr (universal mode) with adonisjs? When i was installing nuxtjs, i chose universal mode with adonisjs as back end.

**Comment by sirdiego** [comment]
Hi @JoaoPedroAS51,

I think I have the same problem with auth-next. I guess it's because there is the check().valid check inside the [refreshTokens](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/refresh.ts#L119))-Method. This will be false when the token is expired but the refresh token is still valid and will then stop the refreshTokens call before refreshing.

Maybe this should use refreshTokenExpired or isRefreshable (which is not set anywhere?!).

If I can help with testing or something else, let me know.

**Comment by JoaoPedroAS51** [comment]
Hi @sirdiego! Thank your for your report!

I can ensure that it's not caused by the `check` method. In this case it's only checking if token and refresh token are defined, not their status.

Further investigation of this issue will be needed. Can you show me your config?

**Comment by sirdiego** [comment]
Hi @JoaoPedroAS51, thanks for your feedback.

Oh, I see. I read the `checkStatus` the other way around... My bad. I'll investigate this further in the coming week!

**Comment by sirdiego** [comment]
Okay, I found that we have a completely different problem here. The backend rejects every request with an invalid token inside the `Authorization` header, since the expired bearer token will be sent to the refresh endpoint along with the refresh token the request gets rejected before even creating a new token. I solved this by setting `headers: { Authorization: '' }` in my refresh endpoint configuration.

**Comment by JoaoPedroAS51** [comment]
Hi @sirdiego! Good catch! I'll fix it :)

**Comment by antonsmolko** [comment]
> since



> Okay, I found that we have a completely different problem here. The backend rejects every request with an invalid token inside the `Authorization` header, since the expired bearer token will be sent to the refresh endpoint along with the refresh token the request gets rejected before even creating a new token. I solved this by setting `headers: { Authorization: '' }` in my refresh endpoint configuration.

Please can explain in detail - where did you specifically set the headers? I cannot solve a similar problem yet.
