### ISSUE TITLE
Is it right-way to use this module?

### ISSUE THREAD

**Issue by estylehq** [nuxt-community/auth-module#723]
Back-end server return:
```
{
    "result": true,
    "msg": <MESSAGE>,
    "data": {
        "id": 1,
        "login_id": <USER_ID>,
        "email": <USER_EMAIL>,
        "email_verified_at": null,
        "api_token": <TOKEN>,
        "access_token": <ACCESS_TOKEN>
        "type": <USER_TYPE>,
        "state": 1,
        "nickname": <USER_NICKNAME>,
        "joined_at": "2020-04-29 14:24:11",
        "withdrawn_at": null,
        "login_ip": <USER_IP>,
        "login_at": "2020-06-08 14:01:38",
        "created_at": "2020-04-29T05:24:11.000000Z",
        "updated_at": "2020-06-08T05:01:38.000000Z",
        "point": []
    }
}
```

My nuxt.config.js
```
auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/api/login',
            method: 'post',
            propertyName: 'data.access_token',
          },
          logout: false,
          user: {
            url: '/api/login',
            method: 'post',
            propertyName: 'data',
          },
        },
      },
    },
    redirect: {
      login: '/login',
      logout: '/',
      callback: '/login',
      home: '/',
    },
    cookie: false,
    localStorage: {
      prefix: 'ls_',
    },
    tokenType: 'bearer',
    token: {
      prefix: '_token.',
    },
  },
```

as you see, ```login api``` is return ```access_token``` and ```user_information```

so, I set ```user url``` same value with ```login url```.

But right to what i know, that user url for fetching current ```user data```. Is it?

Is it right-way ?

If is not, how can I mapped user information calling login?

**Comment by JoaoPedroAS51** [comment]
Hi @estylehq! `user` endpoint must be different than `login` endpoint because we can't persist user data in storage. So we use `user` endpoint to fetch the user again.

For your case you can disable [`autoFetchUser`](https://auth.nuxtjs.org/schemes/local.html#autofetchuser)
> This option can be used to disable user fetch after login. Useful if the login response already have the user.
> It doesn't disable user fetch at all, only the one after login.

Then you can do something like this:
```js
this.$auth.loginWith('local').then(response => {
  this.$auth.setUser(response.data.user_information)
})
```
