### ISSUE TITLE
[Auth0] pkce_code_verifier not set to null after login

### ISSUE THREAD

**Issue by darthf1** [nuxt-community/auth-module#724]
I'm using `@nuxtjs/auth-next` with the `auth0` provider with the `PKCE Grant flow`. In [oauth2.ts](https://github.com/nuxt-community/auth-module/blob/dev/src/schemes/oauth2.ts#L272) I noticed the following code:

```js
// Retrieve code verifier and remove it from storage
if (this.options.codeChallengeMethod && this.options.codeChallengeMethod !== 'implicit') {
    codeVerifier = this.$auth.$storage.getUniversal(this.name + '.pkce_code_verifier');
    this.$auth.$storage.setUniversal(this.name + '.pkce_code_verifier', null);
}
```
I would expect the `pkce_code_verifier` variable be set to `null` after successful login. However, using `auth0` the `pkce_code_verifier` still has the original value in the cookie after a successful login.

![image](https://user-images.githubusercontent.com/17253332/84031959-e0cde580-a996-11ea-9385-8807f4a00534.png)

config:
```js
auth: {
    cookie: {
      options: {
        sameSite: 'strict',
        secure: true,
      },
    },
    localStorage: false,
    plugins: [{ src: '~/plugins/http', ssr: true }],
    redirect: {
      login: '/login/',
      logout: '/',
      callback: '/callback/',
      home: '/',
    },
    strategies: {
      auth0: {
        domain: 'xxx',
        clientId:  'xxx',
        audience:  'xxx',
        scope: ['openid', 'profile', 'email', 'offline_access'],
        responseType: 'token',
        grantType: 'authorization_code',
        codeChallengeMethod: 'S256',
      },
    },
  },
```

**Comment by JoaoPedroAS51** [comment]
Hi @darthf1! This is related to your other issue (#725). `responseType` should be code.

**Comment by darthf1** [comment]
Hi @JoaoPedroAS51 , you're right. Could have found it reading this line:
```
if (this.options.responseType === 'code' && parsedQuery.code) {
```
