### ISSUE TITLE
Add facebook scheme

### ISSUE THREAD

**Issue by pi0** [nuxt-community/auth-module#73]
[original request](https://github.com/nuxt-community/auth-module/pull/61#issuecomment-366537683) by @Syffs

> I've tried adding a [facebook scheme](https://github.com/Syffs/auth-module/tree/multi-strategy), not sure I got it right though...
> SSR is not working and I'm not sure how accessToken is supposed to be sent back to the server. Any insight?
> I also though about implementing this [without SDK](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) not sure what is the preferred way..

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c55">#c55</a>)</em></sub></div>

**Comment by Syffs** [comment]
Thanks, Facebook provider using oauth2 scheme works perfectly. 

It would be great to be able to adjust hardcoded `providers` parameters (mainly `scope` and `userinfo_endpoint`) through `strategies` into `nuxt.config.js`. I've tried setting these setups unsuccessfully:

- Custom strategy as in [here](https://github.com/nuxt-community/auth-module/blob/dev/docs/strategies/README.md):
```
      fb: {
        _scheme: 'oauth2',
        client_id: '1671464192946675',
        authorization_endpoint: 'https://facebook.com/v2.12/dialog/oauth',
        userinfo_endpoint: 'https://graph.facebook.com/v2.12/me?fields=about,name,picture{url},email,birthday,friends',
        scope: ['public_profile', 'email', 'user_friends', 'user_birthday']
      },
```
- Add custom endpoint & scope to existing facebook strategy 
```
      facebook: {
        client_id: '1671464192946675',
        userinfo_endpoint: 'https://graph.facebook.com/v2.12/me?fields=about,name,picture{url},email,birthday,friends',
        scope: ['public_profile', 'email', 'user_friends', 'user_birthday']
      },
```

**Comment by Syffs** [comment]
Another question: Have you though about a specific way of sending `accessToken` or `code` to a specific  endpoint in the callback?
Usually after social authentication, `accessToken` or `code` is sent to your webserver for database provisioning and later access.

I see that `Oauth2Scheme._handleCallback` only pushes authorization `code` to `access_token_endpoint` when `this.options.response_type === 'code'`, but Facebook API allows `response_type=code%20token`  (I don't know about other providers)

**Comment by pi0** [comment]
The Facebook scheme is _basically_ working. I would let enhancement to be done in new issues and PRs.
