### ISSUE TITLE
[dev][bug] yarn upgrade causes `dependency not found` issues

### ISSUE THREAD

**Issue by silverbackdan** [nuxt-community/auth-module#734]
After running `yarn upgrade` the following message then appears if I run `yarn dev`
```
 ERROR  Failed to compile with 1 errors                                                                                                                                          friendly-errors 19:42:51

This dependency was not found:                                                                                                                                                   friendly-errors 19:42:51
                                                                                                                                                                                 friendly-errors 19:42:51
* [absolute path]/src/providers/auth0/scheme.ts in ./demo/.nuxt/auth.js
```

I'm trying to implement a similar methodology as this module to a new module I'm writing. I'm also having trouble after a yarn upgrade where it'd be the equivalent of paths using the alias `~auth` are not found. I think there's something wrong with the way in which the aliases and transpiling paths are being defined.

I'd love to help with a PR but I'm struggling to work out how to do this. I'll keep trying though.

When loading the demo page the error is `Unexpected token '!'`

**edit**
After the first load I can't even seem to resolve this by deleting `yarn.lock` `node_modules` and the `.nuxt` build folder, re-running yarn install and starting with `yarn dev` again - I must re-instate the `yarn.lock` file committed to the repo.

**Comment by silverbackdan** [comment]
A fantastic dev was looking into this with me and looks like a babel update causes this issue. Our resolution was to change the way we import the module.

In the `demo/tsconfig.json` you would add into the `paths` config `{ "@nuxtjs/auth*": ["../src/*"] }` and into `demo/nuxt.config.js` the following:
```js
{
  build: {
    // this is for dev so that @cwa aliases will work
    extend (config, _) {
      if (!config.resolve) {
        config.resolve = {}
      }
      if (!config.resolve.plugins) {
        config.resolve.plugins = []
      }

      config.resolve.plugins.push(new TsconfigPathsPlugin({ configFile: `${__dirname}/tsconfig.json` }))
    }
  }
}
```

Now in dev we will be using the `src` directory and in all the source code where `~auth` is being used, you could use `@nuxtjs/auth` instead. The only issue I can see here would be that the user may be using `@nuxtjs/auth-next`. I'm not 100% sure how to resolve this as yet, but hopefully this will help with a lot of debugging and trying to trace the issue in that it seems to come up from a babel dependency.

**Comment by JoaoPedroAS51** [comment]
Closing here, as this issue should be fixed in latest version of auth v5
