### ISSUE TITLE
Linkedin signin user error

### ISSUE THREAD

**Issue by thomas4Bitcraft** [nuxt-community/auth-module#735]
I wanted to implement linkedin signing with the auth module, but the user is not fetched after the login. Does anybody have done this successfully? 

This is the auth config for linkedin:
```
linkedin: {
        _scheme: 'oauth2',
        authorization_endpoint: 'https://www.linkedin.com/oauth/v2/authorization',
        userinfo_endpoint: 'https://api.linkedin.com/v2/me',
        scope: ['r_liteprofile', 'r_emailaddress'],
        access_type: 'client_credentials',
        access_token_endpoint: 'https://www.linkedin.com/oauth/v2/accessToken',
        response_type: 'code',
        token_type: 'Bearer',
        client_id: '<client-id>'
      }
```

And it is triggered with:
`this.$auth.loginWith('linkedin')`

The signin process itself is working - but after that i get redirected to the login page with a `code` GET parameter

**Comment by tobsch** [comment]
As far as i see this, this code has to be used to get the corrcet token from the ```access_token_endpoint``` endpoint. The doc states, that google uses the same mechanism but I did not find it so far.
Would very much appreciate hints too.

**Comment by tobsch** [comment]
ok, ok. it's called "token_endpoint" and as far as I understand it, the token has to be downloaded by the auth provider.
And for this, a linkedin provider has to be implemented and "addAuthorize" called. see the providers that are part of this package (eg: github).

Any ideas how this can be implemented outside of the node package? eg: as nuxt plugin?

**Comment by tobsch** [comment]
after investing some more time and writing an own api middleware, we've got it working.
Only thing that needs to be done is this #769

**Comment by thomas4Bitcraft** [comment]
@tobsch Can you share your solution how to implement it?

**Comment by bmulholland** [comment]
I'm not clear what the issue here is, and the discussion is a bit old now. I'll close the issue as stale, but please feel free to create a new issue if something is still a problem.
