### ISSUE TITLE
Where did the token property go?

### ISSUE THREAD

**Issue by antonsmolko** [nuxt-community/auth-module#740]
Hi!
I updated package.json and now getting error when trying to get token

![2020-06-24_17-27-59](https://user-images.githubusercontent.com/20865516/85575576-5812a300-b640-11ea-89fc-8975c5af85ae.png)
![2020-06-24_17-27-24](https://user-images.githubusercontent.com/20865516/85575590-5b0d9380-b640-11ea-8781-e7fadc496a6f.png)

I tried to fix this by returning to the previous version ("@ nuxtjs / auth-next": "^ 5.0.0-1590092757.1671dba"). But it did not help.
Then I climbed into the module. But in the constructor Auth did not find the "token" property

![2020-06-24_17-17-30](https://user-images.githubusercontent.com/20865516/85574169-3533bf00-b63f-11ea-9532-36445007437d.png)

And before it was

![2020-06-24_17-22-41](https://user-images.githubusercontent.com/20865516/85576399-0c142e00-b641-11ea-9df2-cdc19ca494ac.png)

How now to access the value of the token property?

**Comment by JoaoPedroAS51** [comment]
Hi @antonsmolko! Now the token instance is initialized inside scheme. You can access it using `this.$auth.strategy.token.get()`.

**Comment by antonsmolko** [comment]
Thank you!

**Comment by agravelot** [comment]
The documentation needs to nbe updated accordingly : https://dev.auth.nuxtjs.org/api/tokens.html
