### ISSUE TITLE
oauth2RefreshTest.vue in the demo app is broken

### ISSUE THREAD

**Issue by kevintechie** [nuxt-community/auth-module#747]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://github.com/nuxt-community/auth-module/blob/dev/demo/pages/oauth2RefreshTest.vue#L119](https://github.com/nuxt-community/auth-module/blob/dev/demo/pages/oauth2RefreshTest.vue#L119)

### Steps to reproduce

1. checkout latest dev branch and install dependencies
1. launch the demo app
1. login using oAuth2
1. follow link to /oauth2RefreshTest
1. see error messages "Cannot read property '_getExpiration' of undefined"

### What is expected ?

I expect to access the page to test out oAuth2 token and refresh token functionality

### What is actually happening?

I see error message. It appears that the this.$auth.token and refreshToken classes are undefined.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c605">#c605</a>)</em></sub></div>

**Comment by kevintechie** [comment]
Is it now recommended to use the Storage class to get and update the tokens for this page? Will updating the tokens via the Storage also update the tokens passed by Axios?

**Comment by kevintechie** [comment]
After some exploring, it looks like the token and refreshToken methods have moved to the strategy object. I might have a PR soon.

**Comment by kevintechie** [comment]
@JoaoPedroAS51 can you confirm my findings about moving of the token and refreshToken methods?

**Comment by JoaoPedroAS51** [comment]
Hi @kevintechie! Thank you for your report! :)

Yes, now the token and refreshToken instances are initialized inside scheme (strategy).

**Note:** This might change in a future release.

**Comment by JoaoPedroAS51** [comment]
Fixed in latest commit 😊

**Comment by kevintechie** [comment]
Thanks, so much. Your commit looked exactly like the changes I made. Also, thanks for the quick response.
