### ISSUE TITLE
this.$auth.loginWith is not a function?

### ISSUE THREAD

**Issue by sergiocastrovale** [nuxt-community/auth-module#75]
- Which operating system are you using ? Windows 10
- Which version of auth-module are you using ? 4.0.0-rc.3
- How did you run your application ? (SSR / SPA / ...) SSR
- Which Nuxt variant are you using ? Nuxt + Express template

I'm trying to integrate this package but so far had no success. My issues:

1) This *could* work:

```
login () {
        this.$auth.login({
          data: {
            email: this.email,
            password: this.password
          }
        }).then(() => {
          this.$toast.success('Logged In!')
        }).catch(e => {
          this.$toast.error(e)
        })
      }
```
... but it seems it's not reading my configs from nuxt.config.js and is always applying defaults (nuxt.config.js sample below) - so I end up having `/api/api/auth/login` paths instead of `/api/testlogin` or any other (dummy) ones.

2) This *doesn't* work:

```
login () {
        this.$auth.loginWith('local', {
          data: {
            email: this.email,
            password: this.password
          }
        }).then(() => {
          this.$toast.success('Logged In!')
        }).catch(e => {
          this.$toast.error(e)
        })
      }
```

I get **this.$auth.loginWith is not a function**.

My nuxt.config.js:

```
  modules: [
    '@nuxtjs/auth',
    '@nuxtjs/axios',
    '@nuxtjs/toast',
    '@nuxtjs/vuetify'
  ],
  ...
  auth: {
    resetOnError: true,
    redirect: {
      login: '/users/login',
      logout: '/',
      home: '/'
    },
    cookie: {
      name: 'testToken',
      options: {
        path: '/'
      }
    },
    token: {
      name: 'testToken'
    },
    strategies: {
      local: {
        endpoints: {
          login: { url: '/testlogin', method: 'post' },
          logout: { url: '/testlogout', method: 'post' },
          user: { url: '/testfetch', method: 'get' }
        }
      }
    }
  }
```

My store:

```
import settings from './modules/settings'
import ads from './modules/ads'
import users from './modules/users'

Vue.use(Vuex)

export default () => {
  return new Vuex.Store({
    modules: {
      settings,
      ads,
      users
    }
  })
}
```

I'm really at a loss here. I was using v3 in another project without any issues, but I can't seem to make v4 work. Any help would be appreciated.

**Comment by AhmedAtef07** [comment]
I think you fetched the library from the master branch, but you are using the released version 4.0.0-rc.3, which doesn't have the code yet. 

Check the actual code you got in your node modules, and you will find out a different one from the master. The code in the master is not pushed yet into a release. 

Hope this solves your problem.

**Comment by wandarkaf** [comment]
It happens the same to me. I'm using V4 :(

**Comment by sergiocastrovale** [comment]
@AhmedAtef07 I've just deleted my whole node_modules folder and `npm install`ed with `"@nuxtjs/auth": "^4.0.0-rc.3"`. There isn't any loginWith method, like you said.

I'm a bit confused: I was just following the docs but apparently none of that is pushed into a live version yet. Is that correct?

**Comment by AhmedAtef07** [comment]
@sergiocastrovale New features are being implemented at the moment it seems, and being pushed to master. When new plans are finished will be pushed into a release, meanwhile you need to stick to the current version, which only supports login as a method. You can dig into the code you find in the node modules, where you can find all possible methods to use. 

If you want to see the code in github, you can check the commits and browse the repo the moment the release was made, I tried to did that for you, but there wasn't any clear point on where the release was taken, nor a branch with that version, nor a documentation from that release.

**Comment by wandarkaf** [comment]
I think this is a big issue, because docs and examples are doing a exposition of this new methods and functionalities, which is kind of confusing. How can we solve this. What is the right version and the right documentation to follow?

**Comment by sergiocastrovale** [comment]
@wandarkaf it definitely is. The problem is the master version has _a lot_ of breaking changes from what we get when we `npm install` (currently v4 rc3).

Our best bet is to make sure we're seeing the readme file from the right tag (https://github.com/nuxt-community/auth-module/tree/v4.0.0-rc.3) but this is very prone to mistakes ...

**Comment by pi0** [comment]
@sergiocastrovale Thanks for your valuable feedback. Meanwhile, i've split `dev` and `master` branches so the docs refer to the latest published version. Also, don't worry, amount of breaking changes is almost so low. Must of the changes are for stability and new features including complete oauth2 support.

**Comment by sergiocastrovale** [comment]
@pi0 Thanks a lot for the effort you're putting into this!
