### ISSUE TITLE
This is Bug?

### ISSUE THREAD

**Issue by antony989** [nuxt-community/auth-module#752]
Version
^4.9.1 & 5.0.0(dev) 

OS: Ubuntu 16.04 LTS
Node: v13.2.0
Backend: strapi

**What is expected ?**

first all works fine.
![imgur](https://i.imgur.com/myG99f7.png)
![imgur](https://i.imgur.com/tt5b7xY.png)

**Status Code: 200 OK**
GET /v1/users/me HTTP/1.1 Host: 127.0.0.1:300 Connection: keep-alive Pragma: no-cache Cache-Control: no-cache Accept: application/json, text/plain, */* Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImlhdCI6MTU5MzY2MjM5NiwiZXhwIjoxNTk2MjU0Mzk2fQ.2CrDolanPwJu9HD3pDZ1VtBuKvL3603dntHn76QZAUE User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Referer: http://127.0.0.1:3000/ Accept-Encoding: gzip, deflate Accept-Language: ko-KR,ko;q=0.9,ja;q=0.8,en;q=0.7 Cookie: auth.strategy=local; auth._token.local=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImlhdCI6MTU5MzY2MjM5NiwiZXhwIjoxNTk2MjU0Mzk2fQ.2CrDolanPwJu9HD3pDZ1VtBuKvL3603dntHn76QZAUE

**However, after a certain period of time, the following error occurs.**
**I did not log out separately. (Auto-Login)**
[There is no toLowerCase in my code once.]
![2020-07-07 오전 9 46 48](https://user-images.githubusercontent.com/24715755/86677757-de62b800-c036-11ea-9d28-c9373751197d.png)

If the error occurs, the function does not work properly and login is not possible.
After exiting the browser and a certain period of time (maybe 3hours later)
![imgur](https://i.imgur.com/xjvgTbI.png)

If it is refreshed after the corresponding error occurs, it works normally.
After refreshing, i can auto login normally
![imgur](https://i.imgur.com/LuND4SE.png)

Browsers: Chrome and Firefox, the bug exists in both browsers, and the live example works as expected in the two browsers.
And i used SSR mode

` 
mode: "universal",
...
 auth: {
    // plugins: [ {src: '~/plugins/axios.js', mode: 'ssr'} ],
    strategies: {
      local: {
        token:{
          property: 'jwt'
        },
        user:{
          property: ''
        },
        endpoints: {
          login: { url: '/v1/auth/local', methods: 'post' },
          user: { url: '/v1/users/me', methods: 'get' },
          logout: { url: '/', methods: 'get' }
        },
        redirect: {
          login: '/login',
          logout: '/',
          home: '/'
        }
      }
    },
    resetOnError: true
  },`

In my guess it seems like a hydration error.
But client-only doesn't solve it.

**Comment by MilesWuCode** [comment]
i have same issue !

**Comment by bmulholland** [comment]
Closing for now; please re-open if Miles' configuration does not resolve the issue.
