### ISSUE TITLE
auth x https - wrong redirect to http

### ISSUE THREAD

**Issue by rawgen** [nuxt-community/auth-module#755]
My stack nuxt with auth module and laravel/socialite have a stranger change in url when call a callback path.

my laravel auth redirect the token to **https**://mysite.com/auth/social-callback?token=[mytoken]
but the nuxt/auth have gerenate a redirect http-code 301 to **http**://mysite.com**:8080**/auth/social-callback?...

to eliminate causes with origins at laravel or nginx, I isolate the rules to nginx and not use laravel.
calling the url _**https**://mysite.com/auth/social-callback_   the same error.

my nuxtconfig:
``` auth: {
    localStorage: false,
    cookie: {
      options: {
        expires: 7
      }
    },
    strategies: {
      local: {
        endpoints: {
          login: {
            url: 'auth/login',
            method: 'post',
            propertyName: 'token'
          },
          user: {
            url: 'me',
            method: 'get',
            propertyName: 'data'
          },
          logout: false
        }
      }
    },
    redirect: {
      login: '/auth/login',
      home: '/',
      logout: '/auth/login'
    },
    plugins: ['./plugins/auth']
  },`

**Comment by gilles6** [comment]
@rawgen  Please, put this before and after your code  ``` to make your code more readable.

**Comment by rawgen** [comment]
For a reason not yet justified, my nginx generated a failure.
We make a partial soliction around, where:
https://mysite.com/auth/social-callback receives a 301 redirect from the server, changing the url to http://mysite.com:8080/auth/social-callback

After force by code a / into url, the problems are apparently solved.
i.e., 
```
https://mysite.com/auth/social-callback/ 
and 
https://mysite.com/auth/social-callback/?token=xxxxxxxxxxxxxxxxxxxx 
```
have success.

Sorry por wrong issue. Tks.
