### ISSUE TITLE
How to implement refresh token through nuxt auth ?

### ISSUE THREAD

**Issue by nerdial** [nuxt-community/auth-module#761]
Hello folks,

I have been trying to find a way to implement refresh token functionality with nuxt auth module, i tried a lot and even read the source code but i could not find a good example to implement it. It seems in new version of nuxt something is missing, some 
methods are not there anymore and docs says it is. 

**what is that strategy people are talking about ? and how to use it ?
Could someone come up with an elegant example ?**

**Comment by JoaoPedroAS51** [comment]
Hi @nerdial! You can check the updated docs here: https://dev.auth.nuxtjs.org/

**Comment by yurriiy** [comment]
Hi @JoaoPedroAS51 is this work in 4.9.1 ?

**Comment by JoaoPedroAS51** [comment]
Hi @yurriiy! No, this is for v5, but it wasn't released yet. If you want to use the dev version, you can install the package `@nuxtjs/auth-next`. Then follow the documentation above :)

**Comment by ojacquemart** [comment]
@yurriiy you should install `@nuxtjs/auth-next`

**Comment by nerdial** [comment]
Is there any way to add more data to refresh token request api ?
 it simply just sends  remember token i need to send more data to my custom api 
@JoaoPedroAS51

**Comment by hvitis** [comment]
Anybody knows if I need to do some extra steps to install the @nuxtjs/auth-next ? Or just change module?
Anybody tried and found a branch that works? I know, not 100% tested but still...

**Comment by jpurdie** [comment]
@hvitis I've been able to get it working with Auth0. Take a look at this repo. Let me know if you have questions https://github.com/jpurdie/frontend_auth

**Comment by hvitis** [comment]
Thanks

**Comment by uchedotphp** [comment]
did you find a way to add more data to the refreshToken for your api? @nerdial

**Comment by ltroya-as** [comment]
I tested the repo and couldn't get the `refresh_token`. Can you guys share your `auth0` config? @hvitis @jpurdie

**Comment by jpurdie** [comment]
@ltroya-as It's been a while since I've done this, but I think I just created an Auth0 application type of "Single Page Application."  What's the problem you're having?

**Comment by ltroya-as** [comment]
@jpurdie Thanks for your response.

Looks like I was missing the `offline_access` scope to receive the refresh token.
