### ISSUE TITLE
I want to use client token until getting access token.

### ISSUE THREAD

**Issue by estylehq** [nuxt-community/auth-module#763]
```
auth-module: v 4.9.1
nuxt: v 2.13.3
```

We created client token for guest user (not logged in user).

so I want to use client token before logged in.

I use custom strategy (extends from local), client token(with id, secret) likes oauth2.

I just defined custom strategy only.

```
   ...
   auth: {
    strategies: {
      custom: {
        _scheme: '~/schemes/CustomLocaleScheme',
        autoFetchUser: true,
        endpoints: {
          login: {
            url: `/api/${process.env.API_VERSION}/login`,
            method: 'post',
            propertyName: 'USER_ACCESS_TOKEN_KEY',
          },
          logout: false,
          user: {
            url: `/api/${process.env.API_VERSION}/users/me`,
            method: 'get',
            propertyName: 'USER_DATA_KEY',
          },
        },
      },
    },
   ...
```

I tried got client token to ```$axios.common.header```, but it seems makes ```null``` after moving other page(s).

request header hasn't ```Authorization``` property.

How can I solve it?

**Comment by bmulholland** [comment]
Sorry, this isn't something that we support so you're on your own. Feel free to create a feature request to add support for guest users, though.
