### ISSUE TITLE
LinkedIn Provider: Requires client_secret

### ISSUE THREAD

**Issue by tobsch** [nuxt-community/auth-module#769]
I got everything working for linkedin. It needs to have a local ```access_token_endpoint```as the original one (https://www.linkedin.com/oauth/v2/accessToken) is not allowing CORS.

One detail that has to be added to the oauth2 module to support linkedins requirements would be: Passing the "client_secret" parameter. 
See https://developer.linkedin.com/docs/v2/oauth2-client-credentials-flow

Could you maybe let the library pass that parameter if it exists in the schema config?

**Comment by cswkim** [comment]
The provider I'm using also requires a `client_secret` parameter to be sent in the token exchange for an `oauth2` scheme. I'm using `auth-next` module, does this mean I have to manually implement the auth flow because of that one item?

@tobsch did you ever find a solution?

**Comment by bmulholland** [comment]
The client secret is just that - secret! If you include it in nuxt, it will be included in your site's JS, which will be happily sent along to every user of your side - _not_ secret! As @Knowledge91 says, don't do this.

If you need to use client_secret, you'll need a backend that does requests using your client secret, which can be securely stored on that server. That's one leg of the "two legged oauth."
