### ISSUE TITLE
How to logout using routes

### ISSUE THREAD

**Issue by freddy-daniel** [nuxt-community/auth-module#771]
I found i can logout by calling `this.$auth.logout()` but i need to execute logout when user route to `/logout` path. I can't find this option anywhere in doc, Only i got config option to set path to redirect after logout success. But i need to trigger logout with route

**Comment by dschewchenko** [comment]
There is no option for this. You can create page for logout and call this.$auth.logout()

**Comment by bmulholland** [comment]
Instead of having a page, I just do this: `<a href="javascript:void(0)" @click="$auth.logout()">Logout</a>`
