### ISSUE TITLE
oauth2 scheme throws nanoid error in v4.

### ISSUE THREAD

**Issue by alperkarahisar** [nuxt-community/auth-module#772]
When oauth2 scheme is used, nanoid generates the error given below with version "^4.9.1".

TypeError: Object(...) is not a function
    at Oauth2Scheme.login (oauth2.js?3a82:92)
    at Auth.login (auth.js?facc:131)
    at eval (auth.js?facc:123)

import nanoid from 'nanoid'
code must be changed to 
import { nanoid } from 'nanoid'

which is fixed in version 5.

**Comment by b1rdhous3** [comment]
Is also fixed with this: 
https://github.com/nuxt-community/auth-module/issues/750#issuecomment-660761642

**Comment by bmulholland** [comment]
Fixed in https://github.com/nuxt-community/auth-module/pull/906
