### ISSUE TITLE
oAuth2 session on server, no logout endpoint available

### ISSUE THREAD

**Issue by RALGIE** [nuxt-community/auth-module#784]
Hello,

I'm using the oAuth2 plugin with "@nuxtjs/auth": "^4.9.1"; When I logout on the client I'm redirected to the login page. My cookie is deleted and I'm on the client site no longer logged in. But on the server site I'm still logged in. Because when I try to login I'm redirected to the main page. Without entering my credentials. When I display the documentation (https://auth.nuxtjs.org/schemes/oauth2.html#options) there is no logout endpoint setting.

Is there an easy way to fix this?

Best regards,
Ralph

**Comment by titoff002** [comment]
hello
i'have a problem with '@nuxtjs/auth-next' with keaycloak, the function this.$auth.loginWith('keycloak')  => this function works correctly, but the other functions do not: they return nothing or null. can you help me ? Have you a complet sample code ?

**Comment by RALGIE** [comment]
hello @titoff002,

I 'm using @nuxtjs/auth and not the @nuxtjs/auth-next version. I can't help you.

**Comment by JoaoPedroAS51** [comment]
Hi @RALGIE! Logout endpoint option for `oauth2` scheme was added in v5. It's now recommended to use v5 instead of v4. See [status](https://auth.nuxtjs.org/status) and #893

Docs here: [oauth2 scheme](https://auth.nuxtjs.org/schemes/oauth2)
