### ISSUE TITLE
Check for existing route query params on redirect

### ISSUE THREAD

**Issue by Sheby** [nuxt-community/auth-module#79]
Hello.
Any chance of making this change on master.
File is: https://github.com/nuxt-community/auth-module/blob/master/lib/templates/auth.class.js
Line 311.

Change it from
```
if (name === 'login') {
    to = to + '?redirect=' + encodeURIComponent(from)
}
```

To 
```
if (name === 'login') {
    let sign = /\?/.test(to) ?  '&' : '?'
    to = to + sign +'redirect=' + encodeURIComponent(from)
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c60">#c60</a>)</em></sub></div>

**Comment by manniL** [comment]
@Sheby Should be fixed in the  `dev` branch.

**Comment by pi0** [comment]
4.0.0 released!
