### ISSUE TITLE
pb with auth-module or @nuxtjs/auth-next, help me please

### ISSUE THREAD

**Issue by titoff002** [nuxt-community/auth-module#790]
Hello,

The connection process it's ok with dev.auth.nuxtjs.org and keycloak.

On the other hand, once the login and password: I go back to my nuxtjs app, but the values (**this.$auth.user**/**this.$store.state.auth.user**) ​​are empty. 

![image](https://user-images.githubusercontent.com/24948237/89424068-9919cf00-d737-11ea-9610-d422bb5b773b.png)

What must be done to make it work?

Do you have any source / demo codes for use with keycloak?

PS: **$auth.fetchUser()** => don't return anything.

my nuxt.config.js :

`
  modules: [
    // Doc: https://buefy.github.io/#/documentation
    'nuxt-buefy',
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    '@nuxtjs/auth-next',
  ],
  router: {
    // middleware: ['auth']
  }, 
  auth: {
    // plugins: [ '~/plugins/auth.js' ],
    cookie: { prefix: 'auth.', options: { sameSite: 'lax' } },
    strategies: {
      keycloak: {
        scheme: 'oauth2',
        user: {
          property: 'user',
          autoFetch: true
        },        
        endpoints: {
          authorization: 'http://127.0.0.1:8080/auth/realms/gedissimo/protocol/openid-connect/auth',
          token: 'http://127.0.0.1:8080/auth/realms/gedissimo/protocol/openid-connect/token',
          userInfo: 'http://127.0.0.1:8080/auth/realms/gedissimo/protocol/openid-connect/userinfo',
          logout: 'http://127.0.0.1:8080/auth/realms/gedissimo/protocol/openid-connect/logout'
        },
        token: {
          property: 'id_token',
          type: 'Bearer',
          maxAge: 1800
        },
        refreshToken: {
          property: 'refresh_token',
          maxAge: 60 * 60 * 24 * 30
        },
        responseType: 'token',
        grantType: 'authorization_code',
        accessType: 'offline',
        redirectUri: 'http://localhost:3000/',
        logoutRedirectUri: 'http://localhost:3000/',
        clientId: 'gedissimo-front',
        scope: ['roles', 'profile', 'email', 'offline_access'],
        state: 'UNIQUE_AND_NON_GUESSABLE',
        codeChallengeMethod: 'S256',
        responseMode: '',
        acrValues: '',
        // autoLogout: false
      }
    }
  },
`

Thank you and have a good day.

**Comment by titoff002** [comment]
i'have a problem with '@nuxtjs/auth-next' with keaycloak, the function this.$auth.loginWith('keycloak')  => this function works correctly, but the other functions do not: they return nothing or null. can you help me ? Have you a complet sample code ?

**Comment by kissu** [comment]
Please provide some properly formatted code if you wish people to help you. ^^

**Comment by bmulholland** [comment]
I don't use keycloak so I'm not able to help, but if you manage to get it working please post what worked so we can update the documentation.
