### ISSUE TITLE
pb oauth2

### ISSUE THREAD

**Issue by titoff002** [nuxt-community/auth-module#791]
hello
i'have a problem with '@nuxtjs/auth-next' with keaycloak, the function this.$auth.loginWith('keycloak')  => this function works correctly, but the other functions do not: they return nothing or null. can you help me ? Have you a complet sample code ?

**Comment by bmulholland** [comment]
This isn't very much to go on. If this is still an issue, please post again with more details and ideally a codesandbox repro.
