### ISSUE TITLE
redirect cause `Cannot set headers after they are sent` error

### ISSUE THREAD

**Issue by PlusA2M** [nuxt-community/auth-module#802]
### Version

v5.0 (latest development build)
~~[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)~~

### Reproduction link

[https://github.com/nuxt-community/auth-module/blob/dev/src/core/middleware.ts#L20:L24](https://github.com/nuxt-community/auth-module/blob/dev/src/core/middleware.ts#L20:L24)

### Steps to reproduce

1) Set any page with `auth: 'guest'`
2) Error on server-sides `Cannot set headers after they are sent to the client`

### What is expected ?

No error

### What is actually happening?

Error thrown

### Additional comments?

I'm currently using @nuxtjs/auth-next, the code on https://github.com/nuxt-community/auth-module/blob/dev/src/core/middleware.ts#L20:L24 should redirect the user to the correct page, however, I think that's a chance for my server to run code on L26:27 `const { tokenExpired, refreshTokenExpired, isRefreshable } = ctx.$auth.check(true)` before the redirect is finished, therefore causing the error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c645">#c645</a>)</em></sub></div>

**Comment by nathanchase** [comment]
This is still a problem, FYI. Always happens when redirecting from login to homepage.

**Comment by cchacholiades** [comment]
Same error here.

```
Cannot set headers after they are sent to the client                                                                              16:21:49

  at new NodeError (node:internal/errors:371:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at Storage.setCookie (server.js:5045:20)
  at Storage.setUniversal (server.js:4897:10)
  at Token._setToken (server.js:5764:26)
  at Token.set (server.js:5712:10)
  at RefreshScheme.updateTokens (server.js:6638:16)
  at RefreshScheme.login (server.js:5943:10)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
