### ISSUE TITLE
Is there a busy state I can use before we know the user is logged in?

### ISSUE THREAD

**Issue by acidjazz** [nuxt-community/auth-module#806]
I'd like to show a proper loading bar while I detect if the user is still logged in.

I noticed in `src/core/auth.ts` you're getting and setting a `busy` attribute

https://github.com/nuxt-community/auth-module/blob/6ab4c1e71bb03d9a588fc82f2120cedac7588af3/src/core/auth.ts#L250

Is this accessable? I tried going after `this.$auth.$state.busy` but I get undefined.

**Comment by fdendorfer** [comment]
Works for me on version ^5.0.0-1595976864.509d9d6. You can also watch .loggedIn, to see, if the user is finished fetching

**Comment by acidjazz** [comment]
@fdendorfer what works for yoU? can you show me how you're using it?

**Comment by bmulholland** [comment]
Do you still get undefined on the latest auth-next version?

**Comment by acidjazz** [comment]
@bmulholland lets been a while, let me test and get back to you.
