### ISSUE TITLE
After success login, i have always 1 extra request every time refreshing the page

### ISSUE THREAD

**Issue by santas156** [nuxt-community/auth-module#808]
After success login, i have autoFetchUser out of the box, and it`s working fine, and user is set in vuex store.
But when i refreshing the page, i have 1 extra request **/api/user/**
My all app is waiting for that request. After it finished, i have in response a user data, and then user in set to vuex store.
So every time i refresh the page? my all app is in guest mode and then flicker to auth mode.
In tutorial, there is no extra request and user data is stored even without js on site

![Снимок экрана 2020-08-25 в 18 21 58](https://user-images.githubusercontent.com/6577091/91268558-3cca2e00-e77e-11ea-8374-2581bc981020.png)

**nuxt.config.js**

```

import path from 'path'
import fs from 'fs'
import SVGSpritemapPlugin from 'svg-spritemap-webpack-plugin'

export default {   
  
    axios: {
        baseURL: 'https://api.local.test/v1',
    },

    mode: 'universal',

    target: 'server',

    server: {
        port: 3666,
        host: 'local.test',
        timing: false,
        https: {
            key: fs.readFileSync(path.resolve('/Users/local/.config/valet/Certificates', local.test.key')),
            cert: fs.readFileSync(path.resolve('/Users/local/.config/valet/Certificates', 'local.test.crt'))
        }
    },

    head: {
        title: process.env.npm_package_name || '',        
    },

    css: [
        '@assets/v3/scss/_animations.scss'
    ],

    plugins: [
        '@plugins/directives.js',
        '@plugins/vee-validate.js',
        '@plugins/axios.js',
    ],

    components: true,

    buildModules: [],

    modules: [
        '@nuxtjs/axios',
        '@nuxtjs/auth',
        '@nuxtjs/pwa',
        '@nuxtjs/style-resources',
        'vue-scrollto/nuxt',
    ],


    build: {
        transpile: ["vee-validate/dist/rules"],        
       
    },

    auth: {
        strategies: {
            local: {
                endpoints: {
                    login: {url: '/auth/login', method: 'post', propertyName: 'data.token'},
                    logout: {url: '/auth/logout', method: 'delete'},
                    user: {url: '/auth/user', method: 'get', propertyName: 'data'},
                },
            },
        },
    },

    router: {
        prefetchLinks: false,
    },

    styleResources: {
        scss: [
            '@assets/v3/scss/_variables.scss',
        ]
    },
}
```

**Login function**

```
          async login() {
                try {
                    let valid = await this.$refs.loginForm.validate()
                    if (valid)
                        await this.$auth.loginWith('local', {data: this.form})
                } catch (error) {
                    if (error.response && error.response.status === 422)
                        this.$refs.loginForm.setErrors(error.response.data.errors)
                    else
                        this.setToastError(error);
                }
            },
```

**Comment by msonowal** [comment]
It must be after the new axios module update

**Comment by nikolayandreev** [comment]
If you want to take control over the user request, you can try https://github.com/nuxt-community/auth-module/issues/828#issuecomment-692036117

**Comment by Lacroute** [comment]
Normal behavior > https://auth.nuxtjs.org/schemes/local.html#autofetchuser

**Comment by msonowal** [comment]
@Lacroute 
Its not true if you do a full reload it will only make one extra request from server side but not again from client side
as the recent axios upgrade has this breaking change in place which makes 2 api calls one from server which returns not authorized as it does not pass the cookies and another from client to get the status again and it will be authorized

**Comment by Lacroute** [comment]
You can log the error by adding a `onError` plugin and see wich method is affected. I notice a `method: request` first then a `method: login` too as you decribe when I have a loggin error.

**Comment by bmulholland** [comment]
The user info is not persisted, and so a fetch to the user endpoint on every page load (to know whether the user is still logged in) is expected behavior.
