### ISSUE TITLE
Page Redirect

### ISSUE THREAD

**Issue by sarfarazengglb** [nuxt-community/auth-module#811]
I am using     "@nuxtjs/auth": "nuxt-community/auth-module#ab927f6557124802003f87a8c5da9af905ea94bd",

When i am logging in with local login The page is redirected temp to the default logout page and then to the intented url.I want to send user to the success page without intermediate redirection.

```javascript
//Login code
 return this.$auth
        .loginWith("local", {
          data: loginData
        })
        .then(res => {
           this.$nuxt.$loading.finish();
           console.log(res);
           if (this.$auth.loggedIn==true) {
            this.$axios.setHeader("x-api-key", this.$auth.user.token);
            this.$toast.success(
              "Your order was placed successfully.Please proceed to payment."
            );
           if (this.$auth.loggedIn==true) {
          this.$router.push("/stores/"+this.name+"/payment")
         }
          } else {
            this.$toast.error("Your OTP is wrong!!!");
           
          }
        })
        .catch(e => {
         console.log(e);
         this.$nuxt.$loading.finish();
           this.$toast.error("Login Failed"+e);
        });
}
```

**Comment by bramburn** [comment]
you need to change the settings in your config so that you set the `redirects` config correctly:
https://dev.auth.nuxtjs.org/api/options#redirect

please use https://cmty.app/nuxt/issues/new?repo=auth-module

**Comment by manalab17** [comment]
I have same issue. is there other ways to redirect success page without redirect `home` route?

**Comment by bramburn** [comment]
> 
> 
> I have same issue. is there other ways to redirect success page without redirect `home` route?

what is the issue here? can you elaborate the sequence to replicate the issue. Or please raise a new ticket.

**Comment by manalab17** [comment]
> > I have same issue. is there other ways to redirect success page without redirect `home` route?
> 
> what is the issue here? can you elaborate the sequence to replicate the issue. Or please raise a new ticket.

It is not issue, just a problem to me.

is the only way that set `home` link in config to redirect after auth.login?

**Comment by bmulholland** [comment]
@manalab17 If this is still an issue for you? If so, please create a new issue with more details.

Closing this one as fixed - please let us know if it isn't.
