### ISSUE TITLE
Authenticatio with Google doesn't work

### ISSUE THREAD

**Issue by YannickSilva** [nuxt-community/auth-module#812]
I guys i'm having some issues whenever i try to login with google oauth, they say in console.log that it's not a function:

TypeError: Object(...) is not a function
    at Oauth2Scheme.login (oauth2.js?3a82:92)
    at Auth.login (auth.js?facc:131)
    at eval (auth.js?facc:123)

I already defined the client id in the nuxt config

**Comment by bramburn** [comment]
@YannickSilva  use this to raise the issue https://cmty.app/nuxt/issues/new?repo=auth-module

**Comment by vinayakkulkarni** [comment]
try:

```
npm i nanoid@2
```

**Comment by bmulholland** [comment]
Fixed in https://github.com/nuxt-community/auth-module/pull/906
