### ISSUE TITLE
v5 - Any specific v5.0.0-xxxxxxxxxx version to use as Alpha / Beta for now ?

### ISSUE THREAD

**Issue by Jonarod** [nuxt-community/auth-module#818]
Sorry for not using the template but the `dev` branch is not listed as a valid version...

I have installed `@nuxtjs/auth-next` to my project as suggested in various issues answers (I need refresh tokens) and nothing seems to work as mentioned in the dev-docs which I guess is normal since `dev` branches usually corresponds to fast sprints.

For instance, I just need to add the `local refresh` strategy like described in the dev-docs, but for whatever reason, redirects won't work on the latest `5.0.0-1595976864.509d9d6` version and it won't even let me to redirect manually using `this.$route.replace('/')` neither. Also it needs manual page reload by the user to make the `isLogged` variable effective. This version is not operable as-is.

I was wondering if someone knows of any v5 version that might be closer to the docs or close to the definition of a more stable `alpha` / `beta` version?

Thanks !

**Comment by bramburn** [comment]
weird, its working for me.
maybe you can elaborate on the actual issue?

are you using auth-next right?

**Comment by Jonarod** [comment]
Yes I did followed all the steps in [https://dev.auth.nuxtjs.org](https://dev.auth.nuxtjs.org) word for word.

But just as I write and after a long trial and error night I think I got the issue...

It is a documentation issue actually: it is never implied nor specified that the very `login.vue` component should also have the `middleware:['auth']` which seems counter-intuitive IMHO. In fact, the docs and specifically this page [https://dev.auth.nuxtjs.org/guide/middleware](https://dev.auth.nuxtjs.org/guide/middleware) implies that the `auth` middleware is aimed at protecting secret pages. I was naively thinking that specifying `middleware:['auth']` in the `login.vue` page would block access to it, so I was never putting it in.

Only after some researches in the `/demo` folder of the dev branch I could spot that. And now I can get that without the `middleware:['auth']` in the `login.vue` the whole redirect logic was not even triggered...

IMHO it would be helpfull to either:
- Specify that clearly in the docs examples directly
- or let the option `auth.redirects.login` in the nuxt.config.js to enforce the logic automatically. i.e: if `auth.redirects.login==false`do nothing, but if `auth.redirects.login != false` enforce redirections from `login` to `home`.

**Comment by bramburn** [comment]
do you think you could correct the docs and PR?

**Comment by rahsaf90** [comment]
have you tried adding below in nuxt.config.js, if you want to protect all your routes.
	
        **router: {
		middleware: ['auth'],
	},**

**Comment by bmulholland** [comment]
Thanks for the thoughts, @Jonarod. I've created #904 to track your doc suggestions. With respect to the original question in this repo, any version published in the v5 series should be fine, but be aware that these are auto-published from `master` so for now we recommend fixing your package.json to a specific version and upgrading with care. See [the status page](https://auth.nuxtjs.org/status/) for more info.

**Comment by ponnex** [comment]
For those who want to implement their own middleware, I've implemented my own instead of using the middleware `auth` that comes with this module and named it `authentication` as using `auth` would use the module middleware `auth`. For example, if the user is logged in and the current route is `signup` I could redirect the user to `/`  and so on. I could add more routes as well.

```ts
import { Middleware } from '@nuxt/types';
import { Auth } from '@nuxtjs/auth-next';

declare const _: any;

const routeAuths: string[] = [
  'profile',
];

const routeNoAuths: string[] = [
  'login',
  'signup',
];

const auth: Middleware = (context: any) => {
  const { $auth, redirect, route }: { $auth: Auth, redirect: Function, route: any } = context;
  const isLoggedIn = $auth.loggedIn;
  if (isLoggedIn) {
    if (_.includes(routeNoAuths, route.name)) {
      return redirect('/');
    }
  } else if (_.includes(routeAuths, route.name)) {
    return redirect('/login');
  }
};

export default auth;

```
