### ISSUE TITLE
User is fetched on every route switch

### ISSUE THREAD

**Issue by exophunk** [nuxt-community/auth-module#820]
```javascript
strategies: {
    local: {
        scheme: 'refresh',
        ...
        user: {
            property: 'user'
        },
        endpoints: {
            login: { url: '/api/v1/auth/login' },
            logout: { url: '/api/v1/auth/logout' },
            user: { url: '/api/v1/auth/user' },
            refresh: { url: '/api/v1/auth/refresh' }
        }
    }
}

```

`"@nuxtjs/auth-next": "^5.0.0-1595976864.509d9d6",`

I use auth-next, because I need Refresh Token. Login and everything works great. But I see that User is fetched again and again and again.

I have a backend API url to deliver the user /api/v1/auth/user (node express). For testing, I've added a log to the function and I see in the backend that the function is called not only on page reload (when logged in) but sometimes twice and also on almost every route switch. So even when I simply go from one page to another, the user is loaded again. As I authenticate via an external API, this creates a big amount of unnecessary API calls.

Is this intended or do I have a bug somewhere? My gut feeling says that it is only necessary on page reload to fetch a user and then never again as it is stored in $auth.user?

Why is this function called so often? As I don't see a /api/v1/auth/user in the network tab, it seems to only happen serverside and it doesn't look right?

**Comment by bramburn** [comment]
I will take a look but I normally get loads of user/ request but I never thought i was an issue.

**Comment by nikolayandreev** [comment]
Can you see if that might help: https://github.com/nuxt-community/auth-module/issues/828#issuecomment-692036117

**Comment by JoaoPedroAS51** [comment]
Hi @exophunk! Can you test if issue still persist in latest version of auth v5?

**Comment by exophunk** [comment]
Now using `"@nuxtjs/auth-next": "^5.0.0-1608461079.ae1e5db"`.

I found out that it only happens in development mode locally. When I've run a production build (`nuxt build` `nuxt start`), it does not happen. So maybe it was only while developing (`npm run dev`) to begin with. Seems to be (or always was) fixed for production build.

Thx!
