### ISSUE TITLE
Redirect after login doesn't occur for nested routes, only basic routes

### ISSUE THREAD

**Issue by james-tyner** [nuxt-community/auth-module#821]
I'm trying to use the `@nuxtjs/auth` module for OAuth2 authentication from Okta in a web app.

My app has a URL structure like: `/browse/{folder}` to view images from a particular folder, where `{folder}` can be any string of text. This is accomplished by creating a top-level view called `browse.vue`, a folder called `browse`, and a child component within that folder called `_folder.vue`. See more on nested routes in the Nuxt.js documentation in more detail [here](https://nuxtjs.org/guide/routing/).

![Screen Shot 2020-08-25 at 9.53.58 PM.png](https://cmty.s3.eu-west-1.amazonaws.com/102371998/2cc02670-e758-11ea-8138-e96263a9d65a.png)

I've added the auth middleware to the `_folder.vue` file. When I navigate to `/browse`, I'm redirected to `/login` and everything works perfectly from here with OAuth2 and Okta. When I'm returned to the app after logging in, I'm taken back to the `/browse` page.

However, if I navigate to a folder, like `/browse/Test`, I'm not redirected back to that folder after logging in. Instead, I'm returned to the `/` view of the app. From here, if I type the path in the address bar again, I am able to successfully view it as a logged in user. This indicates that the login was successful, but something about the redirect wasn't.

I noticed by looking at the cookies in the Firefox developer tools that an `auth.redirect` cookie is not created when I navigate to `/browse/Test`, so I think the auth module is not aware of where to redirect the user after logging in. When I navigate to `/browse`, the `auth.redirect` cookie is created, and the redirect occurs successfully.

Is there something I can do to make the auth module work for redirecting to these dynamic routes, or is this a bug with the module? Everything else about the module has worked perfectly in my app. 

My auth configuration in `nuxt.config.js`, using `@nuxtjs/auth` version 4.9.1:
```
  auth: {
    fullPathRedirect:true,
    redirect:{
      callback:"/login",
      logout:"/"
    },
    strategies: {
      social:{
        _scheme: 'oauth2',
        authorization_endpoint: "https://{my-subdomain}.okta.com/oauth2/v1/authorize",
        scope: ['openid', 'profile', 'email'],
        access_token_endpoint: "https://{my-subdomain}.okta.com/oauth2/v1/token",
        response_type: 'id_token',
        token_type: 'Bearer',
        client_id: process.env.CLIENT_ID,
        client_secret:process.env.CLIENT_SECRET,
        token_key: 'id_token'
      }
    }
  }
```

**Comment by jclaessens97** [comment]
@james-tyner  did you try adding nanoid dependency v2 instead of v3 in your package.json? (see #750

**Comment by james-tyner** [comment]
Just tried that and it didn't resolve it. I think what that issue is describing is that the user is not directed to the Google sign-in page, but that's been happening properly for me. My issue is about where the user is directed after they return from Google sign-in.

**Comment by bmulholland** [comment]
Does this work if you upgrade to `@nuxtjs/auth-next`?

**Comment by james-tyner** [comment]
@bmulholland with `auth-next`, I've always gotten an error in response to a login attempt: `The authorization server encountered an unexpected condition that prevented it from fulfilling the request.` Okta logs show no contact was made with their server, so this error is occurring within the Nuxt app somehow.

This is the configuration I have for `auth-next`:
```
  auth: {
    fullPathRedirect:true,
    redirect:{
      callback:"/login",
      logout:"/"
    },
    strategies: {
      social:{
        scheme: 'oauth2',
        endpoints:{
          authorization:"https://{my-subdomain}.okta.com/oauth2/v1//authorize",
          token:"https://{my-subdomain}.okta.com/oauth2/v1//token"
        },
        token:{
          property:"id_token",
          type:"Bearer"
        },
        responseType:"id_token",
        scope: ['openid', 'profile', 'email'],
        clientId: process.env.CLIENT_ID,
        clientSecret:process.env.CLIENT_SECRET
      }
    }
  }
```

**Comment by bmulholland** [comment]
There's a double slash in the endpoint URLs - is that the problem?

Beyond that, it's hard for me to debug much, since obviously I don't have your code running. We're focused on getting auth-next ready and have basically frozen v4.9, so I'd rather get that fixed for you.
