### ISSUE TITLE
Add option to disable redirect when calling setUserToken or login

### ISSUE THREAD

**Issue by dansullivan86** [nuxt-community/auth-module#823]
### What problem does this feature solve?

My app has a form that includes a login as part of the flow.  I need to log the user in, then submit the form and handle validation responses.  Currently as soon as the user is logged in they are redirected.  N.B I do use the login redirect for other login flows.

### What does the proposed changes look like?

Add an options param to setUserToken / login that enables you to disable the redirect.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c666">#c666</a>)</em></sub></div>

**Comment by bhaskar-nair2** [comment]
Is there an update on this?
