### ISSUE TITLE
$auth.user is not change with $auth.setUser()

### ISSUE THREAD

**Issue by mahammad-sixberries** [nuxt-community/auth-module#831]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

- manually update user with $auth.setUser() (i.e, from profile page)
- it will change in store (local storage)  but won't update in $auth.user

### What is expected ?

$auth.user should update with $auth.setUser()

### What is actually happening?

$auth.user is not updating with $auth.setUser()

### Additional comments?

- using Classic mode of the store with the persisted state (vuex-persistedstate)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c668">#c668</a>)</em></sub></div>

**Comment by bmulholland** [comment]
Please create a new issue for the issue in auth-next, ideally with a repro and proof it's not just your server or configuration that's wrong.
