### ISSUE TITLE
Bearer not include in Authorization

### ISSUE THREAD

**Issue by nal-ws-001** [nuxt-community/auth-module#832]
After successful login, fetch the user api.
Token is included but bearer in not include.
I used setToken('local', token)
Then i fetchUser()

"@nuxtjs/auth": "^4.9.1",
"@nuxtjs/axios": "^5.12.2",
"nuxt": "^2.14.5",

**Comment by Neilpoulin** [comment]
I am having the same issue. The `Authorization` header in the request is just my JWT. If I configure my server to just use the full value from the Authorization header, everything works. I'd like to use the `Bearer XXXTOKEN` scheme if possible. 

Here's my full `auth` config in `nuxt.config.js`

```json
auth: {
    strategies: {
      local: {
        endpoints: {
          login: {
            url: '/users/sessions',
            method: 'post',
            propertyName: 'token',
          },
          logout: { url: '/users/sessions', method: 'delete' },
          user: {
            url: '/users/current',
            method: 'get',
            propertyName: 'user',
          },
        },
        tokenRequired: false,
        tokenType: 'bearer',
      },
    },
  }
```

**Comment by nal-ws-001** [comment]
I fixed by adding Bearer when set token.
