### ISSUE TITLE
Cannot read property 'onError' of undefined

### ISSUE THREAD

**Issue by ikristher** [nuxt-community/auth-module#85]
I've tried using the snippet codes on handling error but it is returning an error. I need to catch the error when the user inputs and invalid credentials. 

Here are the things I've done
1. I created plugins/auth.js and placed this code
```
export default function({ $auth }) {
    $auth.onError((error, name, endpoint) => {
        console.error(name, error)
    })
}
```
2. Add this code to nuxt.config.js
```
{
     plugins:['@/plugins/auth.js'],
}
```

It is returning Cannot read property 'onError' of undefined.
Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/auth-module/issues/c63">#c63</a>)</em></sub></div>

**Comment by javialon26** [comment]
Hello @ikristher i had the same error with v4.0.0-rc.3. My workaround is use app param in destructuring.

Example
```
export default function({ app }) {
    app.$auth.onError((error, name, endpoint) => {
        console.error(name, error)
    })
}
```

**Comment by carmas123** [comment]
This work fine but when I try to use $auth into vue file I got same error

```
 this.$auth.login({
        data: {
          username: this.username,
          password: this.password
        }
      });
```

**Comment by pi0** [comment]
Hi. With 4.0.0 you can now handle login errors.

**Comment by Ashraam** [comment]
Still have the same problem with ^4.2.0

Any fix for this ?

**Comment by samburgers** [comment]
Same problem with ^4.3.0, @javialon26 suggestion doesnt appear to work either. :/

**Comment by samburgers** [comment]
Works for me, could be worth double checking your `plugins` are declared inside the `auth` (rather than the regular place you setup nuxt plugins)

```
{
  modules: {
    '@nuxtjs/auth'
  },
  auth: {
     plugins: [ '~/plugins/auth.js' ]
  }
}
```

https://auth.nuxtjs.org/recipes/extend.html

**Comment by skilljobs** [comment]
This still does not work
