### ISSUE TITLE
Where is ../utilities?

### ISSUE THREAD

**Issue by valVk** [nuxt-community/auth-module#860]
Hi, OAuth module cannot be extended due to missed `../utilities` folder.
Is this important bug? I looked into release tags and did not saw that folder starting form release version `4.0.0` but I see that there is fix from not existed code https://github.com/nuxt-community/auth-module/pull/587/files.
I believe that this is important bug because `4.9.1` version is in production.

**Comment by valVk** [comment]
@pi0 ping

**Comment by matheyal** [comment]
Just encountered this issue too. It would be awesome to have the PR accepted

**Comment by bmulholland** [comment]
Thanks for the patch - merged :)
