### ISSUE TITLE
Cannot set property '~auth' of undefined     with auth-next

### ISSUE THREAD

**Issue by makerGeek** [nuxt-community/auth-module#870]
when running the nuxt app with "@nuxtjs/auth-next": "^5.0.0-1602966760.822bc05" I get the error message

```
 FATAL  Cannot set property '~auth' of undefined                                                  00:15:37

  at ModuleContainer.default (node_modules/@nuxtjs/auth-next/dist/module/index.js:33:33)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:177:34)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1664:43)

```

**Comment by bmulholland** [comment]
Can you please post more information? A working repro would be most helpful: https://codesandbox.io/s/nuxt-auth-demo-45icg

**Comment by JoaoPedroAS51** [comment]
Closing here, as this issue should be fixed in latest version of v5 and due to inactivity. Feel free to reopen if issue persist :)
