### ISSUE TITLE
I feel like really stupid

### ISSUE THREAD

**Issue by igordata** [nuxt-community/auth-module#875]
I spent a few last days trying to make auth module work. And I failed.

I googled for many hours how to make a simple (as I thought) thing: nuxt with auth providing Google oAuth2 login and setting jwt token on success.

What went wrong:
- no working examples for that case in auth repo/wiki
- the google auth example works in the wrong way - the user gets authorized without sending a server-side verification request to google.
- auth module skips request to the backend for no reason randomly when I tried to use examples from stackoverflow due no version was mentioned and different config syntax
- it took some time to figure out why many developers use config syntax that differs from the documentation.
- two documentations for the same v4: https://auth.nuxtjs.org/ and https://dev.auth.nuxtjs.org/
- lots of examples use v5 when it is unstable and is risky to use in production so have no practical value

OK, just give up. I'm stupid. Auth module is about to reach its 5 version. Google has millions of pages mentioning nuxt and auth, its simplicity and how its so great. Developers use it and looks like they are happy. And I'm just not one of them.

I'll do a classic /auth/google server-only location to do all that server-side. I'll try to use auth module only for jwt token. If I'll make work somehow.

Thanks.

**Comment by bmulholland** [comment]
I'm sure everyone is busy and has other priorities, and that's fine, but this project really needs some maintainer love.

**Comment by bmulholland** [comment]
@pi0 @JoaoPedroAS51 Do you need help maintaining this?

**Comment by arnaud16571542** [comment]
Hello.
I was struggling with axios & auth for several days implementing JWT with refresh token... Finally, I identified my problems:
* Using a mix of this.$axios and axios... That's why most of my requests didn't work with auth.
* I used the dev-auth documentation v5 which work with refresh token with the local scheme...and installed the lastest 4.x...
---
The dev-auth website is really nice.... BUT can lead to mistake. Maybe a banner on the top off all pages which explain the web site is a 'work in progress' for the next auth version could avoid to this situation :).

By the way: thank you for this plugin..It works great when all parts are correctly assembled !!

**Comment by kissu** [comment]
True that it took me some time to understand how this one is working but then, it's cool to use (implemented homemade JWT from a backend + Auth0 as a test).
Your use case just should not differ to much from the magic configuration given to you.

**Comment by pi0** [comment]
Hi @igordata. Thanks for reaching out and mentioning this. I have tried to explain history of module and current status in #893. Still apologizes for inconveniences for module usage.

Any help on documentation is of course more than welcome.

**Comment by serenalucasjose** [comment]
I had a pretty rough experience with this module, thou the idea of using Strategy DP is cool, implementing this module on an on-going project with custom login logic was impossible. Guess the idea is to use it from the start.

**Comment by kissu** [comment]
@serenalucasjose it will be reworked in depth anyway for Nuxt3: https://v3.nuxtjs.org/community/roadmap#%EF%B8%8F-roadmap 😉
