### ISSUE TITLE
Callback not working in production

### ISSUE THREAD

**Issue by Ethan-Hill** [nuxt-community/auth-module#880]
[Image of error](https://i.imgur.com/YxijebX.png)

When I redirect from a login it does this, but in development, it work perfectly. 

Any ideas?

**Comment by sdil** [comment]
I believe this is because your "Authorization callback URL" in your nuxt.config.js is not the same as in Github settings. Refer to step #8 here https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-an-oauth-app

**Comment by Ethan-Hill** [comment]
> 
> 
> I believe this is because your "Authorization callback URL" in your nuxt.config.js is not the same as in Github settings. Refer to step #8 here https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-an-oauth-app

I have not set this directly in my config

**Comment by eramosr16** [comment]
Same issue here, oauth + keycloak, authorization works perfect on DEV not working in production

**Comment by bmulholland** [comment]
The attached error is indeed a problem with configuration on the OAuth provider. For security reasons, you must set your production URL with the provider itself. This isn't an issue with the auth module, so closing out.
