### ISSUE TITLE
Callback Error Handling

### ISSUE THREAD

**Issue by bmulholland** [nuxt-community/auth-module#883]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://nuxt-auth.herokuapp.com/callback?error=access_denied&error_description=The%20user%20has%20denied%20your%20application%20access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=mk-asdfasdf](https://nuxt-auth.herokuapp.com/callback?error=access_denied&error_description=The%20user%20has%20denied%20your%20application%20access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=mk-asdfasdf)

### Steps to reproduce

If something goes wrong with OAuth, or the user clicks "cancel" partway through, they are redirected to the callback page and no error mechanism is available. `onError` isn't thrown, and there's no built-in convenience methods to deal with this. The error is not displayed on the page, and the nuxt error page is not displayed. The code just bails: https://github.com/nuxt-community/auth-module/blob/5772ccbde2ff32538f6562bcfc2c6576a6b5bc17/src/schemes/oauth2.ts#L345

Digging through the code, it does seem that fetchUser is called in this situation, and it would /seem/ like callOnError should be called as a result: https://github.com/nuxt-community/auth-module/blob/6ab4c1e71bb03d9a588fc82f2120cedac7588af3/src/core/auth.ts#L155

However, in this case, oauth2 just returns outright, which is not an error to be caught, and so it all falls right through.

The demo app is affected by this bug: https://nuxt-auth.herokuapp.com/callback?error=access_denied&error_description=The%20user%20has%20denied%20your%20application%20access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=mk-asdfasdf

### What is expected ?

I'd expect there to be some way to handle these types of errors. Probably a hook for receiving the error message, and probably a redirect - to home or login page or error page.

### What is actually happening?

User sees endless spinner and there's no built-in way to catch it.

### Additional comments?

This seems like it should be core functionality? Am I missing something?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c706">#c706</a>)</em></sub></div>

**Comment by tnabil** [comment]
Has anyone found any work-arounds for this? I'm particularly interested in handling the case when the callback URL is called with a server error. At the moment, as @bmulholland mentioned, the user gets stuck on the callback page.

**Comment by goatfryed-holos** [comment]
Also run into this issue. I think, there is a flaw in the setup. As others pointed out, the runtime will call `callOnError` with the error, but since no error handlers are registered, nothing happens.
My expectation would be, that plugins are configured before the auth plugin handles anything.

`$auth.error` is a possible workaround to get any feedback. If it's an axios error, we can get the url with `$auth.error.config.url` and the response with `$auth.error.response`.  I guess it's enough to add some useful logic, but it's not quite straight forward and we need to figure out the endpoint and the method for ourself.

**Comment by LangRizkie** [comment]
Any updates on this?

**Comment by bmulholland** [comment]
No, and asking for updates isn't going to make anything happen. Please don't do that.

If you'd like to make progress on this, please write up a proposal of how we should implement it. What's the API? What code would change? Or even a PR with a sample implementation for discussion would be welcomed. That would do much more to get what you want :)

**Comment by LangRizkie** [comment]
i tried to use `$auth.error` and returned `undefined`, `onError` function doesn't seems fired on 400

**Comment by bmulholland** [comment]
Yep, that's right, as stated in the OP
