### ISSUE TITLE
feature: Support login with multiple auth providers in the same session.

### ISSUE THREAD

**Issue by dalexhd** [nuxt-community/auth-module#889]
### What problem does this feature solve?

I want my users to be able to login with a custom provider in my application, and optionally if they want, to be able to log in with any other provider like Spotify.

In >5.0.0 version you're only able to login with a single provider. My idea is to give the availability to store multiple provider's authentication states in all the NuxtJS lifecycle.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c711">#c711</a>)</em></sub></div>

**Comment by laurensV** [comment]
This would be a great feature to have! Any updates on the progress?
