### ISSUE TITLE
refresh token with expired authorization token 

### ISSUE THREAD

**Issue by HenriqueLimaUpp** [nuxt-community/auth-module#924]
Hi guys, i'm using v5 and facing a issue to get auto refresh token, because the request to get a new token is being sent when the authorization token is already expired, then i'm receiving status code 403 from response. What can i do on my client side to fix that?

**Comment by HenriqueLimaUpp** [comment]
Forget it... i figout out the problem. Thanks!

**Comment by JoaoPedroAS51** [comment]
Hi @HenriqueLimaUpp ! The `refresh` endpoint in your backend shouldn't be protected by authorization token. That's the easier way to fix.

But if there is no way to fix the endpoint, I recommend creating a custom sheme that extends the `refresh` scheme, then add a method to schedule auto refresh. See #910

The built-in auto refresh feature was removed, but you can take a look a the code at #634

If you need help to make the auto refresh, just ping me.

**Comment by HenriqueLimaUpp** [comment]
Custom scheme worked like a charm! Thank you very much, @JoaoPedroAS51

**Comment by HenriqueLimaUpp** [comment]
One last thing, although it worked great, i did override the login method for initialize auto refresh schedule when user sign in. It's there a way to watch sign in request wihout override any method?

**Comment by HenriqueLimaUpp** [comment]
I figout out there is a watchState method, that works great as well ;)

**Comment by JoaoPedroAS51** [comment]
Hi @HenriqueLimaUpp! When creating your custom scheme, import the `refresh` scheme like this:
```js
import RefreshScheme from '~auth/schemes/refresh'
```

Otherwise, you may get the error: **Cannot use import statement outside a module**

I just updated #910, fixing the path.

**Comment by CavalcanteLeo** [comment]
> Custom scheme worked like a charm! Thank you very much, @JoaoPedroAS51

Can you share the code?

**Comment by HenriqueLimaUpp** [comment]
> > Custom scheme worked like a charm! Thank you very much, @JoaoPedroAS51
> 
> Can you share the code?

nuxt.config.js
```
  auth: {
    strategies: {
      local: {
        // scheme: 'refresh',
        scheme: '~/schemes/auto-refresh-token',
        token: {
          property: 'token',
          type: ''
        },
        refreshToken: {
          property: 'refresh_token',
          tokenRequired: true
        },
```
schemes/auto-refresh-token.js
```
import RefreshScheme from '@nuxtjs/auth-next/dist/schemes/refresh'
import Token from '@nuxtjs/auth-next/dist/inc/token'
import RefreshController from '@nuxtjs/auth-next/dist/inc/refresh-controller'

export default class CustomScheme extends RefreshScheme {
  constructor ($auth, options) {
    super($auth, options)
    this.token = new Token(this, this.$auth.$storage)
    this.refreshController = new RefreshController(this)
    this._refreshInterval = undefined

    this.$auth.$storage.watchState('loggedIn', () => {
      if (this.$auth.loggedIn) {
        this.initializeScheduledRefresh()
      } else {
        clearInterval(this._refreshInterval)
      }
    })
  }

  refreshIn () {
    return (this.token._getExpiration() - Date.now()) * 0.75
  }

  initializeScheduledRefresh () {
    if (!this.$auth.loggedIn) {
      return
    }

    let intervalDurationMillis = this.refreshIn()

    if (intervalDurationMillis < 1000) {
      intervalDurationMillis = 1000
    }

    clearInterval(this._refreshInterval)

    this._refreshInterval = setInterval(() => {
      this.refreshController.handleRefresh()
        .then(() => this.initializeScheduledRefresh())
    }, intervalDurationMillis)
  }
}
```

**Comment by HenriqueLimaUpp** [comment]
> ```js
> auth/schemes/refresh
> ```

I'm gonna fix it. Thank you!

**Comment by HenriqueLimaUpp** [comment]
> Hi @HenriqueLimaUpp! When creating your custom scheme, import the `refresh` scheme like this:
> 
> ```js
> import RefreshScheme from '~auth/schemes/refresh'
> ```
> 
> Otherwise, you may get the error: **Cannot use import statement outside a module**
> 
> I just updated #910, fixing the example.

I'm gonna fix it. Thank you!

**Comment by CavalcanteLeo** [comment]
I updated to auth-next, but something weird is happening.

After login, the page is not redirected, and even if i type the URL on browser, it goes to login page, and the cache is all set with the a valid token after login. @JoaoPedroAS51

**Comment by CavalcanteLeo** [comment]
@JoaoPedroAS51 sure:

https://github.com/nuxt-community/auth-module/issues/947
