### ISSUE TITLE
Redirection to login page on hard refresh even if Logged In already (laravel/sanctum)

### ISSUE THREAD

**Issue by mohsenMJ** [nuxt-community/auth-module#926]
### Version
module: 5.0.0-1607600955.506103a
nuxt: 2.14.11

#### [mode] univeral
 - [x] universal
 - [ ] spa

## Reproduction
for backend I installed Laravel 8 + laravel/sanctum to handle the authentication.
for frontend I installed Nuxtjs along with @nuxtjs/auth-next package and everything worked fine,

1. http://localhost:8000/sanctum/csrf-cookie ---> Ok
2. http://localhost:8000/login ---> Ok
3. http://localhost:8000/api/user---> Ok
4. redirected to /dashboard with `middleware : 'auth'`

except when I hard refresh on all pages with middleware "auth" it redirects to login page.
here is what I have learnt so far : 

this file `"node_modules/@nuxtjs/auth-next/dist/core/middleware.js"` is responsible for "auth" middleware, when I hard refresh on a page with middleware "auth" attached , in line 16 `if (ctx.$auth.$state.loggedIn) ` I added the console.log to print the content of `ctx.$auth.$state.loggedIn` to see if it is true or not but unfortunately it was undefined , then added store/index.js to see if it could help , the only change I saw was that I was getting default value "false" this time and still detected that I was not loggedIn and redirect me to login page, when page is reloaded now $auth.loggedIn is true and I have the user object but on the Nodejs server side no difference, I have read a lot of pages and people are having the same problem,

#### What is expected?
to simple reload current route without redirecting to login page when loggedIn = true
#### What is actually happening?
when hard refresh redirect to login page even if I am logged In

#### Steps to reproduce
described all in above

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [ ]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
install nuxtjs
install @nuxtjs/auth-next
add configuration as I mentioned in above paragraph
```
this.$auth.loginWith('laravelSanctum', {
     data: {
          email : 'test@test.com',
          password : 'password'
     })
     .then(res => {
          this.$router.push('/dashboard');
      })
     .catch(err => {
          console.log(err);
      });
```

### What is expected?
Stay on current page and just reload the page without redirecting to login page !!!!

You have done a great job handling all the authentication in this package and If you fix this problem , we really appreciate it

Thank you.

**Comment by mohsenMJ** [comment]
as some friends in the following issue mentioned 
[https://github.com/nuxt-community/auth-module/issues/853](url)

I tried some of their solutions but none of them worked for me
downgrade axios to 5.12.1
or

```
auth: {
  cookie: {
    options: {
      expires: 10
    }
  },
  .
  .
}
```

why SSR don't have access to states stored $auth storage!??
I have spent the last two days on this problem, please someone help me :(

**Comment by bmulholland** [comment]
You'll get the best time-to-resolution by doing your own debugging and/or working toward a minimal repro. We're all busy with our own problems and aren't able to help you in real time. If you nail down a specific issue with this library then it really speeds up how quickly we can fix it.

**Comment by msonowal** [comment]
Duplicate of https://github.com/nuxt-community/auth-module/issues/809
please close this and follow with one issue

**Comment by mohsenMJ** [comment]
Yes , thanks for your help, 
I tried their solution and still got nothing , suffer from this behavior. Hope soon a new version will be release that can solve this problem :-(

**Comment by asadullakkh** [comment]
I have tried all of them, but still not working, I have been trying to solve this problem for three days(
