### ISSUE TITLE
Using $auth.setUser in Laravel Sanctum doesn't log the user in

### ISSUE THREAD

**Issue by rkrater** [nuxt-community/auth-module#930]
### Version
module: 5.0.0-1607693598.34d83ea
nuxt: 2.14.11

### Nuxt configuration
 - [x] spa

### Nuxt configuration
```
  auth: {
    strategies: {
      laravelSanctum: {
        provider: 'laravel/sanctum',
        url:
          process.env.NODE_ENV !== 'production'
            ? 'http://localhost:8080'
            : `https://${process.env.APP_SERVER}`,
        endpoints: {
          logout: {
            url:
              process.env.NODE_ENV !== 'production'
                ? 'http://localhost:8080/logout'
                : `https://${process.env.APP_SERVER}/logout`,
          },
        },
      },
    },
    redirect: {
      login: '/auth'
    },
  },
```

#### What is expected?
If a user logs in using `this.$auth.loginWith('laravelSanctum', this.form)` everything works fine. But, if I set the user manually `this.$auth.setUser(res.data.user)` the user set gets updated in vuex but both `this.$store.state.auth.loggedIn` and `this.$auth.loggedIn` are still set to false and doesn't get redirected to the protected route.

**Comment by msonowal** [comment]
@rkrater 
You should use `await this.$auth.setUserToken(200)`

**Comment by bmulholland** [comment]
Closing this for now - please let us know if @msonowal's solution doesn't solve the problem.

**Comment by rkrater** [comment]
Yes, that worked - Thanks!
