### ISSUE TITLE
Accessing this.$store.state.auth via computed property not working

### ISSUE THREAD

**Issue by crslp** [nuxt-community/auth-module#937]
### Version
module: ^5.0.0-1602966760.822bc05
nuxt: ^2.14.6

### Nuxt configuration
 - [X] universal

### Nuxt configuration
```
auth: {
    redirect: {
      login: '/',
      logout: false,
      callback: false,
      home: '/'
    },
    watchLoggedIn: true,
    rewriteRedirects: true,
    strategies: {
      cookie: {
        cookie: {
          name: 'XSRF-TOKEN'
        }
      },
      laravelSanctum: {
        provider: 'laravel/sanctum',
        url: process.env.API_URL,
        endpoints: {
          login: {
            url: '/auth/login',
            method: 'post',
            propertyName: false,
            withCredentials: true,
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type': 'application/json'
            }
          },
          logout: {
            url: '/auth/logout',
            method: 'post',
            propertyName: false,
            withCredentials: true,
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type': 'application/json'
            }
          },
          user: {
            url: '/user',
            method: 'post',
            propertyName: undefined,
            withCredentials: true,
            headers: {
              'X-Requested-With': 'XMLHttpRequest',
              'Content-Type': 'application/json'
            }
          }
        },
        tokenRequired: false,
        tokenType: false
      }
    }
  },
```

## Reproduction
https://codesandbox.io/s/nuxt-auth-breaking-on-page-reload-98479?file=/pages/index.vue
Although this sandbox does not show the same error as my local development does, you'll get an idea of what I am trying to do and what might be the mistake.
Take a look at the index.vue where I put two computed properties to access information about the currently authenticated user.
These two computed properties break my (local development) code. I get this Javascript console-error:
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render. vue.runtime.esm.js:619
TypeError: nodeOps.tagName(...) is undefined
    VueJS 69
    NuxtJS 2
    Babel 12
    NuxtJS 11
```
This error only occurs after I get successfully authenticated by my laravel sanctum api *and*  reload (ctrl+f5) the page.
Navigating through the page right after log in and without reload: no issue at all.

#### What is expected?
Access the auth store without issues like documented here:
https://auth.nuxtjs.org/api/auth#user

#### What is actually happening?
At the time of execution, this
```
this.$store.state.auth
this.$store.state.auth.loggedIn
```
is ```undefined``` and gets populated later (observed via console.log(... appearing multiple times, undefined and later on with expected information).

#### Steps to reproduce
Please have a look at my codesandbox although this can not replicate my error.

## Checklist
* yes:  I have tested with the latest Nuxt version and the issue still occurs
* yes:  I have tested with the latest module version and the issue still occurs
* yes:  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by ArnoldLC** [comment]
I have an error like this with these directives. I use **$auth.loggedIn** in vue template but I have hydration error.
I don't know how solve this, I try **client-only** tag but don't kwon if is the correct solution.
![image](https://user-images.githubusercontent.com/16274102/102517954-aab4a100-405e-11eb-825f-ab58d897d374.png)

![image](https://user-images.githubusercontent.com/16274102/102518011-bef89e00-405e-11eb-9877-8bdf8b48cfc4.png)

**Comment by ArnoldLC** [comment]
For solve my issue I had to change **target** property from **`static`** to **`server`**.
![image](https://user-images.githubusercontent.com/16274102/102583315-7c70a900-40d2-11eb-98df-e37014d0823c.png)

**Comment by crslp** [comment]
Please submit code in text-only format using the github code-markdown helpers: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

As for the issue:
Further investigation led me to the cause of this issue.
In SSR mode, `this.$store.state.auth.loggedIn` can not be true since at render-time no one is authenticated. Being `this.$store.state.auth` makes a call to `this.$store.state.auth.loggedIn` fail which in turn breaks the v-if/v-else statement in the DOM which in turn leads to the current issue.

**In conclusion, this is not a bug but probably a big pitfall which the documentation should point out. Let me know if you would accept a PR with an annotation to this problem.**

For what I learned, it is a safe way to wrap such code in `<client-only>`-Tags.
Furthermore, I made a component out of the logout-button and its logic. It is safe to use like this (correct me if I am wrong).
The try/catch and if-comparisons are extra precautions which are might not be nesseccary when using `<client-only>`.

```
<template>
  <div>
    <client-only>
      <v-btn
        v-if="authenticated"
        @click="logout"
      >
        Logout
      </v-btn>
      <div class="d-inline">
        {{ user }}
      </div>
    </client-only>
  </div>
</template>
<script>
export default {
  computed: {
    authenticated () {
      try {
        return this.$store.state.auth.loggedIn
      } catch (error) {
        return ''
      }
    },
    user () {
      try {
        if ((this.$store.state.auth.user === undefined) || (this.$store.state.auth.user === null)) {
          return ''
        }
        return this.$store.state.auth.user.name
      } catch (error) {
        return ''
      }
    }
  },
  methods: {
    async logout () {
      await /* axios */
    }
  }
}
</script>

```
