### ISSUE TITLE
LoggedIn state doesnt update upon successful login

### ISSUE THREAD

**Issue by MastinGood** [nuxt-community/auth-module#948]
I successfully login to my nuxt app using laravel sanctum but the **loggedIn**  state doesnt update to **true** even if I already set the user using this code. 
```
 const user = await this.$axios.$get('/api/user');       
 this.$auth.setUser(user)  
```
![image](https://user-images.githubusercontent.com/21983499/102683691-b7c3c280-420d-11eb-8ec7-38a33c0b7e44.png)

Here's my nuxt config: 
![image](https://user-images.githubusercontent.com/21983499/102684364-c5c81200-4212-11eb-9e16-4006fccba305.png)

**Comment by msonowal** [comment]
@MastinGood 
You should use along with `await this.$auth.setUserToken(200)` for sanctum
Duplicate
https://github.com/nuxt-community/auth-module/issues/930#issuecomment-744285414

**Comment by MastinGood** [comment]
Throws error on submit.
![image](https://user-images.githubusercontent.com/21983499/102685397-37a45980-421b-11eb-9cee-f1419c1e9ae7.png)

```
<script>
  export default {
    auth: 'auth',
    data() {
      return {
       form: {
            email: '',
            password: ''
            },
        errors: {}
      };
    },
    methods: {
      async login(){
        try{
          await this.$axios.$get('/sanctum/csrf-cookie');
          await this.$auth.loginWith('local', { data: this.form })
          const user = await this.$axios.$get('/api/user');
          await this.$auth.setUser(user);
          await this.$auth.setUserToken(200);
          this.$router.push('/');
        }
        catch({response}){
          console.log(response.data.errors);
          this.errors = response.data.errors;
        }
      }
    },
  };
</script>

```

**Comment by msonowal** [comment]
@MastinGood try with this `await this.$auth.setUserToken('200')`

But may I ask why you are using it manually i.e. csrf token etc just try to use as per the guide it will be automatically done

**Comment by JoaoPedroAS51** [comment]
Hi @MastinGood! I recommend using [laravel sanctum provider](https://auth.nuxtjs.org/providers/laravel-sanctum), it will do all the job for you :wink: 

Then, your login method will look like this:
```js
<script>
  export default {
    auth: 'auth',
    data() {
      return {
       form: {
            email: '',
            password: ''
            },
        errors: {}
      };
    },
    methods: {
      async login(){
        try{
          await this.$auth.loginWith('local', { data: this.form });
          this.$router.push('/');
        }
        catch({response}){
          console.log(response.data.errors);
          this.errors = response.data.errors;
        }
      }
    },
  };
</script>
```

You can also set [redirect](https://auth.nuxtjs.org/api/options#redirect) option in auth config, so you don't need to use `this.$router.push('/')`

**Comment by MastinGood** [comment]
Thanks a ton! It works now 💯

**Comment by MastinGood** [comment]
@JoaoPedroAS51 Can we use laravelSanctum to register like I did in login? or we manually hit this endpoint `/register` to register?

**Comment by JoaoPedroAS51** [comment]
@MastinGood I think you should hit the `/register` endpoint using axios, then, you call `loginWith`.

Something like this:

```js
register() {
  this.$axios.post('/register' , { data: this.form })
    .then(() => this.$auth.loginWith('laravelSanctum', { data: this.form }))
}
```
