### ISSUE TITLE
Why is Authorization false header being set during login?

### ISSUE THREAD

**Issue by greenermoose** [nuxt-community/auth-module#949]
I'm trying to get @nuxtjs/auth-next working with strapi 3.4.0.

I had to set the Authorization header to blank when using loginWith because strapi didn't like it when the Authorization header contained false.

This code works:

        let response = await this.$auth.loginWith("local", {
          data: {
            identifier: loginInfo.email,
            password: loginInfo.password
          },
          headers: {
            "Authorization": ""
          }
        });

but this code does not:

        let response = await this.$auth.loginWith("local", {
          data: {
            identifier: loginInfo.email,
            password: loginInfo.password
          }
        });

The login would fail with a 401 error from strapi complaining that the Authorization header should be of the format "Bearer <token>." Unless I explicitly set the Authorization header to blank it gets set to false somewhere in the nuxt/auth code for loginWith().

I'm not sure why the Authorization header is being set to false and how to override it other than explicitly coding in a blank Authorization header when making the loginWith call.

Any insight would be appreciated!

**Comment by JoaoPedroAS51** [comment]
Hi @greenermoose! Thank you for report. I'll work to find the cause of this issue and let you know when it's fixed :)

**Comment by JoaoPedroAS51** [comment]
Hi @greenermoose! #950 will fix your issue :)

**Comment by greenermoose** [comment]
Thanks for the quick response and fix! I'll test it out today.
