### ISSUE TITLE
Login with domain name

### ISSUE THREAD

**Issue by ngochoaitn** [nuxt-community/auth-module#954]
My config:
server:{ host: '0.0.0.0', port: 3000}

Login with localhost:3000 ok
But login wiith 127.0.0.1:3000 and abc.test (i have edited file host) didn't work

How to config to login with abc.test?

Thank.

**Comment by msonowal** [comment]
@ngochoaitn 
It should work can you tell what the error or screenshot
what is the output of `ping abc.test`

**Comment by bmulholland** [comment]
There's no question connected with the auth module here, so closing.
