### ISSUE TITLE
The --save-exact option in installation setup is canceled by the second install line

### ISSUE THREAD

**Issue by gilles6** [nuxt-community/auth-module#957]
There's something wrong in your [setup page](https://auth.nuxtjs.org/guide/setup/):
```
npm install --save-exact @nuxtjs/auth-next
npm install @nuxtjs/auth-next @nuxtjs/axios
```

It's redundant to use `@nuxtjs/auth-next` in both lines **and** the `--save-exact` option of the first line, which prevent from adding `^` before package version in `package.json`, is canceled by the second line, which adds this unwanted `^`.

Having `--save-exact` is a useful option because version prefixes like `^` and `~` arouse problems on production servers, as `npm install` will then modify `package.json` which prevents `git pull` (unless you do something like `git stash && git stash drop` to cancel this change).

**Comment by bmulholland** [comment]
Thanks for reporting!
