### ISSUE TITLE
OAuth scope defaults should be overwritten when configured

### ISSUE THREAD

**Issue by phani1kumar** [nuxt-community/auth-module#958]
Gone through the documentation and sample implementation in demo. When trying to set the `scope` for github strategy, I realized that the file in auth module source `src/providers/github.ts` has the scope defined as `['user', 'email']`. 

Even when I apply scope `['read:user']` it just appends to the auth request along with existing scopes, I was expecting to overwrite the default scope definition because I don't want to get write access to user profile. That might scare the users when logging in using github. 

Please suggest how I could achieve this?

**Comment by phani1kumar** [comment]
Also, the `authorize` response I am receiving after signing from github is `{"error":"bad_verification_code","error_description":"The code passed is incorrect or expired.","error_uri":"https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"}`

means, there seems to be something wrong with the `github` sign-in process as well! I was able to integrate `facebook` and `google` integration without a glitch. I can see the verification code sent and received are one and the same, but still it says `bad_verification_code`

![image](https://user-images.githubusercontent.com/9419954/103108214-bc540500-466b-11eb-83c2-a41cc3db1dc3.png)

**Comment by bmulholland** [comment]
Thanks for reporting this, we'll look into it. There's a few issues in here and that makes it hard to manage - can you please create another for anything other than the scope default overwrite?

**Comment by bmulholland** [comment]
This issue is older, but there's a nice workaround in https://github.com/nuxt-community/auth-module/issues/1359 so marking that as the original and this as the dupe.
