### ISSUE TITLE
Double URI decoding is done when retrieving values from cookies

### ISSUE THREAD

**Issue by westende** [nuxt-community/auth-module#969]
Thank you for providing this module to the community. I noticed a small issue with retrieving URI encoded data from cookie storage.

### Version

module: 4.9.1
nuxt: 2.14.7

### Nuxt configuration

 - [x] universal
 - [ ] spa

### Nuxt configuration

The Nuxt config is irrelevant for this issue.

## Reproduction

Not necessary as this is easily deductible from the source code.

#### What is expected?

URI decoding is only done once.

#### What is actually happening?

URI decoding is done twice.

## Additional information

The getCookie method of the Storage class calls decodeURIComponent on the cookie value. However cookie.parse has already been called on the cookie's value in the getCookies method of the Storage class. cookie.parse implicitly also calls decodeURIComponent on the cookie value.

## Checklist

* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

**Comment by bmulholland** [comment]
We don't have bandwidth to support 4.9 and are focused on auth-next. Please open a new issue if this is still happening with that new version.
