### ISSUE TITLE
Unexpected callback redirection chain

### ISSUE THREAD

**Issue by pasikon** [nuxt-community/auth-module#976]
### Version
nuxt: 4.9.1

### Nuxt configuration
 - spa

### Nuxt configuration
```
axios: {
    proxyHeaders: true,
    proxy: true,
  },
auth: {
    strategies: {
      local: false,
      keycloak: {
        _scheme: 'oauth2',
        response_type: 'code',
        token_type: 'Bearer',
        token_key: 'access_token',
        refresh_token_key: 'refresh_token',
        grant_type: 'authorization_code',
...
      },
    },
    redirect: {
      login: '/',
      logout: '/',
      callback: '/callback',
      home: '/',
    },
  },
  router: {
    middleware: ['auth'],
  },
```

#### What is expected?

Single redirection to https://example.org/callback

#### What is actually happening?

HTTP 302 Location: https://example.org/callback?state-...... (OK - expected)
HTTP 301 Location: http://example.org/callback/?state=....... (Unexpected - http instead of https. slash after callback?)
Since port 80 is not even open I get the page not found.

I don't understand where this second HTTP 301 redirection comes from and why the protocol is changed to http

**Comment by bmulholland** [comment]
Try configuring the axios base URL. Something like this in nuxt config:

```
  axios: {
    baseUrl: "https://example.org",
    credentials: true,
  },
```

**Comment by pasikon** [comment]
Unfortunately, this has no effect on the behavior :(

**Comment by bmulholland** [comment]
Thanks for trying. Since I don't have your setup, I can't help debug. Please do some tracing within the code of this library to figure out how the redirect URL comes to be. Once you've pinpointed the root case, we can fix.
