### ISSUE TITLE
Cannot log out with Auth0 strategy sometimes

### ISSUE THREAD

**Issue by linh-ebisolvn** [nuxt-community/auth-module#978]
### Version
module: 
nuxt: 

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [ ] universal
 - [x] spa

## Checklist
* [ ]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce
Log in with Auth0, navigate to some other routes
Click logout (under the hood it calls ` await this.$auth.logout()`)

### What is expected?
Sometimes it redirects as expected to auth0 login page. Nevertheless, once in a while it keeps redirect to home route, which causes problem
### What is actually happening?

I am skeptical that the sessions on remote Auth0 server has not been cleared at all. So when the methods get called, it stills navigates to auth0, here due to the fact that the login session is still true, therefore auth0 sends me back to my domain hence causes the loop

**Comment by bmulholland** [comment]
This isn't much to go on. Can you please dig in and diagnose the root cause? We can't do that on our end because we don't have your app running.

**Comment by kleoken** [comment]
Be sure you uninstall the old `@nuxt/auth` module from your project as the new auth module is `@nuxt/auth-next`. They both use the same `$auth` variable and could be competing over its fields.

**Comment by linh-ebisolvn** [comment]
> This isn't much to go on. Can you please dig in and diagnose the root cause? We can't do that on our end because we don't have your app running.
I guess there may be some bugs on auth0 side.  Could be much of a possibility that the logged in state or session is not yet to be cleared on the auth0 server, so when you call the` $auth.logout('auth0')` event of auth-next, auth0 recognized that this user is still logged in and it should redirect you back to the callback url in your app.
I would say 3-4/10 times this would happen
 
> Be sure you uninstall the old `@nuxt/auth` module from your project as the new auth module is `@nuxt/auth-next`. They both use the same `$auth` variable and could be competing over its fields.
Well I just give it a check and only 1 `@nuxt/auth-next` module is installed in my pkg

**Comment by PerryCodes** [comment]
We're seeing the exact same behavior.

**Comment by bmulholland** [comment]
Sorry to hear, but we can't do anything without a repro or further information. Please create a new issue with more details and/or a repro if/when you have it.
