### ISSUE TITLE
Auth middleware doesn't redirect index.vue 

### ISSUE THREAD

**Issue by wgins** [nuxt-community/auth-module#984]
Hey there,

I've followed the instructions provided with the `auth` module and have added the following to my `nuxt.config.js`:

```
router: {
    middleware: [
      'auth',
    ]
  },

  auth: {
    redirect: {
      login: "/login",
      logout: '/login',
      callback: '/',
      home: '/'
    },
    watchLoggedIn: true,
    strategies: {
      google: {
        clientId: '....',
        clientSecret: '....',
        scope: ['email'],
        codeChallengeMethod: "",
      },
    }
  },
```

I have three pages in my nuxt app `pages` directory, `index.vue`, `test-page.vue` and `login.vue`. With the config above when I go to `localhost:3000/test-page` the app successfully redirects me to `login.vue` where I have a button that invokes `this.$auth.loginWith('google')`. However, when I go to `localhost:3000/` the app doesn't redirect. Am I missing something or is there something specific to the index page that's different with regards to redirect behavior when using the auth module globally? Thanks for the help!

**Comment by JoaoPedroAS51** [comment]
Hi @wgins! I think you must set a different callback page, because it needs to be unprotected. In your config the `home` and `callback` redirects are pointing to your index page. So, try to create a new page `callback` and set the callback redirect to it :)

**Comment by pschaub** [comment]
see also: https://auth.nuxtjs.org/api/options#redirect

**Comment by wgins** [comment]
Thanks, @JoaoPedroAS51  and @pschaub! Updating the callback redirect solved the issue.
