### ISSUE TITLE
How to manually set a user in @nuxt/auth-next ?

### ISSUE THREAD

**Issue by gilles6** [nuxt-community/auth-module#986]
I'm using `laravelPassport` strategy to sign in a user and it works perfectly fine. However, when I **register** a user or when a user clicks on a **email verification** link, I need to pass the information from Nuxt to the Laravel API which returns a user authenticated **token** and **user profile**. 

In such case, what should I do to properly set the user in `@nuxt/auth-next` ?

**Comment by pschaub** [comment]
Please have a look into the methods here:
https://auth.nuxtjs.org/api/auth/#methods

**Comment by gilles6** [comment]
@pschaub 
Okay, that's what I needed, indeed, thanks!
